### ISSUE TITLE
pixelDensity missing from Environment documentation

### ISSUE THREAD

**Issue by bmoren** [processing/p5.js#1002]

**Comment by toolness** [comment]
So a funky thing I noticed is that `pixelDensity` is actually currently defined in [`core.js`](https://github.com/processing/p5.js/blob/fff661eaf5ee7f1711f3dfc11ab9bd074383ba87/src/core/core.js#L147) under a section commented as "PRIVATE p5 PROPERTIES AND METHODS". Which suggests it's private, and not meant to be publicly documented. *However*, it's also the only property defined in that area that doesn't start with a `_`, which suggests that it's public.

That said, it seems like the main public interface to `pixelDensity` is [`devicePixelScaling()`](http://p5js.org/reference/#/p5/devicePixelScaling), which *is* documented... Though, that said, there isn't any public interface to *get* the current device pixel scaling settings, which is what `pixelDensity` tells us.

So it seems like there are a few options here:
* Document `pixelDensity` as a *read-only* variable, telling people to use `devicePixelScaling()` if they want to write to it. Also, move `pixelDensity` out of the "PRIVATE p5 PROPERTIES AND METHODS" section of `core.js`.
* Add a new Environment function called `getDevicePixelScaling()`, which just returns the current value of the private `pixelDensity` variable. (Optionally, rename `pixelDensity` to `_pixelDensity`, so it's named like all the other private variables.)
* Do nothing?

**Comment by lmccart** [comment]
thanks for looking into this! I think what happened was `pixelDensity` used to be `_pixelDensity` and it was private, but we later realized it is useful to have access to this when doing things like accessing the `pixels` array directly. let me take a closer look and work on this one. two possible solutions I can think of are to remove `devicePixelScaling()` and just let people set `pixelDensity` directly (I need to check if this works), or have `devicePixelScaling()` with no arguments act as a getter rather than a setter, which is a pattern we're slowly rolling out through other functions in the library. more soon!

**Comment by shiffman** [comment]
I'm not sure to what extent this is helpful but I wonder if aligning a bit with the Processing API might work well here.  For example we could have:

```javascript
pixelDensity(value); // Sets the density
pixelDensity();      // Gets the density (whatever its been set to or default)
displayDensity();    // Get the actual density of the display
```

And so the equivalent of `devicePixelScaling(false)` would be:

```javascript
pixelDensity(1);
```

and the following would always set the density to whatever the display actually is:

```javascript
pixelDensity(displayDensity());
```

**Comment by lmccart** [comment]
yep love it, @reas suggested the same thing, will make the change and add documentation.

**Comment by shiffman** [comment]
Yay!
