### ISSUE TITLE
API glossary/index

### ISSUE THREAD

**Issue by joecridge** [processing/p5.js#1036]
Feel free to close this if one already exists, but do we have a API cheatsheet [like this](https://github.com/processing/processing/blob/a83e4a5f81f4b1089a861127a831bbc0534678ab/core/api.txt) anywhere, or could we generate one in the same way we generate the online reference?

I feel like it would be useful for developers or users who know what functions do but can't quite remember their name or syntax…

**Comment by lmccart** [comment]
all the functions are listed here: http://p5js.org/reference/
though they don't show the parameters until you click into the page.
if we did add a page like this, it would be best if it were auto-generated and auto-updated when the docs are updated. otherwise I worry it just adds another task to an already really long list of things to maintain.

**Comment by joecridge** [comment]
Yeah, I was thinking of single resource that could be easily saved for offline use or to generate syntax highlighting rules, etc. If it's something that could be added as an additional task for the documentation parser that would be awesome, but if it's going to be more involved than that then it probably isn't worthwhile.

**Comment by lmccart** [comment]
ah i see. i think this json file contains all the necessary info then, it is what is used to populate the reference: http://p5js.org/reference/data.json
