### ISSUE TITLE
mask() and <img> or <video>

### ISSUE THREAD

**Issue by shiffman** [processing/p5.js#1044]
This may ultimately just be a need for an example involving copying into a `p5.Image` object, but currently the `mask()` function I believe is not compatible with a video or img DOM element.  So this is really a note to self for me to investigate this at some point and see what is possible.

**Comment by paperkettle** [comment]
+1
found this today trying to mask a video using creategraphics 
then tried video with a png mask and that didn't work either
png masking a png worked tho

major power in the potential of creategraphics masks, and maskable video..!

**Comment by grayfuse** [comment]
^^ 

Was searching through docs to see if the graphics context can be used as a dynamic mask, but it doesn't seem to have parity with image the way I'm used to in some other environments.

As a stopgap solution, is there a most efficient approach to copying the graphics context pixels into an image so that image can be used as the mask after drawing into the context?

**Comment by lmccart** [comment]
cool just added support for this, should work something like this, will be included in the next build:

```javascript
var mask;
var vid;

function preload() {
   mask = loadImage('assets/mask.png')
}

function setup() {
  createCanvas(600, 600);
  vid = createVideo('fingers.mov');
  vid.loop();

}
function draw() {
  background(200);
  vid.mask(mask);
  image(vid);
}

```
