### ISSUE TITLE
tint() and p5.MediaElement not working?

### ISSUE THREAD

**Issue by shiffman** [processing/p5.js#1087]
With the following sketch, I'm getting the image tinted, but not the video capture.

```javascript
var cam;
var img

function preload() {
  img = loadImage("assets/moonwalk.jpg"); 
}

function setup() {
  createCanvas(710, 400);
  cam = createCapture(VIDEO);
  cam.size(320, 240);
}

function draw() {
  background(150);
  tint(255, 0, 0);
  image(cam, 0, 0); // draw the video frame to canvas
  image(img, 320, 0);
}
```

**Comment by toolness** [comment]
I'm not sure how much this helps, but I'm noticing that calling the following just before drawing the video frame to canvas makes things work:

```diff
  tint(255, 0, 0);
+ cam._pixelDensity = cam.pixelDensity; // workaround for #1091
+ cam.loadPixels();
  image(cam, 0, 0); // draw the video frame to canvas
```

This is because `cam.loadPixels()` actually sets the `canvas` property on the `MediaElement` instance, which then causes `image()` to treat it the same way as a `p5.Image` (i.e., applying tint).

I'm not sure what a good architectural change for a PR would be, though, as I'm not very familiar with the codebase... I could try coming up with something though, unless someone more experienced wants to fix it.

**Comment by lmccart** [comment]
thanks @toolness! I can take a look at this one later this week, I was doing some work recently with p5.MediaElement so it's fresh in my mind.. and I think the pixelDensity/_pixelDensity error is fixed in the newest version.

**Comment by toolness** [comment]
Awesome, sounds good! And you're right that the pixelDensity/_pixelDensity error is fixed, I wasn't using the latest master. :disappointed:
