### ISSUE TITLE
Is there any method for mouse event like click on a 3d object, so that i can understand which object is clicked

### ISSUE THREAD

**Issue by suhailsulu** [processing/p5.js#1095]

**Comment by indefinit** [comment]
currently, we don't have any event handlers on 3d objects, nor "3D picking," which is a technique used to determine which object intersects with the vector from your mouse.  That said, it would be a great feature to have as a library addon, if someone wants to tackle it!

**Comment by toolness** [comment]
Oh that sounds like fun!  I'd like to give it a try.

@indefinit, when you say a "library addon" do you mean I should make my own p5.3dpicking.js library, or should I submit a PR to some pre-existing library?

**Comment by indefinit** [comment]
It would be really cool to have a p5.Raytracer library that includes picking.  The lib doesn't currently exist for p5, so you'd have to build it from scratch, but there's plenty of precedence out there in the web. 

One thing that a Raytracer library will depend on is axis-aligned box and spheres.  That would be the basis for ray-plane, ray-box, and ray-sphere intersection.  Adding an axis aligned bounding box isn't that difficult and would be a good PR to the core once I finish the big p5.Geometry refactor.

**Comment by lmccart** [comment]
I think this is a great idea, but I'm going to close the issue here as it seems to pertain to a potential addon library rather than a feature of the core p5.js library itself. This page describes how to make an addon library if you'd like to pursue this option: https://github.com/processing/p5.js/wiki/Libraries#creating-a-new-library.
