### ISSUE TITLE
colorMode(HSB) with color() unexpected behaviour

### ISSUE THREAD

**Issue by pbogdan03** [processing/p5.js#1100]
```javascript
	stroke(255);
	background(51);
	colorMode(HSB);
	var c1 = color(0, 100, 100);
	var c2 = color(100, 100, 100);
	var c3 = color(200, 100, 100);
	var c4 = color(300, 100, 100);

	fill(c1);
	rect(10, 20, 20, 30);
	fill(c2);
	rect(30, 20, 20, 30);
	fill(c3);
	rect(50, 20, 20, 30);
	fill(c4);
	rect(70, 20, 20, 30);
```
Above code displays the following:

![test](https://cloud.githubusercontent.com/assets/9051832/11116155/4eafb264-8939-11e5-89e3-6e89336c878e.jpg)

**Comment by lmccart** [comment]
hmm thanks. @joecridge do you have some time to take a look at this?

**Comment by joecridge** [comment]
Oh no! I'll take a look shortly.

**Comment by joecridge** [comment]
@lmccart it’s 1458a19 that is causing the issue (I think for a similar reason to why we abandoned reusing `results` in `p5.Color._parseInputs()`?). 

I’m not sure how reuse the object correctly, so for now I’ll just reverse the commit and that should fix things.

**Comment by lmccart** [comment]
thanks for looking into this, yes I think the problem is as you explain... I'll think more about how to reuse objects. I think it would involved making these holder vars part of the color prototype, the problem I ran into was getting the context binding right so that they were accessible at the point when the functions are called.
