### ISSUE TITLE
mouseWheel event: "return false" to block page scrolling not working in firefox.

### ISSUE THREAD

**Issue by hellwoodfire** [processing/p5.js#1116]
See the example: http://p5js.org/reference/#/p5/mouseWheel
Edit and uncomment "return false" to block page scrolling. This work correctly in Chrome and IE, but  page scrolling is not blocked in Firefox.

**Comment by limzykenneth** [comment]
it seems the mouseWheel event p5 is using is [deprecated](https://developer.mozilla.org/en-US/docs/Web/Events/mousewheel), switching to the new Wheel event might fix it. I'll submit a PR if I can fix it today.

**Comment by limzykenneth** [comment]
This turns out to be more complicated than I thought, I will need to come back to it in the weekend. : (

**Comment by hellwoodfire** [comment]
Oh! Good luck!

2015-11-17 17:37 GMT-05:00 Kenneth Lim <notifications@github.com>:

**Comment by lmccart** [comment]
thanks for looking into it!

**Comment by limzykenneth** [comment]
Almost done with this, just a few decisions need making:

Support of the `wheel` event on Safari is still buggy, it will work if `return false;` and thus `e.preventDefault()` is passed but hardly if it's not. Any idea to solve this is very welcomed.

Looking at the documentation, the whole thing might not work on IE at all but I cannot test it so that might be something we want to test after the push. Although supporting IE might be a lost cause...

Since it is using standardise method now, we can instead of returning +1 or -1 as a result, actually return the wheel scroll amount. Is this something desirable or do we want to keep it more or less as is?

Cheers.

**Comment by lmccart** [comment]
awesome!
i think the actual scroll amount is preferable over just -1 or +1.
i'm not sure what to do about IE. I think as long as we have a note about using `return false;` to prevent default, this may be sufficient for safari. if people have issues, we can direct them to that?

**Comment by limzykenneth** [comment]
Great! Scroll amount is easier to do for me too. ; )

I think since I can't test for it let's just push the changes and maybe someone with a windows machine can test it out. It might just work.

I'll make the necessary changes to the documentation with note on safari as well.

**Comment by lmccart** [comment]
sounds good!

**Comment by hellwoodfire** [comment]
Kenneth, how to I get the p5.js file containing the fix ? (so that I can
test it)

2015-11-17 4:25 GMT-05:00 Kenneth Lim <notifications@github.com>:

**Comment by lmccart** [comment]
I will post an updated version soon.

**Comment by hellwoodfire** [comment]
I wanted to be sure to mouse wheel still worked in the 2 directions in firefox (scroll up, scroll down).

**Comment by limzykenneth** [comment]
@hellwoodfire if you want a quick test now you can download the repo and generate the library with `grunt`
