### ISSUE TITLE
Two sketch instances don't produce same stream of randoms during draw()

### ISSUE THREAD

**Issue by toolness** [processing/p5.js#1135]
The following script ought to produce two separate sketches that log identical streams of random numbers, I think:

``` js
var SEED = 1;

function randomLogger(name) {
  return function(p) {
    p.setup = function setup() {
      p.createCanvas(100, 100);
      p.randomSeed(SEED);
    };

    p.draw = function() {
      if (p.frameCount < 10)
        console.log(name + " frame # " + p.frameCount + ": " +
                    Math.floor(p.random(0, 10)));
    };
  };
}

var sketch1 = new p5(randomLogger("sketch1"));;

var sketch2 = new p5(randomLogger("sketch2"));;
```

However, when I run this, I get this in my console:

```
sketch1 frame # 1: 2
sketch2 frame # 1: 2
sketch1 frame # 2: 3
sketch2 frame # 2: 5
```

It seems like the random numbers are synchronized during `setup()` and the first call to `draw()`, but not after that.

**Comment by mikewesthad** [comment]
This is the first time I'm poking around p5 source, but I think I see what's going on here.  
The [p5 constructor](https://github.com/processing/p5.js/blob/ad071c96efef47b752d942c69407d600c4c75fc9/src/core/core.js#L37) doesn't create an independent random generator for each instance.  So the [lcg](https://github.com/processing/p5.js/blob/ad071c96efef47b752d942c69407d600c4c75fc9/src/math/random.js#L16) function, which is used to generate random numbers with a seed, is going to be a shared reference across p5 instances.  They can't have different seeds, and they won't generate independent streams of random numbers. 

The stream of random numbers for a seed of 1 is: `2, 3, 5, 7, ...`.  The reason why you are seeing 2 twice is because the seed is being reset between sketch1's first frame and sketch 2's first frame.  If you add a log to p5 core, you can better see what's going on:

```js
p5.js:25841 The seed is being set to: 1
sketch.js:13 sketch1 frame #1: 2
p5.js:25841 The seed is being set to: 1
sketch.js:13 sketch2 frame #1: 2
sketch.js:13 sketch1 frame #2: 3
sketch.js:13 sketch2 frame #2: 5
sketch.js:13 sketch1 frame #3: 7
sketch.js:13 sketch2 frame #3: 0
```

This aspect of p5 seems like part of the design rather than a bug?

**Comment by limzykenneth** [comment]
@mikewesthad I believe you analysis is correct.

I think with instance mode one would expect the seeded RNG to return the same results in all instances if the seed is the same. I'm not sure if it is at all possible to have independent RNG in each instances though.

**Comment by mikewesthad** [comment]
@limzykenneth, right - I think it depends on what "instance" mode is supposed to be.  Is it intended for running two independent sketches concurrently?  It seems to be more for providing closure over a single sketch so that p5 can play nicely with other libraries.

Other aspects of p5 will act weird if you run two instances side-by-side.  E.g. making shapes using vertex will be funky since the [vertices](https://github.com/processing/p5.js/blob/899f7cb724d70d41cdeec9a8440d9dedb71dbd2e/src%2Fcore%2Fvertex.js#L14) array is shared across instances.  Here's a contrived example below - sketch1 opens a quad and adds two vertices, while sketch2 adds two more vertices and finishes the quad.  The canvas in sketch2 ends up with a full rectangle in it.


```js
var sketch1 = new p5(function(p) {

  p.setup = function() {
    p.createCanvas(300, 300);
    p.background(0);
    p.stroke(255);
    p.beginShape(p.QUADS);
    p.vertex(0, 0);
    p.vertex(100, 0);
  };

});

var sketch2 = new p5(function(p) {

  p.setup = function() {
    p.createCanvas(300, 300);
    p.background(255, 0, 0);
    p.stroke(255);
    p.vertex(100, 100);
    p.vertex(0, 100);
    p.endShape();
  };

});
```

![screenshot 2015-12-05 12 56 04](https://cloud.githubusercontent.com/assets/1131802/11609569/b02204de-9b4f-11e5-8878-8102478c99b5.png)

If instance mode is supposed to allow for two independent sketches running concurrently, then it seems like that would require some architecture changes to p5.  If instance mode is just for reducing the number of global variables in a sketch, then maybe there should be a sentence added to the documentation clarifying that it isn't intended for running multiple, independent sketches?

**Comment by limzykenneth** [comment]
Interesting, I haven't come across this behaviour before but to be fair I'm not terribly familiar with instance mode anyway. ;)

I'm not sure what needs to be done if we are to allow two sketches to run on the same page with the expected results, someone else need to take up on that one. Personally I would very much like to have the possibility to have multiple sketch on the same page as it is quite useful in situations such as writing tutorials or other more complex situations.

**Comment by toolness** [comment]
Thanks for looking into this @mikewesthad!

> Personally I would very much like to have the possibility to have multiple sketch on the same page as it is quite useful in situations such as writing tutorials or other more complex situations.

Yeah, p5's own reference docs actually assume this too, as some pages like the docs for [`stroke()`](http://p5js.org/reference/#/p5/stroke) actually have multiple sketches on them. Each sketch isn't self-contained in its own iframe or anything (though I've suggested we do this in https://github.com/processing/p5.js-website/issues/198) so any bugs of this class are likely to surface themselves in the docs. It's made even more likely by the fact that the entire docs is a single-page app, so leftover residual state from one page's documentation can negatively affect the state of another...

I think this behavior would feel a lot more "by design" if the randomness methods were **static methods** of the `p5` class, e.g. reachable via `p5.randomSeed()` rather than `p5.prototype.randomSeed()`. In fact, if the *only* goal of p5's instance mode were to make it play well with other libraries, I think it would make more sense to simply have everything be *namespaced* under the `p5` object rather than providing instantiation mechanisms, which implies a lot of behaviors that may not actually exist.

**Comment by mikewesthad** [comment]
@toolness no problem.  Good point about the existing documentation.  Given that, it seems like it might be a good idea to push for each p5 instance to be independent.  So in this case, the lcg random number generator could be attached to the specific p5 instance (rather than as a variable local to random.js and shared across all p5 instances).  A hacky fix might be: instead of the lcg being local, attach it to the p5 instance when [randomSeed(...)](https://github.com/processing/p5.js/blob/master/src/math/random.js#L66) is called for the first time.  That feel inelegant, but I'm not familiar enough with the p5 architecture yet to suggest something better.

If there is a strategy to be implemented to make p5 instances independent, it should also apply to the local variables in the other modules (like in vertex.js).
