### ISSUE TITLE
pmouseX always equal to mouseX

### ISSUE THREAD

**Issue by BarbaraAlmeida** [processing/p5.js#1176]
When using p5.js v0.4.20  from December 11, 2015 pmouseX/Y is always equal to mouseX/Y.

I've tried the p5.js files on [this issue] (https://github.com/processing/p5.js/issues/1035):

In p5.js v0.4.17 from October 25, 2015 (the one that solved the issue) they are also behaving weirdly: pmouseX/Y is not equal to mouseX/Y when the mouse stops moving (seems to be the same problem reported [here] (https://github.com/processing/p5.js/issues/1162)) and ```line(mouseX, mouseY, pmouseX, pmouseY);``` produces a dashed line.

It seems to work fine with p5.js v0.4.17 from October 13, 2015.

Code:

```javascript
function setup() {
  createCanvas(500, 500);
  background(240);
}


function draw() {  
  line(mouseX, mouseY, pmouseX, pmouseY);
  
  fill(255);
  rect(0, 0, 300, 50);
  
  fill(0);
  text("mouseX = " + mouseX, 30, 20);
  text("pmouseX = " + pmouseX, 30, 35);
  
  text("mouseY = " + mouseY, 180, 20);
  text("pmouseY = " + pmouseY, 180, 35);
  
  if (mouseX == pmouseX) {
    ellipse(10, 20, 10, 10);
  }
  
   if (mouseX == pmouseX) {
    ellipse(160, 20, 10, 10);
  }
}


function mousePressed() {
  background(240);
}
```

**Comment by lmccart** [comment]
This is due to the fact that the mouse coords are update do mousemove, but the pmouse coords are updated each frame, so often the order of events causes them to end up the same. I would suggest instead doing the drawing inside mouseMoved() function:

```javascript

function mouseMoved() {
  console.log(mouseX, pmouseX, mouseY, pmouseY);
}
```

**Comment by KingWalrus** [comment]
I recently reported an issue with pmouseX/Y not updating when the mouse stops moving, but in Processing the mouseX/Y positions update every frame (https://github.com/processing/p5.js/issues/1162), which was fixed by updating pmouseX/Y every frame, but now it seems that not updating current mouseX/Y every frame does not allow for pmousX/Y to be used in the main draw function, which is how a lot of people have been accustomed to using it. For example, the following code form Daniel Shiffman no longer works because of this functionality. 

````javascript
function setup() {
  createCanvas(600,600);
  background(255);
  
}

function draw() {
  stroke(0);
  line(pmouseX, pmouseY, mouseX, mouseY);
}
````

**Comment by lmccart** [comment]
hmm I think I have a good fix that will satisfy both these conditions. will submit a patch soon.

**Comment by BarbaraAlmeida** [comment]
Drawing inside ```mouseMoved()``` results on the same problem reported on #1035 when moving fast.

![2015-12-25](https://cloud.githubusercontent.com/assets/10374661/12002964/b4bc4468-aaf5-11e5-8159-88ec9c41a6bc.png)

**Comment by lmccart** [comment]
ok I just submitted a patch. the issue here is that the mouse coords were being updated on the event (which is async) and the pmouse coords were being updated on each draw() call, so there was often never any time between the two. the fix I've added adds internal vars _nextMouseX/Y and _nextTouchX/Y which get updated on the mouse or touch event. then in draw (each frame), the values of mouseX/Y are updated to the _nextMouseX/Y to match, and pmouseX/Y vals are updated as well.
the original code sample should now run properly.
