### ISSUE TITLE
26270: Uncaught TypeError: Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by sidds1009** [processing/p5.js#1178]
On redraw(), the background changes but the 3D gives an error. This happens when  I use WEBGL  in createCanvas. I get this message and program halts.

"p5.Renderer3D: enabled webgl context"
26270: Uncaught TypeError: Cannot read property 'apply' of undefined

translate(250, 0, 0);
    push();
    rotateZ(theta * 0.01);
    rotateX(theta * 0.01);
    rotateY(theta * 0.01);
    texture(aries);
    box(80, 80, 80);
    pop();
    theta += 0.05;

**Comment by indefinit** [comment]
It's hard to say exactly where the problem might be from this code snippet, but it's possible the Uncaught TypeError is happening because of your call to texture().  Perhaps take a look at your texture image and make sure you're using a power of two image size: 512x512 or 1024x1024, etc.

Other than that, feel free to post a link to your code (github gist) on the Processing forum for others to chime in:
https://forum.processing.org/two/categories/p5-js
