### ISSUE TITLE
Broken local resource links for reference

### ISSUE THREAD

**Issue by limzykenneth** [processing/p5.js#1189]
I've notice the development reference generated from source in in the repo seem to have broken links, specifically if gave me 404 for the following files:

![screen shot 2016-01-02 at 5 52 30 pm](https://cloud.githubusercontent.com/assets/7543950/12075471/bf390270-b179-11e5-955f-6be24e5f260c.png)

I went digging and the problem seems to start from PR #1170 possibly commit `858c99d536f21bb707d06e73048b7d7ea8db1509`. Might be because of the change in site root doesn't coincide with where the files actually are (it goes a level higher).

Is this actually a problem or am I doing something wrong?

Cheers.

**Comment by limzykenneth** [comment]
Ok, I just realized running `grunt yui:dev` will give me the locally linked version. Can we add the instructions to the development guidelines?

**Comment by limzykenneth** [comment]
I've just realised running `grunt yui:dev` will give me the locally linked version. Been out of the loop a bit too long I guess ;)

Just a question before I close this though, why the decision to have `grunt yui` and `grunt yui:dev`?

**Comment by lmccart** [comment]
hi @limzykenneth sorry about the confusion. we recently changed things up so that you can build the files either for local testing or website production. the links are different because when you are running locally you may want to link to the version of p5.js that you just build to confirm all examples work with the most recent. but when running on the web, we want to link to the version that is in the website, which has a different path. by default `grunt yui` creates the production ready version. we defaulted to this to prevent people accidentally pushing broken docs to the web. `grunt yui:prod` also works and has the same effect as `grunt yui`. running `grunt:dev` creates a version linked to the local copy of p5.js so you can test locally. 

if you'd like to update the dev doc that'd be great, otherwise i will get to it in a week or so.

**Comment by limzykenneth** [comment]
Ok, thanks. The dev docs does mention it but it's quite obscure, for me at least, mentioning the `grunt yui:dev` at the very end of the wiki about inline docs. I'm authoring another issue, might edit the wiki after that, do have a look when you can so that I'm not giving any false information by accident.

**Comment by lmccart** [comment]
great thank you!
