### ISSUE TITLE
createGraphics not Translating

### ISSUE THREAD

**Issue by debone** [processing/p5.js#1200]
Hello,
I've found that when we create a Graphics instance, some transformations as `translate` and `rotate` do not work, while `skewX` for example, works.

```javascript
function setup() {
  createCanvas(200, 100);
  background(200);

  pg = createGraphics(100, 100);
  pg.background(100);
  pg.noStroke();
  pg.rect( 0, 0, 50, 50);
  image(pg, 0, 0);

  translate( 100,0 ); //Translate on canvas

  ph = createGraphics(100, 100);
  ph.background(100);
  ph.noStroke();
  ph.translate( 50, 50 ); // This line should translate ph, but has no effect anywhere
  ph.rect( 0, 0, 50, 50);
  image(ph, 0, 0);
}
```

This code outputs this:
![downloada](https://cloud.githubusercontent.com/assets/763457/12186709/7fe5de9c-b58c-11e5-9bba-bcb3689fc127.png)

When the *correct* should be:
![downloadb](https://cloud.githubusercontent.com/assets/763457/12186714/8ec428c4-b58c-11e5-8087-97f4d41b5e25.png)

**Comment by debone** [comment]
I found the problem, the p5.dom inserts `translate()` and `rotate()` into the `p5.Element` prototype and `createGraphics()` is returning a `p5.Graphics` which is a children of `p5.Element`, so p5.dom overwrites it to the translation of the canvas element.
Maybe this is related #645 but apparently is stalled. Anyone?

**Comment by lmccart** [comment]
yes, as @debone points out, the `translate()` and `rotate()` properties are getting overridden by the p5.dom library because the p5.Graphics object extends p5.Element. 

my suggestion would be that we remove the `p5.Element.rotate()` and `p5.Element.translate()` methods since these are already supported in the `p5.Element.style()` method.
http://p5js.org/reference/#p5.Element/style

here's the thread where these were added and some discussion around it.
https://github.com/processing/p5.js/pull/745

sound ok? @shiffman @futuremarc

**Comment by shiffman** [comment]
Sorry to be slow here, but yes agree that these should be removed!
