### ISSUE TITLE
Global namespace

### ISSUE THREAD

**Issue by i3games** [processing/p5.js#1210]
I just did 
```javascript
var location;

function setup() {
// ...
}

function draw() { 
// ...
}
```
and realized that variables are in the global (window, ...) namespace. It would be safer to have a default scope for the sketch without having to resort to "instance mode", as it can generate hard to understand errors especially for beginners.

**Comment by limzykenneth** [comment]
Not a bad idea but I can't imagine how it can be implemented without changing how a user write p5 fundamentally, more specifically, how would the library know if the particular function or variable belongs to the scope of the sketch and not to the global object or other objects? Also with the code you provided, calling `location` in say the `draw()` function would call the `location` variable in the sketch instance or the global instance?

Personally I find it easier to explain to beginner scoping with JS with global scoping because that feels more intuitive, a WYSIWYG kind of logic I guess.

Am I making sense? :P Let me know what you think.

**Comment by lmccart** [comment]
hi @i3games thanks for the suggestion. as @limzykenneth mentions, I think this adds a layer of confusion, even if it would make things nicer in some situations. one goal with p5.js is to be as transparent as possible and not do anything too tricky behind the scenes. the idea here is that if you move away from p5 to other javascript libraries or just plain vanilla js, you should be able to build on the same set of assumptions and expectations you've learned while using p5.js. I think the instance mode covers the case where some scoping is required and if you're at the level where you are dealing with multiple scopes of variables within one page, it shouldn't be too much of a stretch to learn the structure for instance mode.
