### ISSUE TITLE
error callback fails on load* by decrementPreload

### ISSUE THREAD

**Issue by action-script** [processing/p5.js#1229]
The p5 load functions ( loadImage, loadStrings... ) accept two callbacks (successCallback, failureCallback).
If the code implements the preload function, p5._getDecrementPreload will get the last argument, errorCallback, as decrementPreload and call it after success.

```
    if ((window.preload || (this && this.preload)) && 
        typeof decrementPreload === 'function') {
        return decrementPreload;
    } else {
       return null;
    }
```

So both callbacks, success and error, are called; but error has not arguments.
```
    var decrementPreload = p5._getDecrementPreload.apply(this, arguments);
    if (decrementPreload && (successCallback !== decrementPreload)) {
        decrementPreload();
    }
```

Doesn't matter if the loadImage function is called on preload, in an async function, or any other part of the code.

A quick example. p5.js/0.4.21
https://jsbin.com/yarigimanu/1/edit?html,js,output

Is this an error or I'm implementing a wrong practice?

**Comment by lmccart** [comment]
there are two options for using loadImage().
you can either call it with no callback functions inside preload, and the program will load the image synchronously. or you can call it with one or two callbacks functions anywhere else in the program (in setup for instance). if you mix the two, you will get unpredictable results, so this is not recommended.
here are examples of each option:
http://p5js.org/reference/#p5/loadImage

**Comment by action-script** [comment]
Thanks for the quick answer.

In the example that I posted, the loadImage with callbacks is on the preload function.
But the error happens if the loadImage is called out of the preload too.
Basically the error happens if you use a load* function with callbacks and you have preload implemented in your code. **Not necessary calling load* inside the preload function**.

I was just wondering if this scenario is considered.

Thanks for your time.

**Comment by lmccart** [comment]
ah i see, i misunderstood. thank you for the clarification. i'll look into this.

**Comment by raphaelschaad** [comment]
I see the same behavior: `preload()` implemented, `loadImage()` with succ and err callbacks implemented in `setup()`.

The callbacks *both* get triggered on success (err w/o argument) and *none* get triggered (but a "browser error" a la 404 Not Found instead) if I change the path to an image that doesn't exist.

Any update on this? Thanks!

**Comment by lmccart** [comment]
here is an example i'm testing with:
```javascript
var src = "http://lorempixel.com/1280/720/food/";
var data;

function preload() {
  console.log('preload');
  data = loadStrings('assets/test.txt');
}

function setup() {
  console.log(data);
  loadImage('assets/cat.jpga', 
    function(img){
      console.log('success', img);
    },
    function(error){
      console.log('error', error);
    });  
}
```
in this example, i am seeing this output
```
preload
sketch.js:10 ["I am a cat", "I like apples", "I have three feet", "I like my nose", "I smell like butter", "I talk like an orange"]
sketch.js:13 success p5.Image {width: 256, height: 256, canvas: canvas, drawingContext: CanvasRenderingContext2D, _pixelDensity: 1…}
sketch.js:16 error undefined
```

so I think the problem here is that you are trying to load an image from an external url which doesn't work due to the security restrictions of the browser when drawing into the canvas. an alternative would be to use `createImg()`, hide the DOM element created, and draw that element onto the canvas.
```javascript
var img = createImg(yourURL).hide();
    // Draw the image onto the canvas
    image(img, 0, 0, width, height);
```

hope this helps!

**Comment by raphaelschaad** [comment]
In your example above it seems p5js calls the error function even on success – is that expected behavior?

**Comment by lmccart** [comment]
oh interesting, you're right. no, it shouldn't do that. i will investigate.

**Comment by Teufeuleu** [comment]
Any news on this topic? Seems that the issue is still here at the time of p5js__1.4.1.
Even with preload() not being called, I get both success and error callbacks fired from a loadImage().
And it seems that the success callback is not fired once the image is fully loaded as expected, but immediately after loadImage.

But after some more investigation it seems that this does not happen (and loadImage works as expected) when callback functions are called without parenthesis. `img = loadImage(file.data, importSuccess, importError);` works as expected, but `img = loadImage(file.data, importSuccess(), importError());` demonstrates the behavior described above, as well as the arrow function syntax or declaring unnamed function as in @lmccart [example](https://github.com/processing/p5.js/issues/1229#issuecomment-208957892).

I made a [small patch](https://editor.p5js.org/tfl/sketches/9fZOVVG0h) to demonstrate this

I don't know if it's how it's supposed to be in js or if it's a bug in p5js, but at least I found a workaround to this 'issue'.
