### ISSUE TITLE
window.p5_noGlobals

### ISSUE THREAD

**Issue by hlfcoding** [processing/p5.js#1244]
#1210 brought this up, but doesn't seem to mention that globals (ie. `camera`, `print`):

1.  Makes embedding a p5 sketch into a parent js app difficult if there are conflicts in the global namespace.

2. Breaks the modules concept in js itself. I wouldn't be able to do (hypothetically):
  ```js
  import p5 from 'lib/p5';
  // or
  let p5 = require('lib/p5');
  ```
  without polluting the global namespace.

3. Is taking a _big_ risk in assuming browsers won't add these globals themselves in the future.

4. Is not taking advantage of the new language capabilities in ES6, but is enforcing an ES5 or ES3 programming style.

There should be an option to allow more advanced users to _opt into_ not polluting the global namespace, although that can be the default for beginners. Instead, if `p5.<method>` is too much typing, the sketch could:

```js
import {camera, print} from 'lib/p5'
```

**Comment by brysonian** [comment]
hello @hlfcoding! Does [instance mode](http://p5js.org/examples/examples/Instance_Mode_Instantiation.php) not cover this?

**Comment by hlfcoding** [comment]
@brysonian thanks! :bow: I should have read the [source](https://github.com/processing/p5.js/blob/ac42e37/src/core/core.js#L25), which is much more obvious than the site (I went to 'Getting Started' then 'Reference', didn't expect to search 'Examples'). Perhaps that page needs a copy update?

**Comment by lmccart** [comment]
i think it's a bit much for the getting started page, but it is covered in the p5.js overview tutorial: https://github.com/processing/p5.js/wiki/p5.js-overview

**Comment by hlfcoding** [comment]
Excellent stuff. I see from #78 there's been a great discussion already, but I don't quite understand why the code below isn't clear and simple on its own, as opposed to globals? Does simplicity need to come at the cost of safety and good coding habits?

```js
// classes/element.js

export Element = p5.createClass({

  constructor(x, y) {
    this.x = x;
    this.y = y;
    this.toggled = p5.color(0);
  },

  draw() {
    let fill = this.toggled ? p5.color(255) : p5.color(0);
    this.sketch.fillNext(fill).circle(this.x, this.y, 50);
  },

  toggle() {
    this.toggled = !this.toggled;
  }
});

// sketch.js

import Element from 'classes/element';
import p5 from 'libraries/p5';

let sketch = p5.createSketch('sketch-container-0'); // can be abbreviated however the user likes

let elements = p5.createCollection(); // perhaps also add a simpler collections type in p5?

sketch.start({

  setup() {
    sketch.createCanvas(300, 300);
    elements.add(10, (i) => { new Element(100, 10 * i) } );
  },

  draw() {
    sketch.background(0).fill(255);
    elements.each((e) => { e.draw(); });
    elements.selectRandom((e) => { e.toggle(); });
  }

});

// console:

// sketch.pause();
// sketch.stop();
// sketch.destroy();
```

Although full of things probably not in the current p5 API, this is also more idiomatic JS in it clearly associates functions with objects, a core concept in JS. The code now also reads more like an object-oriented (and functional) language, as opposed to a strictly procedural one, which can be actually more limiting and harder to write. Anyway, I know the Processing syntax is tried and true, but just a suggestion based on what I found missing in Processing as I grew beside it through the years. I also wrote in ES6 because it's on the horizontal and the code becomes shorter, although I'd consider a pre-packaged build system to bring much more possibility to any official p5 'starter kit', much like how the Processing editor works.

**Comment by lmccart** [comment]
The code is simple, but not as simple as the base case global. In the case of beginners with p5.js, we'd like to make the barrier to entry as low as possible, even if this comes at the cost of writing less "technically correct" code. The hope is that once someone gets interested enough to learn a little more, they may then start to understand about instance mode and namespaces and everything else on the web, but as a starting point, we assume they are just working with one p5.js sketch, so there is not likely to be a lot of issues with making all variables global. I think better this than turning some people off right from the get go because of unnecessary complication.

Of course, this is not the only approach, and maybe it is not even the best one, but it is the one we've chosen to base this platform on.

If you're curious, there is more about the goals and thinking behind Processing and p5.js here:
https://processing.org/overview/
http://p5js.org/community/
