### ISSUE TITLE
issues with cross browser support for deviceMoved() and deviceTurned()

### ISSUE THREAD

**Issue by karneaud** [processing/p5.js#1282]
Trying to use the _deviceMoved_ and _deviceTurned_ event listeners on **Mozilla/5.0 (Mobile; Windows Phone 8.1; Android 4.0; ARM; Trident/7.0; Touch; rv:11.0; IEMobile/11.0; NOKIA; Lumia 530) like iPhone OS 7_0_3 Mac OS X AppleWebKit/537 (KHTML, like Gecko) Mobile Safari/537**
and get the subject error in **p5.js line:18640**

```
p5.prototype._ondevicemotion = function (e) {
  this._updatePAccelerations();
  this._setProperty('accelerationX', e.acceleration.x * 2); // line 18640
  this._setProperty('accelerationY', e.acceleration.y * 2);
  this._setProperty('accelerationZ', e.acceleration.z * 2);
  this._handleMotion();
};
```

Is it that we need to do our own device support testing???

**Comment by karneaud** [comment]
Applied a fix for it by replacing the above code with
```
p5.prototype._ondevicemotion = function (e) {
  this._updatePAccelerations();
this._setProperty('accelerationX', (e.acceleration || e.accelerationIncludingGravity).x * 2);
  this._setProperty('accelerationY', (e.acceleration || e.accelerationIncludingGravity).y * 2);
  this._setProperty('accelerationZ', (e.acceleration || e.accelerationIncludingGravity).z * 2);
this._handleMotion();
};
```

**Comment by karneaud** [comment]
FY 

you guys should take a look at this https://github.com/tomgco/gyro.js/blob/master/js/gyro.js implementation of cross browser device event logic...might be useful for future versions

**Comment by limzykenneth** [comment]
`e.accelerationIncludingGravity` is typically used by devices with accelerometer but without gyroscope because they cannot compensate for gravity so the error most likely occur because the device you are using does not have a gyroscope and firefox is implemented so that it doesn't register anything with `e.acceleration`. See more [here](https://developer.mozilla.org/en-US/docs/Web/API/DeviceMotionEvent/accelerationIncludingGravity)

The problem with using `e.accelerationIncludingGravity` is that it logs a different acceleration than `e.acceleration` because of gravity (a vector of ~9.8m/s). The way gyro.js deal with this is to introduce a calibrate function and do away with the native implementation of `e.acceleration`. I would like to avoid this approach as depending on the situation, it might introduce new bugs.

I'll try to have a look at what's the best way to implement this if possible though.

**Comment by karneaud** [comment]
@limzykenneth oh...I see!

**Comment by lmccart** [comment]
We've tested this on Android and iPhone and are not able to reproduce. If you can clarify which device / browser combo is causing this issue we can revisit. Thanks!
