### ISSUE TITLE
canvas not visible when stored in pointer

### ISSUE THREAD

**Issue by cochsen** [processing/p5.js#1283]
The example [here](https://github.com/processing/p5.js/wiki/Beyond-the-canvas) generates a canvas with style property visibility: hidden

```javascript
var canvas;

function setup() {
  // We are still calling createCanvas like in the past, but now 
  // we are storing the result as a variable. This way we can 
  // call methods of the element, to set the position for instance.
  canvas = createCanvas(600, 400);

  // Here we call methods of each element to set the position 
  // and id, try changing these values.
  // Use the inspector to look at the HTML generated from this 
  // code when you load the sketch in your browser.
  canvas.position(300, 50);
  canvas.class("lemon");
}

function draw() {
  // These commands are applied to the graphics canvas as normal.
  background(220, 180, 200);
  ellipse(width/2, height/2, 100, 100);
  ellipse(width/4, height/2, 50, 50);
}
```
Must add
```javascript
  canvas.style("visibility", "visible")
```
to setup(). It seems like hidden should not be default.

**Comment by JamesJDillon** [comment]
What browser are you using? I'm running Chrome (Version 48.0) and the canvas is visible by default (in both my editor and Chrome). I'm having trouble replicating the issue.

**Comment by cochsen** [comment]
I'm using Chrome v49 (64-bit) on Windows 10

Here is the canvas tag  copied from Chrome inspector:
<canvas id="defaultCanvas0" class="lemon" width="600" height="400" style="visibility: hidden; width: 600px; height: 400px; position: absolute; left: 300px; top: 50px;"></canvas>

**Comment by limzykenneth** [comment]
The same is happening to me but changing `.class()` to `.addClass()` works. Why is there a `class()` function and why it's behaving like this? I'm not sure, I'll dig around in the source when I can. I'll report back.

**Comment by JamesJDillon** [comment]
[.class() method](https://github.com/processing/p5.js/blob/master/src/core/p5.Element.js#L106#L124)

[.addClass() method](https://github.com/processing/p5.js/blob/master/lib/addons/p5.dom.js#L978#L989)

It seems .addClass is a lot simpler. It checks if there's already a class name, and if there is then it just appends the param to it. If there isn't, it sets it. This requires p5.dom.js.

.class() does largely the same thing except it seems to alter the height and width. I can't outright spot why there'd be such a difference between the two.

**Comment by lmccart** [comment]
weird. i think those width/height lines are a mistake and should be removed! i can't think of any reason they should be in there.

we could also remove the entire .class() method if it still seems to be causing problems, since it is a bit redundant with .addClass() and .removeClass().

**Comment by limzykenneth** [comment]
Found the problem~

First of all the width/height thing is doing nothing but it's not the source (we should remove it anyway). 

Secondly, if I comment out the `.class()` in sketch.js I get DOM element like so:
![screen shot 2016-03-03 at 13 53 00](https://cloud.githubusercontent.com/assets/7543950/13496314/625ea610-e147-11e5-9dd3-ea02637206c0.png)

Note the empty class. The I changed the source for `.class()` from

```
this.elt.className = c;
```

to

```
this.elt.className = this.elt.className+' '+c;
```

and it works!

However I do think with the addClass function of p5.dom the class method of p5 is quite redundant except for when you want to retrieve class of a particular element which I think is majorly useful. Given that elements might have multiple classes it might be worth to return an array of classes instead of just the className string.

**Comment by limzykenneth** [comment]
I have some follow up to this. I was using instance mode to create 2 canvases and somehow if I don't explicitly ask for `visibility` to be `visible`, the first canvas will be hidden by default and it will have a `p5_hidden` class on it.

![screen shot 2016-03-12 at 9 51 09 pm](https://cloud.githubusercontent.com/assets/7543950/13725555/f40a4c0c-e89c-11e5-8c47-d77d953c0c06.png)

Looking at the source this is intended to show the canvas after `setup()` have finished running. Somehow the implementation [here](https://github.com/processing/p5.js/blob/master/src/core/core.js#L309) is not working and by simply using the commented out version at line 303 with the regex defined at line 307 the problem is solved. The regex and replace itself should be enough on its own without the need of the for loop.

@lmccart I have some free time that I can make a PR for what I mentioned and the `.class()` function I just need to know how would you prefer the `.class()` be implemented.

**Comment by lmccart** [comment]
I can work on this one. The reason it's getting hidden with the p5_hidden class is to prevent any page popping that may happen between the time a canvas is created and it is sized properly. Setting a class in setup causes an overwriting of the class p5_hidden which causes it to never get unhidden. I think a better approach would be to use a data attribute instead of relying on a classname for this. Let me look into this a little more.

**Comment by limzykenneth** [comment]
:+1:

**Comment by nsgonultas** [comment]
It still creates a hidden canvas for me. I'm using Ubuntu 14.04, tried with Firefox 46.01 and Firefox DevEdition 48.0a2. Any help please?
![screenshot from 2016-07-01 15 49 21](https://cloud.githubusercontent.com/assets/16865058/16522036/b6120e22-3fa3-11e6-8024-5e82d6abc63c.png)

**Comment by nsgonultas** [comment]
Adding a class to a canvas using `class` method makes canvas invisible. But it **didn't** make my div invisible.

![screenshot from 2016-07-01 16 12 07](https://cloud.githubusercontent.com/assets/16865058/16522463/9ac92b48-3fa6-11e6-8e7a-48a255665ca6.png)

**Comment by limzykenneth** [comment]
@nsgonultas is it only happening on firefox on ubuntu?

**Comment by nsgonultas** [comment]
@limzykenneth I can confirm it is happening on my Android 5.0.2 device and Chromium 51.0.2704.79 on Ubuntu.

**Comment by brt898** [comment]
it is same also on Windows 10, Firefox 43.0.1.
