### ISSUE TITLE
Documentation: How to construct p5.Color

### ISSUE THREAD

**Issue by cochsen** [processing/p5.js#1293]
Hello,

Currently I'm working on a jQuery mobile app for which I want to construct some p5.Color objects outside of setup / draw (so that I can manipulate their properties with UI widgets). I was able to create some variables using 
```javascript
var BG = p5.Color(40, 40, 40)
``` 
but got an error in the console:
**p5.js:9277 Uncaught TypeError: Cannot read property '_colorMode' of undefined**

However, the Color object is functional in spite of the error and I'm able to change it's properties (e.g. levels[]) in the console. Could the parameters for this be added to the documentation or is there another approach?

**Comment by lmccart** [comment]
calling p5 functions outside of setup(),draw(), or a function called by one of these methods will cause errors. it is best to declare the variables outside of setup but assign it inside. also, when creating a color, i'd recommend using the color() method.

http://p5js.org/reference/#p5/color

**Comment by cochsen** [comment]
Thanks for the response. I was able to set it up the way you described.

**Comment by lmccart** [comment]
great! we are working on adding better error reporting so this should be less confusing in the future.

**Comment by gwhitney** [comment]
Commenting from the project referenced just above: the problem seems even worse when one is using p5 from Typescript, in that if one declares, say, a class instance variable `myColor: p5.Color;` it will produce a complaint about myColor not being initialized; but it seems particularly tricky to initialize such a variable since even the default constructor as in `myColor: p5.Color = new p5.Color();` wants there to be a p5 instance, which there might not yet be at instance initialization time. We reviewed what seemed to be the relevant documentation and couldn't see whether there is a specific recommended pattern for p5.Color instance variables in a Typescript class. Any advice?

**Comment by davepagurek** [comment]
My suggestion is a little different, as it isn't *just* a P5.Color it waits on, but also P5, since you wouldn't be able to use the color anywhere before then anyway.

Another suggestion: store the color parameters that you would like to turn into a p5 color, and lazily create it once you have an instance:
```typescript
class MyClass {
  p5: P5.p5InstanceExtensions;
  
  constructor(private colorString: string) {}

  public initialize(p5: P5.p5InstanceExtensions) {
    this.p5 = P5;
  }
  
  private _color?: P5.Color;
  public get color() {
    if (!this.p5) {
      throw new Error('Cannot access color before initializing with p5!');
    }

    if (!this._color) {
      const color = this.p5.createColor(this.colorString);
      this._color = color;
      return color;
    }
    return this._color;
  }
}

```

Potentially it could use all default values if there's no p5 instance, but I could also see that leading to bugs when you change the color mode and maximum values (e.g. make the color channels be from 0-1 instead of 0-255) and colors made before setting that aren't affected.
