### ISSUE TITLE
problems with orientation display of images taken with iphone

### ISSUE THREAD

**Issue by wirsing** [processing/p5.js#1299]
Hi!

If I load an image with portrait orientation taken on the IPhone 6s it gets rotated by 90°. When I re-save it in the preview app it works correctly. 

```
function setup() {
      var canvas = createCanvas(450, 600);
      img = loadImage("pic.jpg");
      img.resize(450,600);
      image(img);
})
```

**Comment by wirsing** [comment]
Can anyone confirm? Apparently just happens when I shoot on the IPhone.

**Comment by lmccart** [comment]
hey @wirsing, could you post one of the iphone images that's causing this issue? i'll look into it further. thanks!

**Comment by wirsing** [comment]
hey @lmccart, thanks! here you go.. funny enough github displays it in landscape as well. really any IPhone 6s portrait photo does this.

![img_0739](https://cloud.githubusercontent.com/assets/938075/13753066/b4269b8a-e9ce-11e5-970e-8270d40e8049.JPG)

**Comment by wirsing** [comment]
just checked the metadata on http://metapicz.com and apparently height and width are swapped, so landscape. but the "orientation" field says "Rotate 90 CW". that might be the problem? if i re-save in preview height and width are correct for landscape and the orientation field says "Horizontal (normal)". it's more an apple thing i guess but if the orientation field could maybe help rotating it correctly again?

**Comment by lmccart** [comment]
thanks. ah i see. well i guess the todo here would be (1) access the orientation info (http://stackoverflow.com/questions/7584794/accessing-jpeg-exif-rotation-data-in-javascript-on-the-client-side) and (2) rotate the image accordingly if necessary. all of this would occur inside loadImage(). ideally we could do this without adding a lot of code to the library just to handle this one case.

one thing to note is that it doesn't seem to be the `.size()` method that's causing the rotation. from what i'm seeing, the image is incorrectly rotated even when there is no resizing. i have updated the issue accordingly.

however, because this is a sort of special case and not an immediate bug in the library, i'd place this as lower priority than some of the other issues we have open right now. that being said, if anyone would like to crack at it, please feel free.

**Comment by wirsing** [comment]
ah right, of course. i updated my comment as well. thanks!

**Comment by davejm** [comment]
@lmccart I'd like to try fixing this. I'd probably use the snippet from the stackoverflow answer. What sort of attribution would I use?.. A link to the answer?

**Comment by lmccart** [comment]
yes, a comment with a link to the answer would be great.
ah, so we can't access the EXIF data if we load the file via loadImage()?

**Comment by lmccart** [comment]
it seems like this issue is beyond the scope of p5, I'm going to close this for now
