### ISSUE TITLE
Bug in XML parser? Different results on same page using Firefox and Chrome

### ISSUE THREAD

**Issue by balain** [processing/p5.js#1304]
I'm trying to read an XML file created by Activiti (scratch.bpmn.xml) - valid XML file - and find different results from Firefox and Chrome on the same page. (Serving the page up via live-server or python -m SimpleHTTPServer both give the same result.)

The P5 XML parser (http://cdnjs.cloudflare.com/ajax/libs/p5.js/0.4.23/p5.js) works fine in Firefox (47.0a2 (2016-03-14)) but doesn't work on Vivaldi (1.0.422.8 (Developer Build) (64-bit)) or Chrome (Version 49.0.2623.87 m).

If you store the xml file in ./assets/, the attached js file in ./js/ and load the index.html page, you'll see. FF display "shapeTags.length = 6" but Chrome and Vivaldi both show "shapeTags.length = 0"

[scratch.js.txt](https://github.com/processing/p5.js/files/174215/scratch.js.txt)
[index.html.txt](https://github.com/processing/p5.js/files/174216/index.html.txt)
[scratch.bpmn.xml.txt](https://github.com/processing/p5.js/files/174217/scratch.bpmn.xml.txt)

If you need any additional details, please let me know. I've tried to reduce the report to the bare minimum.

Thanks!
John

**Comment by lmccart** [comment]
looks like the problem is the namespace (the colon). if you add a console.log(x) inside setup() you can see that the xml document is being returned properly, so I think you just need to find the right javascript for accessing the nodes inside. this is beyond the scope of p5, but this may be helpful: http://stackoverflow.com/questions/1083565/parsing-xml-namespaces.

**Comment by balain** [comment]
Perfect! Thanks for the rapid help and pointer -- just what I needed.
