### ISSUE TITLE
touchEnded fires while still touchDown [bug]

### ISSUE THREAD

**Issue by karneaud** [processing/p5.js#1313]
I'm using the following code 

```
function touchStarted() {
    hit = collidePointCircle(bottleCap.touchX, bottleCap.touchY, windowWidth/2, windowHeight/2, windowWidth/6);
    if(hit)
    {
      drawCircle('orange');

    }

}

function touchEnded()
{
    hit = false;
    drawCircle('grey');
}
```

when my finger is touching `touchStarted` fires but a while after `touchEnded` also fires while finger is still down. this happens on windows phone 8.1 with IE 10

does not happen in iOS

**Comment by karneaud** [comment]
anything on this?

**Comment by limzykenneth** [comment]
@karneaud Unfortunately I don't have a Windows phone so I cannot test this. I think it might be some compatibility issues with IE10. If possible can you try switching to IE11 or Edge and see if the problem persists?

**Comment by karneaud** [comment]
@limzykenneth how does one "switch" to IE11 or Edge on Windows Phone 8.1 :-/ ?

**Comment by limzykenneth** [comment]
@karneaud I'm afraid I'm not familiar with the windows phone ecosystem so I can't help you out there.

**Comment by karneaud** [comment]
lol...ok. will try to debug this when I get a change

**Comment by lmccart** [comment]
I've looked into this a bit and it seems to be a windows phone issue with unexpectedly firing touchend. Unfortunately since the event is coming from phone browser itself, there's not much we can do from a p5 perspective to address this.
http://stackoverflow.com/questions/30648033/on-windows-phones-ie-touchstart-event-ends-automatically-after-few-seconds
https://social.technet.microsoft.com/Forums/ie/en-US/0e939601-c14c-4637-b0c8-08277e850900/ie11-mobile-windows-phone-81-touchend-fired-without-user-action?forum=ieitprocurrentver
