### ISSUE TITLE
loadXML() results in error

### ISSUE THREAD

**Issue by FeliciaE** [processing/p5.js#1325]
Hello, 
I need to get a value from a web page and use this in my p5.js sketch. I do this by using the loadXML command, but it does not work. What I want to achieve is getting a string with the source code of the web page, so that I can get the value out of this string. I tried to do this with the following code:

<pre lang="javascript">
function setup() {
  createCanvas(200, 200);
  var url = 'http://creators.ewi.utwente.nl/site/s1712187/SmartPad/';
  loadXML(url, callback, error);
}

function draw() {
  
}

function callback() {
  print("it is callback");
}

function error() {
  print("it is error");
}
</pre>

"It is error" is the line that is printed when I run the sketch.
Who knows what my mistake is?? Of course the code should be extended by creating a string and reading the data etc. but first the loadXML function should load the html source code properly.

I tried replacing 
<pre lang="javascript">
  var url = 'http://creators.ewi.utwente.nl/site/s1712187/SmartPad/';
</pre>
by 
<pre lang="javascript">
  var url = 'http://crossorigin.me/http://creators.ewi.utwente.nl/site/s1712187/SmartPad/';
</pre>
But that gives me this error:
22532: Uncaught TypeError: Cannot read property 'documentElement' of null.

The only examples that I can find are based on JSON instead of XML.
Can you even load a HTML page using loadXML? If yes, what am I doing wrong??

**Comment by limzykenneth** [comment]
As you suspected, the original code failed because of cross-origin policy, I'm not sure if passing it through `crossorigin.me` have any unexpected effects so I'm not sure if that's where things go wrong. If you have control over the server you are using, try enabling CORS for that particular directory and see if you get the same error.

Also technically, HTML is not strictly speaking XML so that might be where it failed but I'm not that familiar with the implementation of `loadXML()` so take this with a pinch of salt...

**Comment by FeliciaE** [comment]
I have no clue on how to do that. I gave up on this :/

**Comment by limzykenneth** [comment]
@FeliciaE Just a tip, if you are just trying to display the webpage on another webpage, `iframe` will normally suffice. If you want to have deeper access to the DOM in the requested webpage, I've been there trying to do it and despite trying for almost a week it seems impossible. :disappointed:

**Comment by FeliciaE** [comment]
I need data from the webpage, and visualize it in my p5 sketch.
BUT, I found the problem. It had nothing to do with cross-policy. The problem is that when testing the p5 sketch, you run it at the local host. Apparently, this local host cannot load the webpage you are requesting data from. So when you want to test the sketch, you need to upload it to a webpage which is not local, and then it should work!! It worked for me. The sketch above works fine, just not in the local server!

**Comment by linux-man** [comment]
I can use loadStrings on a local server. Why loadXML give such problems? After all, loadStrings and parseXML should do the trick (I'm using atom live server).

**Comment by limzykenneth** [comment]
@FeliciaE hmm...Even when uploaded the sketch to a server online the sketch did not work on my side. The set of errors are the same, cross origin error in the first case and null object on the second case.

@linux-man I think the problem lies with requesting files from a remote server that did not enable CORS and as shown by the example you've given I don't expect there to be problems if requesting xml from the same origin (local storage or with relative paths etc.)

**Comment by linux-man** [comment]
Sorry to disagree. With a
  `xml = loadXML("/data/file.xml");`
I'm stuck with a "TypeError: resp is null".

**Comment by limzykenneth** [comment]
@linux-man No need to be sorry :smiley: 

Might be a silly suggestion but have you tried `xml = loadXML("./data/file.xml");`? 

Something like this works as expected for me:
```
function preload() {
	var url = 'data.xml';
    d = loadXML(url, callback, error);
}

function setup() {
    createCanvas(200, 200);
	console.log(d);
}

function callback(data) {

}

function error(err) {
    print(err);
}
```

**Comment by linux-man** [comment]
Now where're getting somewhere!
It seems that loadXML only accept a file with xml extension - other extensions give the previous error.
For now, it seems that I need to use the workaround I posted, unless you consider this to be a bug and correct it.
I'm glad you came to help.

**Comment by limzykenneth** [comment]
Under the hood p5 is using [reqwest](https://github.com/ded/reqwest) to handle XML loading, perhaps you can have a look, see if it helps. Glad to help anyway. :smile:
