### ISSUE TITLE
p5.js file won't open

### ISSUE THREAD

**Issue by yani1997** [processing/p5.js#1328]
when I try to open the file p5.js of p5.min.js a window pops up saying "Error: expected identifier Code: 800A03F2 Source: Microsoft JScript compilation error" 
I updated Java, tried downloading it on different browsers, restarted my computer... What else should I try?

**Comment by limzykenneth** [comment]
Hi @yani1997 

Can you give a bit more detail? Specifically how and with what did you "open" the file with and were you trying to open p5.js or p5.min.js?

**Comment by yani1997** [comment]
I went to http://p5js.org/download/ and clicked the uncompressed p5js file under "single files." I clicked on the download once it was done, and then the error message popped up. I did this twice on each of my browsers: chrome, explorer, and firefox.

**Comment by yani1997** [comment]
i just tried p5.min.js and it did the same thing

**Comment by limzykenneth** [comment]
@yani1997 Right, those you downloaded are actually the source code of p5.js which you will need a text editor in order to open, to demonstrate, try right clicking > open with > notepad / textEdit. You will then see the source of p5.js. However it probably won't be useful at this stage.

What will actually be more useful is the p5.js editor that can be downloaded on the same page. Once downloaded just launch the executable and you can start coding in p5.js. Also you might want to start with the [Get Started](http://p5js.org/get-started/) page although you can skip half of it until "Your First Sketch" if you are using the p5 editor.

**Comment by yani1997** [comment]
thanks!
