### ISSUE TITLE
Make it possible to pass an Array into random()

### ISSUE THREAD

**Issue by toolness** [processing/p5.js#1331]
I'm not sure how frequently people want to choose a random item from a list--perhaps it's not uncommon, since it's the third example for [`random()`](http://p5js.org/reference/#/p5/random)--but I thought it might be neat for the function to accept an Array as its first argument, so that the third example could be rewritten like so:

```js
// Get a random element from an array
var words = [ "apple", "bear", "cat", "dog" ];
text(random(words),10,50);  // Displays one of the four words
```

Previously this might have been confusing to document, but now that we can [document overloaded methods nicely](https://github.com/processing/p5.js/pull/1295), it might not be so bad.

Anyways, just a thought. Happy to submit a PR if others like the idea.

**Comment by limzykenneth** [comment]
I think it's very useful to have that or else it would be another block of code that I have to write, not sure if putting it under `random()` is best though. See what the others think.

**Comment by toolness** [comment]
Yeah, that's true, I'm not sure if putting it under `random()` is best either. An argument against it is that the return value is actually a list item rather than a floating-point number, which would complicate the documentation.

Perhaps `randomChoice()` instead? Naming taken from Python's [`random.choice()`](https://docs.python.org/2/library/random.html#random.choice).

**Comment by islemaster** [comment]
Personally I'd prefer a separate method as well.  Some other name options:
* `pickRandom` ([used by math.js](http://mathjs.org/docs/reference/functions/pickRandom.html))
* `sample` ([used by lodash](https://lodash.com/docs#sample))

**Comment by lmccart** [comment]
great idea.
there is actually precedence for functions that take either a single number or an array into random and return various types accordingly. nfs() is one example that comes to mind.

http://p5js.org/reference/#p5/nfs
documented more clearly in proceessing ref:
https://processing.org/reference/nfs_.html

i think since the functionality and naming is intuitive, it makes sense to overload the random() function, rather than adding another function name that users have to track down. the added syntax documentation feature helps clear things up, too.

**Comment by toolness** [comment]
Ok, will do! I'll wait until #1330 is merged, since they both deal with the same area of code.

**Comment by lmccart** [comment]
closed with https://github.com/processing/p5.js/pull/1456
