### ISSUE TITLE
p5.AudioIn not working in Chrome

### ISSUE THREAD

**Issue by DigitalWheelie** [processing/p5.js#1340]
Example: http://p5js.org/reference/#/p5.AudioIn

Inspect in Mac Chrome reveals:
"MediaStreamTrack.getSources is deprecated. See https://www.chromestatus.com/feature/4765305641369600 for more details."

**Comment by DigitalWheelie** [comment]
Also not working in Firefox:
"navigator.mozGetUserMedia has been replaced by navigator.mediaDevices.getUserMedia"

**Comment by limzykenneth** [comment]
Firefox is working for me, you need to allow the page to use your microphone, it will popup a dialog about this on the top left when the page loads. The message is just a warning about `navigator.mozGetUserMedia` being deprecated in favour of `navigator.mediaDevices.getUserMedia`. The feature detection is a bit out of date in some places in p5.js.

Chrome is not working not because of the warning you posted, that is also a deprecation message of `MediaStreamTrack.getSources` changed in favour of `MediaDevices.enumerateDevices()`. The real reason it doesn't work on Chrome is probably this message:

> getUserMedia() no longer works on insecure origins. To use this feature, you should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.

which is the same problem as any example that uses webcam on the p5.js site. @lmccart we might need to track down where else the library is using `getUserMedia` and add the relevant warnings like #1305.

@DigitalWheelie It would be very helpful if you can copy and paste this issue [here](https://github.com/processing/p5.js-sound/issues) because the code for p5 sound is not hosted here instead it has a separate repo. Thanks!

**Comment by DigitalWheelie** [comment]
You're right, the P5 demo page does work in Firefox. Cool.

Otherwise I found a similar issue on the P5 Sound page; added my info:
https://github.com/processing/p5.js-sound/issues/105

Thanks @limzykenneth!

**Comment by lmccart** [comment]
Thanks! I'm closing this and linking back to this info from the other issue.
