### ISSUE TITLE
Troubles gettin' a instrument frequency.

### ISSUE THREAD

**Issue by juanarbol** [processing/p5.js#1360]
I don't know how 'FFT' works, but, when you're trying to do a tuner, it does not recognize all the frequencies.

Here's my way to get the frequencies of the microphone, it works, but no for all.

var spectrum = fft.analyze();

  //we search the most big wave
  var freq_central = spectrum.indexOf(Math.max.apply(Math, spectrum));
  //we most convert the bin to a freq in Hz
  var freq = (freq_central*22100)/1024;

**Comment by limzykenneth** [comment]
@juanarbol I'm afraid I don't quite understand your question, specifically what do you mean by "do a tuner"? Anyway, p5.sound have its own repo and people contributing to it, you might get better help if you copy and paste this issue over [here](https://github.com/processing/p5.js-sound/issues).

Cheers.

**Comment by juanarbol** [comment]
This is a [tuner](https://youtu.be/TxZMe9DQohw?t=30s), it's use for 'tuning' all the instruments, I wanna do one but web, without java.

**Comment by limzykenneth** [comment]
Ah I see. I'm not sure if FFT and tuner uses anything fundamentally different to determine the pitch but that's my suspicion. What FFT does is basically analysing (or deconstructing) a given wave into many simpler waves. [This video](https://www.youtube.com/watch?v=u1Lz8pm2npQ) might help you understand it better.

**Comment by joecridge** [comment]
Hi @juanarbol. I think that the problems you are seeing are more likely to be due to the way that you are processing the frequency spectrum than with the FFT itself. For example, it is possible that some very low frequencies in the sample that you are using have a greater FFT amplitude than the fundamental frequency, and so finding the maximum amplitude will not necessarily give you the fundamental.

Could you plot the frequency spectra of two of your samples – one which ‘works’ and one which doesn’t – and post them here (or as an issue in the p5.sound repository)?

**Comment by juanarbol** [comment]
[Here](https://youtu.be/2IQvCOcHsGo) I explain my problem. Sorry for the spoken english, I'm from Colombia (I don't have good skills)

**Comment by joecridge** [comment]
It is difficult to diagnose the problem without viewing the frequency spectrum that the FFT is producing.

From your video it seems that you can tell which frequencies work with the tuner (e.g. E4) and which don’t (e.g. F2), so could you take a screenshot of the spectrum that you see with each of those two notes and post them here?

It would be especially helpful if you could also mark the actual frequency and the frequency that your tuner ‘thinks’ it is hearing on the plot.

**Comment by joecridge** [comment]
@juanarbol I have taken two samples from your video – one of the [E4 at 0:45](https://www.youtube.com/watch?v=2IQvCOcHsGo&feature=youtu.be#t=0m45.5s) (which works with your tuner), and one of the [F2 at 1:45](https://www.youtube.com/watch?v=2IQvCOcHsGo&feature=youtu.be#t=1m44.75s) (which doesn’t work).

This is what the frequency spectrum of the E4 looks like:

<img width="1218" alt="e4" src="https://cloud.githubusercontent.com/assets/11491479/14617991/616a9ffe-05a8-11e6-90da-f5f6a60e7a6f.png">

and this is the spectrum of the F2:

<img width="1194" alt="f2" src="https://cloud.githubusercontent.com/assets/11491479/14617996/683172d6-05a8-11e6-98db-dd8ac053918c.png">

The red line is the fundamental of the note (329.63&nbsp;Hz for E4, 87.31&nbsp;Hz for F2), and the yellow line is the frequency with the highest amplitude (which is what your tuner is identifying).

---

As you can see, the E4 guitar has its tallest peak at the fundamental frequency, and so the yellow and red lines coincide (your tuner finds the right pitch). The F2 note, however, has many tall peaks, and in fact the peaks of F4, C4, F3 and A4 (all harmonics of F2) are taller than the fundamental. This means that the red and yellow lines do not coincide, and so your tuner does not appear to work.

Essentially, your tuner needs to choose the *lowest frequency* peak rather than the peak with the *highest amplitude*.

Does that solve your problem?

**Comment by lmccart** [comment]
thanks @joecridge!

**Comment by Mayesss** [comment]
I think the real problem of the issue is not the frequency of the played note itself, the problem comes from the frequency detection. it's in P5.fft's analyser algorithm, it only detects 1024 frequencies, from 20hz to 20Khz, that is not percise enough.
fortunately for us the highest note that can be played's pitch is about 5Khz 
so the idea is to change the frequency range from **20hz --> 20Khz** to **20hz -->5Khz**. 1024 values within that ragne would be alot more percise.
but i don't know how to do that, please notify me if you found a way to do it.

**Comment by juanarbol** [comment]
Yes! I saw it few months ago, if I get another way I'll tell you, thanks for your colaboration!!

**Comment by Mayesss** [comment]
i found it! another way for detecting the pitch that is alot more percise, instead of using fft.anlyze() and searching the most big wave, you can use fft.waveform() and determine the pitch derectly from the wave length. there are several algorithms for doing that, i used the auto-correlate algorithm. inspired from https://github.com/cwilso/PitchDetect
here's how it should be done with p5:

//first declare these as a global variables
var buf = new Float32Array( 1024 );
var MIN_SAMPLES = 0;
var GOOD_ENOUGH_CORRELATION = 0.9;
var mic;

/*setting the input which is the mic in this case (do this under the setup function or any other function according to your code's architecture */

     mic = new p5.AudioIn()
     mic.start();
     fft = new p5.FFT();
     fft.setInput(mic);

//calling the autoCorrelate function
buf= fft.waveform();
freq = autoCorrelate(buf, sampleRate() );
// the variable "freq" should have the frequency of the note you are playing

//autoCorrelate function 
function autoCorrelate( buf, sampleRate ) {
	var SIZE = buf.length;
	var MAX_SAMPLES = Math.floor(SIZE/2);
	var best_offset = -1;
	var best_correlation = 0;
	var rms = 0;
	var foundGoodCorrelation = false;
	var correlations = new Array(MAX_SAMPLES);

	for (var i=0;i<SIZE;i++) {
		var val = buf[i];
		rms += val*val;
	}
	rms = Math.sqrt(rms/SIZE);
	if (rms<0.01) // not enough signal
		return -1;

	var lastCorrelation=1;
	for (var offset = MIN_SAMPLES; offset < MAX_SAMPLES; offset++) {
		var correlation = 0;

		for (var i=0; i<MAX_SAMPLES; i++) {
			correlation += Math.abs((buf[i])-(buf[i+offset]));
		}
		correlation = 1 - (correlation/MAX_SAMPLES);
		correlations[offset] = correlation; // store it, for the tweaking we need to do below.
		if ((correlation>GOOD_ENOUGH_CORRELATION) && (correlation > lastCorrelation)) {
			foundGoodCorrelation = true;
			if (correlation > best_correlation) {
				best_correlation = correlation;
				best_offset = offset;
			}
		} else if (foundGoodCorrelation) {
			// short-circuit - we found a good correlation, then a bad one, so we'd just be seeing copies from here.
			// Now we need to tweak the offset - by interpolating between the values to the left and right of the
			// best offset, and shifting it a bit.  This is complex, and HACKY in this code (happy to take PRs!) -
			// we need to do a curve fit on correlations[] around best_offset in order to better determine precise
			// (anti-aliased) offset.

			// we know best_offset >=1,
			// since foundGoodCorrelation cannot go to true until the second pass (offset=1), and
			// we can't drop into this clause until the following pass (else if).
			var shift = (correlations[best_offset+1] - correlations[best_offset-1])/correlations[best_offset];
			return sampleRate/(best_offset+(8*shift));
		}
		lastCorrelation = correlation;
	}
	if (best_correlation > 0.01) {
		// console.log("f = " + sampleRate/best_offset + "Hz (rms: " + rms + " confidence: " + best_correlation + ")")
		return sampleRate/best_offset;
	}

	return -1;
//	var best_frequency = sampleRate/best_offset;
}
