### ISSUE TITLE
Make the fourth argument of ellipse() optional?

### ISSUE THREAD

**Issue by toolness** [processing/p5.js#1368]
I accidentally called `ellipse(50, 50, 10)`, thinking it would just draw a circle, and it did nothing... I think there are two options:

1. Have the friendly error system raise/log an error telling the user to supply a fourth argument.
2. Simply default the fourth argument to the value of the third argument if it's undefined.

I kinda like option (2) because it echoes the way that `color()` works, e.g. where `color(25)` sets all R, G, B values to 25.

**Comment by limzykenneth** [comment]
Personally I prefer option 1 because I'm more likely to missed out an argument in `ellipse()` by accident and the error system throw me an error about invalid number of arguments, that's just me. 😉

**Comment by indefinit** [comment]
I'm a fan of option 2.  I don't just see this as a fix for error-leaning code, but rather a shorthand for those wanting to draw circles or squares and not have to type extra numbers.

**Comment by lmccart** [comment]
I can see arguments for both. I am thinking of a case where someone accidentally leaves out one argument and sees a default circle drawn rather than an error alerting them they are missing an argument. Would this cause more confusion? Is this case likely at all, or are the potential confusions here outweighed by the convenience of only have to type one number instead of two for squares and circles?

**Comment by sarahgp** [comment]
I'm very interested in option 2, too.

Imo, the circle drawing as a circle instead of an ellipse is enough of an "error" that it is ok not to throw in the case that users pass one arg when they should be passing two. And given that people tend to draw circles far more often than squashed ellipses, it seems like optimizing for that case is better.

**Comment by benjaminleonard** [comment]
I'm a fan of option 2 also. 9 times out of 10 that I use `ellipse()` I'm drawing a circle anyways.

**Comment by limzykenneth** [comment]
The scenario lined out by @lmccart is exactly what I had in mind. Let's say we have code as follows:

```
var x, y;

function setup(){
  // Setup value for x and y independently
}

function draw(){
  background(255);
  ellipse(10, 10, x);
  // where it should have been ellipse(10, 10, x, y)
}
```

If it did not threw an error and I missed it completely, I may be led to believe that `x=y`. On more complicated sketch it might even take some more time for someone to recognise that error. Personally I feel it is better to be more explicit than implicit.

**Comment by lmccart** [comment]
or even more confusing
```javascript
ellipse(10, x, x);
```

**Comment by indefinit** [comment]
@limzykenneth and @lmccart you make a good point, however I wonder if it's better to create a scenario where a user can make a mistake but see a shape drawn, versus make a mistake and see a red error.  No matter how friendly we make these error messages, an error that prevents code from running can break the flow of creativity, whereas an error that draws something unexpected has the potential for serendipity.

**Comment by lmccart** [comment]
hmm I hear that. with that point in mind, I'm fine with this. @shiffman curious if you have any thoughts here as well?

**Comment by shiffman** [comment]
Ooops, I missed this thread until now.   I like the idea of an optional fourth argument for `ellipse()`.  I think the worry about it leading to extra confusion is also a concern.   The precedent for this is `fill()` which can take 1, 2, 3, or 4 arguments (not to mention HSB vs. RGB) and does, in fact, lead to confusion. . . and ultimately comes down to documentation and examples.

I think the main reason this doesn't exist in Processing is due to the fact that overloading methods with multiple signatures in Java requires so much extra code and it would make it such a pain to maintain and document.    But this idea of an optional fourth argument seems native to the way things in JS tend to work so I'm ok with it if we want to try it out!

**Comment by lmccart** [comment]
I think the consensus is that this is at least worth a try, we can always revert if we find it adds confusion. I'l make the change.
