### ISSUE TITLE
Offline Documentation

### ISSUE THREAD

**Issue by ducklin5** [processing/p5.js#1378]
I'm sorry to have to bring up another one of these but the others I have seen just haven't answered the question, just keeps making me jump around GitHub. Is there an offline documentation (like an offline version of the site). I would just like the reference though not the whole site, as that seems to be pretty large.

**Comment by joecridge** [comment]
Since this has come up again (and because a lot of p5.js users are OS X users to), what would be really awesome is if we could arrange for the p5.js docs to be included with [Dash](https://kapeli.com/dash).

I don’t know how much effort would be involved in making that happen, but I think it would be indispensable!

**Comment by futuremarc** [comment]
That's a great idea to publish to Dash! I'll make this happen since I was trying to build an offline mode anyway

**Comment by dhowe** [comment]
Is this preferable to generating a set of docs on build to be included with downloads ?

**Comment by ducklin5** [comment]
I ended up using the original processing docs on zeal

**Comment by futuremarc** [comment]
@dhowe  ultimately both

**Comment by alelepd** [comment]
I also think having and offline docs would be nicer. So far Im using a .pdf reference from Processing because I noticed they are very similar.

My country suffers from a very drastic electricity problem (Venezuela); when the lights go out, the internet does too, so its very important to have offline resources to continue working and learning until the electricity is restored.

**Comment by BlandSauce** [comment]
The online reference seems to mostly work offline.
I downloaded everything from https://github.com/processing/p5.js-website/tree/master/
After also downloading jquery and changing the reference to it in /reference/index.html, it works offline almost 100%. The problem is that clicking links normally (or from search) only add the appropriate #anchor to the url bar. Opening in new tab instead works just fine. There's also some formatting issues with the code examples. I haven't dug around too much to see what all is actually needed, but it seems like an offline version could be figured out, then updated just by replacing the data.json already being generated for the online version.

**Comment by limzykenneth** [comment]
@BlandSauce I've made a proof of concept actually: https://github.com/limzykenneth/p5.js-reference

For this I'm just wondering what kind of format would best fit it: a offline website, a packaged app, a pdf or something else?

I'm a bit preoccupied at the moment but if anyone is interested, you can have a look at that repo. Cheers.

**Comment by dhowe** [comment]
From my perspective, an offline website (same as the online reference) would be ideal

**Comment by limzykenneth** [comment]
The problem with a offline website is that simply double clicking index.html would not work since features like videos etc would need to be run on a server, and I feel it's too much to expect someone to run a server to read the docs...

**Comment by dhowe** [comment]
Which videos are you referring to? The only problem I see loading index.html from your repo is that its using an AJAX request to fetch the json data...  otherwise most things work OK

**Comment by limzykenneth** [comment]
@dhowe I was thinking about [this one](https://p5js.org/reference/#p5/createVideo) but apparently there's no example then guess we don't need to worry about that. The ajax call for data.json can be fixed very easily so maybe it will work then? 😃

**Comment by limzykenneth** [comment]
@dhowe Sorry, I meant capture such as [this](https://p5js.org/reference/#p5/createCapture) but apparently the example was not enabled the maybe it won't be a problem after all. The ajax call to data.json can be changed rather easily I think so maybe this is possible. 😃

**Comment by lmccart** [comment]
This is great, so so useful and important. I think offline website makes sense, even if a few server-requiring features don't work. We could package it with the p5.js complete download.

**Comment by ducklin5** [comment]
Putting it  in the complete package would be great so long as its not too heft. Otherwise as a separate download. Wouldn't want to force users to download something they don't want

**Comment by lamarqua** [comment]
Please make it available offline.

**Comment by limzykenneth** [comment]
Good news! The prove of concept is fully working. Have a look [here](https://github.com/limzykenneth/p5.js-reference), it will work by simply double clicking on `index.html` at the root of the folder. I figure that will be easiest and not confuse any beginner with all the files they don't need to look at.

Essentially, it is just a strip down version of the full reference site at `p5js.org/reference`. The main changes that will differ between generating the reference for the actual site and this offline reference ishe variable name at the beginning, probably can be automated on build) from `data.json` and update that instead. Now the question is should this offline documentation be maintained as a separate project, pulling in changes other than `data.json` changes manually or should it be merge into the main p5.js project and create a build step to build it from the current reference files. The second option is a bit more work now and may include rewriting the way the reference is generated, not sure, but it sure does save time in the future and prevent errors. The code now could be a bit messy as well because I don't want to change too many things pending the decision on how to build this.

Kinda long update, let me know what everyone thinks! @lmccart @dhowe @futuremarc

**Comment by ducklin5** [comment]
I vote for the first option, a separate repo would be alot better to keep the p5.js repo slim

**Comment by lmccart** [comment]
I wonder if it is possible to host in a separate repo (to keep p5.js repo smaller), but to set up a github webhook and process that would automatically update somehow? this is just an idea... I haven't though too far into how complicated that would be code-wise.

**Comment by lmccart** [comment]
btw fantastic work on this! this is such crucial work, thank you!

**Comment by limzykenneth** [comment]
I like the idea of a webhook doing the update automatically. I'm not that familiar with github webhooks but I did find [this](http://stackoverflow.com/questions/30400104/automatically-copy-pushed-files-from-one-github-repository-to-another) on stackoverflow. There might be other ways but I can't think of any at the moment.

**Comment by lmccart** [comment]
yeah, something like that was what I was thinking. I can take a look at this part if you like, if you want to just set up a repo with the files and stuff to generate the docs?

**Comment by limzykenneth** [comment]
@lmccart That'll be great, I'll spend some time finalising the structure of the repo then.

**Comment by limzykenneth** [comment]
Pushed an update. Tried out many different ways to build, including building from source and some clever handlebars + cp action but I think the easiest is really to do what we are already doing for p5.js-website, copy the whole `reference` folder.

To setup a webhook, it can run the build on p5.js repo and generate the `reference` folder, push it to the offline docs repo's `dist` folder. On the offline docs side, another hook can be setup so that it runs its build on push generating `data.js` from `data.json`. To change the layout and design of the offline docs, relevant files are in `dist/offline-docs`.

To publish, simply package the contents of the `dist` folder and a user can simply just double click index.html. I'm still working to make it responsive.

**Comment by lmccart** [comment]
cool! I'll take a look at getting this all hooked up this week.

**Comment by lmccart** [comment]
hi @limzykenneth I took a look through your repo and looked into pushing things around between repos. the tricky thing about this is that we have to be running a node server, I couldn't find a very good way around this. so I decided the easiest thing was just to add this into the p5.js-website repo and let it build from there whenever the reference/ folder is updated. I basically just ported your gulp task to php, and copied a few of the files you modified.

if you hit this url: http://p5js.org/offline-reference/build-ref.php, it will rebuild the latest ref into p5-reference.zip, which can be found here: http://p5js.org/offline-reference/p5-reference.zip. you can check out the code here: https://github.com/processing/p5.js-website/tree/master/offline-reference.

I think I captured all your custom modifications in the port and copy but let me know if I missed any. if we're all good, I can set up a webhook that will ping that url to rebuild on reference change, and then we can add a zip download link to the online reference page and download pages somewhere.

thanks for all your work on this!

**Comment by limzykenneth** [comment]
@lmccart I think some styling rules are missing, probably from [`render.js`](https://github.com/limzykenneth/p5.js-reference/blob/master/dist/offline-docs/js/render.js#L198), they are used to accommodate browsing on mobile? Come to think of it, they might not be that important since there isn't really a way to read the docs on mobile at the moment. Anyway, this is what it looks like now:
![screen shot 2016-07-12 at 11 39 09 am](https://cloud.githubusercontent.com/assets/7543950/16764516/78c3d628-4826-11e6-9dab-20482d869d7c.png)

and this is what I have on my repo:
![screen shot 2016-07-12 at 11 39 24 am](https://cloud.githubusercontent.com/assets/7543950/16764525/8b26bbbe-4826-11e6-9777-a178069f587e.png)

Other than that, everything looks great! Pretty excited to get it out there.

**Comment by lmccart** [comment]
ok I think we're good! link added to the [reference page](http://p5js.org/reference/) and it will be included in future p5.js complete build zips as well. thanks everyone for your input and work on this! yaaay
