### ISSUE TITLE
save() method splits strings into arrays

### ISSUE THREAD

**Issue by jeremysykes** [processing/p5.js#1385]
I'm trying to save a string to text using the save() method.

eg. save('My super fun string', 'soundTranscript.txt');

but it gets saved in the text file like so:

M
y

s
u
p
e
r

etc.

**Comment by limzykenneth** [comment]
Because the first argument of `save()` when saving text is expecting an array, if you pass in string literal like `'My super fun string'`, it basically reads it as an array of individual character, hence the behaviour. For now, `save(['My super fun string'], 'soundTranscript.txt');` should work as expected.

We might need a little bit of rethink here in terms of saving text files.

**Comment by jeremysykes** [comment]
That works for me, after playing around with my code for a bit I was able to fix the problem I was having. Wrapping a string in an array is easy enough :)

**Comment by lmccart** [comment]
great!
