### ISSUE TITLE
Minor feature request - redraw()

### ISSUE THREAD

**Issue by emilyxxie** [processing/p5.js#1389]
I often find myself writing:
```
for (var i = 0; i <= n; i++) {
   redraw();
}
```
....for _n_ times I'd like to see something be redrawn, either for debugging purposes, or as part of the final sketch. Not sure if anyone else has adopted this habit, but if it's a popular enough pattern, I think it'd be great to be able to optionally pass in a positive integer argument into redraw() and only redraw for that given number of times----provided that such a feature does not go against any best practices.

I would not mind trying my hand at implementing this small feature myself either. Seems like a fun and quick way to start getting involved in contributing to the source code.

**Comment by limzykenneth** [comment]
@emilyxxie I would say go on ahead and implement this yourself! Might even be easier for us to see how useful for most people this could be once it is implemented. Cheers.

**Comment by emilyxxie** [comment]
Awesome---thanks. Just saw this response. I'll dive into implementing this as soon as I square away another project. Excited about this!

**Comment by nok** [comment]
I like your idea @emilyxxie, because with this feature the developers have more flexibility and control about changing variables. So I created this minor feature for us in PR #1498. Again, great idea and request!

---

There is still a failed test with the exception "code took too long to execute". On my local machine all tests passed successfully. I will check it.

**Comment by lmccart** [comment]
closed with https://github.com/processing/p5.js/pull/1498
