### ISSUE TITLE
Applying textures on beginShape()....

### ISSUE THREAD

**Issue by fernandovmac** [processing/p5.js#1402]
Hello P5js,

thanks for the awesome work 👯 

I'm facing an issue when trying to apply a texture on a custom made shape (beginShape(); curveVertex(); endShape();).
I managed, by following the references, to apply textures on primitives but for some reason it doesn't work when trying to apply for the shape - the shape doesn't display at all and I get console errors. I read on forums that this hasn't been enabled so far. Is it so? Or I'm I missing something?

Here's the link just in case: http://smokingtiger.aalto.fi

Any tips or work arounds are very welcome.
Cheers,
Fernando

**Comment by indefinit** [comment]
Hi @fernandovmac,

texture() is a function that's only available in WEBGL mode, which is why you're running into errors in canvas 2d mode.  In order to enable webgl mode, you just add WEBGL as a third parameter to createCanvas:
```
createCanvas(1250, 2700, WEBGL);
```

And then texture() should work with beginShape() endShape().  That said, we haven't implemented curveVertex() in webgl yet, so in order to acheive the effect your looking for you'll need to replace beginShape() endShape with either curve() or bezier() in webgl mode.  texture will work with both of those functions so you should be good to go.

**Comment by fernandovmac** [comment]
Hello @indefinit ,

Thanks a lot for the quick reply.

Just for the record, I did enable WEBGL previously - and changed back, for I didn't achieve the desired results. But now I know that the console errors (that were many and counting) were referring to the curveVertex() points that don't haven't been implemented in WEBGL.
I'll work out with the bezier(). 

Closing this issue, cheers!
