### ISSUE TITLE
windowWitdth

### ISSUE THREAD

**Issue by gregor** [processing/p5.js#1430]
Mapping the window.innerWidth value should be replaced by document.body.clientWidth as this will return the actual avaible space. innerWidth does not substract to the space needed for the scrollbar. Setting the width of your canvas to windowWidth therefore results in horizontal scrollbars.

**Comment by limzykenneth** [comment]
I tend to agree, just that it should be `document.documentElement.clientWidth` instead of `document.body.clientWidth` and also ignoring the scroll bar means that if content on the page is generated dynamically and at some point the content move from no scroll bar to having a scroll bar, value of `document.documentElement.clientWidth` would change where `window.innerWidth` won't.

**Comment by lmccart** [comment]
works for me!
