### ISSUE TITLE
loadTable and saveTable issues

### ISSUE THREAD

**Issue by deepgodot** [processing/p5.js#1436]
Hi,I have been trying to add a new row to a loaded table(new.csv) and save.
However, the saved(replaced) .csv file does not show proper data but this strange symbols as below.
�w^~)�.

Here is my code: 
var table; 

function preload() {
  table = loadTable("new.csv", "csv", "header");
}
/* this is what new.csv looks like.
id, species
1, a
2, b
3, c
4, d
5, e  <----- this row is what I want to add 
*/

function setup() {
  var newRow = table.addRow();
  newRow.setString("id", table.getRowCount());
  newRow.setString("species", "e");
  for (var r = 0; r < table.getRowCount(); r++) {
    for (var c = 0; c < table.getColumnCount(); c++) {
      println(table.getString(r, c));
    }
  }
  saveTable(table, 'new.csv');
}

The row is properly added when I println(table.getString(r, c)); but not in replaced new.csv file. 
I tried to save it with different file name as new1.csv but still doesn't work.
Could you fix this problem for me? Thank you.

**Comment by chiunhau** [comment]
saveTable() actually makes the browser automatically download a new file called new.csv or whatever you put. I guess you are using the p5 Editor because I found many people have similar issue with p5 editor, which also happen to me. 

See [this issue](https://github.com/processing/p5.js-editor/issues/210) and [this](https://github.com/processing/p5.js-editor/issues/236) as reference. However, saveTable() or other save functions work well in a general web browser. Try run your code in browser instead of p5 Editor 😄 

btw I think it's p5 editor's bug, not p5.js 👍

**Comment by lmccart** [comment]
thanks @chiunhau
