### ISSUE TITLE
rotate() function is not defined when using WEBGL mode

### ISSUE THREAD

**Issue by danazkari** [processing/p5.js#1472]
So I was reading through [Getting started with WebGL in p5](https://github.com/processing/p5.js/wiki/Getting-started-with-WebGL-in-p5) guide, and according to the **Translate, Rotate** section, `rotate` should be available in that mode as well, should work if provided with an array parameter `[x, y, z]` indicating on which axises should rotate.

I was wondering if either that guide is outdated and `rotateX`, `rotateY` and `rotateZ` should be used instead, or if this was a bug in the code.

Either way, I'd be more than glad to help out if I can.

**Comment by nok** [comment]
Have a look into the code of [rotate()](https://github.com/processing/p5.js/blob/ed5f0b6810d4181455980edd3321d4ad0fe09d30/src/webgl/p5.RendererGL.js#L434-L437) and the other mentioned [variations](https://github.com/processing/p5.js/blob/ed5f0b6810d4181455980edd3321d4ad0fe09d30/src/webgl/p5.RendererGL.js#L439-L452). As you can see, the partial rotation methods use the rotate method internally. So the following examples do the same:

```
function setup(){
  createCanvas(100, 100, WEBGL);
}

function draw(){
  background(200);
  rotateX(frameCount * 0.01);  // <---
  box(200, 200, 200);
}
```

```
function setup(){
  createCanvas(100, 100, WEBGL);
}

function draw(){
  background(200);
  rotate(frameCount * 0.01, [1, 0, 0]);   // <---
  box(200, 200, 200);
}
```

But notice, that the following examples don't do the same:

```
function setup(){
  createCanvas(100, 100, WEBGL);
}

function draw(){
  background(200);
  rotateX(frameCount * 0.01);  // <---
  rotateY(frameCount * 0.01);  // <---
  box(200, 200, 200);
}
```

```
function setup(){
  createCanvas(100, 100, WEBGL);
}

function draw(){
  background(200);
  rotate(frameCount * 0.01, [1, 1, 0]);   // <---
  box(200, 200, 200);
}
```

The variable `this.uMVMatrix` is an instance of `p5.Matrix`, because we apply a [matrix multiplication](https://github.com/processing/p5.js/blob/ed5f0b6810d4181455980edd3321d4ad0fe09d30/src/webgl/p5.Matrix.js#L548-L559). In general I recommend to use the single methods `rotateX`, `rotateY` and `rotateZ which allow more flexibility.

**Comment by danazkari** [comment]
That's a very good explanation and you got me sold on it. So... what about if I propose a small change to the docs so they reflect what you just posted above?

I'm just getting started with creative coding and I rely HEAVILY on docs. I volunteer myself to make the change although it'll have to wait till 10th of July at least (got like 3 important projects with same-ish delivery dates). So if someone else wanna do it, I'll be more than glad!!!

Again, @nok thanks sooo much for the explanation!

**Comment by lmccart** [comment]
hey @danazkari that'd be great if you want to make the change. thanks!

**Comment by indefinit** [comment]
Going to close this issue for housekeeping but feel free to reopen if you want to continue the conversation.  Thanks!
