### ISSUE TITLE
Equivalent of pTouchX/Y for objects in `touches[]`

### ISSUE THREAD

**Issue by omz** [processing/p5.js#1478]
For tracking multiple touches, it would be useful if the objects in `touches[]` had properties corresponding to the (single-touch) `pTouchX` and `pTouchY` properties.

While it's possible to track the previous locations of the touches separately, by using their `id` property as a key, this seems like a common-enough scenario that it might be useful to automatically include something like `pX`/`pY` in all touch objects.

**Comment by lmccart** [comment]
It's a good idea, but I think a bit beyond the scope of p5.js right now. Because the library is so broad (includes methods for interfacing with a lot of different browser functionality), we can't go as deep as a library dedicated to one particular function. However, it's designed to play really nicely with other JS libraries, and there are a lot of touch libraries out there, I think some of them should definitely do what you like. Here's a pretty comprehensive list of good ones: https://github.com/bebraw/jswiki/wiki/Touch.
