### ISSUE TITLE
windowHeight returns 0 in Firefox

### ISSUE THREAD

**Issue by xuv** [processing/p5.js#1479]
Using the basic example:  
`console.log(windowHeight);` returns 0 in Mozilla Firefox 47.0 (tested with p5.js v0.5.2 June 17, 2016)  
So does `document.documentElement.clientHeight`

Although `console.log(window.innerHeight);` returns an expected value.

**Comment by lmccart** [comment]
Hm, I can't seem to reproduce, which OS are you using?

This is the test code I'm using, does this cause the error for you?
```javascript
function setup() {
  console.log(windowHeight);
}
```

**Comment by xuv** [comment]
I'm using Linux 4.6.2-1-ARCH x86_64.
And yes that code is returning 0 when running the file locally.

**Comment by lmccart** [comment]
aha ok, must be a difference with linux. I'll investigate further, thanks.

**Comment by xuv** [comment]
Some more tests:
Using the `about:blank` page in Firefox 47.0, here is what this code produces:
```
console.log(window.innerHeight); // 990
console.log(document.documentElement.scrollHeight); // 8
console.log(document.body.scrollHeight); // 990
console.log(document.documentElement.clientHeight); // 8
```

**Comment by nok** [comment]
I guess that the [onresize](https://github.com/processing/p5.js/blob/master/src/core/environment.js#L342-L353) event doesn't be triggered initially. Because of that the default values for [windowWidth](https://github.com/processing/p5.js/blob/master/src/core/environment.js#L308) and [windowHeight](https://github.com/processing/p5.js/blob/master/src/core/environment.js#L319) are based on the `document.documentElement.clientHeight` and `document.documentElement.clientWidth` values (≠ `window.innerHeight` and `window.innerWidth`). So I created a [pull request #1494](https://github.com/processing/p5.js/pull/1494) with some fixes. Nevertheless @xuv should test the pushed suggestion and give further feedback please.

**Comment by xuv** [comment]
Hey @nok. Thanks for providing a fix.Unfortunately I can't test it at the moment. I'm having trouble building p5.js from source because of some segfault in the grunt process. Not sure where this is coming from. Nothing related to your code though.

**Comment by nok** [comment]
Okay, I exported the library with the pull request as a public gist for you: [p5.js](https://gist.githubusercontent.com/nok/d33e9f1c133c6f4c8e5fab6faee6ac1d/raw/0f087b6215ee4534e1412874bc2c6c3bb3470bb2/p5.js)

**Comment by xuv** [comment]
@nok thanks a lot for that. Tested. Your code works as expected. `windowHeight` returns a correct value on load.

**Comment by lmccart** [comment]
looks great, thanks for the fix and the testing all, i'll merge it in next chance i get!
