### ISSUE TITLE
capture = createCapture(VIDEO); Can we reference a different Camera on phone?

### ISSUE THREAD

**Issue by ashleyjamesbrown** [processing/p5.js#1496]
capture = createCapture(VIDEO);

Using this on a mobile phone web page generally in my small test calls the front facing camera.

Was wondering about extending so we can have a default, but also pass a parameter to call any other subsequent devices attached (or at least try to) so for example we can call the standard back facing camera ? Please forgive i have missed this in any documentation

Ashley

**Comment by nok** [comment]
On http://p5js.org/reference/#/p5/createCapture you will find the full documentation.

> More specific properties of the feed can be passing in a Constraints object. See the [W3C spec](http://w3c.github.io/mediacapture-main/getusermedia.html#media-track-constraints) for possible properties. Note that not all of these are supported by all browsers.

For instance possible constraints are listed on:
- https://w3c.github.io/mediacapture-main/getusermedia.html#media-track-constraints
- https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia

With the constraints you can define the video source. The following example works on my _desktop_:

```
function setup() {
  createCapture({
    audio: false,
    video: {
      facingMode: {
        exact: "environment"
      }
    }
  });
}
```

You can also test:

```
function setup() {
  createCapture({
    audio: false,
    video: {
      facingMode: "user"
    }
  });
}
```

Facing modes:

- **user**: The source is facing toward the user (a self-view camera).
- **environment**:	The source is facing away from the user (viewing the environment).
- **left**: The source is facing to the left of the user.
- **right**: The source is facing to the right of the user.

![screen shot 2016-07-01 at 15 53 25](https://cloud.githubusercontent.com/assets/670641/16523486/001f41ec-3fa4-11e6-971b-8eaffa6e34fc.png)

Image source: https://w3c.github.io/mediacapture-main/getusermedia.html#dom-mediatrackconstraintset-facingmode

Nevertheless you should check the [browser support](http://caniuse.com/#feat=stream) and read the security specifications (**https**):

> Security note: A new browser security specification requires that getUserMedia, which is behind createCapture(), only works when you're running the code locally, or on HTTPS. Learn more [here](http://stackoverflow.com/questions/34197653/getusermedia-in-chrome-47-without-using-https) and [here](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia).

Darius

**Comment by ashleyjamesbrown** [comment]
Thanks a lot i did read the reference i just didn't follow through the link to the other constraints.

Might be worth updating the demo as well btw as this doesn't show using any constraints at all - let alone my request.

And yeh - i have it on my own server online which has secure hosting. It also has to point to https:// for the scripts which i have hosted on my server as well.

Thanks a lot for the response

Ill do some more tests and report back to see if I can make it work.

**Comment by ashleyjamesbrown** [comment]
[Test:](https://ashleyjamesbrown.com/playcodeshare/camera.html)

If you wish to look. 

Even with the 'desktop' mode you suggest I cant show the image to the canvas yet the camera is clearly streaming. Can you let me know what i'm doing wrong.

**Comment by nok** [comment]
First of all the second sentence of the description of `createCapture()` is wrong:

> Creates a new <video> element that contains the audio/video feed from a webcam. This can be drawn onto the canvas using video().

```
sketch.js:14 Uncaught ReferenceError: video is not defined
```

It can't work with the `video()` method, because there isn't a method with this name.

---

Here is my working example:

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title></title>
  <script language="javascript" type="text/javascript" src="https://ashleyjamesbrown.com/p5js/p5.js"></script>
  <script language="javascript" type="text/javascript" src="https://ashleyjamesbrown.com/p5js/p5.dom.js"></script>
  <script src="sketch.js"></script>
  <style>
    video {
      display: none;
    }
  </style>
</head>
<body>
</body>
</html>
```

The method `createCapture()` creates a `<video>` element, which we want to _hide_.

```javascript
var capture;

function setup() {
  createCanvas(640, 480);
  var constraints = {
    audio: false,
    video: {
      facingMode: "user"
    }
  };
  capture = createCapture(constraints);
}
function draw() {
  image(capture, 0, 0, 640, 480);
  // filter(INVERT); // ;-)
}
```
For testing I use Google Chrome (Version 51.0.2704.103 (64-bit)): http://caniuse.com/#feat=stream

**Comment by ashleyjamesbrown** [comment]
Did not realise i needed a style tag element in the html. Thanks. 

It works fine in the browser and on the phone now and as you say it hides the capture automatically without calling the old function `capture.hide();`

This code though ```
 facingMode: {
        exact: "environment"
      }
```
does not change the phone camera to use the front facing one. On the desktop it calls the same webcam, on the phone it calls the front facing one the same as using _user_

Could we update the reference docs btw about that error line and the html line that needs to go in - i mean once we have a use for this working as currently it does the same as the standard code?

**Comment by nok** [comment]
> Did not realise i needed a style tag element in the html. Thanks.

Thanks, I didn't know this method, but in general it does the same: https://github.com/processing/p5.js/blob/master/lib/addons/p5.dom.js#L1451-L1465

The `hide()` method has the advantage, that you just hide the created and specific `<video>` element. The `css` way would hide all `<video>` elements.

The `user` mode should use the front camera. On the other the `environment` mode should use the rear camera. In your implementation you use the `user` mode.

The constraints will be passed to `navigator.getUserMedia()`, so it's a browser support issue.
https://github.com/processing/p5.js/blob/master/lib/addons/p5.dom.js#L985

I tested your implementation on my phone (Galaxy S6) with [Firefox for Android](https://www.mozilla.org/en-US/firefox/android/#) and [Google Chrome](https://play.google.com/store/apps/details?id=com.android.chrome&hl=de). By using the Chrome browser I just see a black box. By using the Firefox browser I see a stretched version of myself:

![screenshot_20160702-141030](https://cloud.githubusercontent.com/assets/670641/16540298/1500c6fa-4060-11e6-916e-b1bfd23188e0.jpg)

Using the phone was very laggy. I suppose because of the transformation from the `video` source to the `canvas` element. But I didn't test it.

In addition maybe the Chrome browser uses another technologies like the `mediaDevices.enumerateDevices()` and `deviceId` to select the right camera: https://webrtc.github.io/samples/src/content/devices/input-output/

**Comment by dimpapadop** [comment]
hallo.
I tried everything but the camera that opens in mobile phones is the face camera

anyone find a solution?

**Comment by lmccart** [comment]
here is an example of printing out available sources and then specifying one by id to use for capture:
https://github.com/ITPNYU/ICM-2015/blob/master/09_video_sound/02_capture/13_get_sources/sketch.js

**Comment by dimpapadop** [comment]
thanks @lmccart it was extremely usefull.!!!!!!!!!!!
I try to make it more generic for every phone... with no user input.

maybe like:
1. executing the function function gotSources(sources) { .... } to get the video sources Id's to a var or array.
for example  vid_device = sources[i].id;


after that  creating the options var.... somehow like:

  var options = {
     video: {
       optional: [{
         sourceId: vid_device  // instead of the actual string that's unique for every device
       }]
     }
   };

so we have not to place the string 'ahs8d8ssdsd99sd8d8d8s9sd8' etc that is unique for any other device.

How can i format the options var to get the vid_device's value;

excuse my ignorance i am new to js and also my english

**Comment by balsimpson** [comment]
I am trying to make a simple live feed using `createCapture(VIDEO)` on my Raspberry Pi. The problem is that when I access the sketch from my browser, the camera feed switches to my laptop camera. How can I ensure that the createCapture video source is the Raspberry Pi camera?

Thanks for any help.

**Comment by lmccart** [comment]
here's an example: https://github.com/ITPNYU/ICM-2015/blob/master/09_video_sound/02_capture/13_get_sources/sketch.js

@TODO add an example like this to the reference or examples page somewhere

**Comment by balsimpson** [comment]
thank you for the reply. maybe I wasn't clear in my question as to what I wanted to achieve. I want to use a live feed of a camera connected to my raspberry pi as the background image for my p5js sketch. So i can overlay other elements relative to this feed and track my cat movement to play a game. but i cannot seem to proceed because when I open to sketch from a different computer, the feed switches to the local camera from the laptop, which I don't want (it should only be using the raspberry pi cam)

so my question is:

1. do i need to use it in a different manner than `createCapture(VIDEO)`. Like using motioneye and pointing p5js to the images folder using `loadImage`

2. is there someway to specify the camera to be used for the original sketch?

Am still not sure if I've explained it clearly. So just for clarity, am repeating myself:

1. sketch uses raspberry pi cam live feed as background image.
2. when new user opens the page, they see objects and text overlaid on the source image(pi cam feed)
3. use motion detection to use cat movement to interact with the elements overlaid.

thanks for all the help. I tried your sketch but it only shows the camera attached to the local machine from which am accessing the sketch.

**Comment by limzykenneth** [comment]
@balsimpson `createCapture` will only capture the camera device attached to the browser host environment, meaning if you visit your sketch on your laptop, it will use your laptop camera and when you visit it on a Raspberry Pi, it will use the attached Raspberry Pi camera.

If you are thinking of streaming the Raspberry Pi camera feed footage to a sketch running on your laptop, you will be some kind of server setup. I would start with [WebRTC](https://webrtc.org) as a possible solution, others might have better suggestion.

**Comment by CharlesFr** [comment]
I get MediaStreamTrack.getSources is not a function, what have I missed?

**Comment by limzykenneth** [comment]
@CharlesFr does your browser support WebRTC? E.g. Safari doesn't support it yet

**Comment by CharlesFr** [comment]
I'm running it on Chrome Version 57.0.2987.133 (64-bit)

**Comment by limzykenneth** [comment]
@CharlesFr does [this example](https://p5js.org/examples/dom-video-capture.html) work? If it does then we will need to provide more detail about your sketch, if not then we need more detail about your setup.

**Comment by JoelStrawnCode** [comment]
This code though

 facingMode: {
        exact: "environment"
      }

Changed to: 

facingMode: "environment"

Worked for me.

**Comment by CheshtaKumar** [comment]
I'm trying to connect an IP Camera instead of a droidcam or webcam. Is it possible ? If yes, Please suggest on how to use an IP Camera with p5.js

**Comment by CheshtaKumar** [comment]
Hi 
I'm trying to integrate IP camera with p5.js .Is this possible ? If yes, Please suggest how can I do that.

Thanks in advance

**Comment by jywarren** [comment]
Hi! For the pi camera part, we've been able to stream to a canvas from a pi camera using this code:

https://github.com/publiclab/infragram/blob/23cafed8f62f4f7eb42bc195543c921c49372026/pi/index.html#L185-L191

...while the pi is running a pi camera web interface, we have a standard as card image you can use here, that also starts up a wifi net from the pi: http://publiclab.org/pi-camera

Hope that helps!

**Comment by jywarren** [comment]
Also I believe the demo here isn't working due to an API change in webrtc video... If that's correct I can submit a fix soon! Thanks all. 

https://p5js.org/examples/dom-video-capture.html

**Comment by jywarren** [comment]
False alarm, sorry -- it is working in that environment; the video is just cut off the side of the screen. https://github.com/processing/p5.js/issues/3699
