### ISSUE TITLE
Re-enable friendly error system's friendly file load errors

### ISSUE THREAD

**Issue by toolness** [processing/p5.js#1501]
While fixing #1500 I noticed that `loadTable` calls `p5._friendlyFileLoadError()` but it's basically a no-op because the friendly error system's `report()` function was disabled in 3591d3e3a5a77493f6ea8989754614671140a30a.

While I completely understand why `validateParameters` was disabled in 0dc421cdc660ab0858f0a055e18d8e90197523ff, as it's nicely documented in #971, I'm not clear on why `report()` was disabled. Were there problems with the friendly error system beyond `validateParameters`? Is it ok if we bring back just the functionality of `p5._friendlyFileLoadError()` so that users can receive friendly help when annoying situations like CORS errors come up?

**Comment by lmccart** [comment]
aha, yes the error and help suggestion should definitely get logged, this is an oversight. I had commented out this section because I felt that the overall design of the friendly error system might need a review... I got a few comments that the colors and extra language felt confusing, especially because it wasn't consistent throughout the library. but it makes sense to put this back in if that's the easiest fix for now, and the styling etc can be revisted on a later pass. alternatively, we could just use `console.log` for the message instead of `report`.

**Comment by toolness** [comment]
Ok cool!  I will file a PR soonish :)

**Comment by toolness** [comment]
Oh, also, is there a good beginner's guide on CORS in the context of p5/beginners? I thought I had seen one on the p5 wiki at some point but I can't find it now... Just trying to think of a good place we can link to from the console if the user wants to learn more.

**Comment by toolness** [comment]
Hi @lmccart, is there a beginner's guide to CORS I should link to from the friendly file load error?  Or should I write one up?

**Comment by lmccart** [comment]
sorry I started looking for one and forgot to respond here. I strangely haven't been able to find anything very useful though I feel like it must exist somewhere. if you wanted to write something up that would be fantastic!

**Comment by toolness** [comment]
No worries!  Sounds good, I think I may try writing one :grin:

**Comment by limzykenneth** [comment]
I found a very short mention [here](https://github.com/processing/p5.js/wiki/Loading-external-files:-AJAX,-XML,-JSON) but not really useful.

**Comment by lmccart** [comment]
reenabled with gsoc work
