### ISSUE TITLE
can i use pixels[] method in WEBGL context?

### ISSUE THREAD

**Issue by artofmus** [processing/p5.js#1502]
Hello! I saw neccesory great examples about react diff where Daniel Shiffman use pixels[] method, but if i try use this in WEBGL context i get error: 19124: Uncaught TypeError: undefined is not a function. How should I have to do to make it? Or waiting shaders implementation? Thanks!)

**Comment by nok** [comment]
Hello @artofmus, please read the manual of [pixels[]](https://p5js.org/reference/#/p5/pixels[]):

> Before accessing this array, the data must loaded with the loadPixels() function. After the array data has been modified, the updatePixels() function must be run to update the changes. 

For example:

```
loadPixels();  // <---
for (var i = 0; i < 4 * imgWidth * imgHeight; i+=4) {
  var red   = pixels[i];
  var green = pixels[i+1];
  var blue  = pixels[i+2];
  var alpha = pixels[i+3];
}
updatePixels();  // <---
```

Does it solve your problem? If not, then post your full application code please.

**Comment by artofmus** [comment]
Hello @nok i use this example, when i setup defoult renderer (createCanvas(..., ...)) all work but when i setup WEBGL renderer (createCanvas(..., ..., WEBGL)) i get error... (I try in p5 editor on windows)

**Comment by limzykenneth** [comment]
@artofmus I don't think `pixels[]` and the associated functions and properties are available in WEBGL mode, it doesn't really makes sense actually since there isn't a concept of pixels in 3D (WEBGL) space.

**Comment by noisefactor** [comment]
Well, I'm not sure it doesn't make sense. There used to be access to the raw pixels in the SGI stations I programmed in the 1990s even though I was simultaneously using 3D GL graphics routines.

**Comment by artofmus** [comment]
It would be convenient to use it, it's an quick alternative to the use of fragment shaders imho.

**Comment by nok** [comment]
Okay, but there are pixels on the canvas element. In detail the `HTMLCanvasElement.getContext()` method already provides `webgl` and `webgl2` as context type. So, why not?

**Comment by limzykenneth** [comment]
Admittedly my knowledge about 3D is pretty limited, so take a huge pinch of salt. 😉 From what I understand, it should be a bunch of points in 3D space and polygons with textures and shaders combined with the camera actually making them visible.

What I don't understand about using `pixels[]` with 3D mode is what would it store? A three dimensional array that somehow tracks "particles" and represent them without taking account scaling and camera position? The pixels that is currently rendered (or projected) on screen (in a sense what the camera sees in 2D)? The pixels of the specific texture targeted?

**Comment by noisefactor** [comment]
>The pixels that is currently rendered (or projected) on screen
YES

**Comment by limzykenneth** [comment]
@noisefactor Ok, that makes a lot more sense to me, I'm not sure how to do that but let's ping @indefinit

**Comment by nok** [comment]
If you are interested, I started an initial implementation of the [loadPixels()](https://p5js.org/reference/#/p5/loadPixels) method. I'm sure that there are some necessary steps. For instance in [line 142](https://github.com/nok/p5.js/commit/7eed9072a634dedfede0f3581cee5fbf6ff41f39#diff-cf7b699e117a9a29c971f1522616d033R142) I stored the pixels in the window object, what can't be the right way. Nevertheless the architecture is interesting and the implementation is (for me) a challenging task, because there are some proper differences between the `2d` and `webgl` context and the deeper implementation in p5.js. Anyway I want to share my first assessment to follow the next steps.

**Comment by artofmus** [comment]
@nok very interesting and cool!!! we wait and hope)

**Comment by indefinit** [comment]
hi @nok thanks for taking a stab at this.  This reminds me of a conversation over at the Three.js github a while back:  https://github.com/mrdoob/three.js/issues/4538

regarding your implementation, instead of storing the pixels array on the window object, you could do it on the p5 instance or renderer object like here: https://github.com/processing/p5.js/blob/master/src/core/p5.Renderer2D.js#L258

This basically reads the data off the gpu but in order to re-render to a display like updatePixels(), you'll need to upload the data as a texture similarly to how we are in [texture()](https://github.com/processing/p5.js/blob/master/src/webgl/material.js#L131)

@artofmus if all you want to do is manipulate a texture or render buffer on a per pixel basis, then a shader implementation is really going to be the simplest and most performative solution, but right now that method is a work in progress.  @mindofmatthew is very close to pushing the first cut of our new and improved public shaders api, and shaders in general are a big focus for us this summer.

Shaders path aside, I think there's definitely room for @nok 's loadPixels method, especially if someone wants to do collision detection based on gpu processing, so feel free to PR when ready.

**Comment by indefinit** [comment]
I'm going to close this issue for now, but feel free to reopen if you want to discuss more.
