### ISSUE TITLE
lines between quads visible with noStroke()

### ISSUE THREAD

**Issue by codeanticode** [processing/p5.js#1516]
This code:

```
var pts = [];

function setup() {
  createCanvas(640, 480);
}

function draw() {
  pts.push([mouseX, mouseY]);

  background(0);
  beginShape(QUAD_STRIP);
  noStroke();
  fill(255, 255);
  for (var i = 1; i < pts.length; i++) {
    var pt0 = pts[i-1];
    var pt = pts[i];
    var x0 = pt0[0];
    var y0 = pt0[1];

    var x = pt[0];
    var y = pt[1];
    var nx = -(y - y0);
    var ny = +(x - x0);
    var d = sqrt(nx * nx + ny * ny)
    if (0 < d) {
      nx /= d;
      ny /= d;
      vertex(x+10*nx, y+10*ny);
      vertex(x-10*nx, y-10*ny);    	
    }
  }
  endShape(); 
}
```

generates the following output:

![image](https://cloud.githubusercontent.com/assets/62246/16711290/150adb14-4622-11e6-8f4c-e92fcfcb9b60.png)

There are lines or seams separating consecutive quads... shouldn't be a continuous shape? I'm using most recent download version of p5.

**Comment by mikewesthad** [comment]
@codeanticode it turns out those seams are anti-aliasing effects. That'll happen with raw canvas if you draw two paths next to each other: [demo](https://codepen.io/mikewesthad/pen/zBEJbg). The background color will poke through because the shapes aren't perfectly touching.

![image](https://cloud.githubusercontent.com/assets/1131802/16717830/650d732e-46e0-11e6-9209-7510c950fe61.png)

The p5 shapes are created by breaking them into smaller pieces, so that each be independently colored. That has the unfortunate side-effect of those anti-aliasing gaps.

A fix for any sketches running into this bug - stroke (with weight 1) that matches the fill color.

**Comment by codeanticode** [comment]
@mikewesthad Thanks for your comment and fix! However, the fix is effective only if the shapes are completely opaque, but not if they are semi-transparent. Do you think is there any workaround in that case?

**Comment by mikewesthad** [comment]
@codeanticode oh, hmm. Are you looking for the shape to be able to "overlap" itself like this:

![image](https://cloud.githubusercontent.com/assets/1131802/16719314/8f875e68-46ee-11e6-91cd-e2ef6bff8f28.png)

If you aren't looking for that kind of overlap effect, my gut impulse would be to sidestep the p5 bug and  draw the path yourself using canvas methods. If you draw the whole shape using one path (via canvas's beingPath, lineTo, moveTo, closePath and fill) - no more anti-aliasing issue, so the shape can be semi-transparent without a problem. The other workarounds that come to mind would be a lot slower or more tedious.

**Comment by nok** [comment]
I created a workaround based on @mikewesthad input: http://codepen.io/nok/pen/bZoOkL

![screen shot 2016-07-11 at 10 26 11](https://cloud.githubusercontent.com/assets/670641/16724230/ff3373d8-4751-11e6-876d-8b3834ba9e38.png)

```
var pts = [];
var prev_mouse = undefined;

function setup() {
  createCanvas(640, 480);
}

function draw() {  
  background(0); 
  draw_pipe();
}

function mouseMoved() {  // <---
  // Data handling:
  if (typeof prev_mouse == 'undefined') {
    prev_mouse = [mouseX, mouseY];
  }
  var pt0 = prev_mouse;
  var pt  = [mouseX, mouseY];
  prev_mouse = [mouseX, mouseY];
  
  // Your code:
  var x0 = pt0[0];
  var y0 = pt0[1];
  var x  = pt[0];
  var y  = pt[1];
  var nx = -(y - y0);
  var ny = +(x - x0);
  var d  = sqrt(nx * nx + ny * ny)
  if (0 < d) {
    nx /= d;
    ny /= d;
    pts.push([x+10*nx, y+10*ny]);  // <---
    pts.push([x-10*nx, y-10*ny]);  // <---
  }
}

function draw_pipe() {
  // https://github.com/processing/p5.js/blob/657d46e088948c81ebdfb47297dcbd37c79a3cbc/src/core/p5.Renderer2D.js#L842-L865
  if (pts.length > 3) {
    this.drawingContext.fillStyle = 'rgb(255, 255, 255)';
    this.drawingContext.beginPath();
    var i;
    for (i = 0; i + 1 < pts.length; i += 2) {
      if (i + 3 < pts.length) {
        this.drawingContext.moveTo(pts[i+2][0], pts[i+2][1]);
        this.drawingContext.lineTo(pts[i  ][0], pts[i  ][1]);
        this.drawingContext.lineTo(pts[i+1][0], pts[i+1][1]);
        this.drawingContext.lineTo(pts[i+3][0], pts[i+3][1]);
      } else {
        this.drawingContext.moveTo(pts[i  ][0], pts[i  ][1]);
        this.drawingContext.lineTo(pts[i+1][0], pts[i+1][1]);
      }
    }
    this.drawingContext.closePath();
    this.drawingContext.fill();
  }
}
```

I think it's possible to trap this issue programmatically. But it will be an overhead to check whether the assigned points matched or not. What do you think?

Darius

**Comment by codeanticode** [comment]
@nok yes, this was helpful. For the time being I will use the moveTo/lineTo calls in my code. Thank you!

**Comment by mikewesthad** [comment]
@nok I had a local branch with a semi-fix for this that I just had a chance to push live: [here](https://github.com/processing/p5.js/compare/master...mikewesthad:fix-shape-gap?expand=1). It fixes the specific issue that @codeanticode was having (i.e. when a shape has the same fill/stroke throughout) by trying to minimize the number of canvas paths drawn.  If the fill/stroke is the same for all quads in the strip, then a single path can be drawn which avoids the anti-aliasing gap problem. I'm not sure there is anything reasonable that can be done when a single shape has multiple fill/stroke colors though.  Is that what you were thinking about as fix?

**Comment by nok** [comment]
Your (more) simple fix looks fine to me. You can create a push request. 👍

**Comment by mikewesthad** [comment]
@nox, on second thought, this fix would confuse users coming from processing.  Paths in processing are meshes, so a quad strip that overlaps itself ends up just layering faces on top of one another:

![image](https://cloud.githubusercontent.com/assets/1131802/16911342/86040674-4ca3-11e6-9b4c-3c6dfe35b971.png)

Whereas in canvas, the way a path is filled depends on the winding order ([ref](http://blogs.adobe.com/webplatform/2013/01/30/winding-rules-in-canvas/)). You can actually end up "subtracting" away from a filled area if you don't pay attention to the winding:

Initial quad strip:

![image](https://cloud.githubusercontent.com/assets/1131802/16911478/542ed1a0-4ca4-11e6-9c91-e5e8042da36f.png)

Adding a quad face that "subtracts":

![image](https://cloud.githubusercontent.com/assets/1131802/16911497/68ed1264-4ca4-11e6-99c5-5374d1a7a86e.png)

The current p5 implementation is probably best, so this issue should stay closed.

**Comment by SirCodyC** [comment]
I've encountered a similar issue and came up with a quick-fix work-around using `pixelDensity()`. This may not be effective for all purposes, but I've decided to share it, since this one line of code may be a big time saver for those with artistic application.

Flower Generator (p5.js Web Editor) --> [https://editor.p5js.org/cody.crary78/full/VbF4i1aXI](url)

This program efficiently draws flowers by drawing a "half-petal", reflecting it over the x-axis, and then rotating all of the half petals about the origin a variable number of times. Since the petals meet on the lines of symmetry, there are seams because of the anti-aliasing effects. Just like the quad-problem of this thread, it only occurs on diagonals.

![image](https://user-images.githubusercontent.com/71479568/103595876-6d9b3c00-4eb1-11eb-820e-5119d06202a8.png)

However, if you increase the pixel density in the setup, the seams are "filled in" with the increase in resolution. 
```
function setup() {
  createCanvas(600, 600);
  pixelDensity(16); //<--------- The default value is 1, so 16 increases the density.
}
```
![image](https://user-images.githubusercontent.com/71479568/103596155-1a75b900-4eb2-11eb-917c-62d05f1faf58.png)

Since I am interested in image output, I am less concerned with the resulting taxation on program performance that may result from increasing pixel density. However, this may be a concern for some.

May this be of help to someone with a similar issue. - Cody

**Comment by antlii** [comment]
Sadly the issue is still in place, and changing the pixelDensity doesn't help as in the example above from Cody, at least in this case: 

https://editor.p5js.org/antlii/sketches/ciGutZGYy  

```
let cols = 17;
let rows = 13;
let xArr = [];
let yArr = [];

function setup() {
  createCanvas(600, 600);
  noStroke();
  fill(255);
  pixelDensity(10); // Changing pixelDensity makes no difference
  rectMode(CORNERS);
}

function draw() {
  background(0);
  
  for (let x = 0; x <= cols; x++) {
    xArr[x] = map(x, 0, cols, 0, width);
  }
  
  for (let y = 0; y <= rows; y++) {
    yArr[y] = map(y, 0, rows, 0, height);
  }
  
  for (let x = 0; x < cols; x++) {
    for (let y = 0; y < rows; y++) {
      rect(xArr[x], yArr[y], xArr[x + 1], yArr[y + 1]);
    }
  }
  
  noLoop();
}
```

![untitled (2)](https://github.com/processing/p5.js/assets/52974033/a9ed2f55-6977-44de-b46e-ebb912694ca0)

I wonder why in one scenario increasing resolution with pixelDensity helps to avoid gaps between figures, but in such a seemingly simple case it just doesn't.

Interestingly, rounding values like **round(xArr[x], 1)** does not improve the situation, the problem is still there. Only rounding to an integer value negates the effect.  

Maybe anyone has any other thoughts on this. I wonder if I'm missing something, I'm getting really confused.

**Comment by limzykenneth** [comment]
@antlii If the coordinate values provided are not rounded to integers, it will attempt to draw as subpixel drawing. Subpixel drawing is not precise as there are no subpixels, only simulation of it by drawing existing pixels semitransparently, as such there is no guarantee that it will mesh perfectly.

**Comment by davepagurek** [comment]
For the original issue mentioned (specifically, the quads in `QUAD_STRIP`, and not all adjacent shapes in general), currently we are drawing each quad as a separate path. We start a new path within the for loop over quads here: https://github.com/processing/p5.js/blob/3cf3cd2c061a407580eee8c10f77ad0842c87390/src/core/p5.Renderer2D.js#L1047-L1050
...and close the path here: https://github.com/processing/p5.js/blob/3cf3cd2c061a407580eee8c10f77ad0842c87390/src/core/p5.Renderer2D.js#L1069

Would `QUAD_STRIP` still work if we move those out of the for loop so the whole thing is one path?
