### ISSUE TITLE
replace binding in p5 with custom bind to improve speed

### ISSUE THREAD

**Issue by lmccart** [processing/p5.js#1522]
follow up from https://github.com/processing/p5.js/issues/1512#issuecomment-232378970

@mikewesthad has done research into this already and is working on a patch

**Comment by mikewesthad** [comment]
After doing some further research, I don't think this is the right change to make.  

A custom bind definitely speeds up p5 in the p5 editor, but it doesn't appear to do much in the browser.  It speeds up a couple methods (particularly random), but also appears to slow down some methods (at least, sin).  That slowdown of sin is a little troubling and suggests that a change like this needs some more thorough performance testing.

**Conclusions**

Editor: My thought is that the V8 engine powering the p5 editor (nw 0.12.3) is out-of-date with respect to bind optimizations.  I'm guessing that by updating the editor's engine, we'll get speed boosts without having to touch the p5 source.

Browser: Given that this change might speed up some methods and slow down a couple, this issue could be revisited after some general performance tests have been worked out (#1524).

**Results**

```
* = speed up
- = speed down

p5 Editor
random:        1841ms    ->    373ms  *
sin:           2368ms    ->    439ms  *
noise:         4091ms    ->    2242ms *
millis:        6581ms    ->    3858ms *
createVector:  4305ms    ->    2419ms *
text:          3929ms    ->    3236ms *
background:    526ms     ->    458ms
fill:          2385ms    ->    1966ms *
color:         1872ms    ->    1475ms *
rect:          2347ms    ->    2279ms

Chrome:
random:        268ms    ->   197ms *
sin:           364ms    ->   424ms -
noise:         2035ms   ->   2089ms
millis:        1974ms   ->   1995ms
createVector:  1268ms   ->   864ms *
text:          3867ms   ->   3894ms
background:    1338ms   ->   1337ms
fill:          5998ms   ->   5610ms
color:         4791ms   ->   4810ms
rect:          1666ms   ->   1702ms

FF
random:         438ms   ->    268ms *
sin:            45ms    ->    48ms
noise:          229ms   ->    242ms
millis:         105ms   ->    110ms
createVector:   539ms   ->    555ms
text:           2255ms  ->    2433ms
background:     56ms    ->    60ms
fill:           173ms   ->    173ms
color:          107ms   ->    109ms
rect:           921ms   ->    895ms

```

**Custom bind**

```js
var methodBind = function (pInst, p) {
    return function () {
        return p5.prototype[p].apply(pInst, arguments);
    };
};
```

Instead of doing this in core.js:

```js
friendlyBindGlobal(p, p5.prototype[p].bind(this));
```

Do this:

```js
friendlyBindGlobal(p, methodBind(this, p));
```

**Comment by lmccart** [comment]
thanks @mikewesthad for the research. based on what you've written, I'd agree with this analysis and revisit the idea of custom bindings after making progress on #1524 performance testing. I'll also look into updating nw version for the editor.
