### ISSUE TITLE
Parameter to read up to a number of lines

### ISSUE THREAD

**Issue by p10petr** [processing/p5.js#1530]
You should alter the loadJSON() function to take an additional parameter which denotes the number of lines to read (Should we not want to read the entire file)

**Comment by lmccart** [comment]
since JSON files are built around object notation, choosing a number of lines could result in errors by breaking up objects in the middle. restricting the line load wouldn't really reduce the file load time anyway since the whole file is loaded as one before any parsing of the content happens. I would suggest creating a json format where you can easily select the data you'd like to access and ignoring the rest.
