### ISSUE TITLE
How to rotate images?

### ISSUE THREAD

**Issue by 123madskillz** [processing/p5.js#1534]
There seems to be no tutorial on the p5 js website. Is this because rotating images is a pain in the ass to do in p5 js, or just because nobody has gotten around to doing it. (if rotating images in p5 is hard, this should be fixed because this is a feature that most beginners would want)

**Comment by lmccart** [comment]
in p5, drawn shapes or images are not rotate directly, instead the entire drawing matrix can be rotated (or scaled or translated). the [`rotate()`](http://p5js.org/reference/#p5/rotate) function should achieve what you want, `push()` and `pop()` may also be useful.

we should definitely get a tutorial about this up on the p5js.org site, but for now, the processing tutorial is a pretty good resource: https://processing.org/tutorials/transform2d/.

@tegacodes was there someone working on the transforms tutorial port? I seem to recall someone working on this at some point..

**Comment by 123madskillz** [comment]
Ah, I see. It wasn't clear that the matrix functions also applied to images, whoever is writing the tutorials should clarify that.

**Comment by oliviaiscool** [comment]
@lmccart @123madskillz 

I don't know if this will be helpful at all, but I tried converting the Processing tutorial to p5.js and included a couple of examples. 

[2D Transformations in p5.js](https://github.com/oliviaiscool/transformations-p5js/blob/master/README.md)

**Comment by 123madskillz** [comment]
Very nice!

**Comment by Wildernesss** [comment]
Hi everyone. There was a request about image transformation (**rotation**) that was closed 3 in 2016 (https://github.com/processing/p5.js/issues/1534)... I don't really understand why. Because this request is full well founded but apparently no improvement of p5.js in that direction has ever been done. Am I missing something? With p5.js it's easy too transform image color with filters (for instance a color image transformed into a gray scaled image), but apparently there is no function to transform image with a rotation (when I write 'transformation', that means real image pixels transformation, no the way image is drawn on canvas9. If I understand it well, the only one mean is to rotate canvas before drawing the image on the canvas. This can be usefull in certains circumstances, but that transformation of reference point is something very complicate to understand for beginner. I'm not saying here the canvas rotate statement should disappear but that in parallel there really should be more basic transformation on image object available (I mean transformation of image itself, not the canvas), like the basic that is orientation. Something that could be easily improved into p5.js. At least it would be great! Thanks to the whole p5.js development team for their great work! Laurent
