### ISSUE TITLE
Changing options in a select created by `createSelect`

### ISSUE THREAD

**Issue by kwichmann** [processing/p5.js#1554]
I miss a method for changing existing options in a select. Detailed access to these would be a nice addition.

**Comment by Sundftig** [comment]
I noticed even that is impossible (at least for me) add more than one "createSelect". 
If I try to add a series of dropdown menu I can only see the first one. 
The console give me also an error:

`11487: Uncaught TypeError: Cannot read property 'bind' of undefined`

I don't know if this is a bug or my mistake.

**Comment by nok** [comment]
@kwichmann: It shouldn't be hard to implement that request or feature.

Here is the playground: https://github.com/processing/p5.js/blob/204ad04a58ddb39ad96518674da9dd378ca394ce/lib/addons/p5.dom.js#L554

What's the opinion of the community and other developers? Is it useful?

---

@Sundftig: It's still working. Here is an example: http://codepen.io/nok/pen/LkqqBE

If you need help with your sketch, you can share it here.

**Comment by frontwin** [comment]
I would like to work on this issue. So tell me what is the best approach to do this.

**Comment by lmccart** [comment]
hey @frontwin, I think this line that @nok has marked is a good starting point: https://github.com/processing/p5.js/blob/204ad04a58ddb39ad96518674da9dd378ca394ce/lib/addons/p5.dom.js#L554. 

the basic approach would be:
1. search for a child option that has the given name.
2. if name is found, if value is given (2nd argument), update the value. if no value is given, remove the option altogether.
3. otherwise, follow the existing code for adding a new option.

**Comment by frontwin** [comment]
Hey , I think we should not search child on the basis of name because in
SELECT two or more OPTIONS can have same name but not value.

1. So in order to perform operation on a unique element we need a unique
search key like VALUE not name.
2. When creating the "  sel.option('name')  "  if we dont pass value as
second parameter it follows [value=name] so when we are giving new name to
an element
we must check that if the founded one has value==name. If its true we must
remove it and add new element else we can change innerHTML.

example as a good coding practice to follow:

sel.option('mango)  ==> means val='mango'  name='mango';
Now   it cannot be changed to val='mango' name='orange' so we create new
option('orange') and remove mango

but   val='1' name='mango' can be canged to ==> val='1' name='orange'.


Please suggest me if i am wrong with these cases or should follow the above
mailed rules.

Thankyou
Sharang

**Comment by lmccart** [comment]
Ah good point. This sounds right, I'd go ahead with this as you've described in the cases.

**Comment by frontwin** [comment]
//This is the final code for the above issue with all cases handled.Happy
to hear any suggestions .Do i need to check typeof( argument[i] )
//before implementing logic.



  self.changeOption = function( name, value, newname, newvalue )
  {
       var found=0;

    if( arguments.length < 3) return this;

    if(arguments.length >= 3)
    {

      for(var i=0; i<this.elt.length;i++)
      {
        if(value.toString()==this.elt[i].value)
          {  found=1;


              if(value.toString()==name && arguments.length!=4){
                  this.elt[i].innerHTML=newname;
                  this.elt[i].value=newname;
                  console.log('case1');
              }
              else if(value.toString()!=name && arguments.length!=4)
              {
                this.elt[i].innerHTML=newname;
                console.log('case2');
              }
              else
                {
                 this.elt[i].value=newvalue;
                 this.elt[i].innerHTML=newname;
                 console.log('case3');
              }
          }
      }

    }

    if(found==0)
    {
      if(arguments.length==3)
      {
      this.option(newname);
       }
      else
      {
      this.option(newname,newvalue);
       }

    }

  }

**Comment by lmccart** [comment]
I don't think it's necessary to make an additional method called `changeOption()`, I think we could just overload the existing `option()` method. In this case, the logic will need to be adjusted a bit to detect whether an existing option needs to be updated, or whether a new option should be added.

**Comment by dhowe** [comment]
status?

**Comment by DarkPrince304** [comment]
Working on this.
