### ISSUE TITLE
loadImage fails on some images

### ISSUE THREAD

**Issue by Artimbocca** [processing/p5.js#1557]
In processing, loadImage works fine on all three images below, in P5.js only the first one loads, the second and third do not.

function setup (){
  canvas = createCanvas(windowWidth,windowHeight)
  img1 = loadImage('http://molcat1.bl.uk/IllImages/BLCD/big/G700/G70031-13a.jpg')
  img2 = loadImage('http://dspace.bcucluj.ro/bitstream/123456789/52968/1/BCUCLUJ_FCS_ILUSTR_7398.jpg')
  img3 = loadImage('http://www.nli.ie/glassplates/STP/STP_1622.jpg')
}

function draw(){
	image(img1, 200, 200)
}

Thanks for the great work with p5.js, I have been using it for a while now, this is the first serious problem I have. 

Best, Jos

**Comment by limzykenneth** [comment]
The second and third image are protected under Cross Origin Resource Sharing (CORS) policy which means that they cannot be served by another website/domain. There are a few ways to get around this issue but for the above images, you can just download the images and serve them directly from the sketch's folder and use relative links.

**Comment by Artimbocca** [comment]
Thanks Kenneth. Glad to hear this is not a P5 issue. I am curious to hear what ways there are to get around this. I am building an interface that allows visitors an alternative way to explore the (millions of) images and videos accessible through the Europeana “meta” collection. Downloading the images first to my server and then to the client would clearly not be ideal.

 

Please feel free to ignore this, I should and will investigate this further, but this CORS thing is new to me, so any help is appreciated.

 

Best, Jos

**Comment by limzykenneth** [comment]
Happy to be of help!

The more I guess orthodox way of enabling CORS is for the server to enable it by including 

```
Access-Control-Allow-Origin: *
```
on the response header. Since the images you found are not from a server you control, you will need to find a link where the images can be accessed with the above header. Some sites will have them by default, others might have them on a special domain or request url. It might be worth asking the server admin if they can enable it especially if they are of academic sources.

Failing that, there are hacks around it that I have heard of but knew not much about so you can hunt around a bit for that.

**Comment by lmccart** [comment]
thanks @limzykenneth!
