### ISSUE TITLE
Unwanted OSX-specific files included with the zip downloads

### ISSUE THREAD

**Issue by lgautier** [processing/p5.js#1571]
The building of zip archives made available as download on the p5js main site (https://p5js.org/download/) contain OSX-specific files (that are likely also specific to the desktop of the person building these archives.

They appear to be all located:
- under the top-level directory `__MACOSX/` in the resulting archive.
- in the following subdirectories
  * `p5-zip/empty-example/.DS_Store`
  * `p5-zip/empty-example/libraries/.DS_Store`
  * `p5-zip/.DS_Store`
  * `p5-zip/addons/.DS_Store`

I could not find a script to build the zip archives in the repository to propose a pull request.

**Comment by joecridge** [comment]
This is a purely cosmetic issue that occurs when you generate zip files from OS X, but if it’s a concern for users on other systems then it is fairly easily remedied.

---

The `.DS_Store` files determine how the folder looks when you open it in Finder OS X (list or icons, icon size and position, sort order, etc.). They are generated (and updated) whenever the folder is viewed with Finder, so it’s quite difficult for the person making the archive to avoid creating them if they are using OS X. That said, they can be removed pretty easily after the archive is generated:

```bash
zip -d archive.zip '*/.DS_Store'  # Single quotes necessary.
```

The `__MACOSX` tree is a resource fork that contains everything that HFS+ supports but other file systems don’t (folder background image, embedded folder icons, tags, aliases, etc.). This is generated when files are zipped using Finder’s Compress service (or by Archive Utility), but OS X users will still be able to extract the files just fine if it is deleted after creation:

```bash
zip -d archive.zip '__MACOSX/*'  # Single quotes again.
```

To generate the archive without either of these files in the first place, you need to use the `zip` command rather than Finder or Archive Utility:

```bash
zip -r archive.zip source -x '*.DS_Store'
```

**Comment by lmccart** [comment]
thanks @joecridge I've added this to the build steps
