### ISSUE TITLE
mouseX/Y vs touchX/Y

### ISSUE THREAD

**Issue by lmccart** [processing/p5.js#1598]
Is it necessary to have separate mouseX/Y vs touchX/Y variables?  As it is, they both update the other... this allows you to write sketches for mobile and test with mouse without having to change variables. But could we just use mouseX/Y? I'm trying to remember if there is a reason we need to actually have separate ones?

**Comment by limzykenneth** [comment]
I seemed to remember there is a reason behind separating them although I haven't started helping with p5.js when it was first implemented. My guess would be that it is to cover [browsers touch API](https://developer.mozilla.org/en-US/docs/Web/API/Touch_events) so that multi-touch can be utilized although I don't know if it was ever implemented and whether there is plan to do that going forward.

**Comment by daniloprates** [comment]
Maybe having an option to unify them?

**Comment by shiffman** [comment]
@lmccart I agree we could do away with `touchX` and `touchY`.   Am right that `touches[0].x` /`touches[0].y` are also the same thing?   So I think we can say `mouseX` and `mouseY` if you just want to emulate the mouse with a single touch in mobile, but `touches` array for more sophisticated multi-touch interaction.

**Comment by lmccart** [comment]
Ok cool. As a precaution/test, I am going to start by updating the documentation and examples and seeing if there are any issues. If all seems good I'll strip out the touchX/Y itself.

**Comment by shiffman** [comment]
As a matter of update, we did a week on mobile in ICM here at ITP and I didn't get a sense of any problems with explaining that `mouseX` and `mouseY` worked for single touch and `touches` for multi-touch.

**Comment by lmccart** [comment]
same here, so I think I will remove them in the next release

**Comment by eballeste** [comment]
so weird to be referencing mouse properties for touch based events... so so weird...
