### ISSUE TITLE
ellipse can take negative width and height

### ISSUE THREAD

**Issue by coardet** [processing/p5.js#1603]
I found that the doc does not specify negative value of width and height.
For now I think it is converting to a absolute value. If we do so, please explicitly document the behavior, or it is really easy to get confused with the behavior I got. thanks

**Comment by hkirat** [comment]
There is a comment specifying that p5.js does accept negative values for width and height.
![screenshot from 2016-10-04 00 18 47](https://cloud.githubusercontent.com/assets/8079861/19049487/496a7902-89c8-11e6-99dc-5ac2fc677ce9.png)

**Comment by joecridge** [comment]
I think that this needs a bit of thought.

- `rect()` used to ‘support negative widths and heights’ until 36e4d2d by taking the modulus, but now it supports negative widths and heights by *not* taking the modulus. See #1569 *rect primitives do not support negative height& widths*. This now matches Processing, and is useful for things like bar charts.

- `ellipse()` supports negative widths and heights by taking the modulus. This is different from Processing due to #413, but was justified by [parity with p5’s `rect()`](https://github.com/processing/p5.js/blob/master/src/core/2d_primitives.js#L171), and the fact that there is no bar chart-like use case for ellipses.

- `arc()` also ‘supports’ negative widths and heights by taking the modulus, which has the effect of swapping the start and end angles. This is also different from Processing, but p5 already handles `start` and `end` more strictly than Processing, even if `width` and `height` are both positive. I believe that the snippet @hkirat posted is the [justification for `abs()` in `arc()`](https://github.com/processing/p5.js/blob/master/src/core/2d_primitives.js#L123).

Since `arc()` and `ellipse()` no longer have parity with `rect()`, it’s quite hard to say exactly what constitutes negative width/height ‘support,’ and the inline comments aren’t really much to go by (especially for an end-user). The different behaviour is bound to be confusing, so perhaps the best thing to do is document the behaviour for all three in the reference?

**Comment by hkirat** [comment]
@joecridge So what do you suggest?
Inverting the ellipse like we do in rect?

**Comment by joecridge** [comment]
I think I’m erring slightly on the side of keeping the behaviour the same and improving the documentation, but I can see the appeal of making all three consistent, and now would be a good time to do that (i.e. while we’re still 0.x) if it’s going to happen.

**Comment by lmccart** [comment]
@joecridge thanks for laying this all out so clearly. I think I agree, since we aren't going to have perfect parity anyway, let's go toward whatever seems most intuitive and useful and focus on documentation. I think the functionality right now feels good, so this is a case where we just need to more clearly explain what happens with negative input in the docs.
