### ISSUE TITLE
Extraneous "friendly" errors

### ISSUE THREAD

**Issue by shiffman** [processing/p5.js#1633]
I'm filing an issue related to a discussion with @toolness  from https://github.com/processing/p5.js-web-editor/issues/7#issuecomment-247622091. I've noticed the issue with many extra "friendly errors" (so friendly!) is not a web editor issue.   The code below triggers: "Did you just try to use p5.js's exp() function?" regardless of whether I'm using the web editor.  Working with students I've also noticed a similar error message regarding "sin()".   

```javascript
function setup() {
  createCanvas(200, 200);
  ellipse(
}

function draw() {
  background(0);
}
```

**Comment by lmccart** [comment]
aha I found the issue here. in this [line of code](https://github.com/processing/p5.js/blob/5b457a5ed2e278faeda0b4b8874e716618ba5c51/src/core/error_helpers.js#L363) it's checking various p5 function names against the error message that is thrown. the error message is "Unexpected token }" which contains the p5 function name "exp" hehe. so I think it's just a matter of improving the regex search token.
