### ISSUE TITLE
No KeyCode for the Command Key

### ISSUE THREAD

**Issue by lberdugo** [processing/p5.js#1637]
There is currently no KeyCode for the COMMAND KEY. Lots of interesting project might want to implement Command+Z, for instance, as part of their interface. My students at USF are currently requesting this feature.

**Comment by lmccart** [comment]
hm, command is tricky because there are two of them (code 91 and 93) -- you can test here: [http://keycode.info/](http://keycode.info/). 

in sample code like this:
```javascript

function keyPressed() {
  if (keyCode == UP_ARROW) {
    fillVal = 255;
  } else if (keyCode == DOWN_ARROW) {
    fillVal = 0;
  }
  return false; // prevent default
}
```
it's checking the numerical value stored in keyCode against variables that represent numbers. so we couldn't really have one variable that represents both command keys. we could have LEFT_COMMAND and RIGHT_COMMAND. but is this overkill? is it easier/simpler to just write your own if statement checking `if (keyCode === 93 || keyCode === 91)`?

**Comment by kadamwhite** [comment]
This would be a deviation from the key code constants we have now, and I'm not sure I'm endorsing the idea, but: to play devil's advocate, what about a helper function? `isCommandKey( keycode )`

**Comment by limzykenneth** [comment]
To make things worse, firefox uses totally different keyCode for command key (firefox uses 224 and separate `command` from `window`)

**Comment by lmccart** [comment]
oof. ok so maybe the best solution here is to link to [keycode.info](http://keycode.info) in the documentation (or show an example of printing the keyCode), and adding an example of a manual keyCode check for the command key with an if statement that includes all possible encodings for command.

**Comment by lmccart** [comment]
I skipped over @kadamwhite's suggestion here, sorry! I guess my intuition is that this feels like it could be overkill and a bit unwieldy. since use of the command key isn't necessary (ie the programmer could just decide to map a different encoded key), maybe this is the point where we push people toward going deeper into understanding keyCodes and the way that they actually map to numbers. I feel like this aligns with the goal of p5 being a library that is broader rather than deeper, giving users friendly entry points and easing a transition into understanding native/vanilla browser javascript. but I'm open to other thoughts!

**Comment by lberdugo** [comment]
Thanks @lmccart, @kadamwhite, and @limzykenneth. 

Given that keyCodes are different across browsers, would it make sense to allow referencing of keys by their unicode? I realize there may be significant reasons you haven't done this, so forgive me if my question is missing the mark. 

Two arguments in favor of this: Unicode is standardized across browsers; it's a rich teaching tool for students to understand how everything is encoded. 

So instead of: 

`if (keyCode == 93 || keyCode == 91)`

...we'd have

`if (keyCode == 'U+2318')?`

**Comment by limzykenneth** [comment]
@lberdugo I haven't test or check it but I suspect using unicode would not work because unicode "U+2318" is the symbol for the command key ie. this ⌘ character and I suspect the command key would never send any signal that resolves to that character so we cannot look for it, it would simply register as a keypress by the browser with a specific keyCode. (You'll won't type ⌘ by pressing the command key)

@lmccart I'm in favour of using that as a way of understanding keyCode more fundamentally, it would also be a valuable lesson in the inconsistencies across browsers and potentially how to deal with it when making a program.

**Comment by lmccart** [comment]
Ok, I'd like to keep this as is and add a little more to the documentation so users know how to check for any key.
