### ISSUE TITLE
capture object drawn into graphics object is scaled incorrectly on retina

### ISSUE THREAD

**Issue by kylemcdonald** [processing/p5.js#1673]
Hi, I'm trying to work with video from a webcam at two different resolutions. As far as I know, it's not possible to open the webcam at two resolutions, so I tried creating a graphics object and drawing into that:

```javascript

var captureBig;
var captureSmall;
var smallWidth = 160, smallHeight = 120;

function setup() {
  createCanvas(640, 480);
  captureBig = createCapture(VIDEO);
  captureBig.size(width, height);
  captureBig.hide();
  captureSmall = createGraphics(smallWidth, smallHeight);
}

function draw() {
  image(captureBig, 0, 0);
  captureSmall.image(captureBig, 0, 0, smallWidth, smallHeight); // renders incorrectly on retina
  // captureSmall.image(captureBig, 0, 0, smallWidth/2, smallHeight/2); // renders correctly on retina
  image(captureSmall, 0, 0);
}
```

When this is working correctly, you should see a small "picture in picture" at the top left. When it's working incorrectly, that PIP crops out the top left quarter of the image.

Correct:

<img width="641" alt="screen shot 2016-11-23 at 2 55 51 pm" src="https://cloud.githubusercontent.com/assets/157106/20581315/f8a62c36-b18c-11e6-9b3f-b03a16b267c9.png">

Incorrect:

<img width="640" alt="screen shot 2016-11-23 at 2 55 35 pm" src="https://cloud.githubusercontent.com/assets/157106/20581324/ffe6827a-b18c-11e6-9dbc-72160f7395dd.png">

I tested disabling retina by using [RDM](https://github.com/avibrazil/RDM) and selecting a non-retina resolution, and the scaling worked correctly.

**Comment by krongeroso** [comment]
I have the same problem with a similar project. I use the "createGrapichs()" function to draw by layers (like photoshop). The strange thing is that it works well on my computer, but I have the same problem as you when I run it from my smartphone. For some strange reason the image is scaled, so use a cheap solution... scale the image for 1/3 and work ... but only on some phones. In others the scaling factor is another, it is very rare. I do not know why it is scaled or because it is different in some cases. :(

**Comment by krongeroso** [comment]
@kylemcdonald 
I solve the problem!!
Only you need to use the function pixelDensity(1) like this:

pg = createGraphics(200, 200);
pg.pixelDensity(1);

Check this example: 
https://github.com/processing/p5.js/issues/1673
