### ISSUE TITLE
replace reqwest with fetch API?

### ISSUE THREAD

**Issue by lmccart** [processing/p5.js#1694]
per @brysonian's [comment](https://github.com/processing/p5.js/issues/968#issuecomment-264197472)

look into replacing reqwest with [fetch api](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API). this may make things smoother with load functions and get/put/post functions, and remove need to rely on an external library.

**Comment by limzykenneth** [comment]
Is anyone currently working on this? If not, I have some free time to look into this.

**Comment by lmccart** [comment]
go for it!

**Comment by lmccart** [comment]
that would be great, go for it!

**Comment by giltayar** [comment]
@limzykenneth - did you take this? I would love to work on it.

**Comment by limzykenneth** [comment]
@giltayar I haven't started on this yet but going to soon. I'm quite happy to work on this with you if you want. I haven't have a closer look yet so I'm not sure how to break this down though.

**Comment by giltayar** [comment]
Nope - I finally didn't take it. All yours...

**Comment by limzykenneth** [comment]
haha, alright 😄

**Comment by limzykenneth** [comment]
I need some second opinion on a particular implementation. I have managed to very basically replace reqwest with fetchAPI calls and now I'm going through each functions to make them feature complete and add the header fields etc. I'm starting on `loadJSON()` and there are a couple problems.

First, fetch API doesn't support JSONP out of the box so in order to support that, a polyfill will be required. Second, from #968 the purpose of this change is also to make passing headers easier, it is pretty trivial to provide header fields and even POST body fields to the request. I just need a decision on what the valid signature for the function calls will be. Currently, `loadJSON()` has the following singature `loadJSON(path,[callback],[errorCallback],[datatype])`, I'm just wondering how to add the additional fields into the signature, we may be looking at a breaking change? (Also datatype won't be needed in this case if `loadJSON()` doesn't support JSONP).

**Comment by lmccart** [comment]
closed with https://github.com/processing/p5.js/pull/1812
