### ISSUE TITLE
Offline documentation still requires internet connection because it links to various CDNs

### ISSUE THREAD

**Issue by JobLeonard** [processing/p5.js#1711]
The offline reference doesn't load on my laptop without an internet connection, presumably because these resources are missing:
```
    <!-- jquery-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="./js/vendor/jquery-1.9.1.min.js"><\/script>')</script>

    <!-- underscore-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js"></script>
    <script>window._ || document.write('<script src="./js/vendor/underscore-min.js"><\/script>')</script>

    <!-- backbone-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/backbone.js/1.3.3/backbone-min.js"></script>
    <script>window.Backbone || document.write('<script src="./js/vendor/backbone-min.js"><\/script>')</script>
```
Could those be included as offline files instead?

**Comment by JobLeonard** [comment]
Confirmed by trying to save the full webpage in Firefox (which tries to download and save all required JS and CSS files, and changes the required links). After doing so the website works perfectly fine off-line.

For anyone else reading this, this also happens to be an effective workaround until this is fixed:

- open the offline reference in Firefox
- open hamburger menu in top-right
- click "Save Page"
- make sure "Save full webpage" is enabled
- save to a different folder

The resulting webpage now works off-line.

Because it saves the webpage as it was rendered, an extra non-functioning the search box gets added in the process. You can either ignore this, or open the resulting .html file and remove the `<div id="search" class="search-wrapper">` tag and everything inside of it. Voila, fully off-line reference.

**Comment by limzykenneth** [comment]
```
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="./js/vendor/jquery-1.9.1.min.js"><\/script>')</script>
```

The second line should have already taken care of the case where the user is offline (ie. it will look for and use the local copy of the libraries if it cannot retrieve the files from the CDN). There will be errors in the console but the whole thing should still work. Is it not working? Let me know if not, I'll have a look at it.

**Comment by JobLeonard** [comment]
It's not working in either Firefox or Chromium. (I have uBlock/uMatrix installed and just turned them off to check if they might have interfered). But why not immediately rely on the local copy anyway? Is that hard to achieve in the build process?

**Comment by limzykenneth** [comment]
If I remember correctly (been awhile since I made the offline package), it should be because the build process is tied quite closely to how the actual documentation on the p5js.org is generated from source. They essentially used the same templates to generate the files. We want to use the CDN copy for the online reference mainly for load speed because the reference was having a big issue with load times online.

What I'm not so sure is if `index.html` is also generated from the same templates for the offline docs. I'll have a look in the next couple of days, see if I can make it just use the offline copy.

**Comment by JobLeonard** [comment]
Thanks, good luck! 

It would be nice if it was possible to add some kind of conditional rendering in the template, resulting in two different outputs. You know, "if build target is online reference, link to CDN, if target is offline, link to local." But I'm always shocked at how some of the most basic use-cases tend to be forgotten with these type of tools, so I wouldn't be surprised if this is way harder to achieve than it should be.

**Comment by limzykenneth** [comment]
@lmccart The offline reference is broken because of the migration to the new site. Previously the `build-ref.php` script will take care of building the p5-reference.zip file but now because the site structure is different, it cannot find certain files, and for this issue, it cannot find the vendor js files and thus it is not bundled with the final package, which is why it failed.

I need a decision on how to redo this. In my opinion I think we can forgo the php build script and make the offline reference build a step in the static site generation of the current site so it will be updated whenever the site is updated. 

I'll put together a PR to p5.js-website repo when I'm done but feel free to let me know if another way to do this is better, I'm not the one who has to deploy the site after all. 😉

**Comment by lmccart** [comment]
I agree, we don't need the php script, this is great. Thanks for the PR!

**Comment by JobLeonard** [comment]
Did this update get pushed to the website? I just tried downloading the offline reference but I still get the old version, I think, since it still does not work while offline.

**Comment by lmccart** [comment]
I did push whatever changes were made in the repo, @limzykenneth did I miss something?

**Comment by limzykenneth** [comment]
@lmccart Is the website directly pushed from the `dist` folder of the repo? If so the files may be missing because I excluded them from git thinking the build step may be ran before it was pushed to the server. If so, we just need to remove the line from `.gitignore`, build the whole thing again and commit the zip file. From what I see, the PHP script is still in there so the folder is definitely not replaced yet.

**Comment by lmccart** [comment]
Yeah, there's a hook that pushes everything in the repo live whenever there is a push to the master branch of the repo. So it sounds like the .gitignore just needs to be updated, are you able to make this change?

**Comment by limzykenneth** [comment]
@lmccart Done https://github.com/processing/p5.js-website/pull/40

**Comment by lmccart** [comment]
thanks!
