### ISSUE TITLE
Loading image from IDN domain does not work

### ISSUE THREAD

**Issue by mortenmoulder** [processing/p5.js#1725]
I'm trying to load an image from my domain, which happens to have an `ø` in it. Even when I type out the "punycode" domain, I still get the error.

**Test URL**
https://mortenmøller.dk/p5test/

**What I have tried**
IDN domain directly:
`img = loadImage("https://mortenmøller.dk/mario.svg");`

**What does work**
Relative path seems to work.
`img = loadImage("/mario.svg");`

"Punycode" domain:
`img = loadImage("https://xn--mortenmller-mgb.dk/mario.svg");`

**Error**
>GET https://xn--mortenm%20ller-8bb532f.dk/mario.svg net::ERR_NAME_NOT_RESOLVED

**Comment by lmccart** [comment]
As noted in the reference page for loadImage(): "The path to the image should be relative to the HTML file that links in your sketch. Loading an from a URL or other remote location may be blocked due to your browser's built-in security." This is just a limitation of the canvas unfortunately... if you need to load a remote URL, you could look into the createImg() function which behaves somewhat differently but does enable loading of remote URL paths.
