### ISSUE TITLE
incredibly slow sketch on chrome, runs fine in safari

### ISSUE THREAD

**Issue by jtoy** [processing/p5.js#1744]
my first real  p5js sketch that I ported from Processing grinds chrome to a halt. It runs fine in safari though. is this considered a p5js bug or a chrome bug or?
I debugged it, it is due to the while loop it looks like.  I had to use a while loop in this case instead of a for loop.

You can see it run here:
http://www.jtoy.net/2017/01/04/my-experience-with-processing.html

Here is the code:
```

   var radius = 300;
   var direction = 1;
   var ray_length = 0;
  var ray_direction = 1;

  function alternating_ray(radius){
  ray_length +=ray_direction;
  if(ray_length == 10){
    ray_direction = -1;
  }else if(ray_length == 0){
    ray_direction = 1;
  }
  return radius/2+ray_length; 
  }
   
   
 function setup(){
   createCanvas(600, 600);
 }
 function draw(){
   background(0);
   var amount_ray = cos(frameCount/15)*10;
   var amount = sin(frameCount/15)*5;
   var below = height/2+amount;
   translate(width/2,below);
   fill(229,155+amount_ray,16);
   ellipse(0,-170,radius,radius);
  stroke(229,155+amount_ray,16);
  //for(i=0;i<=360;i+=1){
  i = 0;
while(i != 361){
  var arr = alternating_ray(radius);
  var new_x = cos(radians(i))*arr;
  var new_y = sin(radians(i))*arr;
  line(0,-170,new_x,-170+new_y); 
  i+=1;
 }
   
   radius+=direction;
    if (radius == 400){
  direction = -1;
 }else if(radius ==50){
    direction = 1;
 }
   
   fill(205);
   triangle(-250, 250, 0, -100, 250, 250);
      

   ellipse(0, 270, 400, 40);
   ellipse(0, -170, 120, 120);
   

 }
```

**Comment by limzykenneth** [comment]
@jtoy It happens on firefox as well and the difference is mainly due to different optimisation priorities across browsers. However, I think you can optimise your code a bit to get better performance. The main problem is not the fact that you are using while loops instead of for loops, it rarely makes a difference, the problem lies in this line in the loop `line(0,-170,new_x,-170+new_y);`.

What you are doing there with that line is basically drawing 360 lines with the `line` function every frame, 60 frames a second. It gets really hard when the radius becomes very small and the CPU needs to calculate lots of small floating point calculations and handle a lot of subpixels drawing, thus the framerate is extremely low when the circle becomes small.

Here's my quick and not so good optimise code:
```javascript
if(radius > 120){
  if(i % 5 === 0){
    line(0, -170, new_x, -170 + new_y);
  }
}else if(radius > 100){
  if(i % 10 === 0){
    line(0, -170, new_x, -170 + new_y);
  }
}
```
It avoids drawing all of the lines and it draws less lines the smaller the circle is. It's not a great optimisation but it gives you an idea of what you may need to do. A potentially better way to do this is to avoid using `line()` but use `beginShape(LINES)` and `endShape()` instead, see [here](https://p5js.org/reference/#/p5/beginShape). I haven't tried it but I think it may give you better performance and still draw everything you want.

**Comment by jtoy** [comment]
I had found that issue also.  Its unfortunate that each of the major browsers react differently when running p5 code.

**Comment by lmccart** [comment]
thanks @limzykenneth!
