### ISSUE TITLE
Downloading problem in windows 10

### ISSUE THREAD

**Issue by akhilanadimpalli** [processing/p5.js#1818]
Hi guys. I'm newbie programmer.
I'm having difficulties to install p5 js in windows 10.
can u guys please help me.

**Comment by joecridge** [comment]
Hi @akhilanadimpalli. The easiest way to get started is to download the [p5.js complete](http://p5js.org/download/) bundle from p5js.org. Unzip the file, and then find the folder in there called `empty-example`.

Open up `index.html` in your browser, and open up `sketch.js` in a text editor (you can use Notepad, but you’ll probably find something like [Brackets](http://brackets.io/), [Atom](https://atom.io/) or [Visual Studio Code](https://code.visualstudio.com/) more useful in the long run). You can type p5 code into `sketch.js`, save the file, and then refresh `index.html` in your browser to see your sketch run.

Alternatively, for a quick play around, you can check out the [p5.js web editor](https://alpha.editor.p5js.org/), which doesn’t involve any setup!

There’s more information on the [getting started](https://p5js.org/get-started/) page on p5js.org.

PS: GitHub is more for letting us know about bugs with p5.js so that we can fix them, rather than asking for help using p5.js. [Our forum](https://forum.processing.org/two/categories/p5-js) is the best place ask how-to questions, and there are many people there that would be happy to help you get started 😃

**Comment by akhilanadimpalli** [comment]
Hi @joecridge .
thank you so much
