### ISSUE TITLE
Unable to view or set frameRate

### ISSUE THREAD

**Issue by omundy** [processing/p5.js#1822]
On latest Chrome (56) on Macbook Sierra (10.12) it appears I am unable to change [frameRate](https://p5js.org/reference/#/p5/frameRate) or see it in the console if I call it in setup(). It does seem to work in draw(). The documentation states the opposite.

```
var n = 0, t = 100;
function setup() {
  console.log(1,frameRate());
  frameRate(40);
  console.log(2,frameRate());
}

function draw() {
  console.log(3,frameRate());
  frameRate(10);
  console.log(4,frameRate());
  if (n++ > t) noLoop();
}
```

**Comment by lmccart** [comment]
The output I'm seeing when I run that code looks like this:
<img width="159" alt="screen shot 2017-02-26 at 6 52 22 pm" src="https://cloud.githubusercontent.com/assets/191056/23347138/d5c68914-fc54-11e6-89d9-978910713138.png">

The reason the frameRate() reads 0 for the first for calls is because it doesn't actually have a value until a full loop through setup and draw has occurred. The code that updates the internal framerate variable looks like this:
```javascript
this._frameRate = 1000.0/(now - this._lastFrameTime);
```

When I comment out the `frameRate(10)` call, the output looks like this:
<img width="163" alt="screen shot 2017-02-26 at 6 52 56 pm" src="https://cloud.githubusercontent.com/assets/191056/23347169/0e204c82-fc55-11e6-8f98-a666c7f7530e.png">

Which shows that the framerate is capped at 40 as set in setup.

If I comment out all framerate calls, the output looks like this:
<img width="159" alt="screen shot 2017-02-26 at 6 52 49 pm" src="https://cloud.githubusercontent.com/assets/191056/23347174/2050b68a-fc55-11e6-90f7-0a7138957590.png">

Which confirms that the frameRate(40) call is indeed having an effect, otherwise the framerate is higher.

Are you seeing different output? Or does this seem to make sense?

**Comment by omundy** [comment]
> The reason the frameRate() reads 0 for the first for calls is because it doesn't actually have a value until a full loop through setup and draw has occurred.

Thanks for the explanation. It wasn't clear in the documentation that I couldn't view the frameRate until draw() finished at least one loop. 

This might be a good addition?

> Calling frameRate() with no arguments returns the current framerate. **_The draw function must run at least once before it will return a value._** This is the same as getFrameRate(). 

This edit may make it more clear that calling frameRate(value) sets a cap, and there will still be variance based on the environment?

> Specifies the **_approximate_** number of frames to be displayed every second.

**Comment by lmccart** [comment]
ah, very good suggestion. @almchung is going to work on adding this.

**Comment by lmccart** [comment]
fixed with https://github.com/processing/p5.js/pull/1838
