### ISSUE TITLE
InvalidStateError: An attempt was made to use an object that is not, or is no longer, usable

### ISSUE THREAD

**Issue by mburakerman** [processing/p5.js#1827]
I created a game with p5 but it gives me error in Mozilla (51.0.1) and can't start game.
[This ](https://mburakerman.github.io/runicorn/) my project.
You can check it on Mozilla.
I get this errors.

```
[44]</d.Renderer2D.prototype.image 
[56]</e.prototype.image 
bound  self-hosted
Unicorn/this.show 
draw 
[47]</d.prototype.redraw 
[37]</e/this._draw< 
bound  self-hosted
[37]</e/this._runIfPreloadsAreDone 
[37]</e/this._decrementPreload 
bound  self-hosted
[56]</e.prototype.loadImage/d.onload 
```
Why i get this errors?

**Comment by lmccart** [comment]
I looked through the game a bit but it's hard to track down the error because the files are all minified and there's quite a bit of code involved. Because the error mentions loadImage, I might start by confirming that all image files you're loading exist, have the proper read permissions, are correctly named (capitalization too) and are in the right place.

If this doesn't solve anything, I'd suggest commenting out pieces of your code until it runs again in order to identify the problematic line. If you're able to isolate this line, please post it here and we can better figure out where the bug is.

**Comment by mburakerman** [comment]
Ah, i figured out now. 
I use [p5.js gif library](https://github.com/antiboredom/p5.gif.js) and it gives the [issuse ](https://github.com/antiboredom/p5.gif.js/issues/1 )tho.

**Comment by lmccart** [comment]
Ah ok, glad you tracked it down. Yes, that library is pretty old and I've heard of several issues with it. Hope you can get it fixed over there!
