### ISSUE TITLE
password type for createInput doesn't seem to be working

### ISSUE THREAD

**Issue by anurupmitra** [processing/p5.js#1830]
I assume
`createInput("Password", password)`
should work - but it doesn't. Am I doing anything incorrectly?

**Comment by feedzh** [comment]
password is a string.

```
createInput("Password", "password")
```

**Comment by anurupmitra** [comment]
Thanks a bunch!

A little odd - because the _text_ type works without quotes...

**Comment by feedzh** [comment]
yes. because the code says - if type doesn't exist use text. If it does use password.

```
elt.type = type ? type : 'text';
```

When you say password that means variable called password. By default this variable is undefined. When you have it in quotes, it becomes  string (text variable) with value of "password"

**Comment by anurupmitra** [comment]
Thanks again!
`createInput("Text", text)` displays a text input box whereas `createInput("Password", password)` displays nothing. That is probably why I got even more confused...

**Comment by feedzh** [comment]
in barebones what is happening:

```javascript
var text;
//text equals undefined/0/null/NaN/false
 createInput("Text", text);

//from createInput code
//elt.type = type ? type : 'text';
//when type exists, use type, if not, use 'text'
```
That is the reason why it worked.

**Comment by anurupmitra** [comment]
Understood!

But shouldn't _password_ (without quotes) also throw undefined and hence default to a text type?

**Comment by feedzh** [comment]
createInput("Text", text) is the same as createInput("Password", password)

**Comment by anurupmitra** [comment]
Yup - so why don't they have the same behaviour? Like I wrote some time back. The former displays and the latter does not.

**Comment by feedzh** [comment]
because in createInput("Text", text) - text is also undefined. And in the function where it is declared undefined equals 'text' (notice quotes) without quotes it is a variable and should have value.

**Comment by anurupmitra** [comment]
I might definitely be getting on your nerves by now, :-) but I am not sure we are talking about the same thing.

What should I expect to see in the browser when I use `createInput("Text", text)?`

What should I expect to see in the browser when I use `'createInput("Password", password)'?`

**Comment by wmmnola** [comment]
So the issue is that when you use

`createInput("Text",text)`

You are passing in `text`which is an undefined variable. The same thing happens when you 'createInput("Password",password)'. So the variable 'password' as type 'undefined' because you never defined it. When 'createInput()' was changed to allow for multiple text types, I decided that in order to prevent people stuff from breaking if the 'type' variable was undefined it would just default to the 'text' type. 

So when you use 'createInput("Password", password)' the password variable is undefined so the input DOM type defaults to 'text'

**Comment by anurupmitra** [comment]
Thanks again and sorry to be such a bore!

Here's the rub - if I use `createInput("Password", password)` it shows NOTHING in the browser rendering. From what you and feedzh have said I understand (unless I am being completely daft about something) it should default to a normal text input. But it doesn't.

`createInput("Password", text)` DOES default to a normal text input.

Now I am beginning to suspect that it could be a particular issue from my side. However, I have tried this with both the p5 editor (Linux) and Chrome (on Linux again)

In sheer desperation ;-) I have managed to open up the Javascript console and this is what I can see

> Uncaught ReferenceError: password is not defined

**Comment by feedzh** [comment]
createInput("Password", **"**password**"**);

Actually this fills password field with text "Password". If you want empty password then use

createInput("", **"**password**"**);

example basic sketch.js

```javascript
function setup() {
    noCanvas();
    createInput("","password");
}

function draw() {
  
}

```

The error, what you see in console is the thing what we have been talking about.

**Comment by wmmnola** [comment]
The reason `createInput("Password", text)` does something is because the
code is catching the undefined error, and if `text` is undefined it
defaults to something. `password` is a new variable you are creating and
passing into `createInput` because you never defined it, it has property
`undefined` and will crash your JS.
