### ISSUE TITLE
csv & mapbox question

### ISSUE THREAD

**Issue by Dirma** [processing/p5.js#1836]
Hi everyone,

I'm quite a beginner in p5.js and I want to do the following:

I have a csv table with data of medication use in The Netherlands, per town. This data I want to show on an interactive mapbox map. 

- Problem 1:
The csv file only has the names of the towns, not the longitude & latitude.  Is there a way to generate this automatically? Otherwise I have to do it manually for about 400 towns:(.
- Problem 2:
When I have the longitude and latitude, how can I show them on a map, using mapbox, via p5.js?

I hope you can help me with this!!!

Best,

Dirma

**Comment by feedzh** [comment]
Hello,

1) Yes MapBox has a free geocoding API: https://github.com/mapbox/mapbox-sdk-js I suggest to use it once and save coordinates in the CSV for later use.

2) Daniel Shiffman made an earthquake map using MapBox: https://www.youtube.com/watch?v=ZiYdOwOrGyc
The other option is not to use P5 at all and use just Leaflet map (the map comes from MapBox), where you can place markers on the map. They also support custom markers, where you can use your own image.

Reijo

**Comment by Dirma** [comment]
Thanks for the help, really appreciated!

I'm a newbie, so how does the geocoding API work:)? I downloaded it from github, do I have to install it on the node server? I tried to do that, but I get an error message. And where does the csv file come into play? 

Best, Dirma

**Comment by lmccart** [comment]
Hi @Dirma excited you're getting started with p5.js! Can I ask that you post your questions over here at the [forum](https://forum.processing.org/two/categories/p5-js)? The github issues are really for bug reports for the library itself and the forum is a good spot for asking questions because they can be answered by the whole community and the archive is more easily searchable by others with similar questions. Thanks and welcome!

**Comment by Dirma** [comment]
Hi @lmccart , of course! Thanks for letting me know. best, Dirma
