### ISSUE TITLE
loadPixels() ignores side-effects of rect()

### ISSUE THREAD

**Issue by azerton** [processing/p5.js#1877]
When working with loadPixels() and updatePixels(), any intermediate drawing that does not manipulate the pixels array directly appears to be ignored.

Example:

```
loadPixels(); 

rect(this.x, this.y, this.r, this.r);

updatePixels(); # the changes done by rect() are not present in the new pixels array

````

From the documentation, it is not clear if this is intended behavior or not. I have tried variants which use `updatePixels()` without results either.

**Comment by lmccart** [comment]
hm this is the intended behavior. what text do you suggest we add on the reference page to make this more clear?

**Comment by azerton** [comment]
Thanks fot he response!
Well, it's not really clear what impacts the pixel array.

For example, if I update the array manually, then I would indeed expect the changes to persist to canvas once I do updatePixels() (which is the case).

However, how can I ask p5.js "I will draw a rectangle now, and after that give me the updated pixel map"?

**Comment by lmccart** [comment]
the only two things that will affect it are using the [set()](https://p5js.org/reference/#/p5/set) function or directly setting values in the [pixels](https://p5js.org/reference/#/p5/pixels) array. I think the fix is to add a line into the documentation of loadPixels() and updatePixels() that notes these are the only two that will have an effect, all other drawing will not get implemented by updatePixels.

however, I'm not sure if it's a typo in your example, but the code you posted should actually reflect a change to pixels. for example:

```javascript
function setup() {
  createCanvas(10, 10);
  noLoop();
}

function draw() {
  loadPixels();

  console.log(pixels); // output: {"0":0,"1":0,"2":0,"3":0,...
  rect(0, 0, 5, 5);

  loadPixels();
  console.log(pixels); // output: {"0":0,"1":0,"2":0,"3":255,...
}
```

I'm thinking maybe you meant updatePixels() at the end though?

**Comment by azerton** [comment]
Indeed, I meant updatePixels(), my bad. I corrected the first comment!

If it actually does change in your example then I must have had a bug in my code, since it clearly did not work for me, with almost the exact same syntax as you used (loadPixels -> create object -> loadPixels -> no difference in the pixels array).

I will investigate and get back in case this is a recurring issue in my code.

Thank you for the support!

**Comment by lmccart** [comment]
@mlarghydracept the todo here is to add a line to the reference that makes the point noted in this comment: https://github.com/processing/p5.js/issues/1877#issuecomment-292663194
