### ISSUE TITLE
p5 touch event blocks normal touch behavior

### ISSUE THREAD

**Issue by milkyklim** [processing/p5.js#1887]
I have a sketch on my [webpage](http://milkyklim.com/write-it-right/). 

Sketch [code](https://github.com/milkyklim/milkyklim.github.io/blob/master/assets/sketches/rain.js).

Expected behavior: when mouse is clicked or touch is down invert sketch colors.

Desktop version is fine. 

Mobile version is not working properly. When I touch the screen the color changes but I can't click any of the objects on the page (try share buttons, _previous post_ or _leave comments_). 

I think this is a bug because I don't use anything like `function touchStarted(){ return false; }` to prevent normal touch workflow.

Tested the code on iPhone 5, Safari.

**Comment by b2renger** [comment]
I have the same problem here : https://b2renger.github.io/p5js_harmony-directed-layout/
I'm using p5js with quicksettings

0.58 : I cannot modify quicksettings paremeters on a mobile browser.
0.57 : does work with quicksettings but has still the double firing bug on mobile

There have been some related changes here that have proably broken things down https://github.com/processing/p5.js/commit/cc52045d132385d9ee862bf740f4a39d8db8bd8b 
but I don't I get it

**Comment by b2renger** [comment]
@milkyklim 

So after investigations, the commit I mentionned earlier is actually the fix for our bug.
It turns out that this commit is not in 0.58 and will be in the next release.

I checked out the master branch built the lib according to these instructions https://github.com/processing/p5.js/wiki/Development

and replaced the p5.js file, it works but I get back the double firing bug on mobile.
While waiting for 0.59 you can either get back to 0.57 or get the 0.58-1 I built (here : https://github.com/b2renger/p5js_harmony-directed-layout/blob/master/libraries/p5-0.58.1.js)

this probably shoud be kept open until a new version si rolled out.

**Comment by milkyklim** [comment]
The problem I had is solved in 0.5.9. We can close the issue.
