### ISSUE TITLE
Chrome WEBGL

### ISSUE THREAD

**Issue by ihpar** [processing/p5.js#1897]
Hi there,
I see this message in chrome console:

[.Offscreen-For-WebGL-......]RENDER WARNING: there is no texture bound to the unit 0
WebGL: too many errors, no more errors will be reported to the console for this context.

Here is the code:

```
push();
translate(x, y, z);
ambientMaterial(147, 230, 255, 200);
box(44, 44, 44);
pop();
```

My environment is win 10 x64 and chrome v 57.0.2987.133.
This code does not cause the same issue in FF and Edge.

Thank you very much for this wonderful library. It saves loooots of effort!.
Best wishes!

**Comment by mlarghydracept** [comment]
Thanks for the info! It looks like [threejs dealt with this last year](https://github.com/mrdoob/three.js/issues/8666). Seems like this will require a bit of reworking the [texture()](https://github.com/processing/p5.js/blob/master/src/webgl/material.js#L118) and [bind()](https://github.com/processing/p5.js/blob/master/src/webgl/material.js#L174) functions.

**Comment by mlarghydracept** [comment]
It is being addressed as part of the WebGL summer of code work. Expect a fix in the next few weeks.

**Comment by mlarghydracept** [comment]
This is fixed with the updates in the WebGL_GSOC17 branch. We still aren't sure when that branch will be merged into master (sometime in the next month or two) but if you want to fix the issue sooner you can download from that branch and build the library using the instructions [in the setup section here](https://github.com/processing/p5.js/wiki/Development).

The issue can stay open till the changes are pulled into master.

**Comment by kjhollen** [comment]
merged the google summer of code webgl work :)
