### ISSUE TITLE
White bars on side of canvas on chrome depending on canvas width

### ISSUE THREAD

**Issue by stuuuuuuuuuu** [processing/p5.js#1925]
I think I found a bug where white bars appear on the side of the canvas depending on width. To test the bug I copied the exact code from the p5.js getting started page on only added `background(51);`
after `createCanvas(640, 480)`. This does not produce the bug but if the width is then changed it sometimes shows white bars on the right side of the canvas with varying widths and distance from the edge depending on what the width is. I also tested on firefox and safari and did not have this issue

**Comment by stevengreens10** [comment]
What widths cause this to happen?

**Comment by stuuuuuuuuuu** [comment]
After going up by 10s for a while i found 660-690, 720-740, 790-820, 850-880 so it seems to alternate about every 30

**Comment by stevengreens10** [comment]
Hm, I can't seem to replicate it. Is this still with 480 height?

**Comment by stuuuuuuuuuu** [comment]
Yes, here is the code I currently have:

sketch.js
`function setup() {
  createCanvas(740, 480);
	background(51);
}`

index.html
`<html>
  <head>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.5.8/p5.js"></script>
    <script src="sketch.js"></script>
  </head>
  <body>
  </body>
</html>`
 
and here is the result
<img width="876" alt="bug" src="https://cloud.githubusercontent.com/assets/17538258/25777156/a7414398-32a2-11e7-9994-f9d22c3f3764.png">

**Comment by stuuuuuuuuuu** [comment]
Also i'm on osx if that matters

**Comment by stevengreens10** [comment]
Here is what I see on Windows:
![screenshot 2017-05-06 at 9 31 51 pm](https://cloud.githubusercontent.com/assets/26755396/25777192/b93dfe28-32a3-11e7-9f06-8a4501261d06.png)
Perhaps it does have something to do with you being on osx.

**Comment by mlarghydracept** [comment]
I am on osx and this is what I see:
![screen shot 2017-05-07 at 12 19 27 pm](https://cloud.githubusercontent.com/assets/10382506/25784335/b7adb36a-331f-11e7-927e-36374eb6a506.png)

What version of chrome are you running?

**Comment by lmccart** [comment]
@stuuuuuuuuuu one thing I would recommend is using a local server to view your sketch, rather than opening the file directly. there are instructions here: https://github.com/processing/p5.js/wiki/Local-server. alternatively, you could use a code editor like [brackets](http://brackets.io) that will run a server for you. I'm not sure this would have any effect on white bars, but might save you some troubles with other things like loading images down the line.

**Comment by runemadsen** [comment]
I suddenly started seeing this for all of my sketches. I didn't change my P5 version since it started popping up, so I believe this has to do with a new Chrome version or something. I'm getting it everywhere whether running locally or remote.

Take this simple sketch: https://alpha.editor.p5js.org/runemadsen/sketches/ry-Bd6WxW

```
function setup() {
  createCanvas(600, 500);
  background(30);
}
```

Which looks like this to me:
![screen shot 2017-05-11 at 1 17 24 pm](https://cloud.githubusercontent.com/assets/192021/25946709/a1fac3fc-364c-11e7-9d7c-1c1c8ae9aaf3.png)

Not sure exactly what's going on, but I'll be happy to try to debug if you need help.

**Comment by runemadsen** [comment]
Okay, here's an update after diving into this some more. The white lines have nothing to do with P5. I whipped up the following code which shows the same problem:

```html
<canvas id="myCanvas" width="600" height="500"></canvas>
<script type="text/javascript">
      var ctx = document.getElementById('myCanvas').getContext('2d');
      ctx.fillStyle = 'rgb(30, 30, 30)';
      ctx.fillRect(0, 0, 600, 500);
</script>
```

So this much be a bug related to Chrome's canvas rendering.

**Comment by stuuuuuuuuuu** [comment]
Thanks for figuring that out, I am on version 57.0.2987.133 (64-bit) if that helps

**Comment by lmccart** [comment]
thanks @runemadsen! @stuuuuuuuuuu sounds like unfortunately we can't do anything to fix this from the p5.js end, but you could report the issue on the chrome issue tracker: https://bugs.chromium.org/p/chromium/issues/list
