### ISSUE TITLE
.in files not supported

### ISSUE THREAD

**Issue by Poomaster800** [processing/p5.js#1928]

**Comment by bmoren** [comment]
Can you give more detail, in what way? How are you trying to use a .in file?

**Comment by Poomaster800** [comment]
.in file contains input data for a coding competition, pretty much just many lines of numbers

**Comment by Poomaster800** [comment]
also the rules state that you must use the .in file for the input (no copy/pasting to a .txt)

**Comment by lmccart** [comment]
I'd suggest using loadStrings, something like this:
```javascript
var data;

function preload() {
  data = loadStrings("assets/test.in");
}

function setup() {
  createCanvas(500, 500);
  console.log(data);
}
```

**Comment by Poomaster800** [comment]
I tried that and it saidthat .in files aren't supported

It's why I opened this issue

**Comment by limzykenneth** [comment]
@Poomaster800 is it possible to share a copy of the file you are trying to load? `loadStrings()` wrap the native Fetch API pretty thinly so any problem you have is likely due to the Fetch API itself. I suspect it may have to do with the encoding of the file but I need to examine it to know for sure, possible do some tests directly with the Fetch API as well.
