### ISSUE TITLE
loadTable creates extra objects for blank lines

### ISSUE THREAD

**Issue by lee2sman** [processing/p5.js#1931]
I have a ultraquick sketchy sketch that wasn't properly looping and I couldn't figure out why.
After deleting some extra blank lines at the end of the loaded csv it properly loops.

Link to my [sketch](http://alpha.editor.p5js.org/2sman/sketches/SkIbHjRyb) here. To recreate the issue, add some blank lines to the end of the crimes.csv file

**Comment by mlarghydracept** [comment]
[That comes from these lines](https://github.com/processing/p5.js/blob/master/src/io/files.js#L627-L630). It only handles one blank line at the end of CSV files. When you have more than one line the inbetween lines won't evaluate to undefined but rather come out as an empty string. This could be fixed but I feel like it might have to be a clumsy fix because if we also check for empty strings that aren't the last line then we have to deal with the possibility of blank lines in the middle of the file.

It might be better to just update the documentation for loadTable() to  let people know that they should take out empty lines in their .csv files.

**Comment by lee2sman** [comment]
Okay, I see, that makes sense. 
I wish there was a way to throw an error message about it.

**Comment by limzykenneth** [comment]
Hmm...maybe we should look for some way to deal with this in the library, some times you just can't control the csv files you are loading in... 😞

**Comment by lmccart** [comment]
I'm wondering if at that code section that @mlarghydracept points to, could we just not add any line that is empty -- at the end or in the middle? rather than breaking completely, just skip the row creation and go on to the next?

**Comment by mlarghydracept** [comment]
@lmccart *slaps head* yeah that should be good! We can just use 'continue' instead of 'break'. I'll make a PR when I get a chance.
