### ISSUE TITLE
deviceTurned not called when performing video capture

### ISSUE THREAD

**Issue by seeme00** [processing/p5.js#1933]
Hi

In the following sample, the deviceTurned function is never called on Chrome Android:

```
function deviceTurned() {
	print(deviceTurned);
}

function setup() {
  createCanvas(100, 100);
  createCapture(VIDEO);
}


function draw(){
}

````
The expected behavior is that the deviceTurned function is properly called.

Thanks,
Julien N.

**Comment by stevengreens10** [comment]
The deviceTurned function was working for me on Chrome for my Android phone:

![screenshot_2017-05-10-19-21-17](https://cloud.githubusercontent.com/assets/26755396/25925458/b542057e-35b6-11e7-808f-4009a0c935f4.png)

**Comment by lmccart** [comment]
@seeme00 have you included the p5.dom library in your html file? it could be that the createCapture() line is breaking the code preventing deviceTurned() or anything else from working. if so, are there any other errors in the console that you see?

**Comment by mlarghydracept** [comment]
@seeme00 I also tested with Android and Chrome. Everything is working as expected.
![screenshot_2017-05-14-16-29-56](https://cloud.githubusercontent.com/assets/10382506/26038712/3f47fc24-38c3-11e7-89d7-36b53a33d046.png)
 I would definitely double check that you included the p5.dom library in your html file. I am going to close this issue for the time being because I don't see a problem with the library but if you get more specific feedback from your error feel free to comment and I will reopen the issue. Good luck!
