### ISSUE TITLE
image doesnt get drawn if noLoop() is called

### ISSUE THREAD

**Issue by 9fingerjoe** [processing/p5.js#1945]
```javascript
var img;
function setup() {
    createCanvas(500, 500);
    noLoop();

    img = loadImage("img.png");
}

function draw() {
    background(51);  
    image(img, 0, 0, 100, 100);
}
```
--> Image doesnt get drawn
If noLoo(); doesnt get called it works fine;

**Comment by lmccart** [comment]
@9fingerjoe the issue here is that your image hasn't loaded in time before the draw loop runs once. this is why if you take out the noLoop() call, you see it show up once loaded. I would suggest loading your image in preload() instead of setup() to solve this problem. https://p5js.org/reference/#/p5/preload
