### ISSUE TITLE
Word spacing is handled differently for default font compared to the same font loaded from file

### ISSUE THREAD

**Issue by cqx931** [processing/p5.js#1958]
Test case: http://chenqianxun.com/testcases/p5textTest.html
In default font:
Line 1: The whole string is written with text()
Line 2: Each word is written separately with an offset of the space width
Two lines are exactly the same.

In loaded Helvetica_light.ttf (which is the default sans-serif font on mac)
Line 3: The whole string is written with text(), the spacing is different compared with default font
Line 4: Same as line 2, Each word is written separately with an offset of the space width

**Comment by mlarghydracept** [comment]
Hmm after an embarrassingly long time spent looking through the code for parsing glyphs, I decided to just look at the advanceWidth property for each of the glyphs. Strangely the advancedWidth property is the exact same (278) for the space in the default and the loaded font in the given example. So I assume that this means the mistake in width isn't happening when reading info from the font table. I will keep working on this but will post as I go in case someone with more experience coding for text display wants to jump in and offer advice.

**Comment by dhowe** [comment]
A couple of things to note here. First, due to a bug in the opentype library when this was initially written, spaces are handled separately from other glyphs in loaded fonts. I requested an update to opentype in p5 once this was fixed, which I think was done [here](https://github.com/processing/p5.js/pull/1903). Since space-handling changed in opentype (and now should work correctly) you might just want to try removing this special casing ([here](https://github.com/processing/p5.js/blob/29fe10f5467308398d984d84f08ace5b60db3fc3/src/typography/p5.Font.js#L137)).

**Comment by dhowe** [comment]
Glancing at the code, I also notice what appears to be another small bug in textBounds (called by textWidth), which I am fixing now (though I don't think it will affect this issue).

**Comment by dhowe** [comment]
Actually, I'm not even sure this is a bug. There is an assumption here that the spacing between words is _only_ determined by the width of a space (and does not take into account things like kerning), but that may not be the case for all fonts

**Comment by mlarghydracept** [comment]
Hm yeah I don't know enough about type to know whether this is expected behavior. Removing the special casing you mentioned doesn't give a different result on the extra wide line but it does break the calls to `textWidth(' ')` on the loaded font.

**Comment by dhowe** [comment]
I don't see the 'break' you mention. Can you try the same test with [this PR]( https://github.com/processing/p5.js/pull/1970) ?

**Comment by mlarghydracept** [comment]
Yeah so the 'break' I mentioned doesn't happen with that branch. I probably accidentally changed something else when I was removing the lines you mentioned. Everything looks exactly as it does in the current release in my tests on that branch. With that said, the spacing is still different on the loaded font from @cqx931's example so maybe this is expected behavior?

**Comment by dhowe** [comment]
https://stackoverflow.com/questions/22904372/how-do-i-calculate-the-space-in-between-two-glyphs-in-a-ttf-font

**Comment by dhowe** [comment]
In any case, I might recommend reposting @cqx931's question as an [opentype issue](https://github.com/nodebox/opentype.js/issues) (creating a very simple test without p5.js, based on the code in the [README](https://github.com/nodebox/opentype.js))

**Comment by mlarghydracept** [comment]
@cqx931 maybe do you want to take @dhowe's advice for the time being? As it stands it is feeling like this isn't a p5 specific issue. I am going to close for now but feel free to comment on this issue or open another one if any new information arises.

**Comment by dhowe** [comment]
Here's a test of the 3 cases (p5/default, p5/custom, and opentype): opentype has the same behavior and spacing as what we are getting in p5, so it is not something specific to our code. Though whether that extra-space comes from kerning, advance, or some other metric in opentype, is still an interesting question...

![image](https://cloud.githubusercontent.com/assets/737638/26728885/509d4a86-47de-11e7-88f5-396706df44fc.png)

**Comment by dhowe** [comment]
I've done a bit more digging and the spacing above is cause by the fact that opentype does the layout using advance-width, rather than bounding-box.width, and for some glyphs, like spaces, these values are difference. Here is the manually corrected result of the test above (the difference is that the 2 lines in the 3rd set are now the same width):

![image](https://cloud.githubusercontent.com/assets/737638/26730120/826d1768-47e2-11e7-83bd-b176407e885f.png)

**Comment by dhowe** [comment]
The only issue remaining is that this means of (correctly) calculating the advance is not included in the the version of opentype that we are using (v0.6.9), so we should update to the current version (see )

**Comment by dhowe** [comment]
with the help of @cqx931, I've submitted a PR that address this issue and #1976

**Comment by dhowe** [comment]
With the help of @cqx931 (who also provided a font whose layout matches the default rendering), here's  a [PR](#1977) that address this and #1976:

![image](https://cloud.githubusercontent.com/assets/737638/26733006/1e4cbc0c-47ec-11e7-987e-b2e6510aa39f.png)

**Comment by lmccart** [comment]
awesome @dhowe and @cqx931! closed with https://github.com/processing/p5.js/issues/1976
