### ISSUE TITLE
Feature request/discussion: Simpler for loop syntax

### ISSUE THREAD

**Issue by kristianpedersen** [processing/p5.js#1990]
I still remember the disappointment and confusion when I was introduced to for loops. 

Printing out a range of numbers, or repeating something n times, should be simpler. Ruby has `1000.times`, and lodash.js has `_.times(1000)`, for example.

# Someone somewhere meets the for loop

Student:
"Can I make a program that counts to 1000? ツ

Teacher:
"Yes, you can! Counting is one of the things computers do best! First you write "for", just because that's the word they use. Then you write parenthesis and declare a variable called i, which will be your counter program's starting point. Then you write a condition which will keep the loop running as long as it evaluates to true. In this case, the loop should run while i is less than or equal to your finishing number. Ah and don't forget to increment the variable. Yes, you have to do it in this order. You thought you knew addition? Well, now you can write two pluses! Or you also say i = i + 1, or i += 1.":

```
for (var i = 1; i <= 1000; i++) {
  print(i);
}
```

Student: 
ಠ_ಠ

Of course, this is a terrible explanation to give to someone who has never programmed before. Regardless, the code above is quite a handful to take in for a beginner, and I think it's kind of awkard to be honest.

# Simpler approaches

What I would like to see is something along these lines:

`count(1, 1000, print(i))` // 1..1000
or 
`count(1000, print(i))` // 0..999

I think it makes sense to have it default to 0, do you agree? Counting from 0 instead of 1 trips up beginners no matter what, so at least it would be nice with a more readable syntax.

Something very close to what I want can already be done in lodash.js, although it seems you have to use -functions- for it to work:

`_.times(1000, i => print(i+1))`

`_.times(1000, () => ellipse(random(width), random(height), random(100), random(100)))`

For arrays that already have contents, forEach and map (native JavaScript, not p5) are nice:

`blobArray.forEach(blob => blob.update())`
is much more readable than
`for(var i = 0; i < blobArray.length; i++) {blobArray[i].update()}`

Next up is the this dot, never forget the this dot.

# People who pick up p5.js just wanna have fun

Of course, every programmer should know about for loops, but not everyone is going to be a programmer, and I think it would be cool if beginners could focus more on high-level ideas instead of awkward syntax. 

P5 users come from a very diverse set of ages, ideas, backgrounds, goals, skillsets and personalities - and they all have something to share. It's already a super exciting initiative, and I'm looking forward to seeing it continue to grow. Cheers!

**Comment by mlarghydracept** [comment]
I am really interested in this and you make a good argument. I feel like it fits in with p5's mission as you stated at that bottom.

A few questions though:

- Do you think having a functions like the `count()` that you proposed would make it harder for people to read across javascript and p5 code? 
- In a similar vein, what do you think about hiding the for-loop from new users? Is that removing a hurdle or delaying it with added confusion later on?
- In the example you gave the variable `i` appears somewhat magically which presupposes a familiarity with for-loops or iterators. Is there a way to make this more transparent? Could be through naming conventions but in that case `i` may be the best because of the above questions.

Thanks for the well written proposal!

**Comment by kristianpedersen** [comment]
> Do you think having a functions like the count() that you proposed would make it harder for people to read across javascript and p5 code?

Isn't this already the case in regards to Canvas, DOM manipulation and many other P5 abstractions? 
For DOM, I'm more used to native JS than jQuery, but I'm more used to P5 than native Canvas.

Also, I think P5's `map()` is good example of potential confusion, but high usefulness. It could be confusing coming from JavaScript's native `Array.map()` function, which does something completely different. Also, for non-programmers, I guess it's confusing that it doesn't have anything to do with navigation. It's still one of the most useful functions in P5.

---

> In a similar vein, what do you think about hiding the for-loop from new users? Is that removing a hurdle or delaying it with added confusion later on?

Well, this proposed simplicity -would- add more complexity and potential confusion to the P5 project.

I think it would be worth it, as beginners could immediately get the experience of creating 1000 circles on the screen, and say "hey, look at this" without having to look up confusing verbose for loops.

It's like teaching phrases in a foreign language, which can be used immediately, and rather learn the difficult stuff later on. When a grammatical construct is introduced, you can then recognize it from sentences you've learned and used, rather than trying to make sense of it from scratch without anything to associate it with.

Similar principles apply to music teaching, I think. I recently taught someone how to play chords (three notes simultaneously) on a piano.
You start somewhere, and play every other white key. (C would be C-E-G, and D would be D-F-A). 

I could have said that the C is major and D is major, that their notes can be shifted an octave (A-D-F and F-A-D), and that the black keys don't matter, but the distance between each note does. 

My simplified lesson didn't teach her as much as she could have learned, and she would have trouble comminucating with experienced musicians, but she found it very enjoyable, and even figured out some things along the way herself.

---

> In the example you gave the variable i appears somewhat magically which presupposes a familiarity with for-loops or iterators. Is there a way to make this more transparent? Could be through naming conventions but in that case i may be the best because of the above questions.

Good point. I guess `currentNumber`, or even `currentNumbers` would be a better choice. 

---

> Also might be worth thinking about how nested count() calls and multiple statements would look inside this function. Styling stuff could become confusing pretty fast.

I'm not sure how to handle nested calls to `count()`. What would be the output of `count(1, count(3, 14))`, for example?

Maybe something super simple like `grid(5, 4)` would be a better option? I'm not exactly sure what its output should be though, as people might have very differing expectations.

Either way, traditional nested for loops require you to type/read a lot before you get to the point. In a way, it makes me think of the intimidating, formal and terminology-heavy language used in academia and the public sector:

```
for (var x = 0; x < 5; x++) {
  for(var y = 0; y < 4; y++) {
    // ...
  }
}
```

I'd be curious to hear experiences from successful and failed efforts to simplify programming concepts this way. I've been to a couple of Scratch workshops, and it was cool to see both kids and teachers get into it.

**Comment by sixhat** [comment]
My 2cents:

one has to be careful with the kind of abstractions one makes and that in the end hide design patterns from the user. 

One thing is to hide complicated stuff that results from the language having to deal with `externalities`. The canvas example is a good one. Dealing with canvas (an externality to javascript) is complicated (not complex) and therefore is a good candidate to simplification and abstraction. The same goes with the DOM, or asynchronous calls, etc...

The other thing is to try to abstract basic design patterns of the programming language (javascript) itself. The for loop (or the while loop) is a construct of the basic language and not of an externality. That would mean inventing a new language that would run on top of the javascript engine (remembering languages that run on the JVM).  I don't think that this is a good thing to do, because then P5.js would become P5.nameOfNewLanguage. 

Also, javascript has many other constructs for loops and iterations that can be used. ES6 even brings a few more. And if some user really needs some `simpler?` functions that abstract basic design patterns P5.js already allows the user to add external libraries (after all it is JS) and the user can go and import `underscores.js` or `jQuery`, or whatever they are comfortable with.

Maybe it would be better to explore the route of giving examples to new users on how to do take advantage of `for` loops instead of trying to hide the language from them.

Another aspect that might be important to notice is in teaching. As a teacher myself at our Univ. (a Design University) we use P5 not just because it is easy for the students to start with, but because it allows us to teach them algorithms and programming patterns that they can take and use with other libraries when they need. If they learn only P5 specific language that hides javascript, then they won't carry that knowledge to other situations. Potentially it will makes us drop P5 in favour of other solutions.

Sorry if this seems a bit harsh. It is just that don't think one really should change core fundamentals of the language, and should instead focus on the features of the library, that simplify the interaction of the core language with the `externalities`. 

-- Dave.

**Comment by lmccart** [comment]
very interesting idea. I love the ease that your suggested methods provides. I do agree that I think there's something useful about not abstracting away for loops completely though.
to me, this seems like a perfect starting point for a helper addon library that could be used with p5.js to provide these sort of convenience methods.

**Comment by kristianpedersen** [comment]
Thanks for very helpful and insightful input, Dave! This is excellent.

One disadvantage of my proposal is that such convenience methods won't be found much in tutorials and other online resources, which I can imagine being a bit disheartening. 

Also, maybe someone is starting out and needs help from a friend who is an experienced programmer. 

In both cases, it would then be nice not to be overwhelmed by for loops, and rather focus on the problem at hand.

Dave has a very good point, in that as someone grows comfortable with P5, they're able to explore the endless possibilities of the rest of the JavaScript community - definitely a really important concern.

Perhaps the best solution would be to go show a few available options. 
In a classroom setting, students could first get solid practice with regular for loops, and later be shown things like `.forEach()`, `_.times(n, fn)` or even this: `[...Array(500)].forEach(() => ellipse(random(100), random(100), 50, 50))`.

___

However, I still can't shake the feeling that a tool whose users include artists and non-programmers should include simple functions for setting up ranges and grids.

It's important to be familiar with common syntax, but also to think about iteration, repetition and your sketch's design on a higher level.

**It would be cool if things like `ellipse` could accepts arrays as arguments!** 
If several arrays are passed to it, the largest array's length would determine how many get created. 

Combined with an imaginary `range(start, upToIncluding, stepSize[optional, default: 1])` function, it could look like this:
```
const stepSize = width / 10;
const x = range(0, width, stepSize);

ellipse(x, height/2, 50, 50);

// Or this, which reads super nicely:
ellipse([0, 100, 200, 300], height/2, 50, 50);
```
or
```
const stepSizeX = width / 10;
const stepSizeY = height / 10;
const x = range(0, width, stepSizeX)
const y = range(0, height, stepSizeY)

ellipse(x, y, 50, 50);
ellipse([0, 100, 200], [0, 100, 200], 50, 50); // Obviously creates a 2D grid! :)
```

**Comment by limzykenneth** [comment]
Great discussions, really look forward to what everyone thinks here!

Generally I agree with @sixhat about not abstracting too much away, I like to treat p5.js more as a library to ease new users to Javascript but it should present away to move forward from it even if it means using something else.

> **It would be cool if things like `ellipse` could accepts arrays as arguments!**

That though I kinda like although it probably is a bit too specific for the library to implement. I actually was doing some initial design for a grid drawing addon library a few months ago but got sidetracked...

**Comment by meiamsome** [comment]
If you aren't too adverse to ES6 it might be worth looking at the [for...of operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...of).

Examples:
```javascript
for(const i of [0, 1, 2, 3, 4]) {
  console.log(i);
}
// Outputs the numbers in a row.
```
Or perhaps something like:
```javascript
for(const i of new Array(10).keys()) {
  console.log(i);
}
// Outputs 0 to 9 inclusive
```

Not very pretty way to get the number though. Perhaps a good candidate for p5js would be to introduce a range function similar to [pythons](https://docs.python.org/3.6/library/functions.html#func-range) such that it could be used:
```javascript
for(const i of range(10)) {
  console.log(i);
}
// Outputs 0 to 9 inclusive
```

**Comment by lmccart** [comment]
thanks for the great discussion everyone! I agree with not layering too much magic on top of native JS, so that people can transition easily from p5.js to the rest of the web. I'll follow up on the other PRs to continue this discussion.
