### ISSUE TITLE
gif file doesn't work on chrome browser

### ISSUE THREAD

**Issue by estelll** [processing/p5.js#2029]
I recently used p5 to realize some animation. I load .gif file but it did not change and was static.
Here is my code:
`function preload(){
    for(var i = 0; i < 19; i++){
        imgs.push(loadImage('img/' + str(i) + '.gif'))
    }
    currentImg = random(imgs);
}
    image(currentImg, width, height, imgSize, imgSize);
`
But I read the reference on p5.org which said that 

> p5 can display .gif, .jpg and .png images.

How can I let my .gif move?

**Comment by lmccart** [comment]
since p5.js redraws many times per second, gifs are not able to play out in canvas. an alternative is to use the [`createImg()`](https://p5js.org/reference/#/p5/createImg) method which adds an image to the sketch outside of the canvas that is not effected by the draw loop. for further help, please post in the [forum](forum.processing.org)
