### ISSUE TITLE
I think texture is broken ... i can't able to use it

### ISSUE THREAD

**Issue by glearner** [processing/p5.js#2039]

**Comment by kjhollen** [comment]
Hi @glearner,

Can you provide us some more details, like a sample program where texture() doesn't work?

I think that if you call stroke() or fill() after texture(), the p5 renderer will will the shape instead of using the texture. Note that using texture() with beginShape() and endShape() is not currently supported in 3D mode. (See Issue #1421).

**Comment by limzykenneth** [comment]
@glearner I'm closing this issue for now. Feel free to reopen if you can provide more details.
