### ISSUE TITLE
Faster Bezier

### ISSUE THREAD

**Issue by ChristerNilsson** [processing/p5.js#2063]
I think bezierPoint can be sped up by a factor 3.
Reason: Math.pow(x,3) is slow compared with multiply.

Current implementation:
```
p5.prototype.bezierPoint = function(a, b, c, d, t) {
  var adjustedT = 1-t;
  return Math.pow(adjustedT,3)*a +
   3*(Math.pow(adjustedT,2))*t*b +
   3*adjustedT*Math.pow(t,2)*c +
   Math.pow(t,3)*d;
};
```

My proposal:
```
bezierPoint = (a,b,c,d,t) ->
	s = 1-t
	s*s*s*a + 3*s*s*t*b + 3*s*t*t*c + t*t*t*d
```
I guess there are related Bezier functions that can be sped up to.

**Comment by ChristerNilsson** [comment]
Actually, the speed up is closer to a factor 2.

**Comment by limzykenneth** [comment]
Of the browser I've tested (Safari, Chrome, Firefox; all latest version and on latest macOS), only Safari showed faster execution for multiplication compared to `Math.pow`, I suspect being the javascript engine is less optimized for this case for Safari compared to the other two. You can run the tests I found on [jsPerf](https://jsperf.com/jslayer-math-pow-vs-multiplcation/2).

While it is a speed up for Safari users (maybe some other browsers as well), I wonder if the calls to `Math.pow` is the bottleneck for this function. If possible, I would like to have a test case to stress test this particular function and see what kind of runtime improvements we can get from making this change.

Having said that, I don't see too much problem for changing to use multiplication instead of `Math.pow` fundamentally.

**Comment by ChristerNilsson** [comment]
I tried a more complete test, but could only repeat your findings.
[jsperf](https://jsperf.com/bezierpt) 
Using Chrome Version 59.0.3071.115, Windows 7 and Sony Vaio from 2012.
Maybe we should drop this issue.

**Comment by ChristerNilsson** [comment]
My own measurements shows an improvement. This can't be repeated using jsperf.
I also get a feeling, that the execution order is important. Try acb instead of abc.

```
millis = function() {return window.performance.now();};

bezierPointOrig = function(a, b, c, d, t) {
  var adjustedT;
  adjustedT = 1 - t;
  return Math.pow(adjustedT, 3) * a + 3 * (Math.pow(adjustedT, 2)) * t * b + 3 * adjustedT * Math.pow(t, 2) * c + Math.pow(t, 3) * d;
};

bezierPt = function(a, b, c, d, t) {
  var x;
  x = 1 - t;
  return x * x * x * a + 3 * x * x * t * b + 3 * x * t * t * c + t * t * t * d;
};

start = millis(); // a
for (var n = 0; n < 1000000; n++) {bezierPointOrig(5.0, 4.50, 5.0, 5.0, n/1000000);}
print(millis() - start);

start = millis(); 
for (var o = 0; o < 1000000; o++) {bezierPt(5.0, 4.50, 5.0, 5.0, o/1000000);}
print(millis() - start);

start = millis(); // b
for (var l = 0; l < 1; l+=0.000001) {bezierPointOrig(5.0, 4.50, 5.0, 5.0, l);}
print(millis() - start);

start = millis();
for (var m = 0; m < 1; m+=0.000001) {bezierPt(5.0, 4.50, 5.0, 5.0, m);}
print(millis() - start);

start = millis(); // c
for (var i = 0; i < 1000000; i++) {}
print(millis() - start);

start = millis();
for (var k = 0; k < 1; k+=0.000001) {}
print(millis() - start);

```
43.775000000000006
9.859999999999985
76.15
27.845000000000027
6.569999999999936
27.004999999999995
