### ISSUE TITLE
Missing dragStart event

### ISSUE THREAD

**Issue by libasoles** [processing/p5.js#2103]
#### Nature of issue?
- [x] Existing feature enhancement

#### Most appropriate sub-area of p5.js?
- [x] Events

#### Which platform were you using when you encountered this?
- [x] Desktop/Laptop

#### Feature enhancement details:
As you can see, there's a 'dragend' event, but not a 'dragstart' one.
However, we do have 'touchstart' and 'touchend'.

``` javascript

 this._events = { // keep track of user-events for unregistering later
    'mousemove': null,
    'mousedown': null,
    'mouseup': null,
    'dragend': null, // SEE HERE
    'dragover': null,
    'click': null,
    'mouseover': null,
    'mouseout': null,
    'keydown': null,
    'keyup': null,
    'keypress': null,
    'touchstart': null,  // HERE
    'touchmove': null,
    'touchend': null,  // AND HERE
    'resize': null,
    'blur': null
  };
```

I think we should be able to differentiate 'mousemove' from 'mousedrag'. First one has no mouse click involved, but second does.

Check mouse.js for more info:

``` javascript

p5.prototype._onmousemove = function(e){
  var context = this._isGlobal ? window : this;
  var executeDefault;
  this._updateNextMouseCoords(e);
  
  if (!this.mouseIsPressed) {    // <- SEE HERE
    if (typeof context.mouseMoved === 'function') {
      executeDefault = context.mouseMoved(e);
      if(executeDefault === false) {
        e.preventDefault();
      }
    }
  }
  else {   
    if (typeof context.mouseDragged === 'function') {
      // HERE EVENT SHOULD BE NAMED 'dragstart' BUT IT'S CALLED 'mousemove' 
      executeDefault = context.mouseDragged(e); 
      if(executeDefault === false) {
        e.preventDefault();
      }
    } else if (typeof context.touchMoved === 'function') {
      executeDefault = context.touchMoved(e);
      if(executeDefault === false) {
        e.preventDefault();
      }
    }
  }
};
``` 

Not sure what is 'dragover' btw.

**Comment by limzykenneth** [comment]
`dragStart` and `dragOver` are not mouse events, they are events bound to DOM elements, a lot of the times text elements. Have a look at the specs [here](https://developer.mozilla.org/en-US/docs/Web/Events/dragstart). Whether would it be a good idea to bootstrap one for mouse events ourselves, I'm not very keen on simply because it veers away from parity with native events.

**Comment by libasoles** [comment]
Thanks for the link. I didn't know about the standard. 
So, I'm missing an event for mouse drag. See, _mousedown_ & _click_ events are basically the same. They happen once. And yes, we have _mousemove_ that tracks the mouse every frame. But it's up to the user to check if one of them occurred before _mousemove_ to assure that mouse is being pressed while moved.

See, in processing _mouseDragged_ emits an event on every single frame. Try this sketch:

```
void mouseDragged() {
  print(".") ;
}
``` 

By other hand, as far as I can tell browser events specification doesn't fit p5 entirely, because clearly those events co-exist with elements (_text_ or whatever). And we don't have these elements natively in p5. So I'd spec something like processing more than a browser specification on this.

**Comment by limzykenneth** [comment]
Yeah, when I say parity with native events, that just is a nice to have so people know what to expect when moving to p5 from something else or moving to something else from p5. There is also a `mouseDragged` function in p5 that works similarly while not long ago I have proposed an element specific `mouseDragged` handler as well. 

I agree that detecting when the `mouseDragged` event starts would be useful for some cases, I just wonder if it would be something that needs to be implemented in p5, since the user can just have a variable tracking start such as this:

```
var dragStart = false;
function mousePressed(){
  dragStart = true;
}

function mouseDragged(){
  if(dragStart){
    // dragging just started
  }
  dragStart = false;
}
```

What are your thoughts?

**Comment by lmccart** [comment]
the drag events only work if an element is set to draggable. they are not fired by default on a document. our general principle is to do as little behind the scenes magic and customization as we can, so for now, I think we can leave this is. if you want to broadcast an event, I'd suggest broadcasting from a custom mouseDragged() function you create and modifying the event type there.
