### ISSUE TITLE
problem with mouseIsPressed

### ISSUE THREAD

**Issue by F4Tornado** [processing/p5.js#2113]
when I call the alert function, mouseIsPressed variable will say true even when it should say false until you click.

#### Nature of issue?

- [x ] Found a bug

#### Most appropriate sub-area of p5.js?

- [ x] Events

#### Which platform were you using when you encountered this?

- [x ] Desktop/Laptop

#### Details about the bug: 

- p5.js version: p5.js v0.5.4 October 01, 2016
- Web browser and it's version: Google Chrome 60.0.3112.90
- Operating System: Windows 10
- Steps to reproduce this: call alert function.

```
alert('evil bugs');
setInterval('console.log(mouseIsPressed)', 10);
```

**Comment by lmccart** [comment]
the alert() dialog will halt the running of the sketch completely, so this may cause mouse events and variables to not get updated properly. I'm not sure we can handle this in the library since the alert() interrupts the normal library function, but you could make your own alert dialog using createElement(), show(), and hide()?
