### ISSUE TITLE
Feature request: boolean 3d modeling

### ISSUE THREAD

**Issue by bcbradle** [processing/p5.js#2130]
#### Nature of issue?

- [x] New feature request

#### Most appropriate sub-area of p5.js?

- [x] Shape

#### New feature details:

I think it would be really cool if p5.js had three additional functions to create new 3D primitives:

difference(a, b) would subtract volume b from volume a, for instance cutting a rectangular hole in a cylinder.

union(a, b) would return the union of the volumes-- for instance you could use it to return a sucker shape by putting a sphere on the end of a thin cylinder.

intersection(a, b) would return the shape common to both shapes, for instance the intersection of a cube and a sphere could return a cube with rounded corners and edges.

alternatively, these functions could also operate on 2d shapes and/or a mix of shapes of different dimensions. For instance, the intersection of a plane and cone at the right angle can give a curve that is a "bow" shape.

Here is my reasoning:

Doing anything very sophisticated in 2D (custom shaders or framebuffer management) would probably necessitate dropping out of p5.js and using opengl directly-- and thats fine, its not the mission of p5.js to supplant opengl. People use p5.js not because of the power it gives them, but because of the bargain at which they get the power offered-- using p5.js is so simple even a newcomer can use it with confidence, and that is vital to the mission goals of p5.

I think the suggested functions give people a way to think about and work with shapes in 3d and provide a lot of value for very little cost. That isn't to say that the cost of implementing these functions isn't high, but that they cognitive cost from the perspective of the user is low.

**Comment by lmccart** [comment]
thanks @bcbradle! I think the donut function is beyond the scope of the p5.js api (we try to keep as minimal as possible) but it could be a great starting point for an addon library. see the docs here for how to create an addon: https://github.com/processing/p5.js/wiki/Libraries#creating-a-new-library

**Comment by nevahid** [comment]
@bcbradle  @lmccart  hi people... i found this request while searching for a way to make a hole in a 3d shape... is there any progress about this? anything made public?
thanks in advance

**Comment by lmccart** [comment]
@nevahid sorry, no updates on this from the p5.js library end

**Comment by nevahid** [comment]
@lmccart thanks or our response... do you think i can achieve it by using gl.blendFunc()?

**Comment by stalgiag** [comment]
Hi @nevahid I don't think you will be able to achieve this with gl.blendFunc. Boolean operations are very much out of scope for this library. Even three.js doesn't have this feature as far as I know. If your shape is relatively simple and you know how to make it with custom vertices then you might look into [building this work-in-progress branch](https://github.com/processing/p5.js/pull/3680). Most likely the simplest solution is to make the hole in 3d modeling software and load the model into p5. Otherwise you might try looking [into csg.js.](http://evanw.github.io/csg.js/). Good luck!

I am closing this. It is a nice idea but very out of scope.

**Comment by nevahid** [comment]
@stalgiag thank you very much for your response and your guidance... i was trying to use csg.js and was thinking about somehow applying its ideas... i just saw the post you mentioned... i think it will really help me, because my objects are only axis aligned boxes, thank you a lot...

**Comment by ffd8** [comment]
@stalgiag thanks for the tip above to checkout csg.js! A student was really interested in this capability, so I started doing some research = not quite as easy as I hoped... Definitely makes sense as a library rather than built in function (maaybe) – and I see there's a few THREEjs bridges ([ThreeCSG](https://github.com/chandlerprall/ThreeCSG), [THREE-CSGMesh](https://github.com/manthrax/THREE-CSGMesh), [threejs-csg](https://github.com/looeee/threejs-csg), [three-2-csg](https://github.com/knee-cola/three-2-csg), [...](https://github.com/search?q=csg+threejs)).. sadly couldn't find a p5 specific one....yet. Any idea how hard this would be to do? I put together a [very basic demo](https://editor.p5js.org/ffd8/sketches/ltqoUz4b6) with original csg.js lib – however only works as strokes (with lots of overlap).. shading with texture or fill/lights fails, since each of these polygons are isolated rather than a solid model/mesh = where I'm lost. Any idea if there's a relatively simple function to bridge back and fourth between how csg deals with polygons vs p5 model? Would be amazing to pass these CSG functions back and fourth with p5 for custom complex shapes from primatives and imported models!
