### ISSUE TITLE
clarify remove() documentation (note that it doesn't remove variables, functions, intervals)  and add an example indicating what is removed

### ISSUE THREAD

**Issue by RoseCrime** [processing/p5.js#2132]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [x] Core
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

- p5.js version: 0.5.11(min)
- Web browser and it's version: FireFox Developer Edition (56.0b3),FireFox(55.0.2),Chrome(60.0.3112.101)
- Operating System: Win 7.

Bug info in short:
remove() function in p5 doesn't erase all global variables as reference (https://p5js.org/reference/#/p5/remove) says.Also,it doesn't stop or erase setInterval functions.
(removes canvas and stop draw loop works).

- Steps to reproduce this:
1.Make any simple sketch with any variables.
2.Remove it with p5 remove() function
3.Check it's value.
4.Now we know - variables and values saves.
5.Make new sketch (even "new p5" will restore same canvas,since all variables saved)
5.Make counter increase in setInterval JavaScript function.
6.remove() everything again.
7.open console and check counter value;
8.check it again;
9.and again;
10.All values are different.
11.Make any function,not nessesary to call it.
12.remove() everythin'.
13.Check function in console.
14.It still exist too.

Simple example:
https://codepen.io/RoseCrime/pen/QMmqzj

**Comment by limzykenneth** [comment]
The reference may not be clear enough but what it means by

> unbind any properties or methods from the window global scope

is not removing global variables created by your code but rather global variables created by p5 global mode, ie `setup`, `draw`, `PI`, `TWO_PI`, etc.

It won't stop or erase any intervals because that isn't what `remove` does as well. You will have to take care of cleaning up intervals in your code. The main reason that `remove` doesn't clean all these up for you is because there is no way of knowing what is created by your p5 sketch's code and what is created by some other non-p5 related code. The p5 `remove` function will just ensure that all functions and variables created by the library for the library as well as the canvas is removed, any other global variables created by your code will remain.

**Comment by RoseCrime** [comment]
Alright,thanks for clearing that up :)
Hope reference will be more clearly at this point some day too.
(Even now I can't imagine what exactly it can remove except Canvas and stopping loop
My experiments with little game shows - everything' still exists except canvas ,just paused.
Everything from shapes to whole setup() and draw() functions...
But guess cause it stores in arrays or variables...except setup and draw , again.)

Guess I just need a simple example what exactly it can remove and what can be restored with "new p5"

Sorry for about to off-topic comment.

**Comment by lmccart** [comment]
thanks @RoseCrime for reporting this, it helps us to understand where the documentation is unclear or lacking. I'm going to update the issue title to turn this into a todo to add clearer documentation and a good example of remove.
