### ISSUE TITLE
camera rotation

### ISSUE THREAD

**Issue by drcrotato** [processing/p5.js#2161]
#### Nature of issue?

- [ ] Found a bug
- [ ] Existing feature enhancement
- [x ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [x ] WebGL
- [ ] Other (specify if possible)

#### New feature details:

I would like something that can change the direction the camera is pointing, for example,

`rotateCamera(1, 2)
//rotate the camera 1 radian right, 2 radians up.
`

And
`rotateCamera(-1, -2)
//rotate camera 1 radian left, 2 radians down
`

**Comment by stalgiag** [comment]
I am closing because I think that this original request has been filled for the most part. While it isn't the exact api that you requested, the [camera](https://p5js.org/reference/#/p5/camera) function provides something functionally similar to this with `centerX`, `centerY`, and `centerZ` parameters.

**Comment by AidanNelson** [comment]
If you create a camera object using `let cam = createCamera()` you are able to then use `cam.pan(delta)` and `cam.tilt(delta).` More info on that API here: https://p5js.org/reference/#/p5.Camera
