### ISSUE TITLE
var position = new p5.Vector(width,height); // Bug detected (width and height does not work here)

### ISSUE THREAD

**Issue by Worseize** [processing/p5.js#2162]
#### Nature of issue?

- [x] Found a bug

#### Most appropriate sub-area of p5.js?

- [x] new p5.Vector( width, height ); // width and height does not work here

#### Which platform were you using when you encountered this?
- [x] Desktop/Laptop

#### Details about the bug: 

- p5.js version: 3.3.6 
- Web browser and version: 60.0.3112.113
- Operating System: Windows 10
- Steps to reproduce this:
new p5();
function setup() {
  createCanvas(768,768);
}
var position = new p5.Vector(width,height); // Bug detected (width and height does not work here)
function DrawLine(){
  stroke(255);
  strokeWeight(2);
  line(position.x,position.y,width/2,height/2);
}
function draw() {
  background(0);
  DrawLine();
}

**Comment by lmccart** [comment]
In your code, you're assigning position = new p5.Vector(width, height) outside of draw. Even though the code is after the setup function on the page, it gets evaluated first because first all global (outside of setup or draw or a function) code gets evaluated, then setup gets run. So at the point the p5.Vector is created, width and height are still 0. The width and height don't get set until the canvas is created. I have rearranged your code to declare the variable outside setup, but assign it inside, after the canvas is created, and now the drawing renders correctly.

```javascript

var position;

function setup() {
  createCanvas(768,768);
  position = new p5.Vector(width,height)
}

function DrawLine(){
  stroke(255);
  strokeWeight(2);
  line(position.x,position.y,width/2,height/2);
}

function draw() {
  background(0);
  DrawLine();
}
```
