### ISSUE TITLE
Implement arc() for webgl mode

### ISSUE THREAD

**Issue by kjhollen** [processing/p5.js#2181]
#### Nature of issue?

- [ ] Found a bug
- [ ] Existing feature enhancement
- [x] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [x] WebGL
- [ ] Other (specify if possible)

#### Feature enhancement details:

arc() only works in 2D mode currently, but it would be great for WEBGL mode, too.

This would make a great first contribution for someone who wants to get to know the project and write a little webgl code! the implementation for ellipse() would be a good place to look as a reference.

**Comment by Siphonophora** [comment]
Hi, 

I can take this on. 

Quick question. When drawing an arc like the one below, we can either define the straight edge with two vertices or several. I would prefer the left option, because it would let me precisely place the two red vertices. Let me know if having all the edges radiate out from the center is preferable (and any thoughts about placing the two red vertices). 

![image](https://user-images.githubusercontent.com/32316111/30916563-b80169ac-a367-11e7-95b3-0b51d66c36f1.png)

**Comment by kjhollen** [comment]
The left side picture seems reasonable to me. Also, while I'm thinking of it, there might be a little more work needed here to ensure that stroke for this is the outline rather than outlining all the shapes... @mlarghydracept would probably have more insight here!

**Comment by Siphonophora** [comment]
I would appreciate input on drawing the edges. So far, I have been focusing on the textured output. From left to right those are OPEN, PIE, and 'FAN'. The last is an alternate texture mode for the PIE shape.   

![arc results](https://user-images.githubusercontent.com/32316111/30950560-aee5e4d6-a3eb-11e7-9592-8c5ec0328172.png)

Underlying geometry
![arc results geometry](https://user-images.githubusercontent.com/32316111/30950807-409972ac-a3ed-11e7-8a74-3c84b332658f.png)
