### ISSUE TITLE
Calling redraw does not cause an increase in frameCount

### ISSUE THREAD

**Issue by meiamsome** [processing/p5.js#2192]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [x] Core
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

This should probably not be the default behaviour?

Example modified from the redraw documentation:

```javascript
var x = 0;
function setup() {
   createCanvas(100, 100);
   noLoop();
 }
function draw() {
   background(204);
   line(x, 0, frameCount, height);
 }
function mousePressed() {
   x += 1;
   redraw();
 }
```

**Comment by limzykenneth** [comment]
I'm not entirely sure increasing `frameCount` would be the intended behaviour with `redraw`. 

According to documentation it only says "Executes the code within draw() one time" and didn't mention anything about frameCount so we need to think about potential use.

Not increasing `frameCount` on `redraw` will serve as a more accurate measure of how long the code have executed barring external calls to `redraw` (no idea if `frameRate` is tied to this directly or not but if it is, that would be messy). Increasing `frameCount` on `redraw` is one way to easily count how many times the code in `draw` has executed without resorting to defining your own counter and `counter++` it in `draw`.

I'm not sure which is better for usability because I seldom use `frameCount` and can't come up with any practical example at the moment. What do you think?

**Comment by meiamsome** [comment]
It's hard to say which is better - I too also don't really use `frameCount` all too much, but was surprised that its name doesn't reflect the count of frames rendered. What is Processing's behaviour?

Either way, we should ass a test to check that the `frameCount` does what's expected.

**Comment by lmccart** [comment]
processing does update the frameCount, and I agree with the logic that frameCount should be the count of frames render, so let's see if we can adjust the code and add a test toward this.
