### ISSUE TITLE
pixels array is an object/string, not an array!

### ISSUE THREAD

**Issue by lee2sman** [processing/p5.js#2206]
#### Nature of issue?

- [X] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [X] Core
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [ ] Desktop/Laptop
- [X] Others (specify if possible) - Alpha Editor

#### Details about the bug: 

- p5.js version: Alpha Editor
- Web browser and version: Chrome
- Sample code [Here](http://alpha.editor.p5js.org/2sman/sketches/SJqDWWDoW)

Hi, This is outputting an object on the console when I think it should be printing an array!

**Comment by lmccart** [comment]
heheh it is an object masquerading as an array!

**Comment by lee2sman** [comment]
ah, so it's intentional?!

**Comment by lmccart** [comment]
i dont think so..

**Comment by lmccart** [comment]
pixels is a reference to the canvas (ImageData object](https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Pixel_manipulation_with_canvas). we've kept the direct reference because it speeds getting and setting pixels. however, it is confusing as you point out. would it make sense to just change the type to object but leave the description and examples illustrating how to access it as is?

**Comment by lee2sman** [comment]
yes, that would help. i was expecting an array and got very confused when i tried to access it like one.

**Comment by meiamsome** [comment]
Note that using `console.log` instead of p5's `print` yields the correct result - a `Uint8ClampedArray`. It looks like passing that through JSON stringify (as in `print`) results in an Object representation, not an Array.
