### ISSUE TITLE
Failed Preloads: intended behaviour?

### ISSUE THREAD

**Issue by meiamsome** [processing/p5.js#2208]
What is the intended behaviour for a request in preload that fails - currently it hangs the sketch in the "Loading..." screen and doesn't give any feedback to the user by default. Perhaps we could add a default "Failed to load" render, and a function to overload it.

(Note that this is partly related to #1881)

**Comment by limzykenneth** [comment]
The current implementation is so that if it fails, it throws and error in the console and decrementPreload is not called since it is assumed that the required data for the sketch is not loaded. If an error callback is provided, that will be used to handle the error and the error won't be thrown by default, however, decrementPreload will still not be called.

**Comment by kaininc** [comment]
Same problem here

**Comment by lmccart** [comment]
If there's an error in the console, I think this is feedback. I'm hesitant to go too far with popping up things into the sketch itself, I'd rather instead try to get users to think to look there. The FES helps with this to some extent, the web editor will make this easier because the console will be open by default. I wonder if we need to do anything else like updating the get started docs to recommend opening the console?

**Comment by meiamsome** [comment]
There appears to be no error in console when the network requests succeeds but the returned result is invalid (3xx/4xx/5xx error codes)

**Comment by lmccart** [comment]
ah ok, we definitely do want these to be reported as well. I can look into it.

**Comment by lmccart** [comment]
I tried hitting each of these and as far as I can tell each one threw an error in console. Can someone point out one that doesn't work? Am I testing this right?

```javascript
function preload() {
    loadJSON('https://httpstat.us/300');
}
```

**Comment by limzykenneth** [comment]
I am also getting the error which is probably the default error the browser throws when it receives an errored response (4xx, 5xx) which I think is good enough to indicate what's wrong. As for 3xx series, because it is not technically an error, the browser shows no error message but (same with the others) there is an Unhandled Promise Rejection error which isn't helpful.

I can go back and make sure the promises returned by fetch are all caught in case they encountered errors like these but other than that I think we are mostly covered by default behaviour of browsers?

**Comment by lmccart** [comment]
I just tried that out and actually found the resulting errors logged to be less clear or informational than the current error thrown. Given all this, I think I'd like to just leave this as is for now as it seems to throw at least some kind of error for every failed preload call.

**Comment by shiffman** [comment]
Noting that these errors don't necessarily show up in the console of the web editor (we're doing loading data from APIs this week), I'm compiling some other similar misses and can file there. Let me know if I'm missing anything?
