### ISSUE TITLE
[Request] Only source files on NPM

### ISSUE THREAD

**Issue by designbyadrian** [processing/p5.js#2244]
There should be an NPM package that only holds the P5 source files, not a whole grunt project. Some might want another project build tool or test suite. This package should be an example setup.

**Comment by sakshamsaxena** [comment]
Hi !
Currently, we only publish certain files to NPM and Bower, which are essentially the distribution version of the library. The source is only available here at GitHub Repository. Publishing the entire repo as NPM package was not at all ideal as the aim was primarily browser usage, so only the complete library files were considered. 
What is it that you seek exactly ?

**Comment by aendrew** [comment]
I'd like for this to be reopened, there are a lot of very valid use cases for also including the unbuild sources with the npm package. For instance:

a. You're using Rollup/Webpack2 and want to use its dead code removal features to reduce the size of your bundle (Though AFAICT this isn't really possible due to relying on CommonJS modules)
b. You're in a situation where you want to bundle your own polyfills, or want to use a service like polyfill.io to provide polyfills.

Currently I'm wanting to bundle P5.js with my Gatsby.js site and am unable to do so because the build process is dying on Paul Irish's requestAnimationFrame shim. 

Some of this is related to #2215; replacing the CommonJS modules with ES6 modules and updating the build process to use something like Rollup would not only modernise the codebase considerably but also enable the final bundle to be more optimised via tree-shaking. Am happy to help with such an effort if it would help push things forward. 👍
