### ISSUE TITLE
smooth() not working in WebGL

### ISSUE THREAD

**Issue by Revanee** [processing/p5.js#2250]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core
- [ ] Data
- [ ] Events
- [ ] Image
- [x] WebGL
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: v0.5.14
- Web browser and version: Chrome 61.0.3163.100
- Operating System: Windows 10 Home 64x
- Steps to reproduce this:

With the following code:

function setup () {
    createCanvas(800, 600, WEBGL)
}

function draw () {
    smooth()
}

I get: Uncaught TypeError: this._renderer.smooth is not a function

It seems that smooth() is not implemented with WebGL. Is this deliberate or is it a bug?

**Comment by bomoko** [comment]
@Revanee - I've seen a few functions that haven't yet been implemented in the WEBGL renderer yet, you've stumbled on one of them here. This is actually being discussed right now over at #2226.

**Comment by Siphonophora** [comment]
@Revanee smooth() is the default in 2d mode (so generally it doesn't need to be turned on) and as you found, it is not active in wegbl. Were you using it because of some geometry in webgl which did not look smooth enough? You can generally increase the detailX, detailY parameters to get smoother geometry, but it would depend what you are doing.

**Comment by mlarghydracept** [comment]
Okay noticing that this should have some documentation on the website but in addition to increasing the detailX and detailY you can also tell the WebGL renderer to turn on antialiasing. This will only work on certain devices but it can be accomplished with a single line in `setup()`. Note that this **should not** be put in any rapidly reoccurring code (the draw function for example) because it resets and reloads your GL context.

Here is some example code:

```
function setup() {
  createCanvas(150,150,WEBGL);
  setAttributes('antialias', true);
}

function draw() {
  background(255);
  fill(0,0,0);
  box(50);
 }
```
