### ISSUE TITLE
Bug with rect in WEBGL mode.

### ISSUE THREAD

**Issue by a-y-u-s-h** [processing/p5.js#2252]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [x] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 
Not sure if this is a legit bug. I was just checking out behavior of rect in WEBGL and I ran this code first to oscillate rectangles : 

![1](https://user-images.githubusercontent.com/19586719/31378898-4f481c54-adca-11e7-9a71-409e83e66159.png)

..but the output was too slow

But when I used translate : 

![4](https://user-images.githubusercontent.com/19586719/31378727-d7a5c318-adc9-11e7-95c7-cac72a549841.png)

It was all good.

- p5.js version: 0.5.14
- Web browser and version:Chrome 61.0.3163.91 (Official Build) (64-bit)
- Operating System: Linux - Ubuntu 17.04
- Steps to reproduce this: As done in the images above.

**Comment by Siphonophora** [comment]
Hi, 

Whats happening here is that the first option is generating every rectangle from scratch (because they each have a unique set of arguments), while the second sketch is reusing a single rectangle. Probably not exactly a bug, but also not ideal. 

It is something I think I hadn't mentioned in #2226 yet, but this is probably part of that discussion. It doesn't make sense for the X and Y coordinates to be in the geometry ID, except that we need them to properly place the geometry. Thoughts on whether we can include only H and W in the geometry ID and then take care of the translation for the user? Similar issues would apply for someone drawing a bunch of triangles or quads.

**Comment by kjhollen** [comment]
@Siphonophora this is spot on. it might be worth doing a test to see if immediate mode (using beginShape + vertex + endShape) is now fast enough that we can use that for some of the 2D primitives. previously there had been a bug that made it very, very slow, but we resolved it over the summer. It might make some basic uses like this one faster!

**Comment by Spongman** [comment]
I fixed a similar issue for some of the 3D primitives, here: #2473. I didn't bother with the 2d primitives like rect & triangle, but it should be simple to do.

There's still the question of what is supposed to happen to wireframe stroke widths when the model is scaled. Should they be scaled also?

**Comment by Spongman** [comment]
this was fixed in #2473
