### ISSUE TITLE
Problem importing model 

### ISSUE THREAD

**Issue by drcrotato** [processing/p5.js#2263]
#### Nature of issue?

- [ x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ x] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x ] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: It gives this error when after loading a model,

Uncaught (in promise) RangeError: Maximum call stack size exceeded p5.js:69856

- p5.js version: v0.5.16 October 11, 2017
- Web browser and version: Chrome 
- Operating System: Windows
- Steps to reproduce this: Import a model (from what I can tell)

**Comment by lmccart** [comment]
can you post the loadModel() code snippet you used and the model you're trying to load?

**Comment by mlarghydracept** [comment]
Hi! You should definitely still post a loadModel() snippet with the model that you are trying to use but I just wanted to point out that I may know what is happening. It is most likely that you have a complex model and the call stack is being exceeded on the [_flatten](https://github.com/processing/p5.js/blob/master/src/webgl/p5.RendererGL.js#L910) function. I tested a lot and thought the function would not cause errors but I never tested models with extremely large number of vertices. I changed the _flatten function from the [old implementation](https://github.com/mlarghydracept/p5.js/blob/master/src/webgl/p5.RendererGL.Retained.js#L135) in order to gain quite a bit of speed at load (often 2-3 seconds) but it is possible that this isn't optimal if people want to load complex models. 

If anybody has a better idea on how to flatten very large 2 or 3 dimensional arrays very quickly before sending to the shader, the help would be super welcome. Otherwise, I think the current version of _flatten should be good for 99% of cases and maybe it is just a matter of having it fail with a more helpful message. I can work on this soon but am swamped for the next couple of weeks.

**Comment by meiamsome** [comment]
Some sort of middle ground solution would be along the lines of:

```javascript
var result = [];
for(var i = 0; i < arr.length; i += 10000) {
  result = [].concat.apply(result, arr.slice(i, i + 10000));
}
return result;
```

Where 10000 is an arbitrary chunk size that (hopefully) most browsers support being used in `apply`

Performance can be analysed here: https://jsbench.me/qgj8sx1nl8/1 
You can mess with input size and chunk size on that and run them. Input size of 1000000 results in an error on Chrome & Firefox for me  for the first one and slow on the second. 

To be honest, looking at the amount of vertices you'd need for it to be a problem I'd be tempted to just say that this is best left as it is and the solution is to simplify any models exceeding this.

**Comment by mlarghydracept** [comment]
@meiamsome I agree that it feels like it might make sense to just make an adjustment to the docs or friendly-error system that lets people understand that they should simplify their model before loading it.

**Comment by lmccart** [comment]
I can add a line to the reference warning about large models, @mlarghydracept can you suggest a maximum size or some language I can use here to communicate the limit?

**Comment by SouzaGuilherme** [comment]
Hello, I see that there is still a limit on vertices. When using a parser (https://webgl2fundamentals.org/) browsers support such a quantity. Wouldn't p5.js achieve the same? (I don't know the lib in-depth, I'm trying to use it)
