### ISSUE TITLE
image() reference documentation syntax issue

### ISSUE THREAD

**Issue by braithw8** [processing/p5.js#2323]
https://p5js.org/reference/#/p5/image

In the reference for the image() function the syntax is stated as:

image(img,dx,dy,dWidth,dHeight,sx,sy,[sWidth],[sHeight])

Should this not read:

image(img,sx,sy,sWidth,sHeight,dx,dy,dWidth,dHeight)

I am new to all of this, so I could be out to lunch. p5.js is great, I'm loving it so far and I am new to coding.

FinlayB

**Comment by limzykenneth** [comment]
Hi @braithw8, for the syntax `image(img,dx,dy,dWidth,dHeight,sx,sy,[sWidth],[sHeight])` it means `sWidth` and `sHeight` are optional, so you can do `image(img,dx,dy,dWidth,dHeight,sx,sy)` and `sWidth` and `sHeight` will be automatically default to the maximum dimensions of the source image.

Is it confusing to document it this way? Can we change something in a way that would be easier to understand? It would be nice to hear your thoughts especially because you are new to all of this, we are pretty much too deep in the matrix to know for sure. 😜

**Comment by Jared-Sprague** [comment]
@braithw8 Ahh yes a subject near to my heart :smile:   The confusion might be because image() originally a had the order  `image(img,sx,sy,sWidth,sHeight,dx,dy,dWidth,dHeight)`,   see the [original pull request](https://github.com/processing/p5.js/issues/942) that added the extra augments.  I implmented it this way at first to match the specification for [drawImage()](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/drawImage).

But as someone rightly pointed out in [this issue](https://github.com/processing/p5.js/issues/1653),  this was confusing,  so the order was [changed](https://github.com/processing/p5.js/commit/6ac5bc00e101c739e1c423939294a8db51cf3210) to:  `image(img,dx,dy,dWidth,dHeight,sx,sy,[sWidth],[sHeight])`

I think the new order is easier to understand because the position of dx, and dy doesn't change, when using all the arguments.

If you're curious about how all the arguments for image() work together, check out my [image zooming demo](http://jaredsprague.com/2017/10/26/p5-js-image-zoom-example/), I created specifically to show this.

**Comment by lmccart** [comment]
👍
