### ISSUE TITLE
Create webgl graphics error

### ISSUE THREAD

**Issue by tbremner** [processing/p5.js#2342]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [x] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 0.5.15 & 0.5.16 
- Web browser and version:  Chrome 62
- Operating System: MacOSX
- Steps to reproduce this:

```
function setup() { 
  createCanvas(400, 400);
  var pg = createGraphics(100, 100, WEBGL);
} 
```
<img width="598" alt="screen shot 2017-11-06 at 1 33 06 pm" src="https://user-images.githubusercontent.com/29671817/32422879-12009e06-c2f7-11e7-917a-13bf47b3e9d3.png">

**Comment by mlarghydracept** [comment]
Okay looking into this it is because for some reason when a `p5.Graphics` object is created with a WebGL renderer it doesn't have the same structure as one created with the 2D renderer. For some reason, variables that should be accessible at `this._pInst` are instead available at `this._pInst._pInst` which is definitely wrong. Not sure why yet!

**Comment by mlarghydracept** [comment]
Hi thanks for the issue! It is a similar issue to #2478 and though this one was posted first that issue has useful comments so I am going to close this one for organization. Feel free to follow that issue for updates.
