### ISSUE TITLE
Uncaught TypeError: Cannot read property 'width' of undefined p5.min.js:33

### ISSUE THREAD

**Issue by SagaRantanen** [processing/p5.js#2387]
I'm a p5.js beginner and trying to code a scene of randomly varying images raining.

I've been following a couple of tutorials and I think my code should work but it only gives me the error message of "Uncaught TypeError: Cannot read property 'width' of undefined p5.min.js:33".

## **My main sketch.js:**

var objects = [];
var sense = [];

function preload(){
  sense[0] = loadImage('senses/eye.png');
  sense[1] = loadImage('senses/mouth.png');
  sense[2] = loadImage('senses/finger.png');
  sense[3] = loadImage('senses/nose.png');
  sense[4] = loadImage('senses/ear.png');
}

function setup(){
  createCanvas(800, 600);
  var r = floor(random(0, sense.lenght));

  for(var i = 0; i < 25; i++){
    objects[i] = new Thing(sense[r]);
  }
}

function draw(){
  background(255);

  for(var i = 0; i < objects.length; i++){
    objects[i].drive();
    objects[i].display();
  }
}

## **my thing.js**

function Thing(ypos, xpos, speed, img){

  this.xpos = random(width);
  this.ypos = random(height);
  this.speed = random(2,4);
  this.img = img;

  this.drive = function(){

    if(this.ypos > height){
      this.ypos = -200; 
      this.xpos = random(width);
    }
    this.ypos = this.ypos + this.speed;
  }

  this.display = function(){
    image(this.img,this.xpos, this.ypos, 50, 50);
  }
}

**Comment by Siphonophora** [comment]
Hi, 

The function Thing's arguments don't match what you are using in sketch.js when you call New Thing(). Right now, this.img is null, because the 4th argument is empty. If you open the console (F12) and type objects, it should return the array of Things you created and you can confirm the thing.img is empty. I assume the width error you are getting where width is null is from trying to display using the image function, with a missing image.

It looks like think.js should start as shown below, because you are only passing in the image to the Thing function and you are calculating the xpos, ypos and speed. 

```Javascript
function Thing(img){
```

**Comment by SagaRantanen** [comment]
Thank you for your reply, it works now! Also turned out I had misspelled the word 'length' :D
