### ISSUE TITLE
WebGL Origin

### ISSUE THREAD

**Issue by mlarghydracept** [processing/p5.js#2437]
I saw a discussion about this beginning over in [this issue](https://github.com/processing/p5.js/issues/2351) but to avoid taking over that thread I just wanted to bring up the question of the WebGL origin in its own issue. 

So the origin in WebGL is current at the center of the canvas or the equivalent of `width/2, height/2` in 2D mode. I am not sure why it was set up this way. This was already the standard in place when I first started working on the project. Does anybody recall the reasoning for this? I am asking mostly because this differs from Processing which uses a top-left origin for all of its modes. It also makes prototyping between 2D and 3D more difficult. Currently if you want to start from the top-left you will need to use `translate(-width/2, -height/2, 0)`. Not sure if this is confusing!

Anyways, just wanted to get a temperature read on the topic.

**Comment by Spongman** [comment]
my guess is that it's because most documentation on projection matrices tends to place the origin in the center of the viewport. it can be a little ambiguous what having the origin in the corner actually means. is it that the corner pixel is the whole Z axis (it, the camera is centered on the corner and the viewport is just showing the bottom-left corner of what the camera can 'see'), or is the camera centered on the center of the viewport and the coordinate space is just shifted so the origin just happens to appear at the top-left of the viewport?

i agree, though, that being different from 2d and from Processing is a little confusing. big breaking change, though.

**Comment by lmccart** [comment]
This decision to break with Processing and 2D mode was 1. to align with the normal default webgl origin (I think), and 2. because the top left becomes sort of arbitrary when working in 3D space. As soon as there's any rotation in the canvas or change in camera perspective, the origin is floating at a  somewhat random point, rather than having it centered in the viewport.

**Comment by mlarghydracept** [comment]
Got it! Makes sense. I'll close this issue. Hopefully it'll be useful for others in the future trying to figure out why this decision was made. 📻

**Comment by ffd8** [comment]
Juuust ran into this issue and thought I was going nuts until reading the docs closer. I get the logic for moving it – but still wish it hadn't broken from Processing for ease of code between the two (I say that while modifying 70% of the code to become JS friendly).
