### ISSUE TITLE
Issue with p5 DOM + classes

### ISSUE THREAD

**Issue by Siggi005** [processing/p5.js#2486]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [x] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 
Written a class and getting an issue in the ToggleContent() method that this.content and this.btn are undefined.

- p5.js version:  0.5.11
- Web browser and version:  Firefox 57.0.3
- Operating System:  Windows 10
- Steps to reproduce this:

```
class DropDown {
  constructor(head, parent, expanded) {
    this.dd = createDiv('');
    this.dd.class('DropDown');
    this.dd.parent(parent);
    this.headline = createDiv(head);
    this.headline.class('Headline');
    this.headline.parent(this.dd);
    this.btn = createButton();
    this.btn.class('Button');
    this.btn.parent(this.headline);
    this.btn.mouseClicked(this.ToggleContent);
    this.content = createDiv('');
    this.content.parent(this.dd);
    this.expanded = !expanded;
    this.ToggleContent();
  }
  
  ToggleContent() {
    this.expanded = !this.expanded;
    if(this.expanded) {
      this.content.style('display', 'block');
      this.btn.html('<img src="open-iconic/svg/chevron-bottom.svg">');
    }
    else {
      this.content.style('display', 'none');
      this.btn.html('<img src="open-iconic/svg/chevron-left.svg">');
    }
  }
  
  AddElement(elt) {
    elt.parent(this.content);
  }
}
```
TypeError: this.content is undefined (interface: line 60)
TypeError: this.btn is undefined (interface: line 60)

**Comment by Spongman** [comment]
the issue here is that, when you click the mouse, your `ToggleContent` function is being called with a value of `this` that you're not expecting. `this` is set to the button itself, not your `DropDown` object.

in order to fix this, you'll need to fix up your `this`.

you can either use a lambda:

````
this.btn.mouseClicked(() => this.ToggleContent());
````

or function.bind:
````
this.btn.mouseClicked(this.ToggleContent.bind(this));
````

or a closure:

````
var _this = this;
this.btn.mouseClicked(function () { _this.ToggleContent(); });
````

**Comment by Siggi005** [comment]
Thank you very much, I think I still have much to learn

**Comment by Spongman** [comment]
yeah, this is one of those weird javascript-isms that trips a lot of people up: the fact that `this` can refer to different things at different times in the same code. it's especially egregious in ES6 because it borrows the 'class' architecture from other languages (like Java) but _still_ doesn't guarantee that `this` always refers to the method's object instance.

@shiffman touches on this issue in this video: https://www.youtube.com/watch?v=KeZBpeH59Q4?t=8m0s
