### ISSUE TITLE
Update build process to use ES6 modules + Rollup

### ISSUE THREAD

**Issue by aendrew** [processing/p5.js#2503]
#### Nature of issue?

- [x] New feature request

#### Most appropriate sub-area of p5.js?

- [x] Other (specify if possible)

#### New feature details:

See my comment [here](https://github.com/processing/p5.js/issues/2244#issuecomment-355742620) on #2244. Effectively, updating the build process to use ES6 modules would modernise the codebase, enabling smaller bundles and more flexibility in terms of how people use P5 in their own build process.

**Comment by Zalastax** [comment]
This is a solution to the problem in #522, right?

Rollup is nice in that it has [support for multiple export types](https://rollupjs.org/#core-functionality).
It creates small bundles and doesn't require any polyfills. Do we know how far away we are from a code base that could use ES6 modules?

For direct inclusion in the browser we would create a bundle using UMD. This bundle would just be included in the zip-file directly, and not referenced from package.json. I don't think there's any point in using a [browser field](https://github.com/defunctzombie/package-browser-field-spec).

For usage as a npm library we  would get create two bundles: CommonJS and ES6-modules.
Doing this is very easy, we just need [two different fields in package.json](https://github.com/rollup/rollup/wiki/pkg.module). This would be very similar to the [rollup-starter-lib](https://github.com/rollup/rollup-starter-lib) example.

**Comment by aendrew** [comment]
@Zalastax That would indeed, though providing the sources in the npm package as per #2244 would also solve that — it's the difference between `import something from 'p5/lib/something'` versus `const something = require('p5/lib/something')` — you don't need to convert to ES6 modules to benefit from that, any build process supporting CJS would be able to already do that if you supply the sources in the npm package, but using ES6 modules would optimise the bundle more due to the static analysis requirement (thus enabling dead code removal/"tree shaking"). 

Also, as you've mentioned, yes, setting the `module`/`js:next` field in `package.json` enables tools like Rollup to get at the modular sources while still providing a UMD bundle for browser consumption via the `main` field (considering much of the docs for P5 use globals provided via UMD this is probably preferable to building a separate CJS bundle and setting that as `main` as per rollup-starter-lib, IMO — UMD can be consumed as CJS and it's likely most people wanting to use modular bits of the lib will be using tooling that can consume ES6 modules). Also, AFAICT, using ES6 modules when referenced via the `module` field is preferred over CJS.

**Comment by meiamsome** [comment]
Are there any issues with the nature of the way p5 is built? What I mean is that all the sub-packages just add functionality onto the p5 object. I could see this being a bit weird to use as an import - would we want `import { httpDo } from 'p5'` or `import { httpDo } from 'p5/io'` or perhaps `import httpDo from 'p5/io/httpDo'`

**Comment by meiamsome** [comment]
That looks like an excellent example of how to do it, @Zalastax! Do we think we can do the conversion in parts or will we have to rewrite the entire codebase at once?

**Comment by limzykenneth** [comment]
@meiamsome I believe you can include babelify as a transform in browserify so you can use es6 import in part of your codebase (babelify will transform them to commonjs require before passing to browserify), you won't get the benefit of tree shaking I think but you can start converting the codebase gradually that way.

**Comment by Zalastax** [comment]
Should we just add support for [ES2015 modules](http://babeljs.io/docs/plugins/transform-es2015-modules-commonjs/) or a [full ES2015 transform](http://babeljs.io/docs/plugins/preset-env/)? Is there a roadmap for the codebase?

**Comment by limzykenneth** [comment]
I don't think there's a roadmap yet. To be honest I'm a bit wary about a full convert as it means we will need to babel the whole codebase for compatibility, I much prefer to introduce new features as they become more supported worldwide (ie. less people using IE 😨 ). For example `let` is actually fully supported on IE11 so we should be able to introduce it with no problem and no conversion needed while retaining their benefits.

What do you think?

**Comment by Zalastax** [comment]
The [env preset](http://babeljs.io/docs/plugins/preset-env) already makes sure that there are no conversions for features that are supported in all our target browsers. Since Babel only transforms syntax (like arrow functions), using newer features shouldn't inhibit a big cost. I think we should avoid babel-polyfill though, since it is quite large. http://babeljs.io/ has a brief list showing what you get from the transpilation and what you get from the polyfill.

**Comment by stephanmax** [comment]
I would love to see this coming to p5, please let me know if I can help.

**Comment by Spongman** [comment]
does anyone have a solution to the fact that what p5.js does - define a single class across many files - doesn't seem to be well supported by es2015 modules or ES6 language features?

**Comment by Zalastax** [comment]
I don't think there are any problems with augmenting the p5 "class" from multiple files - modules can handle it fine.
If we want to use classes, [this](https://stackoverflow.com/questions/32699889/es6-declare-a-prototype-method-on-a-class-with-an-import-statement) is one method of doing so. I basically did exactly this in [another project](https://github.com/Zalastax/openschedule/blob/master/src/rx-custom/add/filterUndefined.ts) and as you see it's even compatible with TypeScript!

I suggest we start by just replacing browserify with rollup (no babel). YUIDoc already supports ES6 and modules so the change shouldn't break anything.

**Comment by Spongman** [comment]
yeah, that's kind of what i was worried about: every method definition requires at least two additional lines of boiler-plate just to shoehorn it into the prototype. i guess i'd like to see a complete example of a class defined in, say, 3 files with functions in each referencing properties & methods in the other files. i don't know that this is even possible in typescript without defining everything as interfaces due to issues with reference cycles.

**Comment by Zalastax** [comment]
TypeScript is only a consideration for the far future. I mentioned it just to illustrate that it's a well recognized pattern. ES6 modules shouldn't add any boilerplate at all.
If we eventually want to consider TypeScript, partial classes by naming an interface the same thing as the class + using the prototype is well supported. It might be the case that another structure will suit us better then but let's have that conversation when the time comes.

**Comment by Spongman** [comment]
sorry, yes i dind't mean to complicate things with typescript, i just know that typescript doesn't support partial classes (which is basically how p5.js is structured) and the reason usually given for this is that es2015 modules don't really support this kind of structure. but if you have some way of doing this nicely that's great!

**Comment by Zalastax** [comment]
I went and tried this out, both [with](https://github.com/Zalastax/p5.js/tree/rollup) and [without](https://github.com/Zalastax/p5.js/tree/rollup-no-babel) babel. 
Since we augment p5 not only as a class, but also as a module, some trickery is needed. E.g. if a file is [converted from commonjs to modules](https://github.com/Zalastax/p5.js/blob/07a9875a3c4f111cd583fb91a45f8a482a872400/src/webgl/p5.RendererGL.js) we need to create a [separate file](https://github.com/Zalastax/p5.js/blob/07a9875a3c4f111cd583fb91a45f8a482a872400/src/webgl/p5.RendererGL.augment.js) that actually modifies the p5 module.
The end goal should however be that the p5 class is modified but that the p5 module is exported via export statements as it's done in [rxjs](https://github.com/ReactiveX/rxjs/blob/master/src/index.ts). I tried that out but didn't want to change more than needed so I went with the extra file instead. I think some of the added require's *could* be removed again but we should go towards each file importing the augmentations they need anyway.

What's left now is mainly a decision on babel or not. For me the choice is clear, babel can make for simpler code and doesn't incur a runtime/size cost. As long as we're using UglifyJS (at least the current version) we can't start using any ES6 features since it doesn't understand them; e.g. it will crash on `const foo = 1;`.  It would be great if we can set up eslint to warn if we use for example Array.includes (Not in IE11), but at least it will warn if we try to use Promise.

**Comment by Zalastax** [comment]
@lmccart could you chime in on how you want to proceed?
We have rollup working and it does not require changing the whole project at once. What it gives us is access to ES6 modules. It is possible to use with or without babel.

I'd like us to

1. Replace browserify with rollup
2. Enable ESLint rule [no-commonjs](https://github.com/benmosher/eslint-plugin-import/blob/HEAD/docs/rules/no-commonjs.md) but add an ignore comment to every file that needs it. This makes it easy to track progress and prevents us from going in the wrong direction.
3. Convert files one by one, using [p5.js augmenter files](https://github.com/Zalastax/p5.js/blob/07a9875a3c4f111cd583fb91a45f8a482a872400/src/webgl/p5.RendererGL.augment.js) when needed.
4. Replace augmenter files with ES6 module equivalent. Since `core/main.js` will be in ES6 module style by then, this will be a simple task.
5. Remove `rollup-plugin-commonjs`

**Comment by lmccart** [comment]
Hi all, thanks for the work and discussion on this. Yes, we are moving to ES6. The target timeline is still being finalized on this. I would like to pause on rollup+ES6 and other ES6 updating until we've officially kicked things off. You can expect an update in the next month or two with more of a timeline on this. I'm also working on adding milestones and timeline for the repo, so we have a better sense of priorities moving forward. I will post milestones intended as a draft and open an issue for discussion, before we finalize.

**Comment by outofambit** [comment]
closing this since we have a discussion going in #3425 as well.
