### ISSUE TITLE
inline examples for math

### ISSUE THREAD

**Issue by shiffman** [processing/p5.js#252]
Going to work on some inline examples for math stuff

- [x] noise
- [x] random
- [x] randomGaussian
- [ ] p5.Vector

**Comment by workergnome** [comment]
There is currently an example for [this](http://p5js.org/reference/#/p5.Vector).  Can we close this issue?

**Comment by lmccart** [comment]
I'm guessing @shiffman's intention was to add examples for all p5.Vector() methods (see further down the page). However, this issue was made at a time when we had a lot of people working on examples, to avoid overlapping efforts. Since @shiffman is not actively working on this, I don't think it's necessary to have an issue just for this section, it is already mentioned in the documentation that examples are desired for all functions.

**Comment by shiffman** [comment]
And it looks like examples have been added with #692.  Amazing!
