### ISSUE TITLE
Stroke doesnt show in a canvas created with WEBGL.

### ISSUE THREAD

**Issue by pishleback** [processing/p5.js#2553]
#### Nature of issue?

Found a bug

#### Most appropriate sub-area of p5.js?

WebGL

#### Which platform were you using when you encountered this?

Desktop/Laptop

#### Details about the bug: 

- p5.js version: 0.5.11
- Web browser and version: FireFox 57.0.4
- Operating System: Windows 10 Pro version: 1709 OS Build: 16299.192
- Steps to reproduce this:

In the online editor (https://alpha.editor.p5js.org/), I create a new project and paste the following code in the sketch.js file:

function setup() {
  createCanvas(200, 200,WEBGL);
}

function draw() {
  background(0);
  stroke(240, 150, 150);
  fill(100, 100, 240);
  rotateX(frameCount * 0.01);
  rotateY(frameCount * 0.01);
  box(75, 75, 75);
}

directly from the referance page for stroke (https://p5js.org/reference/#/p5.RendererGL/stroke). When I press run I see a box rotating but the edges are not drawn, only the blue silhouette.

**Comment by kjhollen** [comment]
thank you for this report! this is fixed in version 0.5.16. The online editor still defaults to 0.5.11... but if you want to, you can change the version number in the editor by updating the index.html file for your sketch. Look for the script tags linking the various p5.js libraries and change where you see 0.5.11 to 0.5.16—should work ok then!
