### ISSUE TITLE
Latest version for CDN

### ISSUE THREAD

**Issue by masiama** [processing/p5.js#2584]
#### Nature of issue?

- [ ] Found a bug
- [ ] Existing feature enhancement
- [x] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [x] Core
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [x] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [x] Others (specify if possible)

#### New feature details:

Idea is to have latest version in CDN just like jQuery have for [latest stable version](http://code.jquery.com/jquery-latest.js)

**Comment by bmoren** [comment]
I'd also be interested and was also recently looking into this as well for my [p5js/atom.io toolbar](https://atom.io/packages/p5js-toolbar). However since p5js [uses cdnjs, I think it's unlikely](https://github.com/cdnjs/cdnjs/issues/987) unless p5js hosted it's own CDN which also seems unlineky due to overhead.

**Comment by Spongman** [comment]
it's not really a CDN, but the p5.js website uses the latest version, here: https://p5js.org/assets/js/p5.min.js

**Comment by lmccart** [comment]
this has been discussed here:
https://github.com/processing/p5.js/issues/2521

there are no plans to add this in the near future
