### ISSUE TITLE
Working with p5.js to create a type writer, help needed on coding

### ISSUE THREAD

**Issue by xtongch** [processing/p5.js#2585]
I am currently working on a school project that I would like to design a typewriter that goes wrong, which means that the text output is different from the text input by the user. Here is my code and I am not quite sure how to make the text goes to the next line and to rotate the text horizontally(maybe flip the canvas horizontally).

I am quite new to programming and p5.js, really appreciated if anyone can help.

var contents = "";
var r,g,b;
var x,y;
var bell
var ding

function setup() {
  createCanvas(400,600);
  r = random(255);
  g = random(255);
  b = random(255);
  x = 50;
  y = 50;

  soundFormats('wav');
  bell = loadSound('typing.wav');
  ding = loadSound('return.wav')

}

function draw() {
  background(200);
  fill(r,g,b);
  textSize(50);
  text(contents, x, y, 400, 600);

//   x = x + random(-1, 1);
//   y = y - 1;
  
//   Reset to the bottom
//   if (y < 0) {
//   y = height;
// }
}

function myBox(k) {
 var txt = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ';
 var i = txt.indexOf(k);
 var next;

  if (i+1 < txt.length) {
   next = txt[i+1];
 }
  else {
  next = txt[0];
 }
  return next;
}

function keyTyped() {
  contents += myBox(key);
  r = random(255);
  g = random(255);
  b = random(255);
  bell.play();
}

function keyPressed() {
  if (keyCode === ENTER) {
    ding.play();
  }
}

**Comment by limzykenneth** [comment]
Personally how I would do something like this is to use DOM elements (checkout the p5.dom.js addon library), because with the DOM the text that was typed will be automatically warped to the next line if necessary so you don't need to worry about handling new lines. 

Also with DOM element (including canvas) you can flip it using CSS transfrom, have a look at this [page](https://css-tricks.com/almanac/properties/t/transform/) if you are not familiar with CSS transform, by doing `transform: translateX(-100%)` you effectively flip the element horizontally.

In future this kind of questions mainly about your own code is bese posted on the [forum](https://css-tricks.com/almanac/properties/t/transform/). Github issues are usually used for bug reports or feature requests. Thanks!
