### ISSUE TITLE
precommit prettify doesn't stage prettified results

### ISSUE THREAD

**Issue by Spongman** [processing/p5.js#2602]
i think i have found the issue that is causing some people to commit un-prettified source code, leading to travis failures and general confusion.

here's the workflow:
- `git add` (stage changes)
- `git commit` (results in precommit failures)
- `npm run lint:fix` (fixes precommit failures, but DOES NOT stage them!)
- `git commit` (precommit succeeds because it runs against un-staged, prettified files, but only the previously _staged_, erroneous changes are committed).

the problem is that the precommit is verifying un-staged changes. i doubt this is simple to fix :(

**Comment by tau-** [comment]
I observed the same behavior. The only work around is to run `npm run lint:fix` before staging changes.

**Comment by lmccart** [comment]
I'm going to close this because it's not exactly a bug, it's a workflow issue to be aware of, and I can't think of any simple fix that doesn't result in counterintuitive behavior elsewhere. For example, if `npm run lint:fix` automatically staged changes, this would be unexpected. If others have a good solution and want to address this we can reopen.
