### ISSUE TITLE
Mirror effect

### ISSUE THREAD

**Issue by mcanepa** [processing/p5.js#2611]
#### Nature of issue?

- [x] New feature request

#### Most appropriate sub-area of p5.js?

- [x] WebGL

I think it woul be neat to have a way to place a 3D object with mirror properties that reflects what is happening in the scene.

My main idea is placing a looking glass (plane) in a virtual room, but I think this could apply to all sort of things, like a shiny steel ball (sphere), etc.

Looking for this I stumble across this [demo](https://threejs.org/examples/webgl_mirror.html)

**Comment by Spongman** [comment]
Currently p5.js doesn't have any concept of a scene graph, which is something that would be required for long multiple rendering passes on multiple objects  p5.js is an immediate-mode renderer: you say 'sphere' you get a sphere drawn and it's done. In order to render mirrors you need to draw the sphere (at least) twice, once in the camera and once reflected in the mirror, and to do this for a whole scene you need to retain the geometries in a graph. This could be built upon p5 with some additional support (stencil buffers, maybe?), or you could use something like Three which I believe has scene graph support built in.

**Comment by lmccart** [comment]
I think this function is beyond the scope of the p5.js api (we try to keep as minimal as possible) but it could be a great starting point for an addon library. see the docs here for how to create an addon: https://github.com/processing/p5.js/wiki/Libraries#creating-a-new-library

**Comment by kjhollen** [comment]
I think this is probably beyond the scope of the base library, too—I hope the WebGL mode becomes a good stepping stone to three.js, but I'd expect our approach to stay minimal and focused on new programmers. I think this would be a great library add-on, though!
