### ISSUE TITLE
String|Constant Parameter Bug in Instance Mode?

### ISSUE THREAD

**Issue by J-Fo-S** [processing/p5.js#2613]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [x ] Core
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x ] Desktop/Laptop
- [ ] Others (specify if possible)

Hello, if I run the following code in instance mode I receive an ****Uncaught ReferenceError: CENTER is not defined

The same is true for when one tries passing other String|Constants (e.g. rotate(TWO_PI))

```javascript
var globals = {};   
globals.someGlobalVariable = 0;
// do for all other global variables

new p5(function (p) {
  "use strict";
 
  var someSketchVariable = 255;
 
  p.setup = function () {
    p.createCanvas(600, 400);
  };
 
  p.draw = function () {
    p.background(globals.someGlobalVariable);
    p.fill(someSketchVariable);
    p.rectMode(CENTER);
    p.rect(100,100,400,200);
  };
 
}, "sketch01");
```

**Comment by limzykenneth** [comment]
@J-Fo-S Perhaps I've misunderstood but I cannot replicate the problem with the code you provided. Substituting `globals.someGlobalVariable` in the line `p.background(globals.someGlobalVariable);` with `CENTER` does give the error but that's expected because you are in instance mode which does not attach the variables to the global namespace so in this case you should be passing in `p.CENTER` instead.

**Comment by J-Fo-S** [comment]
Actually, my apologies - I seem to have accidentally omitted the code causing the problem. It was p.rectMode(CENTER). I will edit for clarity.

**Comment by limzykenneth** [comment]
Great, glad to help. I'll close this issue then.
