### ISSUE TITLE
Enable passing headers when loading an Image

### ISSUE THREAD

**Issue by j6k4m8** [processing/p5.js#2634]
#### Nature of issue?
- [x] Existing feature enhancement

#### Most appropriate sub-area of p5.js?
- [x] Image

#### Feature enhancement details:
**Support passing headers along with an image request when calling `p5#loadImage`.** Supporting headers would be useful for:

* Authorized/authenticated image requests (e.g [JWT](https://jwt.io/introduction/))
* Passing Accept types (`Accept: image/png` etc is common in APIs that serve multiple formats from the same endpoint)
* Sending auxiliary information about a request to the server

`p5#loadImage` currently doesn't support passing headers when retrieving an image from a remote location. This is because the `<img />` `src`-setting technique does not support passing headers along with the request for the image.

My solution is to fetch the image via HTTP request, and then reconstruct a `ObjectURL` from the response blob. Code is below!

In my (admittedly fast and simple) testing, there was no dramatic performance-loss by switching to this method, even for very large (e.g. 100s of MB) images. (I imagine there _would_ be a performance hit if you requested the same exact image a bunch of times, and could benefit from the browser's internal cacheing of `<img />` `src`s. But that seems.... Uncommon.)

Looking forward to hearing your thoughts; I think this makes p5 better, but if there are design decisions / reasons for why this doesn't exist, I'd love to hear them!

#### Implementation

At [image/loading_displaying.js:66](https://github.com/processing/p5.js/blob/master/src/image/loading_displaying.js#L66):

```javascript
p5.prototype.loadImage = function (path, successCallback, failureCallback, headers) {
    p5._validateParameters('loadImage', arguments);
    var img = new Image();
    var pImg = new p5.Image(1, 1, this);

    var self = this;

    let URL = window.URL || window.webkitURL;
    headers = headers || {};

    fetch(path, {
        headers,
    }).then(res => {
        if (res.ok) {
            res.blob().then(b => {
                // Start loading the image:
                img.src = URL.createObjectURL(b);
            })
        } else {
            console.error(res);
        }
    });

    img.onload = function () {
        pImg.width = pImg.canvas.width = img.width;
        pImg.height = pImg.canvas.height = img.height;

        // Draw the image into the backing canvas of the p5.Image
        pImg.drawingContext.drawImage(img, 0, 0);
        pImg.modified = true;

        if (typeof successCallback === 'function') {
            successCallback(pImg);
        }

        self._decrementPreload();
    };
    img.onerror = function (e) {
        p5._friendlyFileLoadError(0, img.src);
        if (typeof failureCallback === 'function') {
            failureCallback(e);
        }
    };

    //set crossOrigin in case image is served which CORS headers
    //this will let us draw to canvas without tainting it.
    //see https://developer.mozilla.org/en-US/docs/HTML/CORS_Enabled_Image
    // When using data-uris the file will be loaded locally
    // so we don't need to worry about crossOrigin with base64 file types
    if (path.indexOf('data:image/') !== 0) {
        img.crossOrigin = 'Anonymous';
    }

    return pImg;
};
```

This is a fully working replacement function, so forgive the redundant code.

The important changes are:

Find the browser's supported URL library, and default to empty dict for headers if none are provided
```javascript
    let URL = window.URL || window.webkitURL;
    headers = headers || {};
```

Use `fetch` (we can use something else if you have concerns about backwards compatibility); the `success` callback still sets the `src` attribute of an `<img />` tag, so the existing `onload` and `onerror` functions still work without modification.

```javascript
    fetch(path, {
        headers,
    }).then(res => {
        if (res.ok) {
            res.blob().then(b => {
                // Start loading the image:
                img.src = URL.createObjectURL(b);
            })
        } else {
            console.error(res);
        }
    });
```

----

PS: Sorry for multiple issues in one day! Especially sorry to code owners / maintainers that just received a bunch of email notifications from me... :)

**Comment by lmccart** [comment]
Unless something has changed, I believe that loading an image from an external url will prevent it from being drawable in the canvas due to cross origin issues. Am I mistaken?

there is this [httpGet](https://p5js.org/reference/#/p5/httpGet) method which could be useful, or the more generic [httpDo](https://p5js.org/reference/#/p5/httpDo)?

**Comment by limzykenneth** [comment]
Yes, loading image that need to be drawn on canvas needs to have its crossorigin property to be "anonymous". Which the original codebase and the adapted one above have done so it may not be a problem, we can just test to make sure.

Depending on whether cross compatibility between different module would be a concern (I'm guessing not since both are packaged into core under modular build system if I remember correctly), I would recommend using `httpDo` for consistency sake.

**Comment by j6k4m8** [comment]
@lmccart As far as I know, that's correct, unless the resource is marked to permit cross-origin requests. To clarify, is this closed because this isn't a useful addition, or because you'd prefer 
a `httpDo` implementation?

**Comment by lmccart** [comment]
The `httpDo` method already supports the passing of headers (see example [here](https://p5js.org/reference/#/p5/httpDo) so I think this may be covered? I don't imagine the use case of `loadImage` with headers is a very common one, especially since the images loaded in this way are blocked by the canvas. So I'd suggest just using `httpDo` to load the files and then handle or draw from there. Does this seem feasible?

**Comment by j6k4m8** [comment]
Sounds fine to me. Turns out to be a bit roundabout in practice, but not a
problem. Thanks for the clarification!
