### ISSUE TITLE
nfs prepends 0s instead of spaces

### ISSUE THREAD

**Issue by bristor** [processing/p5.js#2641]
### Nature of issue?
On the reference page for nfs():
>https://p5js.org/reference/#/p5/nfs

the example is such that one cannot readily see the prepending of spaces.  More importantly, after modifying the example so that it should show spaces, it does not: instead of prepended spaces, there are prepended zeroes, just as with nf().
- x Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- x  String Functions; specifically nfs()

#### Which platform were you using when you encountered this?
Yours :-) I am directly using the reference page.  Oddly, and perhaps a bit surprisingly-to-annoyingly, the reference pages don't say what platform nor version they are referencing / using.

- x Mobile/Tablet (touch devices) iPad
- x Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 
On the reference page for nfs():
>https://p5js.org/reference/#/p5/nfs

the example is such that one cannot readily see the prepending of spaces.   More importantly, after modifying the example so that it should show spaces, it does not: instead of prepended spaces, there are prepended zeroes, just as with nf().

Using the reference page's built-in editor, I altered the example from:
>var num1 = 11253106.115;
var num2 = -11253106.115;

to:
>var num1 = 112.115;
var num2 = -112.115;

The result shows the (incorrect) result of:
>0112.11
-0112.11

instead of
>_112.11
-_112.11

where I've used "_" (underscore) instead of a space, because it's darn hard to show a space in this case!

Finally, because of the bug, and the less-than-stellar documentation, it's not clear how "-112.115" should be formatted.  That is, which comes first, blanks or the minus sign?  This?
>-_112.11

or this?
>_-112.11

So, there are THREE things required to demonstrably fix this bug:
(a) Fix nfs()
(b) Change the nfs() reference page to use numbers that will show the effect of nfs(); the current ones have too many digits to left of the period (i.e., the integral part)
(c) Change the nfs() reference page to describe whether the minus sign precedes the prepended spaces, or vice-versa.

FWIW: On forum.processing.org, I found people carping about the same issue in April 2017 (look for "Working with GoPro Hero5 sensors" and user "Kajuna".  This suggests that perhaps the same bug plagues Processing itself, and it's behavior in p5.js is an attempt to be bug-for-bug compatible.  That would be a shame, though an understandable one.

- p5.js version: 
You tell me ;-)  Really: PLEASE put version number information on the reference pages!!!

That said: I did download Version 0.6.0 (January 19, 2018) from your site and it exhibits the same problem (caveat: I tested this version only with Safari).

- Web browser and version:
Safari 11.0.3
Chrome 64.0.3282.140 (Official Build) (64-bit)
Firefox 58.0.1
jsanywhere (iPad app)

- Operating System: 
macOS Sierra 10.12.6

- Steps to reproduce this:
See notes in the Details About This Bug, above.

#### New feature details:
There's one other thing I believe worth adding: and API call to get the version of p5.js.  I'd sure like to tell you what version is being used in this case, but can't really do that :-(  It's not on the reference pages, I don't see an API call, etc.  (PS: It's annoying that on the download page, from which I wanted to copy the version information for you, I could not, because it is contained within the link.  I had to actually type it into this report by hand!  In 2018!!!)

So: Please add an API call to get the version of p5.js being used.  Maybe, a couple:
- one to get the version as a string
- one to get the major, minor, micro (or whatever you call them) as separate numbers (e.g., return an array of ints)

**Comment by Spongman** [comment]
verified that this happens with 0.5.16 & 0.5.14, also.

**Comment by lmccart** [comment]
thanks @bristor, we will look into this.
the version number is listed at the top of the p5.js file

**Comment by limzykenneth** [comment]
The issue here is due to the [call from `nfs` to `nf`](https://github.com/processing/p5.js/blob/master/src/utilities/string_functions.js#L425) and as such the same problem exist with `nfp` as well. The reason is that `nf` will pad the numbers with 0 at the beginning by design if passed a `left` argument. The line in `nfs` that calls `nf` `apply` the whole arguments array to `nf` which will cause it to interpret the arguments meant only for `nfs` to be passed to `nf` and so 0 is padded.

The line that calls `nf` can simple be changed to 
```javascript
var nfRes = p5.prototype.nf.call(this, arguments[0]);
```

or to use named arguments

```javascript
var nfRes = p5.prototype.nf.call(this, num);
```

---

Correct me if I'm wrong but I don't see how having an API call would aleviate the need to at least copy and paste the version number if not type by hand into github issue? If the problem is that the version number is not highlightable on the downloads page then yes, I guess it would be helpful to have the version number somewhere on the page as just text but I don't see why an entire endpoint would be necessary.

**Comment by Spongman** [comment]
i'm not sure that solution will work. doesn't it still need to take the `left` and `right` parameters into account? i believe that fixing this will require a whole new version of `doNf` that handles spaces instead of `0`s - since the placement of the negative sign is different for those two cases.

**Comment by limzykenneth** [comment]
I haven't test out all cases yet, just tried to trace down where the 0s came from. From what I assume, the idea is probably first to pass the number into `nf` to get a string version back then pad that string according to `left` and `right`, which means if it is negative, the left padding space should go to the left of the minus sign and not between the number and the minus sign.

**Comment by Spongman** [comment]
> it is negative, the left padding space should go to the left of the minus sign and not between the number and the minus sign

no, i think you're right here. left padding is different for negative numbers depending on whether or not it's a zero. consider:

`-000123.456`
`___-123.456`

**Comment by bristor** [comment]
@lmccart: Thanks for pointing out where I could find the version!  But, hat didn't help me determine what version is running on the documentation pages of the p5.js website.  IMHO it's a Good Thing to mark each documentation page with appropriate version information.  E.g., Oracle marks the Java doc pages with the major version as part of the doc page's URL.

@limzykenneth: My reasoning to lmccart is part of the reason I favor an API that provides the version.   As to the downloads page: That's where I found version information that's used in the bug report.  It was only very mildly depressing that I had to type it in by hand (and thereby potentially introduce yet another place to put a bug into this process ;-)  "Only mildly depressing" like those websites that haven't yet been informed of password managers.

@Spongman: I agree with the format you presented, that the whitespace not go between the minus sign and the number (i.e., ___-123.456).

Please advise if it is appropriate to comment back to all of you in one note, instead of in different notes.  Either way's fine by me; each has pros & cons...

Thanks all for addressing this so promptly!

**Comment by Spongman** [comment]
i think you can safely assume that the reference docs are running against the same version that they're built from - the one on the download page.

**Comment by Spongman** [comment]
in addition, i think there's an issue with `nf()` and engineering format numbers.

for example, `nf(1e50, 5, 5)` currently returns

    1e+50.00000

wheras i think it should probably return something closer to

    1.00000e50

since the exponent is always an integer.


also, `nf(1.234e50, 5, 5)` is completely broken.

**Comment by kgolid** [comment]
My two cents:

`nfs()` is _not_ supposed to be a variant of `nf()` where zero-padding is replaced with space-padding.  It is only adding a space in front of the number (padded or not) in order to make it align with the same number negated.

Here is the nfs-description over at Processing.js, which I found to clarify the matter: 
> [...] Similar to nf() but leaves a blank space in front of positive numbers so they align with negative numbers in spite of the minus symbol. [...]

Same thing goes for ´nfp()´: numbers get padded just like with `nf()`, but in addition gets prefixed with either + or -.

**Comment by vipulrawat** [comment]
What I think so far from the disscussion and the issue:
**Function definitions** `nfs(num, [left], [right])` and `nf(num, [left], [right])`

I think `nfs()` and `nf()` are doing their job perfectly fine what they are meant to do *(apart from engineering format numbers)*.

> In short, nfs in case of a positive number prepends the number with a blank space, just to do the alignment. As negative number contains '-' (minus sign) but positive number don't  (generally) there is ill alignment in between digits in nf

So, the `nfs` intentionally prepends 0's if passed to it as a `left` argument if `left > length of integer part of the number` whether the number is negative or positive. *(this can be changed for negetive numbers in the program to not prepends additional 0's, but for positive number it's just users choice whether to pass `left` or not)*

Now coming to the issue, there is miss alignment in the canvas when using `text(nfs(num, [left], [right]))`. According to me, the miss alignment is due to `text()` not `nfs()`. `nfs()` is returning string i.e. number is converted to string. But when passing that to the `text` there is major padding difference between alphabets and integers. And this padding difference is likely to cause the error. I mean all numbers 0-9 have different padding between each number and all alphabets incl. '-' (minus sign) and '_' (space) have different.
Maybe my explanation is not well. Checkout this pen: [https://editor.p5js.org/vipulrawat/sketches/SkPdbj4TX](https://editor.p5js.org/vipulrawat/sketches/SkPdbj4TX)

See the output in console and corresponding output in canvas. Code is save for both. See the padding differences between alphabets **( '-' minus sign is considered as alphabet)** and between numbers too.
![deepinscreenshot_select-area_20181112122052](https://user-images.githubusercontent.com/26515826/48331503-4b615700-e676-11e8-9190-6f57a6662ba3.png)

![deepinscreenshot_select-area_20181112122846](https://user-images.githubusercontent.com/26515826/48331587-8a8fa800-e676-11e8-9952-107b698f1020.png)
---
Please correct me If am I missing something?

**Comment by lmccart** [comment]
Thanks for looking into this @vipulrawat. So if I am understanding correctly, the functions actually seem to be fine, but perhaps what is missing is a clear note in the description that the 0 padding behavior is expected.

Regarding the padding, I think this is the default behavior of the typeface and we need not account for it in the text() function itself, if the user can address this and see expected results by using a monospace typeface.

**Comment by lmccart** [comment]
addressed with https://github.com/processing/p5.js/pull/3314
