### ISSUE TITLE
audio

### ISSUE THREAD

**Issue by nomiliveson** [processing/p5.js#2654]
issue with audio - when playing multiple audio files simultaneously, there is an unexpected delay on each track

example :

    song1.playMode('restart');
    song1.loop(0, 1, 1, 0);

    song2.playMode('restart');
    song2.loop(0, 1, 1, 0);

    song3.playMode('restart');
    song3.loop(0, 1, 1, 0);

    song4.playMode('restart');
    song4.loop(0, 1, 1, 0);

    song5.playMode('restart');
    song5.loop(0 1, 1, 0);

very basic - the files all play at different times

please fix

<3 X O

**Comment by tstefanich** [comment]
Hello!

This may be caused by not preloading the audio files. The audio files will only play once they have been downloaded and are "ready". Often different files, depending on file size, will finish loading at different times which means when you try to play the audio files they will ultimately start at different times. 

Are you loading files like in this examples https://p5js.org/reference/#/p5.SoundFile/loadSound
"loadSound() returns a new p5.SoundFile from a specified path. If called during preload(), the p5.SoundFile will be ready to play in time for setup() and draw(). If called outside of preload, the p5.SoundFile will not be ready immediately"

If you could share a working example of this I may be able to help more. 

Warm regards, 
Tyler

**Comment by nomiliveson** [comment]
thank you Tyler, and yes im using the preload() function

function preload() {

  song1 = loadSound('assets/melody.mp3');
  song2 = loadSound('assets/highs.mp3');
  song3 = loadSound('assets/mids.mp3');
  song4 = loadSound('assets/lows.mp3');
  song5 = loadSound('assets/bass.mp3');

}

function setup() {
  createCanvas(windowWidth, windowHeight, WEBGL);

}

function keyTyped() {


  if (key == '1') {

    song1.playMode('restart');
    song1.loop(0, 1, 1, 0);

    song2.playMode('restart');
    song2.loop(0, 1, 1, 0);

    song3.playMode('restart');
    song3.loop(0, 1, 1, 0);

    song4.playMode('restart');
    song4.loop(0, 1, 1, 0);

    song5.playMode('restart');
    song5.loop(0, 1, 1, 0);

  }

}

it still does load the audio files simultaneously 

Thanks

**Comment by tstefanich** [comment]
Mmmmm I tried running this code with files I have and making 5 copies of the same files and loading each one and playing each one to see if I could hear a delay. Both with a longer file and a shorter file.

Both resulted in what seemed to be synchronized sound. (See attached files)
[p5-sound-delay-test.zip](https://github.com/processing/p5.js/files/1738343/p5-sound-delay-test.zip)

Would you mind sharing your files? for further testing?

**Comment by limzykenneth** [comment]
Sorry to interject, but can this discussion be moved to p5.js-sound repo [here](https://github.com/processing/p5.js-sound/issues), just so that we can track sound related issue where it is developed. Thanks!

**Comment by nomiliveson** [comment]
@tstefanich thanks, but i think its because they are different sound files. not sure why it effects start time if they have been preloaded already..? - @limzykenneth  sure thing

**Comment by nomiliveson** [comment]
@tstefanich 
[PLYR.zip](https://github.com/processing/p5.js/files/1739896/PLYR.zip)
