### ISSUE TITLE
createImage v/s loadImage with CodePen.IO

### ISSUE THREAD

**Issue by computhinkers** [processing/p5.js#2655]
I've noticed in [CodePen](www.codepen.io) with P5.JS, The **loadImage** and **createImage** are causing strange behavior. (here is a sample Pen):
https://codepen.io/computhinkers/pen/rJVbyV?

Loading an image in preLoad just completely sets CodePen into the infamous "Loading..." screen.

```
function preload() 
{
  // preload() runs once
  img = loadImage('http://th07.deviantart.net/fs70/PRE/i/2011/260/3/5/dash_hooray_by_rainbowcrab-d49xk0d.png');
}
```

Using createImg() seems to work
`img = createImg("http://th07.deviantart.net/fs70/PRE/i/2011/260/3/5/dash_hooray_by_rainbowcrab-d49xk0d.png");`

but the moment I try to use the resize function, the image consumes the whole page and removes all the other objects.

`img.resize(50,0);`

--------------
Removing the loadImage call from preLoad and putting it into the setup() function doesn't cause the "Loading .... " issue but rather does nothing.  No image displayed:

```

img =  loadImage('http://th07.deviantart.net/fs70/PRE/i/2011/260/3/5/dash_hooray_by_rainbowcrab-```
d49xk0d.png');
image(img,350,175, 100, 100);
```

#### Nature of issue?

- [X] Found a bug

#### Most appropriate sub-area of p5.js?
- [X] Image

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [X] Desktop/Laptop
- [ ] Others (specify if possible)

CodePen.IO External Resources
https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.5.16/p5.js
https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.6.0/addons/p5.dom.js

Tested on:
Google Chrome Version 64.0.3282.167 (Official Build) (64-bit)
Safari Version 10.1.1 (12603.2.4)

MacBook Air MacOS Sierra 10.12.15 (16F73)

**Comment by tau-** [comment]
Two issues, in both cases CORS will prevent loading of an image from a remote server.

![screenshot 2018-02-18 at 8 02 44 pm](https://user-images.githubusercontent.com/1418502/36362139-bc6cd206-14e6-11e8-93a3-dbd2923ee6bb.png)

You should try to build this locally instead of in an online editor like CodePen. In the case where you call `loadImage` in setup you need to supply a callback to display the image after the load is complete. An example is given in the [documentation](https://p5js.org/reference/#/p5/loadImage):

```
function setup() {
  // here we use a callback to display the image after loading
  loadImage('assets/laDefense.jpg', function(img) {
    image(img, 0, 0);
  });
}
```

**Comment by lmccart** [comment]
thanks @tau-!
