### ISSUE TITLE
duplicate imports results in dulpicate canvases

### ISSUE THREAD

**Issue by Spongman** [processing/p5.js#2681]
p5 v0.6.0

demo: https://codepen.io/Spongman/pen/eVoKqb?editors=1010

based on #2679

if you import the p5.js script twice, you'll get two canvases and presumably a whole bunch of other undefined behavior.

it may be useful to have the p5 library detect this and generate an error.

**Comment by limzykenneth** [comment]
Would this form part of FES or would this be something the library itself will take care of even without FES? 

Got an idea how to do this detection? I'm thinking if the problem arise from the library being load twice, would it make sense to just check at the very beginning if `p5` is already defined?

**Comment by Spongman** [comment]
i think it should be independent of FES since FES is only a thing in un-minimized builds.

yeah, i think just checking for the presence of p5 at the start would work fine.

**Comment by ankur54** [comment]
Hi. I had a doubt. How is one supposed to check the presence of p5? Sorry, if it is a very trivial question.
Also, is this issue still open?

**Comment by Nishant-Ingle** [comment]
> Hi. I had a doubt. How is one supposed to check the presence of p5? Sorry, if it is a very trivial question.
> Also, is this issue still open?

I guess so as the bug is still there in p5 v0.10.2

**Comment by akshay-99** [comment]
Hey everyone! 
Adding my two cents to this discussion. 
This could be solved easily as an FES warning telling the user about the duplicate imports. But currently the FES produces [this](https://user-images.githubusercontent.com/38867671/75705959-6b40e200-5ce2-11ea-8f57-b1213322d2bf.png) barrage of messages for a duplicate p5 import. 
So another FES message is easy to miss in this case. ( Not to mention it is quite intimidating for someone just starting off to encounter so many error messages at once :sweat_smile:  ). 

Instead of changing this behaviour of the FES, it would be better instead to have the library itself take care of it, preventing double running of the initialization code. 

What are your thoughts?

Also @limzykenneth  I can work on it?

**Comment by limzykenneth** [comment]
> Instead of changing this behaviour of the FES, it would be better instead to have the library itself take care of it, preventing double running of the initialization code.

@akshay-99 That's what the check for `p5` in the beginning that's mentioned above about. You'll just need to check for already existing definition of `p5` in the `window` object then if it exist don't initialize.

@ankur54 Sorry it is rather late but are you still interested in working on this? I'll assign @akshay-99 if you are no longer available or haven't reply in a couple days.

**Comment by limzykenneth** [comment]
@akshay-99 I'll assign this to you. Let us know if you need help with this. Thanks.
