### ISSUE TITLE
Destroying the Wiki?

### ISSUE THREAD

**Issue by spencermathews** [processing/p5.js#2715]
@lmccart I just noticed that a number of Wiki pages have been unceremoniously ripped out. Some content appears to have found homes in other pages (e.g. [FAQ](https://github.com/processing/p5.js/wiki/Frequently-Asked-Questions)), while other content seems to have vanished from the Wiki altogether (e.g. [Instantiation Cases](https://github.com/processing/p5.js/wiki/Instantiation-Cases)) without nary a redirect. Some of this content was quite useful.

Question: What's the motivating factor here? Is this part of a larger reorganization?

Request: Please at the very least set up temporary redirects, and perhaps consider marking content as deprecated as an alternative to complete deletion.

**Comment by lmccart** [comment]
hi @spencermathews, good question. sorry for the abrupt changes.
we felt that heavy reliance on the wiki is non-ideal because it's difficult to track changes, and the content is ordered alphabetically in the sidebar so it can be hard to get a sense of the content. additionally, we realized there was a lot of general web/html/js tutorial content there that isn't specifically to p5.js, and is actually better presented in other places on the web dedicated to such resources.

our plan is this:
- move all development related docs into markdown files in the repo, so changes made will be tracked via issues and pull requests
- move non-p5-specific pages/tutorials out of the wiki, and post in other places if relevant, or delete if better resources can be found elsewhere.
- move general non-development information to the p5js.org website
- leave p5.js specific tutorial pages in the wiki, and link to them clearly from the p5js.org website. this allows us to still leverage the easy edibility of these pages (they are currently getting updated pretty regularly), letting more people contribute in a low barrier to entry way.
