### ISSUE TITLE
Get() only returns pixel

### ISSUE THREAD

**Issue by JamesLightn** [processing/p5.js#2720]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core
- [ ] Data
- [ ] Events
- [x] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: p5.js v0.6.0 January 19, 2018
- Web browser and version: Chrome 65.0.3325.162 (Official Build) (64-bit)
- Operating System: MacOSX 10.13.3 
- Steps to reproduce this:
visit https://p5js.org/reference/#/p5.Image/get
remove '60, 90' params from  'c = myImage.get(60, 90);'
hit run
Expected: 'If no params are passed, those whole image is returned'
Actual: it breaks/ no image displayed
It seems this also is broken for all params filled out too

I find this issue within my own code as well.

**Comment by limzykenneth** [comment]
It actually works as expected, `get(x, y)` is meant to return the pixel value of the specified coordinate, ie. an array of `[r, g, b, a]`. While `get()` is meant to return an image, ie. an instance of `p5.Image` that you can draw on screen. 

It breaks on the reference page when you remove the arguments is because on the next line it is calling `fill(c)` and you can't pass in a `p5.Image` to `fill()` so it fails. The same goes for `get(x, y, w, h)`, it returns a `p5.Image` as well.

**Comment by JamesLightn** [comment]
Oh wow, I feel so stupid. Yes, thank you.

**Comment by limzykenneth** [comment]
@JamesLightn No worries, if you think the documentation is potentially confusing do open an issue and we can look into making it clearer. Cheers.

**Comment by Spongman** [comment]
i tried to fix this in the docs, but there's a larger issue in that only the return type of the first overload in the docs is shown in the 'returns' section.

i think the issue here is that the documentation was originally intended for methods that didn't have multiple overloads and multiple return types. grouping the parameter descriptions together in a single table, and having a single line for the return type is a consequence of this.

i think that this could be improved by having a separate section for each overload, where each overload section lists the syntax, the parameter descriptions and the return type for _that_ overload. this would remove the ambiguity over which parameters and return types apply to which overload.
