### ISSUE TITLE
Insert Module in Magic Mirror

### ISSUE THREAD

**Issue by leejaeuk** [processing/p5.js#2745]
#### Nature of issue?

- [ ] Found a bug
- [ ] Existing feature enhancement
- [O ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [O ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [ ] Desktop/Laptop
- [ O] Others (specify if possible)

#### Details about the bug: 

Hello developeing Eng.. 
I wondered about use way p5.js.
I'm used raspberry pi 3B & installed Magic Mirror and I also insert other modules .

but I want to make a my custom module from p5.js.(or p5.js.example)
How can I insert HTML.js to node.js and are there any way to insert Magic mirror?
please give me any information about that..
Thank you!

**Comment by kjhollen** [comment]
hi @leejaeuk! this sounds like a good question for the p5.js forums: https://forum.processing.org/two/categories/p5-js-programming-questions please try posting there—I'm sure someone will be able to offer some insight. github is more for reporting issues with p5.js itself rather than for questions about using the library. thanks!
