### ISSUE TITLE
Documentation of unimplemented 2D vs WebGL

### ISSUE THREAD

**Issue by AlexKraken** [processing/p5.js#2756]
#### Nature of issue?

- [ ] Found a bug
- [x ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [x] Core
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [x] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [ ] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 
Add documentation of what is and isn't included in the WebGL mode at each release or create a running list within the WebGL wiki page which lists unimplemented functions in WebGL such as blendMode. This would clear up issues for WebGL beginners and provide a single resource to know why these things aren't working. It looks like this has been an issue since 2015: #986
- p5.js version: 
0.6.0
- Web browser and version: 
Safari Version 11.0.2 (13604.4.7.1.3)
- Operating System: 
macOS 10.13.2
- Steps to reproduce this:

```javascript
// must create canvas with WEBGL
blendMode(SCREEN)
fill(0,255,0,100)
ellipse(0,0,100,100)
fill(255,0,0,100)
ellipse(50,50,100,100)
```

**Comment by stalgiag** [comment]
Okay just want to update this with the remaining functions that are current not working with WEBGL mode. Luckily there are only a few now:
`filter()` - needs implementation or at least protection/warning message
`strokeCap()` - implementation will be arduous, has protection and warning message
`strokeJoin()` - implementation will be arduous, needs protection/warning message
`textStyle()` -- this is implied in the documentation since a loaded font is required in GL and the docs say to switch the current font instead of using when `textStyle()` when using a loaded font.

**Comment by stalgiag** [comment]
Okay. I have opened issues for the remaining 2 unprotected, unimplemented WEBGL functions:

filter - #4046 
strokeJoin - #4047 

Almost all functions work in both renderers now. By my count, there are 5 functions that only work in 2D. After those two issues above are filled, all 5 of those functions will log warnings and have proper documentation. I think that means we can close this issue. Thank you for filing the issue!
