### ISSUE TITLE
p5 Not launching :(

### ISSUE THREAD

**Issue by malremaithi** [processing/p5.js#2776]
So i recently downloaded p5.Js and once I want to open p5, it shows a Microsoft JScript compilation error (i still have the latest Java version). It gives me:

Script: C:\Users\......
Line: 31251
Error: Expected identifier, string or number
code:800A0404
Source: Microsoft Jscript error

Just to observe what's happening, i opened p5 using Notepad++ (didn't meddle with anything) and showed the following code (The last line is the Error line): 

// Record = same as Table, but inlined (a Table has an offset and its data is further in the stream)
// Don't use offsets inside Records (probable bug), only in Tables.
var table = {
    Table: Table,
    Record: Table,
    Coverage: Coverage,
    ScriptList: ScriptList,
    FeatureList: FeatureList,
    LookupList: LookupList,
    ushortList: ushortList,
    tableList: tableList,
    recordList: recordList,
};

Thanks,

**Comment by Spongman** [comment]
the error you're seeing is caused by attempting to run p5.js as a program. this is not the intended use of p5.   the recommended way to use it is to create a project directory containing an .html file and a script .js file, and run the .html file in your browser. the easiest way to do this is to use the empty example project that's included in the download. see https://p5js.org/get-started/#file-setup for instructions on how to do this.

**Comment by lmccart** [comment]
thanks @Spongman!
