### ISSUE TITLE
loadShader() parameters are not optional

### ISSUE THREAD

**Issue by lorenzo-lipparini** [processing/p5.js#2805]
#### Nature of issue?

- [x] Found a bug

#### Most appropriate sub-area of p5.js?

- [x] WebGL

#### Details about the bug: 

In the documentation, the `loadShader()` function is said to accept two optional parameters, but in reality if either one of them is omitted the code breaks.
This happens because the function still tries to make an http call to load the file, although the file name is actually `undefined`.

**Comment by Spongman** [comment]
yeah, the `loadShader` method's preload behavior is also broken (fixed in #2717)

**Comment by stalgiag** [comment]
[Unable to create a shader program without both frag and vert](https://stackoverflow.com/questions/45038172/is-it-possible-to-create-webgl-programs-with-only-vertex-shaders). It seems that to fix this we should either change the documentation so that both parameters are required or add a basic backup frag shader to load when the [shader's frag source is undefined](https://github.com/processing/p5.js/blob/master/src/webgl/p5.Shader.js#L75).

**Comment by stalgiag** [comment]
I think that it makes sense to require both the vert and frag. I [quickly made a branch](https://github.com/stalgiag/p5.js/commit/ca4376e81ae1f1996a6b07b84f2318c2c0b88b6c) that assigns a default frag shader to any shader created without a frag but this opens up questions about why the frag is optional and not the vert. I think use cases where a user wants to use a custom vertex shader but doesn't feel like adding a simple frag shader is pretty limited. While the inverse may occur more often and more closely reflects the Processing implementation. I think in lieu of flipping the order of the parameters and making vertex optional, we should just update documentation to require both.

**Comment by stalgiag** [comment]
I am closing this as it was decided to require both arguments and this new requirement was put in place by #2996. Thanks for filing the issue!
