### ISSUE TITLE
rectangles half the size of canvas given the same value

### ISSUE THREAD

**Issue by zimo-xiao** [processing/p5.js#2840]
#### Nature of issue?

- [x] Found a bug

#### Most appropriate sub-area of p5.js?

- [x] Core/Environment/Rendering

#### Which platform were you using when you encountered this?

- [x] Desktop/Laptop

#### Details about the bug: 

- p5.js version: v0.6.0
- Web browser and version: Chrome/Safari
- Operating System: MacOSX
- Steps to reproduce this:
My rectangles are always half the size of the canvas given the same value. Though, positioning rect is correct. I suspect that this has something to do with my high resolution display. Setting pixel density to 1 does not help.

```JavaScript
const canvas_width = 1000;
const canvas_height = 400;

function setup() {
  createCanvas(canvas_width,canvas_height);
  frameRate(30);  //set 30 frame pre second
}

function draw(){
  background(0);
  fill(255);
  noStroke();
  rectMode(CENTER)
  rect(0,canvas_height,canvas_width,30);
  push();
  translate(canvas_width,0);
  rotate(-PI/6);
  rect(-canvas_width,0,canvas_width,10);
}
```

![image](https://image.ibb.co/dOf3Yn/Screen_Shot_2018_05_02_at_11_53_58_PM.png)

**Comment by mislavmilicevic** [comment]
The code above functions as intended. The documentation clearly says that when using CENTER mode, the first two parameters are defining the shapes CENTER point. Since you are defining the center point on the edge of the screen, the other half of your rectangle is getting rendered off canvas.

If you want to get the desired effect, set your center point to the center of the canvas (half width and half height)

**Comment by zimo-xiao** [comment]
thanks a lot dekmm!! I didn't realized that this has to do with the mode I'm using. Silly.
