### ISSUE TITLE
on openprocessing, I can't do the hour() or the minute()

### ISSUE THREAD

**Issue by TheBestCoder101** [processing/p5.js#2922]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [x] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 
- Web browser and version: 
- Operating System: 
- Steps to reproduce this:

**Comment by limzykenneth** [comment]
Hi, can you include more info about your issue? If you can fill in the issue template in the "Details about the bug" section we can better understand what your problem is, if you can include a link to openprocessing and/or a simple code snippet demonstrating the problem it will be very helpful as well. Thanks.
