### ISSUE TITLE
show error message when loading files that are too big

### ISSUE THREAD

**Issue by kjhollen** [processing/p5.js#2981]
#### Nature of issue?

- [ ] Found a bug
- [x] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [x] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Feature enhancement details:

There are currently two open issues for when the browser fails to load a file because it is too big: #2661 for `loadStrings()` and #2216 for `loadTable()`. I think they are not possible to fix, but it would be good to produce an error message for the user and suggest breaking the data into smaller files as a work around.

**Comment by TanviKumar** [comment]
Taking this up as part of GSoC

**Comment by lmccart** [comment]
hi @TanviKumar what's the status on this one?

**Comment by TanviKumar** [comment]
Hi @kjhollen, in order to limit the user from the loading very large files (in this case anything greater than 64MB in size), I plan on using the HEAD request to obtain the content length of the file without fetching the entire body. Would it be wise to use synchronous XHR or Async XHR? Here's a [link](https://bitexperts.com/Question/Detail/3316/determine-file-size-in-javascript-without-downloading-a-file) to what I've been referring to.
