### ISSUE TITLE
Capture Canvas State and Retain Canvas State

### ISSUE THREAD

**Issue by Aditya21196** [processing/p5.js#2983]
#### Nature of issue?

- [ ] Found a bug
- [ ] Existing feature enhancement
- [x] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [x] Core/Environment/Rendering
- [x] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [x] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### New feature details:
There should be function which retains all the pixels of the canvas and captures it in a variable. The variable should be such that it can later be used to retain the state of the canvas.

For eg: 

`background(retainedCanvasState)`

 This will save a lot of computation time in many cases when only a small detail needs to be varied in the sketch.

**Comment by limzykenneth** [comment]
Would the [`pixels`](https://p5js.org/reference/#/p5/pixels) array suit your needs? Or you can use [`get()`](https://p5js.org/reference/#/p5/get) to grab an image of the current canvas to be drawn at the start of the next draw frame. If neither suit your needs, can you provide us with a more complete use case? Thanks.

**Comment by Aditya21196** [comment]
Yes sure. So I need to draw an array of lines on a graph. As the user scrolls over the graph, I am executing a function to show the x-co ordinate and y-co ordinate of where the cursor is. But every time I go on to the next frame in the draw loop, I have to draw all the lines again and then show the location of cursor as per mouseX and mouseY. Why do I have to draw the lines again? That is redundant. In fact, in some cases, there is even lag.

 So I was suggesting a way of retaining the graph as background while I draw the co-ordinate information onto it.

An alternate way could be to overlay another transparent layer onto the canvas ( like in d3 you can work with layers). That would be awesome too.

Do you think this could be solved by the pixels array? If so, could you please provide me with a code snippet for that?

 I don't want to use `get()` since it involves images and the scale of images is different in p5 than the canvas.  Thanks.

**Comment by limzykenneth** [comment]
There are multiple ways to achieve the effect you want, following is just my preferred method:

In this case, you can utilize graphics buffer with `createGraphics`, start by creating a p5.Graphics that is the same size as the width and height of your canvas:
```javascript
var graph;

function setup(){
  createCanvas(500, 500);
  graph = createGraphics(width, height);
}
```
Then you can draw all your lines in the array into `graph` with something like so:
```javascript
function drawLines(){
  for(var i=0; i<lines.length; i++){
    graph.line( ... draw the line using lines[i] object that you have in the array ... );
  }
}
```
Then whenever you want to update the lines in the graph, just call `drawLines()` anywhere in your code.

That way, you don't have to redraw the lines every single frame but rather just draw `graph` onto the canvas using `image(graph, 0, 0)` at the beginning of the draw loop, since in between frame you have not called `drawLines()` it will remain the same until you call it with changes to `lines` array. You will also have the benefit of having the whole graph available instead of as a static background that you can export, draw elsewhere or something else.

**Comment by kjhollen** [comment]
Great suggestion, @limzykenneth! That's what I'd do, too. @Aditya21196, since this proposed solution works I'm going to close this—but if I've misunderstood, please reopen. Thank you!
