### ISSUE TITLE
JSON

### ISSUE THREAD

**Issue by KingInBush** [processing/p5.js#3034]
![image](https://user-images.githubusercontent.com/28199270/41604713-19b8ab92-740a-11e8-9170-b412b5e714d2.png)

**Comment by montoyamoraga** [comment]
Did you only open the HTML file on the browser?
When you are using external files, like loading images or a JSON file,
you need to open the HTML file through a server.
Please check this tutorial for details on how to use it.
[https://github.com/processing/p5.js/wiki/Local-server](https://github.com/processing/p5.js/wiki/Local-server)
Also feel free to use the [Processing forum](https://discourse.processing.org/)
for doubts, the issues on this repository are mostly for bugs, instead of doubts.
Hope it works out, let me know if it does so I can close the issue, best!
