### ISSUE TITLE
p5 conflicting with JavaScript Standard Style extension in Visual Studio Code

### ISSUE THREAD

**Issue by GiaFil7** [processing/p5.js#3043]
When all the correct files of the library are properly loaded, if the JavaScript Standard Style extension is enabled   I get an error message that [function] is not defined and it doesn't recognise the setup and draw functions. Disabling the extension fixed the issue. It would be better if p5 and the extension could work together on a workspace.

**Comment by kjhollen** [comment]
Hi @GiaFil7, thank you for filing this issue. I suggest posting on the p5.js forums https://discourse.processing.org/c/p5js to see if any other folks are using VSCode and might have some advice. Also cc'ing @aferriss on this because I know he is a VSCode user.

Can you provide more detail on what might need to be done to support this extension? If it's something that would generally help the project, we can probably fix it—however, we can't support every editor and plugin configuration. If it is an issue that only applies to using this particular plugin + editor, I'll probably close the issue. Let me know!

**Comment by lmccart** [comment]
I looked into this a bit and the [JS Standard Style](https://standardjs.com/) doesn't support globally defined functions and variables in libraries. p5.js makes use of these in order to make it easy for new programmers to get up and going with the library. There is a [workaround](https://standardjs.com/#i-use-a-library-that-pollutes-the-global-namespace-how-do-i-prevent-variable-is-not-defined-errors) that you could do yourself, but it doesn't seem quite feasible to integrate into the library as a whole since this is a somewhat specific use case.

**Comment by GiaFil7** [comment]
@Imccart Thank you for pointing this out! I will close the issue.
