### ISSUE TITLE
WebGL setAttributes() leads to multiple contexts being created

### ISSUE THREAD

**Issue by mattdesl** [processing/p5.js#3061]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [x] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [x] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

Hi there. :wave: I'm using WebGL and one of the first things I do is turn on MSAA since it dramatically improves the visual quality (and later, if performance starts to become an issue, turn it back off). 

I noticed that the current structure of p5.js does not allow you to create a canvas with specified attributes; instead, you have to create a WEBGL canvas, then call `p5.setAttributes` after to enable MSAA. The result is that the first GL context is destroyed, and a new one created.

This is not a huge deal, although it's a bit wasteful and produces some doubled-up console noise.

```
p5.RendererGL: enabled webgl context
p5.RendererGL: enabled webgl context
```

I think a clean fix might be to allow `setAttributes` to be called before hand (right now it throws an error), thus storing the attributes until the first `createCanvas` call. Thoughts?

**Comment by mlarghydracept** [comment]
Hello! Thanks for the suggestion! I agree that would be better. Two approaches come to mind but neither are ideal.  

First - If there isn't a renderer yet, `setAttributes` could store its[ `attr` object](https://github.com/processing/p5.js/blob/master/src/webgl/p5.RendererGL.js#L339) then `createCanvas` could pass it as the fourth argument [when constructing RendererGL](https://github.com/processing/p5.js/blob/master/src/core/rendering.js#L104).

The other option would just enable an overload on `createCanvas` that is an attributes argument similar to what you would pass to `setAttributes`. 

The first isn't ideal because it adds another object to the p5 core. The second is even less ideal because it adds another overload that won't be used often to one of the most important functions. The first option might be acceptable. I am not sure. There is also probably a more elegant solution that isn't coming to mind at the moment.

**Comment by mattdesl** [comment]
Thanks for looking into it.

I agree it is not good to add more surface area to the API for end-users. But an additional private variable seems fine to me, is there any reason that would not be desirable?

**Comment by sanketsingh24** [comment]
I think we can add `setattribute` to preload, maybe change the name and the method to like `preloadattribute` and implement what @stalgiag said in the first approach.

OR, we can add an optional argument to `createcanvas` which accepts an object with property name and values, but it would certainly add a little load on the function, but it would save the time taken to recreate an entire context again.

**Comment by stalgiag** [comment]
Hi @sanketsingh24, I don't think it is necessary to have a separate preload function. `setAttributes` never doesn't need to do anything asynchronously and there is no read/write happening. I think it is best to keep it simple and do as @mattdesl suggests and just do this with a single private variable. The only tricky thing is that this needs to work when the current renderer is 2D as is the case before a user calls `createCanvas`. I have [a branch with a working fix here](https://github.com/stalgiag/p5.js/tree/singleContextsetAttributes). It is fairly simple as a fix but feels a bit noodle-y. I'll reread this again tomorrow and if it seems alright I'll open a PR and request a review from you @sanketsingh24 .
