### ISSUE TITLE
canvas.style and canvas.position is not a function p5.js

### ISSUE THREAD

**Issue by bassamElabid** [processing/p5.js#3073]
even though i included the p5.dom.js file in the html file i'm still getting this error message from the chrome's console i tried everything and i always get this phrase and the canvas does not appear on the page.
this is my code it's really simple
var canv;

function setup(){
canvas = createCanvas(400,400);

canvas.style('z-index','-1');
canvas.position(100,100);
}

function draw(){

background(51);
    fill(0);
rect(200,200,200,200);

}

this is the html file 
<!DOCTYPE html>

<html>
<head>
     
    <script src = "p5.dom.js"></script>
    <script src = "        p5.js"></script>
    <script src = "  sketch.js"></script>
  
        </head>
<body>
    
   
    </body>

</html>

**Comment by aferriss** [comment]
Hi @bassamElabid !

I believe the problem is that your variables weren't consistently named. You wrote `var canv;` but then in setup() you used a variable named `canvas`. If you change `var canv;` to `var canvas;` your code might run as expected. The other thing that might be bugging out your sketch is the extra white space in your html file. It should look more like this:

````
<html>
  <head>
    <script src = "p5.dom.js"></script>
    <script src = "p5.js"></script>
    <script src = "sketch.js"></script>
  </head>
  <body>
  </body>
</html>
````

Here's a [quick example](http://alpha.editor.p5js.org/aferriss/sketches/HkkpCLlm7). I hope that helps!

I would also suggest that in the future for issues like this, you post on the [processing forum](https://discourse.processing.org/c/p5js) (https://discourse.processing.org/c/p5js), which has it's own p5js section. The github issues page is a place where bugs in the library or new features are discussed. I understand that in this instance the error was probably a bit ambiguous, but just offering a friendly tip :D

**Comment by bassamElabid** [comment]
@aferriss no that's not the problem my variable is canv but i changed it in this issue just to be more clear but in my original code my var is canv and it's the same where ever i use it the problem is that i'm using the .position and .style but it's saying that it's not a function even that i'm using both p5.js and p5.dom.js and that's really pissing me off

**Comment by bassamElabid** [comment]
@aferriss no that's not the problem my variable is canv but i changed it in this issue just to be more clear but in my original code my var is canv and it's the same where ever i use it the problem is that i'm using the .position and .style but it's saying that it's not a function even that i'm using both p5.js and p5.dom.js and that's really pissing me off and the space isn't also the problem i just changed it and it's still giving me the same problem

**Comment by lmccart** [comment]
try flipping the p5 script lines so you first include the p5 library, and then the dom addon
```
<script src = "p5.js"></script>
<script src = "p5.dom.js"></script>
```

**Comment by bassamElabid** [comment]
And whenever i use and p5 library it tells me that it cannot read property 'prototype' of undefined at some p5.dom.js lines or the p5 librarie that i'm using

**Comment by lmccart** [comment]
let's keep the issues focused so we can solve them. please a second issue for the other problem you describe if you'd like.

 did flipping the order of those two lines work? here's [an example](http://alpha.editor.p5js.org/lmccart/sketches/S182CCl7X) that demonstrates this.

**Comment by bassamElabid** [comment]
Yeah it worked and it solved the other problem about the prototype undefined thanks alot
