### ISSUE TITLE
global-mode errors fired during mocha tests

### ISSUE THREAD

**Issue by Spongman** [processing/p5.js#3093]
(current master)

i'm seeing a bunch of global mode binding errors being fired during the global-mode mocha tests. this is happening both in-browser and on the command line (including travis).

```
p5 had problems creating the global function "_initializeInstanceVariables", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
You just changed the value of "_initializeInstanceVariables", which was a p5 function. This could cause problems later if you're not careful.
```

**Comment by Zalastax** [comment]
This was a tricky bug to hunt down.
Those errors are generated when `_createFriendlyGlobalFunctionBinder` is called, which happens when sketch is not defined https://github.com/processing/p5.js/blob/438b59617fd98cae7e4d88a64a6763a229d9f017/src/core/main.js#L503-L528
Looking at the trace I found that this happens at https://github.com/processing/p5.js/blob/438b59617fd98cae7e4d88a64a6763a229d9f017/src/core/init.js#L17-L29 when `window.mocha` is undefined.
I found it strange that `window.mocha` was undefined when in a test but eventually noticed that some tests define an iframe which they run code in: https://github.com/processing/p5.js/blob/438b59617fd98cae7e4d88a64a6763a229d9f017/test/unit/core/core.js#L129-L215
The problematic test is `'works when p5.js is loaded asynchronously'` which accidentally adds a p5 script tag twice: https://github.com/processing/p5.js/blob/438b59617fd98cae7e4d88a64a6763a229d9f017/test/unit/core/core.js#L174 https://github.com/processing/p5.js/blob/438b59617fd98cae7e4d88a64a6763a229d9f017/test/unit/core/core.js#L176-L189
That test breaks if the iframe is created via: `createP5Iframe(' ');` (which causes it to not automatically inject a p5 script tag) but it does not break if these lines are removed: https://github.com/processing/p5.js/blob/438b59617fd98cae7e4d88a64a6763a229d9f017/test/unit/core/core.js#L183-L186
To me the `load` callback looks correct, but apparently it's not.
I would love if someone takes over and fixes the test.

There are many other things logged when running the tests and I think it would be great if we made sure that tests fail if they have: uncaught errors / lost promisses (even in iframes they create), if they create elements that are not cleaned up, or if they use console.log. I'd like tests to inject their own logger instance (possibly by simply shadowing window.console) and that the test asserts something about the log output. Tests that should log can then keep doing so (and they can assert that it actually happens) and tests that accidentally create warning logs will be detected.
