### ISSUE TITLE
vector.setMag() behavior

### ISSUE THREAD

**Issue by 4skinSkywalker** [processing/p5.js#3172]
Hi guys, I'm a bit confused about the `setMag()` method.

**Should** 
`vector.setMag( vector.dot( another ) ) `
**have the same result of** 
```
vector.normalize()
vector.mult( vector.dot( another ) )
```
**?**

Thanks in advance ;)

**Comment by Zalastax** [comment]
Yes!
That's actually how it's implemented.
https://github.com/processing/p5.js/blob/a64959e2722c4cad9327246be494f0b472ccd54c/src/math/p5.Vector.js#L996-L998

**Comment by 4skinSkywalker** [comment]
I feel the two approaches are different in this particular case because object in JS are passed by reference...
Take the following 'real' example:

var A = createVector( 2, 3 )
var B = createVector( 2, 3 )
A.setMag( A.dot( B ) )
log( A ) => Vector {p5: p5, x: 7.211102550927979, y: 10.816653826391969, z: 0, name: "p5.Vector"}

// Reset vector A
A = createVector( 2, 3 )

A.normalize()
A.mult( A.dot( B ) )
log( A ) => Vector {p5: p5, x: 2.0000000000000004, y: 3.0000000000000004, z: 0, name: "p5.Vector"}

It's not the same behavior.
Are those two expected to behave the same or not?

Thanks in advance

**Comment by meiamsome** [comment]
@4skinSkywalker 
It's to do with the order of operations, you would need to calculate `a.dot(b)` before normalizing a:

```javascript
var a = createVector(2, 3)
var b = createVector(2, 3)
var dot = a.dot(b) 
a.normalize()
a.mult(dot)
console.log(a)
```

**Comment by 4skinSkywalker** [comment]
@meiamsome 
So you say the following shouldn't work.
```
A.normalize()
A.mult( A.dot( B ) )
```
But it is actually working... It is the counterpart with `setMag()` which is not.

**Comment by meiamsome** [comment]
@4skinSkywalker 
It's not really a matter of should or shouldn't work, it's about what you're computing
```javascript
A.normalize(); // This line is 'redefining' A
A.mult( A.dot( B ) );
```
Calculates
![equation](https://latex.codecogs.com/gif.latex?%5Cdfrac%7BA%7D%7B%7CA%7C%7D%20%5Cleft%20%28%20%5Cdfrac%7BA%7D%7B%7CA%7C%7D%20%5Ccdot%20B%20%5Cright%20%29)
And given that A and B are the same, you get 
![equation2](https://latex.codecogs.com/gif.latex?%5Cdfrac%7BA%7D%7B%7CA%7C%7D%20%5Cleft%20%28%20%5Cdfrac%7BA%20%5Ccdot%20A%7D%7B%7CA%7C%7D%20%5Cright%20%29%20%3D%20%5Cdfrac%7BA%7D%7B%7CA%7C%7D%20%5Cdfrac%7B%7CA%7C%5E2%7D%7B%7CA%7C%7D%20%3D%20A)


Whereas the other examples above just calculate 
![equation3](https://latex.codecogs.com/gif.latex?%5Cdfrac%7BA%7D%7B%7CA%7C%7D%20%5Cleft%20%28%20A%20%5Ccdot%20B%20%5Cright%20%29)
Which, given A and B are the same, gives:
![equation4](https://latex.codecogs.com/gif.latex?%5Cdfrac%7BA%7D%7B%7CA%7C%7D%20%5Cleft%20%28%20A%20%5Ccdot%20A%20%5Cright%20%29%20%3D%20%5Cdfrac%7BA%7D%7B%7CA%7C%7D%20%7CA%7C%5E2%20%3D%20A%7CA%7C)
Where `|A|` is sqrt(13), which gives the multiplication factor that you get when you run through that code

This is due to the mutability of A more than any passing-by-reference. That is to say that the call to `A.normalize()` changes the value of `A` further through the code. If the p5.Vector was made immutable then you would have to do something like the following, which would hypothetically create 2 extra p5.Vector instances.
```javascript
var a = createVector(2, 3); // A
var b = createVector(2, 3); // B
var aNorm = a.normalize(); // A/|A|
var c = aNorm.mult(a.dot(b)) // A/|A| * (A.B)
console.log(a) // still (2, 3)
console.log(aNorm) // still (2/sqrt(13), 3/sqrt(13))
console.log(c); // (2, 3) as well
```

Hopefully that helps explain why the two codes are separate?
