### ISSUE TITLE
Disable Friendly Errors sometimes doesn't work

### ISSUE THREAD

**Issue by catarak** [processing/p5.js#3178]
#### Nature of issue?

- [X] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [X] Other (specify if possible): Friendly Errors

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [X] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version:  0.7.1
- Web browser and version: 
- Operating System: 
- Steps to reproduce this:

In trying to work on processing/p5.js-web-editor#417, I noticed that sometimes using the flag p5.disableFriendlyErrors works, and other times it doesn't work. For example,
```js
p5.disableFriendlyErrors = true;

function setup() {
  ellipse(3, 3);
}
```
won't display the friendly error, but
```js
p5.disableFriendlyErrors = true;

var myFont;
function setup() {
  myFont = loadFont('doesntExist.ttf');
}
```
will still show the friendly error. Maybe it has to do with `loadFont()` being asynchronous? I notice the same behavior with `loadImage()` as well.

**Comment by lmccart** [comment]
I believe the disabling refers to the removal of the type checking for arguments, which is what slows down the code. In the case of loading images or fonts, an error is returned by the browser if the file isn't found, and the FES just adds some info to make it a little clearer. We could of course prevent this, but it's not causing any performance slowdown in these cases. Or maybe we need to change the documentation and name of `p5.disableFriendlyErrors` to something like `p5.disableParameterChecking`? I don't know though, because this naming might be more confusing for beginners.. thoughts?

**Comment by catarak** [comment]
Got it. I agree that the naming change would be confusing to beginners. Maybe just the documentation could be updated? Is it documented outside of the wiki (https://github.com/processing/p5.js/wiki/Optimizing-p5.js-Code-for-Performance#disable-the-friendly-error-system)?

**Comment by lmccart** [comment]
Thanks, I've updated the documentation in the wiki and in the developer docs.
