### ISSUE TITLE
reference docs out of date

### ISSUE THREAD

**Issue by Spongman** [processing/p5.js#3190]
the docs @ https://p5js.org/reference/ are currently the ~~0.7.1~~ 0.6.1 😲  docs, whereas the library that it uses, and the download lins are 0.7.2.

i wonder if there's a way to automate pushing the docs simultaneously with the library? also, maybe there's a way to include the release version in the footer of the docs pages?

**Comment by limzykenneth** [comment]
I thought the release task already automatically updates the docs as well?

+1 for the release version in the docs page.

**Comment by Zalastax** [comment]
https://github.com/processing/p5.js-website/pull/260 shows how the release version can be included in the docs - it just needs a design!

This happened in the last release as well, see https://github.com/processing/p5.js/issues/3164 and https://github.com/processing/p5.js-website/pull/254#issuecomment-416065295.

**Comment by Spongman** [comment]
i'm reasonably sure the docs are out of date as described.

compare https://p5js.org/reference/#/p5/text
with https://github.com/processing/p5.js/releases/download/0.7.2/p5.js, line 69969

**Comment by Spongman** [comment]
actually, i think it's worse than i originally guessed. 

it looks like the docs are actually still the `0.6.1` docs.

from `https://p5js.org/reference/data.min.json`:
```json
{
  "project": {
    "name": "p5",
    "description": "...",
    "version": "0.6.1",
  },
```

**Comment by limzykenneth** [comment]
Right didn't expect it to be a version that old which confuses me before. I'll have a look at what went wrong here.

**Comment by limzykenneth** [comment]
From what I find it probably have something to do work my previous work on simplifying the docs build process, as it stopped updating since then. However, I'm not sure where in the process it went wrong.

The first step is to generate data.json with yuidoc which the build steps still do fine and generate the latest from source, the generated files however are not committed (`docs/reference`). Next, after the files are generated they are copied over to the website repo with the command defined here: https://github.com/processing/p5.js/blob/master/tasks/release/release-docs.js#L41

Then over on the website repo, Assemble will assemble everything, including the docs files which should have been copied over to https://github.com/processing/p5.js-website/tree/master/src/templates/pages/reference and populate the final build but the latest version was not copied over to the website repo for some reason. I suspect it's something wrong with this file: https://github.com/processing/p5.js/blob/master/tasks/release/release-docs.js
