### ISSUE TITLE
Include info on options for p5.Font.textBounds()

### ISSUE THREAD

**Issue by dhowe** [processing/p5.js#3251]
1. Include what font-size is chosen if no argument is supplied
2. Include info on the optional 'opentype options' argument

**Comment by vipulrawat** [comment]
`textBounds(line, x, y, [fontSize], [options])`

I was trying to pass `options` explicitly but couldn't find any solution. Every time it is taking the parent element's properties (i.e. default 'left' and 'alphabetic'). I have tried several solutions even mocking the `this.parent` but the only thing that worked is changing the LEFT in `core/constants.js` to 'center' instead of 'left'.
I am not sure of this behavior, maybe I am missing some crucial point while rendering the text. What could be the possible solution to pass options that includes alignment and baseline explicitly.

code to `textBounds()` : [https://github.com/processing/p5.js/blob/master/src/typography/p5.Font.js#L47](url)

**Comment by lmccart** [comment]
@dhowe can you provide any helpful info here?

**Comment by dhowe** [comment]
p5.Font.textBounds() use the metrics from the p5.Font, but inherits the font size (unless specified as 4th arg) and alignment of the _current context,_ as set by textAlign(),  textSize(), etc. 

The options object (for all p5.Font functions)  is simply passed on to opentype, and is present primarily for future uses. There are relevant opentype options  for p5.Font.textToPoints(), but not for textBounds() at this point. So the documentation for that argument should probably be removed...

**Comment by vipulrawat** [comment]
I am closing this as default font size is added now and some reference is put in the docs about OpenType options.
