### ISSUE TITLE
webgl: setAttributes() breaks resizeCanvas aspect

### ISSUE THREAD

**Issue by Spongman** [processing/p5.js#3265]
new in 0.7.2 (doesn't repro in 0.7.1)

- https://codepen.io/Spongman/pen/KGmNrB?editors=1010
- resize the window
- notice the circle is stretched

calling `setAttributes()` causes `resizeCanvas()` to *not* set the aspect ratio of the canvas correctly.

```javascript
function setup() {
  createCanvas(windowWidth, windowHeight, WEBGL);
  setAttributes('foobar', true);
}

function windowResized() {
  resizeCanvas(windowWidth, windowHeight);
}

function draw() {
  background(0);
  ellipse(0, 0, width/4);
}
```

**Comment by sanketsingh24** [comment]
Hey! I would like to take up this issue!

**Comment by sanketsingh24** [comment]
After some debugging, I think the problem is with `push() `and `pop()` used in `setattributes()`.  [`push()` in `RendererGL` module saves the `_curCamera` properties ](https://github.com/processing/p5.js/blob/master/src/webgl/p5.RendererGL.js#L785)and persists with them even after `resizeCanvas()` changes them. 

I think this was not reproducible in 0.7.1 because `_computeCameraDefaultSettings()` and `_setDefaultCamera()` are moved to a different file now.

**Comment by sanketsingh24** [comment]
Used the following example to debug:

function setup() {
  createCanvas(100, 100, WEBGL);
  setAttributes('foobar', true);
}

```js
function mouseClicked() {
  resizeCanvas(200, 300);
}
function mouseWheel() {
  resizeCanvas(100, 200);
}
function draw() {
  background(0);
  ellipse(0, 0, width/2);
}
```

https://codepen.io/sanketsingh24/pen/aPKRGK

**Comment by Spongman** [comment]
godo catch. it looks like `resizeCanvas` needs to force an update to the camera.

i wonder how this should work if a non-default camera is configured?

**Comment by sanketsingh24** [comment]
@Spongman One of the solution I can presently think of is that changing `pop()` to update only when camera type is `custom`, and bypass when cameraType is `default`. What are your thoughts on this?

**Comment by Spongman** [comment]
that might work, but i'm worried that it might affect the way `pop` works in other circumstances. can you explain the mechanism by which the `push`/`pop` calls cause the canvas to be sized incorrectly?

**Comment by Spongman** [comment]
i think the real cause here is that the camera has a `_renderer` property that's getting out of sync.

if you hit a breakpoint on the first line of `p5.prototype.resizeCanvas()`, then you'll see that `this._renderer._curCamera._renderer === this._renderer` is `false`.

**Comment by sanketsingh24** [comment]
Oh yes, totally missed that my solution can break alot of things, my bad. 

According to me, the `viewport` is updating, but the `aspectRatio` and other properties inside `_curCamera` are not updating, because the whole `_curCamera` is pushed and when `resizeCanvas` is called, `_curCamera` doesn't update and gets out of sync, as you correctly noted.

I think we need to place the invariant in `resize()` rather than after `pop()` because the invariancy rises after `resizeCanvas()` is called, and in this way we will be able to calculate the _curCamera too.

**Comment by sanketsingh24** [comment]
What I think is happening

-  `createCanvas` is called, which forms p5 instance's renderer as `renderer1`, and has `camera1` as its `_curCamera`.
-  `setattributes` is called, where `push()` is present, which pushes `camera1` to `properties`.
-  Now, `resizeCanvas` is called, which forms a new `renderer2` with different width, height and other  properties. 
-  Now `_resize` in `p5.camera` is called which somehow (i have no idea here) receives `renderer1` and doesn't update camera (as the camera  for `renderer1` is `camera1`).

Now some of my observations - 

1.  [Both `push()` and `pop()` calls are present in `setattributes`,](https://github.com/processing/p5.js/blob/master/src/webgl/p5.RendererGL.js#L365) which is called just once at the start of the sketch as `setattrubutes` is present in `setup()`.
2.  [`this._renderer`](https://github.com/processing/p5.js/blob/master/src/webgl/p5.Camera.js#L894) in `p5.Camera.prototype._resize`, which is called [here](https://github.com/processing/p5.js/blob/master/src/webgl/p5.RendererGL.js#L692), somehow receives `renderer1`. This function is responsible for updating `_curCamera`, when `resizeCanvas` is called.
3.  Bug is not observed when [this line](https://github.com/processing/p5.js/blob/master/src/webgl/p5.RendererGL.js#L785) is commented out in `push()`, or the `pop()` in `setattributes`.
4.  Bug is also not observed when `  this._curCamera._renderer = this;` is placed [here](https://github.com/processing/p5.js/blob/master/src/webgl/p5.RendererGL.js#L691).

**Comment by sanketsingh24** [comment]
Yes, I also think that, if we implement the fix in `resize` it might break the whole thing. I also think the same, fix needs to be in `setattributes`.

**Comment by Spongman** [comment]
I think we want to do the `push`/`pop` dance every time, since it’s creating a brand new canvas & 3d context and we want to make sure all the properties are copied across. This isn’t just to preserve the camera state.

**Comment by sanketsingh24** [comment]
Sorry for mistyping, I just read what I wrote and I didn't phrase it clearly :sweat_smile:.

Some possible fixes - 
1.  I meant that we can `push` the `_curCamera` only when `cameraType` is `custom`, because when `cameraType` is `default`, we compute it again [here from scratch](https://github.com/processing/p5.js/blob/master/src/webgl/p5.Camera.js#L931).

2.  I think when `resizeCanvas()` is called, we update `this._renderer` but we never update `this._renderer._curCamera._renderer`, which is infact used to compute the camera again. We can update that and then call `_curCamera._resize`

**Comment by sanketsingh24** [comment]
@Spongman Please review.
