### ISSUE TITLE
call back of createVideo does not return properly

### ISSUE THREAD

**Issue by INT-ZC** [processing/p5.js#3285]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [x] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 0.7.2 
- Web browser and version: Chrome 72.0.3588.0
- Operating System: Windows 10 181012-1414
- Steps to reproduce this: 

video = createVideo('assets/video.mp4', fileLoad('video'));
Crate a video like above, the function fileLoad was called when the video isn't ready to play yet.

**Comment by lmccart** [comment]
In this case, you just need to pass the name of the callback function.
`video = createVideo('assets/video.mp4', fileLoad);`
If you write the full function call, it will get called immediately instead of waiting. If you are trying to call the function with a specific argument, you can wrap it in a function definition like this:
`video = createVideo('assets/video.mp4', function() { fileLoad; });`
