### ISSUE TITLE
all-contributors commands/scripts not working

### ISSUE THREAD

**Issue by justinsunho** [processing/p5.js#3335]
#### Nature of issue?

- [x ] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?
- [x ] Other (all-contributors docs)

#### Details about the bug: 

- Steps to reproduce this:

Running `all-contributors` outputs: `command not found` unless you globally install `all-contributors-cli`. 

Likewise running `npm run contributors:add` and `contributors:generate` doesn't work.

`npm run contributors:add -- (username) (contribution types)` outputs `Cannot read property 'then' of null`

`npm run contributors:generate` works, but it wipes the `README.md` of the table. 

I've deleted `node_modules` multiple times, used node versions 8.11.1 and 9.9.0 (npm version 5.6.0 for both). I don't believe its an issue with `all-contributors-cli` since `npm run contributors:generate` still runs. It would be nice to see if this issue is reproducible so we can tell if the fault is in `p5.js` or `all-contributors-cli`.

#### Feature enhancement details:
Reconfigure `all-contributors-cli` so that adding contributors is done so easily through the command line.

**Comment by lmccart** [comment]
I periodically just run `all-contributors` on my end where I have it globally installed. Is this sufficient? Or do you know of a way to configure things so anyone can run it?

**Comment by sanketsingh24** [comment]
I think this can be easily fixed by executing directly from bin, or changing [these lines to](https://github.com/processing/p5.js/blob/master/package.json#L13)

```json
"contributors:add": "./node_modules/.bin/all-contributors add",
"contributors:generate": "./node_modules/.bin/all-contributors generate",
"generate": "./node_modules/.bin/all-contributors generate",
```

As `all-contributors` is already present in `package.json` as so is present in everybody's node_modules, and the users don't need to install globally and @lmccart doesn't need to run it every time.

**Comment by meiamsome** [comment]
@sanketsingh24 As far as I can tell this issue is not an issue with the `package.json` command setup. It looks correct to me and the `npm run contributors:add` and `npm run contributors:generate` work fine for me in current master without a global install of `all-contributors`

**Comment by sanketsingh24** [comment]
Ok, I was not able to run `npm run contributors:add`, but when I added the bin path in `package.json`, I was expectedly able to run. Also, I have seen some repos using bin just so that the user does not have to install those dependencies globally, so I thought it was this error.  Anyways, just my opinion.

**Comment by meiamsome** [comment]
@sanketsingh24 Ah, interesting - I wonder if you are on Windows? Do you have issues with any other of the  `npm run` commands where you don't have the command it runs available globally (like `npm run precommit` perhaps)?

**Comment by sanketsingh24** [comment]
Ok, I found out that I have not updated my npm for a very long time,  sorry for that :disappointed: also, i had grunt and eslint globally installed so others did not get affected
