### ISSUE TITLE
WEBGL GL_OES_standard_derivatives not supported

### ISSUE THREAD

**Issue by letoast** [processing/p5.js#3351]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [x] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

official Web Editor
Google Chrome | 70.0.3538.102 (Official Build) (64-bit)
Windows 10

using #extension GL_OES_standard_derivatives : enable
in shader files throws:
"Darn! An error occurred compiling the fragment shader:WARNING: 0:1: 'GL_OES_standard_derivatives' : extension is not supported"

I don't understand why standard derivatives wouldn't be supported for all features, though, since I see that it explicitly enables it only for the Font shader... Makes no sense - derivatives are used all over in modern shaders...

**Comment by Spongman** [comment]
Very strange. Do you have a  link to a sketch that repros this? Maybe it’s a video driver issue?

**Comment by Spongman** [comment]
Ah yes that makes sense. You _do_ have to call getExtension for it to be usable.

I’m not sure about the vertex shader, doesn’t that extension only made sense for fragments?

**Comment by dghez** [comment]
Having the same issue here, on V2: https://editor.p5js.org/dghez/sketches/UdsFTpFvR
@moritzsalla

**Comment by davepagurek** [comment]
It uses webgl 2 by default so you don't need to enable an extension, you can just use `fwidth` 🙂 If you do need to use webgl1 + extensions, call `setAttributes({ version: 1 })` (see https://beta.p5js.org/reference/p5/setattributes/ for details) to force it.

**Comment by dghez** [comment]
@davepagurek thanks but it still yells at us that is not available even if it's webgl2.
Neither `dFdx, dFdy` are available

Am i missing something? 

SANDBOX: https://editor.p5js.org/dghez/sketches/UdsFTpFvR

<img width="1282" height="678" alt="Image" src="https://github.com/user-attachments/assets/e57b34bc-8df3-4177-85c4-a978410e8545" />

**Comment by davepagurek** [comment]
Here's a version that works: https://editor.p5js.org/davepagurek/sketches/VTbwsmSsP

<img width="1258" height="678" alt="Image" src="https://github.com/user-attachments/assets/4c024f2a-df14-46c6-8c0f-d8f6c58239b5" />

The main difference is that you have to use `#version 300 es` instead of the default version (100), which is the one that needs extensions. So, WebGL 2 does not support those extensions and has built-in support for derivatives, but requires you to use version 300.

I also took out some of the `drawingContext` bits of that sketch because alpha and premultiplied alpha are turned on by default now, and the blend modes are already set up to use that.
