### ISSUE TITLE
Video Element Do not refresh when using video.get()

### ISSUE THREAD

**Issue by Leiyufazhuangjia** [processing/p5.js#3359]
#### Nature of issue?

- [ x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [x ] Other Capture dom element 
#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [ x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 
- Web browser and version: chrome 70.0.3538.110
- Operating System: 
- Steps to reproduce this:windows10

I just try to Reproduce this coding train lesson:
https://editor.p5js.org/leiyufazhuangjia/sketches/rJdRvpQkV
But it seems that the Video Element Do not refresh automatically,the particals always just get the color of the first frame of the video element, is it a bug?

**Comment by Ajayneethikannan** [comment]
Hey @Leiyufazhuangjia ! I cloned your code and tried to fix it , this is what I got:<br/>
You forgot to call the background() method in the draw function , which is used to clear the display window at the beginning of every frame. Since it was not used, the ellipses created in the first frame were never removed and it appeared as if the video was stuck. <br/>
Link to the cloned sketch:  https://editor.p5js.org/TheSkepticSniper/sketches/rkOe19QMV<br/>
Also @Leiyufazhuangjia  , since this issue is related to how to do something with the library, rather than a bug in, or an issue with the library itself, <br/>
I would refer you the community through the **processing forum**:  https://discourse.processing.org/c/p5js.
<br/>
I request the author or the maintainers to please close this issue, if you consider it to be solved.

**Comment by Ajayneethikannan** [comment]
Hi @Leiyufazhuangjia ! I remember earlier that this sketch does not work if you do not call background method. It was by luck the sketch started working when background function was called,  I tried to find out what the bug was, and after a long time , I have finally found the issue.

Even though calling the background method seems to be enough to make the sketch functional, it is hiding a pretty big bug under the hood.

When **video.get(x, y, w, h)** is called, 
  it internally calls the **loadPixels** method of the **p5.MediaElement** instance wrapping the video object, seen by
**p5.MediaElement.prototype.get method:**
``` p5.MediaElement.prototype.get = function(x, y, w, h) {
    if (this.loadedmetadata) {
      // wait for metadata
      var currentTime = this.elt.currentTime;
      if (this._pixelsTime !== currentTime) {
        this.loadPixels();
      } else {
        this._ensureCanvas();
      }
```

followed by calling **p5.MediaElement.prototype.loadPixels()** , which creates a canvas for the video element and draws the frame on the canvas. 

**p5.MediaElement.prototype.loadPixels method:** 
```
if (this._pixelsDirty || this._pixelsTime !== currentTime) {
        // only update the pixels array if it's dirty, or
        // if the video time has changed.
        this._pixelsTime = currentTime;
        this._pixelsDirty = true;

        this.drawingContext.drawImage(
          this.elt,
          0,
          0,
          this.canvas.width,
          this.canvas.height
        );
      //drawing the video frame to new hidden canvas. 
        p5.Renderer2D.prototype.loadPixels.call(this);
      }
```

which in turn calls **Renderer2D.prototype.loadPixels** method, where the problem starts.

**p5.Renderer2D.prototype.loadPixels**
```
p5.Renderer2D.prototype.loadPixels = function() {
var ctx = this._pInst || this; //here ctx refers to _pInst. this refers to the mediaElement
  if (!ctx._pixelsDirty) return;
  ctx._pixelsDirty = false;
  var pd = ctx._pixelDensity;
  var w = this.width * pd;
  var h = this.height * pd;
  var imageData = this.drawingContext.getImageData(0, 0, w, h);
  // @todo this should actually set pixels per object, so diff buffers can
  // have diff pixel arrays.
  ctx._setProperty('imageData', imageData);
  ctx._setProperty('pixels', imageData.data);
};
```

here, the **ctx** refers to the **_pInst** (p5 instance) and **this** refers to **MediaElement**, which has its separate drawingContext. So when this method is called , the **global pixels** array is manipulated wrongly, due to different references in different parts of the code. 

After this , we return to the **p5.MediaElement.prototype.get** function, 
where it returns the value by passing the MediaElement instance to p5.Renderer2D.prototype.get method,
**p5.MediaElement.prototype.get method:**
```
   return p5.Renderer2D.prototype.get.call(this, x, y, w, h);
```

**p5.Renderer2D.prototype.get method**
  var ctx = this._pInst || this;
  var pd = ctx._pixelDensity;

  var sx = x * pd;
  var sy = y * pd;
  if (w === 1 && h === 1) {
    var imageData, index;
    if (ctx._pixelsDirty) {
      imageData = this.drawingContext.getImageData(sx, sy, 1, 1).data;
      index = 0;
    } else {
      imageData = ctx.pixels;
      index = (sx + sy * this.width * pd) * 4;
    }
    return [
      imageData[index + 0],
      imageData[index + 1],
      imageData[index + 2],
      imageData[index + 3]
    ];
  } 

Here ctx refers to _pInst again, and pixelsDirty value is false here if we have called loadPixels function,
so it will go to second part and get the first frame's pixel data alone, stored in global pixels array.

From what I understand, video.get currently messes with the global pixels array and it causes it to be stuck in the first frame as it is loaded only once into the global pixels array.

@Leiyufazhuangjia  Maybe the issue name can be changed to 
"video.get does not work without calling background method", if you see it fit.

Some doubts about the issue:

1. What is the exact use of _pixelsDirty variable ?
2. From my understanding , we are using p5.Renderer2D.prototype.loadPixels method to create p5.Image, objects, so it should refer to pixels array of  MediaElement instance.

3.The main problem seems to be with **defining the ctx variable** in each function .Since the syntax to get the instance (ctx) is the same throughout the codebase, it would be really helpful if someone can clarify my doubts regarding the issue, and the changes to be brought , before solving it. 

PS:  I am really sorry for the size of the message , I could not figure out how to bring the issue in some other way.

Need help please !

**Comment by meiamsome** [comment]
@Ajayneethikannan Nice analysis, looks like this is the same bug that is fixed in #3504 then?

**Comment by Ajayneethikannan** [comment]
Oh yes ! I will try to help there, thank you for referring to the PR  !

**Comment by limzykenneth** [comment]
@Ajayneethikannan `_pixelsDirty` is an optimization to make `get()` faster. Have a look at #2832 and #2833 for some context.

**Comment by Ajayneethikannan** [comment]
Got it , Thank you @limzykenneth !
