### ISSUE TITLE
print() function opens print dialog if you don't pass any parameters.

### ISSUE THREAD

**Issue by lminsky** [processing/p5.js#3362]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [x] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: v0.7.2
- Web browser and version: Google Chrome	70.0.3538.110 (Official Build) (64-bit)
- Operating System: MacOS Mojave Version 10.14
- Steps to reproduce this:
Calling the print() function without any parameters will open the print dialog. If you put it in the draw loop it will keep opening print dialogs until you close the page. It seems like the p5 print should overload the native print function whenever it can.

Here's an example: https://editor.p5js.org/lminsky/sketches/SkdYYI_1V

**Comment by lmccart** [comment]
I'm sorry, I think there was some confusion in our conversation. This is by design, so as not to block the browser native [print method](https://developer.mozilla.org/en-US/docs/Web/API/Window/print). If there's a problem with the auto-refresh in the web editor calling the function too soon, that issue can be posted over there.
