### ISSUE TITLE
Move away from browserify?

### ISSUE THREAD

**Issue by outofambit** [processing/p5.js#3425]
While working on #3385, (and from discussions in #3409) I can't help but wonder if this project would be better served by a babel + webpack build process over the current browserify + uglify infrastructure.

I _think_ we can replicate the existing behavior with [babel](https://babeljs.io/), using [babel-preset-env](https://babeljs.io/docs/en/babel-preset-env) and [babel-minify](https://github.com/babel/minify), and [webpack](https://webpack.js.org/) to do the bundling.

We might also be able to use something as simple as [rollup](https://github.com/rollup/rollup), though I am less familiar with that tool.

What do y'all think on a migration like this? Are there other tools worth considering?

**Comment by limzykenneth** [comment]
What would be the benefit of moving from browserify to webpack or rollup? What would be the drawbacks, if any?

**Comment by bigmstone** [comment]
**Disclaimer:** I am a `webpack`/`babel` user which artificially inflates my desire to see it in other places. I also help maintain a `gulp`/`browserify` app as part of my day job, and honestly don't have much bad to say about it. It's mainly set it and forget it. We have all the features I would want from a normal `webpack` setup. Including hot reload. Also use `babelify`, so we have access latest language features.

One weak(ish) reason to switch to `webpack` would be mind share and development resources. `webpack` has orders of magnitude more usage based on GH stars (meh) and NPM downloads (less meh). Having more usage will lead towards the usual suspects: trend towards having new features, able to respond quickly to competing features, quick bug discovery & patching, etc.

I just low-key want to help P5 get better ES6/"Instance" support since ES6 actually made me "okay" with JS. So mainly +1 to bringing `babel` into the mix. Either through `webpack` + `babel` or existing build system + `babelify`.

**Comment by Spongman** [comment]
with webpack, how easy is it to run custom build steps? for example, something like the grunt task defined in `eslint-samples.js` ?

BTW: there's an example of a babelified, ES6 version of p5 over here: #3394. still uses grunt, but hey.

**Comment by limzykenneth** [comment]
If there isn't a strong benefit to switch build tool then the effort may not be worth the reward so that's why I'm asking. 

Out of curiosity, because I haven't have a project that uses webpack or rollup but I want to try, how do they integrate with test runner like mocha or linters like eslint? Do they run with plugins on top or are they completely seperate, ie run with two shell commands (or one npm script with something like `&&`)?

**Comment by limzykenneth** [comment]
When I was looking through the dependencies to find obsolete ones `derequire` do stuck out as something I don't understand why it is there (still don't, really). I have heard of the complex configuration file of webpack and grunt seems to be comparable in terms of config complexity. Parcel on the other hand was something that I dipped my toe into recently and only gave up because it doesn't support Vue out of the box, however, if Parcel can deliver its promise of zero configuration for our build I think that will be a great improvement, we don't need to write new configurations to migrate over and the build process cannot be simpler. I don't know how Rollup compare to Parcel but I'm prepared to support something that significantly reduce the complexity of the dev setup with minimal effort to migrate.

---

On another note, I've seen Babel being thrown around in these discussion, and maybe I'm not familiar with some aspect of it, what I don't understand is why do we need it? Most of the biggest ES6 features  are already supported by all major browsers for several years and so well covered by our compatibility targets (discounting IE 😞 😠 ) so I assume the aim is not to transpile to ES5? 

Then if I'm not missing anything else Babel will then be used to transpile features not yet widely implemented by browsers to something current browsers can run, in this case I would be more wary. I see the source code of p5.js as a learning resource for everyone including beginners as well but if we include code that doesn't run in the user's environment out of the box when they copied it, it becomes a source of confusion and another barrier to entry because now they need to know about Babel before continuing.

**Comment by bigmstone** [comment]
> what I don't understand is why do we need it?
There are commonly used features that haven't been fully standardized yet. [Field declarations](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes#Field_declarations) being one. Now that the industry seems to have centered around `babel` this will likely be a "norm" for the foreseeable future as the language evolves. It's also easy to get language feature support for lots of browsers with little effort without needing to manually check against your supported browser list. You just build to what `babel` supports and sleep well.

> in this case I would be more wary. I see the source code of p5.js as a learning resource for everyone including beginners as well but if we include code that doesn't run in the user's environment out of the box when they copied it, it becomes a source of confusion and another barrier to entry because now they need to know about Babel before continuing.

I can see your point, but we can all admit javascript has historically been fractured. Take your pick: dependency management, build tooling, framework flavor of the week (I'm looking at you jquery, angular, react, vue), browser support circus. So I can appreciate what the popularity of `webpack`/`babel` has brought to the JS community. Namely removing the browser circus. Sadly we're still fighting a few of those (node/yarn, vue/react).

Rereading that comment I think you _might_ not be talking about beginners working on the library (which 1. would likely not be realistic and 2. babel would be "abstract" from them by the build process), but rather consumption of the library. My assumption with ES6+ support w/ `babel` is the library would still ship a transpiled distribution. So a beginner can use P5 as they always have.

**Comment by lmccart** [comment]
I don't currently have a strong opinion here, I need to do some more research into the different options before I can weigh in more substantively. But I'm excited about exploring possibilities for improving the build system. One note @bigmstone, it is indeed a goal that beginner programmers find the p5.js ecosystem friendly enough to make contributions. This is different than a lot of software projects, and requires us to make certain decisions privileging readability over more software heavy lifting. (Sidenote: this makes me realize that the list of goals we hashed out in a meeting last spring never made it to the github, so I need to work on getting this up there! Currently, there's not any way to know the extent to which we aim to make this beginner accessible.)

**Comment by outofambit** [comment]
There's a lot of other things we could have babel do, but I think the strongest case for babel in p5js is to ensure backward compatibility with older browser versions (or ones that are the minority in not supporting an ES syntax/feature) using [babel-preset-env](https://babeljs.io/docs/en/babel-preset-env).

Supporting a [range of browsers](https://github.com/processing/p5.js/blob/master/developer_docs/supported_browsers.md#our-stated-goal) is much easier with [babel-preset-env](https://babeljs.io/docs/en/babel-preset-env). When added to your build process, it will polyfill and transpile your javascript to work on [the browser versions listed in a configuration file](https://babeljs.io/docs/en/babel-preset-env#targets) (which we maintain as part of our repo). It's super cool and would allow us to embrace whatever features of es6+ we find appropriate without limiting the library's (browser) reach.

-----

On the topic of build processes and readability: I did a quick proof of concept in #3429 to explore what using `rollup` might look like. There's still a couple details that need to be worked out, but I think the core is there? I find removing the need for a separate uglify and derequire step is pretty compelling (simpler and easier to follow), but I would love to hear what others think! 💭 

(Also, the promise chain at the end is a little wonky. That could be cleaned up with async/await but I don't think grunt supports promises, so we could just separate the `.then`'s out instead of chaining them all at once like I did.)

**Comment by hydrosquall** [comment]
One key benefit of `rollup` over parcel that I haven't seen mentioned in this discussion yet is that because of techniques like `tree-shaking`, it has the potential to grant significantly (10x) faster build times + smaller bundle sizes.

https://x-team.com/blog/rollup-webpack-parcel-comparison/

**Comment by limzykenneth** [comment]
@hydrosquall Pacel also has [tree shaking support](https://parceljs.org/cli.html#enable-experimental-scope-hoisting/tree-shaking-support) albeit experimental still, and Parcel also caches builds so according to them provides even faster builds, not sure how it compares for us though.

**Comment by coreygo** [comment]
I've too have been trying to reduce the size of p5 as much as possible for a single sketch which uses very few of the features in p5 and am limited by the current build process.

I'm also having a separate issue using p5 and [Gatsby](https://www.gatsbyjs.org/docs/debugging-html-builds/) together. I've tried various workarounds as part of the debug process but no such luck in my case… @aendrew has also mentioned this in #2244 and #2503—with additional general discussion in #522.

It seems using rollup, webpack, or parcel would help.

I thought maybe if I tried `npm run grunt combineModules:core/shape:color:math:image` that would do the trick but the generated `p5Custom.js` is _larger_ than the complete `p5.min.js`. 😕

The current grunt task for combineModules doesn't also create a [p5Custom.min.js](https://github.com/processing/p5.js/blob/2981ec4cdbdc0ff4102dca9eec4e299cd43d15e5/Gruntfile.js#L274-L292) using uglify like the normal grunt build task. 😉

**Comment by lmccart** [comment]
@coreygo have you tried this? https://github.com/processing/p5.js/blob/master/developer_docs/custom_p5_build.md

**Comment by coreygo** [comment]
@lmccart yep… 😃 I was actually about to update that doc since it's not currently accurate.

* `grunt` fails, it should be `npm run grunt combineModules`
* `core/shape*` isn't included as part of core by default — so 2d_primitives like line() won't work
* `npm run grunt` is a missing step after `npm install`, without that step running `npm run grunt combineModules` fails with `Fatal error: Cannot find module '../../docs/reference/data.json' from '~/Projects/p5.js/src/core'`

**Comment by outofambit** [comment]
hey all, https://github.com/processing/p5.js/pull/3431 is ready for review as a first step to simplifying the build process with parcel!

**Comment by lmccart** [comment]
As discussed in https://github.com/processing/p5.js/pull/3431, we've explored the options and unfortunately none of them provide what we need right now. parcel seemed like the best fit, but because of transpiling limitations it doesn't suit our purposes. I'm closing this for organization, we can revisit in the future as the state of the web evolves :) Thanks all for the discussion and @outofambit for investigating the parcel solution and other alternatives.
