### ISSUE TITLE
I NEED HELP

### ISSUE THREAD

**Issue by Blingboy740** [processing/p5.js#3492]
I have the complete library installed and after trying to run this code:

let names;

function preload(){
  names = loadStrings("names.txt");

}
function setup() {
  createCanvas(windowWidth,windowHeight);
  console.log(names);
}

function draw() {

}

i get this error : 
p5.min.js:3 Fetch API cannot load file:///C:/Users/Bogdan%20Cuciureanu/Desktop/p5/empty-example/names.txt. URL scheme must be "http" or "https" for CORS request.
v.httpDo @ p5.min.js:3
2p5.min.js:3 Uncaught (in promise) TypeError: Failed to fetch
    at m.v.httpDo (p5.min.js:3)
    at m.v.loadStrings (p5.min.js:3)
    at m.<anonymous> (p5.min.js:3)
    at preload (sketch.js:4)
    at m.<anonymous> (p5.min.js:3)
    at new m (p5.min.js:3)
    at n (p5.min.js:3)

WHAT DOES THIS MEAN?

**Comment by hellonearthis** [comment]
It's a security feature with Chrome that protects users by forcing file access to be via https.
Solutions : 
use a server with https like xamp
Use vscode live server with it configured to https 
Use Firefox (I think it doesn't have this issue) 
Use the P5 Web editor

**Comment by limzykenneth** [comment]
Hi @Blingboy740, in the web environment if you want to load in external files (ie. something like `loadStrings`) you need to serve your webpage with a web server (remote or local). Have a look at [this page](https://github.com/processing/p5.js/wiki/Local-server) for some options for running a local web server. Otherwise you can use the [web editor](https://editor.p5js.org/) to run your code which doesn't require any additional setup on your side.

**Comment by Heinrichxiao** [comment]
I also got this same error just using loadImage
