### ISSUE TITLE
Doubt: Filter function in pixels.js

### ISSUE THREAD

**Issue by Ajayneethikannan** [processing/p5.js#3522]
#### Nature of issue?

- [x] Existing feature enhancement

#### Most appropriate sub-area of p5.js?

- [x] Image

#### Which platform were you using when you encountered this?

- [x] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop

#### Details about the bug: 

- p5.js version: 0.7.3 
- Web browser and version: Google Chrome 64 bit 72.0.3626.96 
- Operating System: Ubuntu 16.04  
- Steps to reproduce this:

This example can be used as reference  : 
https://p5js.org/examples/dom-video-capture.html 

Since we have separate constants defined for the filter function, I have a doubt regarding the use of String.toLowerCase inside the filter function's implementation , as seen here 
https://github.com/processing/p5.js/blob/master/src/image/pixels.js#L409 
My opinion is that here we are hardcoding the filter parameters in the codebase, and negating the use of constants . 

Should the code be changed so that it uses only the predefined constants ? 
I will close this issue , once the doubt is cleared.

Thank you!

**Comment by stalgiag** [comment]
Hi @Ajayneethikannan good catch! I agree that this seems a bit odd. If you go back in the history it seems that this code has been around a very long time, since before there were constants for the filters. 

`Filters.apply(this.canvas, Filters[operation], value);` works fine. Note that this is also done in [p5.Image](https://github.com/processing/p5.js/blob/master/src/image/p5.Image.js#L660).

**Comment by Ajayneethikannan** [comment]
@stalgiag thank you for suggesting the recommended changes ,
I request you to review them ,
Thank you again !
