### ISSUE TITLE
Additional parameter for position function.

### ISSUE THREAD

**Issue by Ajayneethikannan** [processing/p5.js#3570]
#### Nature of issue?

- [x] Existing feature enhancement

#### Most appropriate sub-area of p5.js?

- [x] Other (specify if possible) DOM

#### Which platform were you using when you encountered this?

- [x] Others (specify if possible) Device Independent

#### Details about the bug: 

- p5.js version:  0.7.3
- Web browser and version:  Browser independent
- Operating System:  OS independent
- Steps to reproduce this:

#### Feature enhancement details:

Currently , the position function works by providing two numbers x and y, 
and the element on which the function was called , has its position changed to x pixels, and y pixels on the web page, and the position style is set as 'Absolute' 

Current syntax : 
```
some_elt.position(10, 10);
```

**Modification :** 
 
It would be nice to have an extra optional parameter , which will allow us to also set the type of the position we want , like this 
```
some_elt.position(10, 10, ABSOLUTE);
```

```
some_elt.position.(10, 10, FIXED); //always relative to current viewport
```
(The default option would be ABSOLUTE)

The use case of the optional property may arise when the element may be present inside another div,
this issue can be considered as an example ,
processing/p5.js-website#394

Would love to hear your thoughts about it,
Thank you !

**Comment by ankur54** [comment]
Hello. Is this issue still open? Is anyone working on this issue? I would love to work on it if possible. Thank you

**Comment by limzykenneth** [comment]
@ankur54 As with most feature requests, we need to have some concensus on whether to include the feature in the library first or not, from the community and mainly from the maintainers of the project. So until that concensus is reached I would not suggest working on the implementation in the source code yet.

If you think this feature is worth including, you can indicate so in this issue. And if you are keen an outline of how it may be implemented.

**Comment by lmccart** [comment]
thanks for the suggestion @Ajayneethikannan. I just want to be careful here with the scope of p5.dom. the general approach is that it provides a good entry point to thinking about the dom. if a user requires significant control beyond that, a library like jquery or other JS dom library may be more appropriate. the idea being that we don't want to reinvent the wheel when there are already good solutions out there. so this particular feature strikes me as going a level of detail further than most of the p5.dom library. but I would like to hear what others think.

**Comment by Ajayneethikannan** [comment]
I agree @lmccart . Thank you for considering the suggestion !

**Comment by limzykenneth** [comment]
At first glance this functionality can be achieved rather straightforwardly with `style()` and I figure in both cases a basic understanding of CSS would probably be required (understanding what `absolute`, `relative`, `fixed`, etc means).

Personally I like to keep styling in CSS and not do any styling stuff in JS but that's because I can, so I would like to know about the perspective of someone with some experience in p5.js but not so much CSS yet.

**Comment by Ajayneethikannan** [comment]
I completely agree to your point @limzykenneth .
The **style** function documentation says if 'position' is passed as the first argument , then it shall take numbers as the 2nd and 3rd arguments.Though this is added functionality, it leads to confusion.  I think this documentation can be improved and point more towards styling position in CSS, like setting absolute , relative ,etc. while the **position** function can be used for passing numbers as arguments. 
In my opinion , preventing style() from calling position()  internally, would remove the dependency between the two. 
Would love to hear your opinion on this !

**Comment by limzykenneth** [comment]
> In my opinion , preventing style() from calling position() internally, would remove the dependency between the two.

That's what I'm pushing for in #3447 and #3448, that `style()` should not be calling `position()` and deal with CSS exclusively.

**Comment by nebbles** [comment]
Given the updated status of #3447 and `style()` no longer calling `position()` I think there is now an onus to support specifying the type of positioning needed. For example, `'fixed'` may commonly be used to keep a P5 canvas filling the background of the webpage, rather than remaining anchored to the top right. Integration would provide a user-friendly and still intuitive way to improve positioning of elements (especially canvases).

So I'd suggest a third optional parameter for `position()` which allows passing of a string related to the CSS position type e.g. `position(0, 0, 'fixed')` as mentioned above by @Ajayneethikannan
