### ISSUE TITLE
webgl: 'mixedMode' manual calls `normalMaterial` incorrectly

### ISSUE THREAD

**Issue by Spongman** [processing/p5.js#3575]
`normalMaterial()` doesn't take these parameters:
https://github.com/processing/p5.js/blob/b2d1abce3ab5ebdeeb93558645405072521eaa13/test/manual-test-examples/webgl/mixedMode/sketch.js#L16

**Comment by stalgiag** [comment]
To do: fix the call to `normalMaterial` in [mixedMode](https://github.com/processing/p5.js/blob/master/test/manual-test-examples/webgl/mixedMode/sketch.js) to follow the [current proper usage](https://p5js.org/reference/#/p5/normalMaterial). (hint: no arguments)

**Comment by EOstling** [comment]
Has anybody claimed this? If not I would like to take this issue.

**Comment by stalgiag** [comment]
great! go for it @EOstling !

**Comment by Janglee123** [comment]
@EOstling if you not started yet I would also like to work on this. :smile:

**Comment by ashwathbhat** [comment]
#3587 resolves the issue.
Thank you

**Comment by stalgiag** [comment]
@Janglee123 If you are still interested this issue is accepting new pull requests again. Just to clarify, the only thing that should be done here is the removal of the arguments for `normalMaterial()` in this [manual test example.](https://github.com/processing/p5.js/blob/master/test/manual-test-examples/webgl/mixedMode/sketch.js#L16)

**Comment by ashwathbhat** [comment]
@stalgiag Can I work on this? I already had a PR for this issue.

**Comment by stalgiag** [comment]
Yep go for it @ashwathbhat !

**Comment by ashwathbhat** [comment]
@stalgiag #3660 fixes this issue.
