### ISSUE TITLE
Stroke rounding inconsistency

### ISSUE THREAD

**Issue by Whitevinyl** [processing/p5.js#3576]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [x] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 0.7.3
- Web browser: Chrome, Firefox & Safari
- Operating System: MacOSX
- Steps to reproduce this:

When drawing different types of 2d shape (rect, triangle, quad, ellipse) adjacent to each other, their fills will line up consistently, but their strokes are misaligned.

![image](https://user-images.githubusercontent.com/6706406/53903989-ed011f80-403c-11e9-986d-c1f97e84b7fa.png)

![image](https://user-images.githubusercontent.com/6706406/53903957-dbb81300-403c-11e9-8e50-d48b3ad412f9.png)

This sketch demonstrates it (try commenting out the noStroke() and fill() lines):
https://editor.p5js.org/wvnl/sketches/6LZUiLAy0

It looks like rect() rounds up while others are centered.
If I replace rect() with a quad() of the same location/dimensions it lines up consistent with the others.

**Comment by Ajayneethikannan** [comment]
This seems to be because of the optimisation for cleaner stroke lines like this ,
```
  // Translate the line by (0.5, 0.5) to draw a crisp rectangle border
  if (this._doStroke && ctx.lineWidth % 2 === 1) {
    ctx.translate(0.5, 0.5);
  }
.
.
.
.
.
  if (this._doStroke && ctx.lineWidth % 2 === 1) {
    ctx.translate(-0.5, -0.5);
  }
```


which is present in the case of rect,  and line , but not in the case of other shapes such as triangle, and quad. 

If this should suffice as a solution, I am ready to make the changes by adding/removing the optimisation for crisp stroke everywhere . 

Would love to hear more suggestions ,
Thank you !

**Comment by lmccart** [comment]
@Ajayneethikannan this sounds like the right approach, a pull request is welcome!

**Comment by Ajayneethikannan** [comment]
@lmccart 
Should I remove the optimisation code in rect and line ? 
I think since this is beneficial only for vertical and horizontal lines, as well as integer parameter values for rect and line  ( most of the sketches use fractional values also) , and also difficult to control when shapes like ellipse are drawn, this should be removed.
Please correct me if I am wrong.
Thank you !
