### ISSUE TITLE
shifting pushMatrix, popMatrix to legacy.js

### ISSUE THREAD

**Issue by Ajayneethikannan** [processing/p5.js#3589]
#### Nature of issue?

- [x] Existing feature enhancement

#### Most appropriate sub-area of p5.js?

- [x] Core/Environment/Rendering

#### Which platform were you using when you encountered this?

- [x] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [x] Others (specify if possible) Platform Independent

#### Details about the bug: 

- p5.js version:  0.7.3
- Web browser and version:  Browser independent
- Operating System:  OS independent

#### Feature enhancement details:
By #243 , pushMatrix and popMatrix from processing were removed in favour of push and pop.
My doubts are, 
- Should they be shifted to legacy.js .
- Is the feature printMatrix going to be implemented .

Waiting to hear your suggestions ,
Thank you !

**Comment by lmccart** [comment]
@Ajayneethikannan yes, I think these methods should be moved to legacy.js.
no, we are not planning to implement printMatrix() because the underlying canvas does not track the matrix so to implement this method we would have to add our own tracking of the matrix. we would instead like to direct people to libraries like [this one](https://simonsarris.com/a-transformation-class-for-canvas-to-keep-track-of-the-transformation-matrix/)
