### ISSUE TITLE
loadPixels and get only works on first draw

### ISSUE THREAD

**Issue by CarstenHoyer** [processing/p5.js#3669]
loadPixels() and get() only works on first draw. get(1,1) will give me the color at 1,1 - but subsequent get() calls will not update the value. This goes on for around 7 draw() iterations. After that the result from get() is undefined. See example code below.

#### Nature of issue?

- [x ] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [x ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x ] Desktop/Laptop (docker)
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 0.7.3
- Web browser and version: 
Chrome 73.0.3683.86 (Official Build) (64-bit) 
Firefox. Quantum 66.0.2 (64-bit)
- Operating System: Macos Mojave 10.14.2 (18C54)
- Steps to reproduce this:

```
function setup () {
  createCanvas(20, 20)
  background(255);
}

function draw () {
  strokeWeight(5)
  stroke(random() * 255, random() * 255, random() * 255)
  line(0, 0, 5, 5)

  loadPixels()
  let currentPixel = get(1, 1)
  debugger
}`

**Comment by Ajayneethikannan** [comment]
Hey @CarstenHoyer !

This bug was removed as a result of #3519, as the pixelsDirty variable was not being set, when the drawing methods like rect( ), line( ) were called, not allowing the pixels[ ] to update correctly.

Also in present state, you don't have to call loadPixels in order to get( ) the pixel value from the canvas or any image. 
You can refer to this [link](https://p5js.org/reference/#/p5/get) too.
