### ISSUE TITLE
SaveBytes() new feature request

### ISSUE THREAD

**Issue by hellonearthis** [processing/p5.js#3693]
I was trying to save a variable as binary file and found there wasn't an easy way to do that in p5. 
I found some code that did this and was wondering how complex it would be to add to p5.
 Processing has a saveBytes() function

- [x] New feature request

#### Most appropriate sub-area of p5.js?
- [x] IO

#### New feature details:
from stackoverflow  https://stackoverflow.com/a/23451803/45966

```javascript
var sampleBytes = new Int8Array(size_required);
var saveByteArray = (function () {
    var a = document.createElement("a");
    document.body.appendChild(a);
    a.style = "display: none";
    return function (data, name) {
        var blob = new Blob(data, {type: "octet/stream"}),
            url = window.URL.createObjectURL(blob);
            a.href = url;
            a.download = name;
            a.click();
            window.URL.revokeObjectURL(url);
    };
}());

saveByteArray([sampleBytes], 'output_file.bin');
```

**Comment by limzykenneth** [comment]
It's usually pretty unusual for many programming languages, including javascript, to be saving things in binary form, except for binary file format like images and audios. I only know of mongodb and numpy doing this but that's because they are saving in a data format that is meant to be read by them only.

Can you share a bit more about the use case?

**Comment by hellonearthis** [comment]
This would be like processings [saveBytes()](https://processing.org/reference/saveBytes_.html) function. 
I recently converted an file of ascii hex values to ints and saved it using the above to produce a binary file.

**Comment by Spongman** [comment]
p5 already has this (kinda):

````javascript
let bytes = new Uint8Array(...);
let blob = new Blob(bytes, 'application/octet-stream');
downloadFile(blob, 'foo.bin');
````

**Comment by hellonearthis** [comment]
I don't know where the reference to **downloadfile** is.  Is it undocumented?

**Comment by lmccart** [comment]
@hellonearthis we made a decision a while ago to skip saveBytes() just because the overhead to implement it was a lot (at least at the time), and it seemed as @limzykenneth a rather unusual function, especially for beginners to use. we thought skipping this one would allow us to put more energy into supporting other more commonly used functionality.
