### ISSUE TITLE
rect() x value with leading zeros gives wrong position.

### ISSUE THREAD

**Issue by hellonearthis** [processing/p5.js#3716]
Hi,  was just play with rect and when I used the value  rect(052, 12, 52, 54)
it change the x value to 42.    

- [ x] Found a bug

- [x] Other (specify if possible)

Shapes, 2D Primitive

- [x ] Desktop/Laptop

#### Details about the bug: 

- p5.js version: p5 0.7.3
- Web browser and version: Chrome 74.0.3729.108 
- Operating System: Win10
- Steps to reproduce this:
Add a leading zero to a number. like  rect(052, 12, 52, 54)

**Comment by stalgiag** [comment]
I think this is because [JS is interpreting the leading zeros as octal number literals.](https://stackoverflow.com/questions/37003770/why-javascript-treats-a-number-as-octal-if-it-has-a-leading-zero) so it isn't a bug in p5. That said, handling this case and obfuscating this unexpected behavior for people might make sense for the library.

**Comment by hellonearthis** [comment]
Thanks,  I didn't know that..
