### ISSUE TITLE
feature request: PDF export

### ISSUE THREAD

**Issue by liasomething** [processing/p5.js#373]
i was thinking it would be nice to have the possibility to export the canvas as PDF (like in processing).
i have no idea how complicated that is (probably very), but it would be such a nice feature...

**Comment by zenozeng** [comment]
Hey guys, I created a simple module for this: https://github.com/zenozeng/p5.js-pdf

**Comment by liasomething** [comment]
hey zeno, this is AWESOME !!! 
thanks for taking the time to do this !!! :)

i tested the demo, and it works fine in chrome on my mac.

i tried to get the whole tree onto only one page only by leaving out the call to  this.nextPage();, but in this case i am getting about 3 branches on 1 page and not what i thought it should do (the whole tree on one page). 
could you please point out how this could be achieved ?
and again: THANKS so much for this !!!

**Comment by zenozeng** [comment]
The size of a image is calculated based on its width, height and ppi, you
can set a bigger ppi if you want smaller image.

See also: https://zenozeng.github.io/p5.js-pdf/doc/p5.PDF.html

**Comment by zenozeng** [comment]
@liasomething I guess you want something like print as 3*3 (or custom rows*cols)? I will add this feature later today (+8 timezone).

**Comment by liasomething** [comment]
hello zeno, i was more thinking of "not having to think" ;) like in processing: when the window is at a ratio of 4:3 for instance, then the pdf would get exactly the same ratio. and when i start a pdf recording in processing, then it automatically writes everything that is inside the draw function into one page, until i finish the pdf recording. do you think this is doable as well using the size of the canvas as ratio, and just producing one pdf page (maybe optionally?)
+ thanks again for your work !!!

**Comment by zenozeng** [comment]
@liasomething options.columns & options.rows was now added. But I haven't test it yet. It's about 01:30 am now and I have to go to sleep now. (Sorry I didn't finish today's homework until 00:23, and don't have enough time to write code). I will add support for custom margin and imagePadding tomorrow. What's more, auto calculation for columns and rows will be added and will allow writing all images into one page.

**Comment by liasomething** [comment]
this all sounds great! thanks and take care of getting enough sleep !!! :)

**Comment by zenozeng** [comment]
@liasomething Hi, p5.js-pdf@0.2.0 now is out. Updates: 
- Add options.columns & options.rows
- Generating options is now params for toObjectURL, toDataURL and save
- Add options.landscape
- Add options.imageMargin
- Add options.margin
- Add single-page layout

checkout the single-page demo to see if this is what you want: 
https://zenozeng.github.io/p5.js-pdf/demo/

**Comment by zenozeng** [comment]
@liasomething Since, p5.js-pdf@0.2.2, The PDF file will use single-page layout by default.

**Comment by liasomething** [comment]
hi zeno, this already looks like a lot of work you did !!! 
what i thought is referring to two things:
1) if possible the pdf rendered should have the same aspect ratio like the canvas: for instance if i have  a canvas that is 1000 x 10 pixels, then the pdf should also have the same aspect ratio. let's say i would want to open the file in illustrator later on, then the "page" in illustrator should be 1000x10 pixels. this is the output that i would get from an exported processing pdf. if i draw some line that starts inside the window in processing and goes over the edges, then in the pdf in illustrator i will have a clipping path that is the same size as my processing window, and the line would be visible only inside that clipping path, but continue outside of the illustrator page. (i hope i am clear and do not sound too  
confusing)
2) is it possible that all the branches would overlay each other, in the sense that the whole tree in your example would be on one page: one tree on one page... ?
+ again, thanks for your great work here !!!!!

**Comment by zenozeng** [comment]
@liasomething, what you said sounds easy, but I am a little confused.
I think it's it more common and convenient to have a A4 size PDF?  (for printing or something else). 
And if all images overlay each other, how could I see each image?

**Comment by liasomething** [comment]
hello zeno, 
oh, now i get it !!!
i thought you are actually exporting vector graphic, like processing is doing it.
(sorry i did not open it in illustrator, so i missed that!)
by "overlaying" i meant that when two lines are drawn one after the other in two frames, and i don't draw a background, then the two vector lines would show up in one vector graphic.
and i understand that with bitmaps you can not do that!
i think the term "pdf" was misleading to me, as in processing this means exporting vectors.
what i am looking for is actually vector graphic, because i generate some images (usually with processing or openframeworks), then i export them for prints in high resolutions...
anyway, thanks for your work again!!!

**Comment by zenozeng** [comment]
@liasomething Maybe you can use [canvas2svg](https://github.com/gliffy/canvas2svg) for vector graphic?

**Comment by liasomething** [comment]
hi zeno, thanks for the advice, i will have a look at it in a while!

**Comment by zenozeng** [comment]
@liasomething @workergnome @lmccart @shiffman  I am now working on vector export for PDF. Seems that PDF doesn't support embed SVG difrectly. jsPDF's SVG support is buggy and very limited. I found that maybe using [pdfkit](https://github.com/devongovett/pdfkit/blob/86c94d2c19a455f8d48d65c0f72f74e6ec9f88ac/lib/mixins/vector.coffee) is somehow better. But this library is also limited and may need a lot of work to make it work.

I wonder, if it is acceptable to use [p5.SVG](https://github.com/zenozeng/p5.js-svg/) & window.print (print to pdf) to do this, since the browser's print function support vector by default and could work even the element was modified by third party library and this will avoid crashing due to creating large files in memory. Browser's print support custom size and filename (works on chrome_linux, buggy on firefox_linux). I created a simple demo for this: http://zenozeng.github.io/p5.js-pdf/demo/print/

**Comment by workergnome** [comment]
I think we need to define the actual feature that we're looking to implement here.  

PDF Export is sort of a strange feature because PDFs are a document layout format, and are designed for reliable printability.   p5.js, even more so than, say, processing, is a tool for manipulating pixels, and most strongly supports bitmapped representations of data. SVGs are vector representations of image data, and a third way of thinking about these images.

It looks like the processing pdf export intercepts all the drawing code, and replaces a bunch of the core drawing methods with new ones from a text library—basically, rather than drawing to a canvas, you're drawing to a PDF surface using native Postscript/PDF commands, and throwing errors for all features not implemented or possible in PDF.

I believe that `p5.SVG` is @zenozeng's attempt to write a port of p5.js that uses SVG as a replacement for canvas, which would allow for a vector-native representation of a p5 sketch.


Basically, none of these three models will convert cleanly to one another.  @zenozeng's first strategy was to take the bitmap representation of the image and embed it in a PDF, but that loses all that vector data that we have in memory (though not displayed.).  Using p5.SVG, we can build a (currently incomplete) vector representation of a p5.js sketch, but that doesn't natively convert to PDF either, but it **does** maintain all that lovely vector data that we're creating.  We could export a SVG, but not a PDF.

We could also find (or write our own) a tool that allows javascript drawing to a PDF, and re-implement the core drawing functionality from p5.js, similarly to what @zenozeng is doing for SVG.  But that's a huuuuge project, and mostly duplicates the functionality from p5.SVG, if the only goal is to get vector output from p5.js.


Does this make sense to anyone but me?  (I'm not even sure it makes sense to me!)

**Comment by zenozeng** [comment]
Yeah, I think it's really painful and could be buggy to create another svg2pdf or canvas2pdf library. So, if it is acceptable to use browser's print to pdf function, I will implement a basic p5.PDF based on [CSS3's Paged Media](http://www.w3.org/TR/css3-page/).

**Comment by hamoid** [comment]
I just tried opening a random SVG in Firefox (Linux), print to file (PDF), open the PDF in Inkscape, and I can edit each element and edit the vectors freely. At least on Linux it seems easy to produce a PDF out of an SVG.

**Comment by workergnome** [comment]
I think, rather than have a method called PDF that opens a print dialog, we should just document somewhere that the best way to create PDFs is to use a conversion tool or "print to PDF".  I think that if you can get your SVG library complete, that will handle the vector creation pat appropriately.

Thoughts?

**Comment by hamoid** [comment]
@workergnome I agree. And in many cases SVG files will probably be enough, as vector design programs and browsers can directly open SVG files.

**Comment by zenozeng** [comment]
@workergnome @hamoid Yes, but documentation is not enough. Browser's default print to PDF is not handy enough. I hope p5.PDF could do auto set pages size based on the canvas (while browser's PDF always defaults to A4, we can custom it use css's page size, though not work in firefox). Also, I hope p5.PDF could do the layout, for example, display 2 * 3 images per page in our PDF. And I hope finally we will have something like this in p5.PDF:

```javascript
saveFrames(filename, 'pdf', duration);
```

```javascript
pdf = createPDFGraphics();
// or pdf = createGraphics(w, h, 'pdf');
pdf.capture(); // capture current default graphic
pdf.nextPage(); // manually add a new page.
```

I think while SVG provides us with vector support. 
PDF is going to provide:

- multiple images per page
- multiple pages

**Comment by zenozeng** [comment]
@liasomething p5.pdf@0.3.0 now is released. It now supports vector export if you use `createCanvas(100, 100, SVG)`.  Also, in v0.3.0, I added nextColumn(), nextRow(), beginRecord() and endRecord(). Customing page size, page margin, column gap and row gap is also supported. I have created some examples, view with Google Chrome:
http://zenozeng.github.io/p5.js-pdf/examples/

See also: 
- https://github.com/zenozeng/p5.js-pdf
- https://github.com/zenozeng/p5.js-pdf/releases/tag/v0.3.0
