### ISSUE TITLE
loadPixels in 0.8.0 drops frames

### ISSUE THREAD

**Issue by harveymoon** [processing/p5.js#3741]
#### Nature of issue?
- [X] Found a bug
#### Most appropriate sub-area of p5.js?
- [X] Image
#### Which platform were you using when you encountered this?
- [X] Desktop/Laptop
#### Details about the bug: 

P5js V0.8.0
Chrome  Version 74.0.3729.131 (Official Build) (64-bit)
On a mac 10.14.4
Tested on multiple computers.

Using V0.8.0 the loadPixels function will _sometimes_ return no image from the camera grabber. This causes dropped frames, when using CV or a frame difference this is most pronounced. 

Comparing to the functionality of V0.6.1 this is not functioning properly.

you can see this easiest in Kyle's CV examples : https://kylemcdonald.github.io/cv-examples/FrameDifference/

Once you change it to v0.8 you should see the result flashing, indicating the bg frame is loading null

I was able to track this down and remove the issue by commenting these lines in 
p5.Renderer2D.prototype.loadPixels function

```
  if (!pixelsState._pixelsDirty) return;
  pixelsState._pixelsDirty = false;
```

I need to understand better what dirty pixels are before I propose a solution or anything. Maybe someone else can replicate this and chime in. 

This seems to not be the same issue as to what was solved in 0.8.0
I am able to grab the video frame most of the time, it will hit this return intermittently.
https://github.com/processing/p5.js/issues/3359

My best guess is that it has something to do with the update time of the cam vs canvas. I tested this with an 8fps webcam, when I set the canvas frameRate(10) I can see a very visible repeating frame drop that resembles a phase offset. ( increasing the frame rate will speed the rate of frame drop and vice versa)

Bringing the frame rate of P5 to 8 or lower then the camera removes this issue entirely.

**Comment by lmccart** [comment]
@harveymoon I think this may have been addressed with https://github.com/processing/p5.js/pull/3781/files. could you pull the latest from master and see if it is resolved?

**Comment by stalgiag** [comment]
Okay I am doing some checking around. This occurs sometime between 0.6.1 and 0.7.

Also looking at this example in particular reveals more issues around capture that are present in 0.9.0. I'll open issues as I understand them better. Thank you for reporting @harveymoon !

**Comment by stalgiag** [comment]
`_pixelsDirty` is a way to avoid updating the `pixels` array if no changes have occurred. 

Part of what is happening here is that the example given has an optimization that causes `loadPixels()` to occasionally run more than once in a row without a call to `updatePixels()` in between, which worked fine with 0.6.1 but not anymore. 

https://github.com/kylemcdonald/cv-examples/blob/823dd20701a57552420dbab8a72bba71561381e3/FrameDifference/sketch.js#L72-L73

In frames where this is happening, `loadPixels()` sets `_pixelsDirty` to false, and `updatePixels()` hasn't run to set it back to true. If in this same frame the `capture.elt.currentTime` hasn't updated (which honestly seems to be unreliable and I am not sure that it should be used for these purposes), then this check will evaluate to false:

https://github.com/processing/p5.js/blob/1f6b1378592b58368ff983d812099a3abd8f4781/src/dom/dom.js#L2884

Note though that `updatePixels()` doesn't always set `_pixelsDirty` to true. This check does not make sense to me.

https://github.com/processing/p5.js/blob/1f6b1378592b58368ff983d812099a3abd8f4781/src/core/p5.Renderer2D.js#L346-L348

I don't know why we would assume that the `pixels` haven't been modified unless the location or size have changed. So if we remove that check and change the example given so that it calls `updatePixels()` every frame then the problem is eliminated.

This state of `_dirtyPixels` is a bit tangled in my head, so I may be missing something but if I make the change suggested in the prior paragraph then the bug in the example is fixed and no new bugs are identifiable in the examples or tests. Definitely this state management should be rewritten to be more clear at some point, but not sure what the best approach would be.

This behavior first starts appearing [in this commit](https://github.com/stalgiag/p5.js/commit/fe614f4e4ad6529964ce63ff98c683c8df648aa9).

**Comment by lmccart** [comment]
@stalgiag thanks for looking into this one. I think it makes sense to remove that check as you suggest. from what you can tell, does `_dirtyPixels` have other uses beyond this? or would it make sense to consider removing completely?

**Comment by stalgiag** [comment]
I think it would be okay to remove it completely.

On one hand it feels like a sensible optimization to only update the pixels array when a canvas has been modified but on the other hand it was [introduced fairly recently](https://github.com/processing/p5.js/pull/2833) and I can't find a trail of issues that complain of the performance of pixel reading operations. It seems like something that will be prone to breaking since it is a flag that needs to be modified with every kind of drawing (which I already can't be sure is happening). Perhaps there is a smart way to rewrite it that would be less brittle but a quick bit of research revealed nothing.

For reference, this value is only read in these places:
- [MediaElement._retrieveCanvas()](https://github.com/processing/p5.js/blob/master/src/dom/dom.js#L2884)
- [Renderer2D._getPixel()](https://github.com/processing/p5.js/blob/master/src/core/p5.Renderer2D.js#L280)
- [Renderer2D.loadPixels()](https://github.com/processing/p5.js/blob/master/src/core/p5.Renderer2D.js#L263)
- [Renderer2D.set()](https://github.com/processing/p5.js/blob/master/src/core/p5.Renderer2D.js#L319)
- [RendererGL._getPixel()](https://github.com/processing/p5.js/blob/master/src/webgl/p5.RendererGL.js#L744)
- [RendererGL._loadPixels()](https://github.com/processing/p5.js/blob/master/src/webgl/p5.RendererGL.js#L777)

**Comment by lmccart** [comment]
Ok, for simplicity, let's go ahead and remove.
