### ISSUE TITLE
mouseX and mouseY is NaN with a canvas of 0, 0

### ISSUE THREAD

**Issue by clankill3r** [processing/p5.js#3749]
I'm using the mouse position just in the dom document, I noticed today that they are NaN with a canvas of 0x0. So now I have a canvas of 1x1, but it would be better if the mouse works regardless of a canvas?

**Comment by Ajayneethikannan** [comment]
Hi @clankill3r ! I think you can make use of winMouseX, winMouseY for now, as it does not include any scaling factors with respect to the canvas.

I think making sx and sy  in [getMousePos( )](https://github.com/processing/p5.js/blob/master/src/events/mouse.js#L397) 1 if they are not numbers would solve this problem.

Would be happy to make a PR if that suffices.

Thank you.

**Comment by lmccart** [comment]
@clankill3r can you explain more about why the need for a 0x0 canvas? I don't think p5 was really intended to run this way. if you want to remove the canvas completely you can use the `noCanvas()` function and `mouseX` and `mouseY` should work as expected.

**Comment by Ajayneethikannan** [comment]
@lmccart This still causes a problem, but now instead of producing NaN, it is giving me Infinity.
Reference: https://editor.p5js.org/TheSkepticSniper/sketches/y794hehMd
What I have found out is that when we call **noCanvas( ),** though the canvas node is removed from the DOM, it is still kept in memory. But after we remove it,in **getMousePos( )** the scrollWidth becomes 0, while the height remains the default 100px. So finally we get Infinity as the value for mouseX and mouseY.
Would love to hear more on this !

**Comment by lmccart** [comment]
ah I see, good find. I am adding a fix now.

**Comment by clankill3r** [comment]
Thanx, winMouseX will do the trick for now till the bug fix is released.
