### ISSUE TITLE
feature request: would like to see modelX(), modelY() functions that exist in Processing

### ISSUE THREAD

**Issue by dnassler** [processing/p5.js#377]
I like using the matrix functions: translate, rotate, scale. But sometimes I need to know the coordinates of points drawn from the perspective of the main canvas co-ordinate space. So for example if I have a point A that was drawn using a set of matrix transforms and another point B that was drawn using a different set of matrix transforms, I might want to draw a line from point A to point B. To do that I need to have a common co-ordinate space. The functions modelX(), modelY() in the Processing reference do this, it seems, and it would be nice if p5js had these functions as well. See Processing reference: http://processing.org/reference/modelX_.html

**Comment by MAKIO135** [comment]
Is this issue still not doable ? Would love to see these features on p5js

**Comment by mkmori** [comment]
I keep missing `modelX/Y/Z()` (and `screenX/Y/Z`), too. I think this closed request is specific to P2D. (In P2D, `modelX/Y()` and `screenX/Y()` would give the same, x,y values, right?)

If so, are these limitations specific to canvas/P2D? And so, in WEBGL mode, `modelX()`, `modelY()`, `modelZ()` might be possible? (Or maybe trivial?) Are `screenX`, `screenY`, and `screenZ` (z-buffer depth?) similarly possible or already available in WEBGL mode? (Is some "view" or "projection" matrix readily available?)

If "`getMatrix()`" (or "`getGlMatrix()`") were a thing, it might be used with `applyMatrix()` to reproduce (WebGL) transformations outside of a `push()/pop()`, right? I read on one of the links below that "`getMatrix()`" would be problematic...but, again, is that a P2D/canvas-specific problem? Otherwise, is this basically doable? Maybe there is already an easy way to grab the current (3D) transformation matrix, (`p5.Matrix.mat4` or something)?

Even with a function like "`getMatrix()`", I'm not sure how one would get transformed coordinates: If only, in addition to "`getMatrix()`", `applyMatrix()` could perhaps be applied to a 3-vector, e.g., `pv.set(0,0,0);  pv.applyMatrix();` A vector whose x,y,z values could then be read out?

FWIW! Kinda out of my depth, but happy for any hints or advice!

https://github.com/processing/p5.js/issues/243 (`push()/pop()` discussion)
https://github.com/processing/p5.js/issues/377 (this issue, `modelX()`, `modelY()` feature request)
https://github.com/processing/p5.js/issues/1553 (`screenX()` `screenY()`, `screenZ()` feature request)
https://github.com/processing/p5.js/issues/1873 (`modelX()`, `modelY()` feature request)
https://github.com/processing/p5.js/issues/4337 (matrix functions...completed!)
