### ISSUE TITLE
Text Kerning 

### ISSUE THREAD

**Issue by feve1752** [processing/p5.js#3800]
#### Nature of issue?

- [ ] Found a bug
- [ ] Existing feature enhancement
- [x] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [x] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 
- Web browser and version: 
- Operating System: 
- Steps to reproduce this:

**Comment by limzykenneth** [comment]
There is no direct support of text kerning in HTML canvas, you can however set the CSS [`font-kerning`](https://developer.mozilla.org/en-US/docs/Web/CSS/font-kerning) and [`text-rendering`](https://developer.mozilla.org/en-US/docs/Web/CSS/text-rendering) properties on the canvas itself using CSS which can help with kerning in some cases.

However, if you mean text tracking (ie. custom letter spacing) instead of text kerning (which is something built into the font's design) then there isn't really a way to do it. Rolling something custom like drawing individual letters onto the canvas will like produce a bad result for most fonts as text tracking is applied on top of the kerning and without the kerning the overall text will look very uneven with uniform tracking.

**Comment by lmccart** [comment]
Thanks @limzykenneth. I think these suggestions are the best way to handle this case for now.
