### ISSUE TITLE
Multiple types of materials to support WebGL Geometries

### ISSUE THREAD

**Issue by sanketsingh24** [processing/p5.js#3806]
#### Nature of issue?

- [x] Existing feature enhancement

#### Most appropriate sub-area of p5.js?

- [x] WebGL

#### Details 
Currently, in p5, only one of the `specularMaterial()` or `ambientMaterial()` can be applied to a geometry. But many objects in the real world can exhibit both behaviour. Take a look at this sketch from processing-

![Screenshot_2019-06-09_21-55-37](https://user-images.githubusercontent.com/24548786/59205289-4179e500-8bc0-11e9-9f53-915a7faf82a3.png)
[_(Code)_](https://pastebin.com/usCdhdZ3)

In short, the left sphere has just ambient (red) properties whereas the right sphere has both ambient (red) and specular (white) properties.

As I am implementing `emissiveMaterial()` also, we (me and @aferriss ) just got this thought and this would be a good feature. One of the things which we noticed was both [`specularMaterial()`](https://github.com/processing/p5.js/blob/master/src/webgl/material.js#L665) and [`ambientMaterial()`](https://github.com/processing/p5.js/blob/master/src/webgl/material.js#L614) use the same uniform and same variable, [which causes the later one to render](https://editor.p5js.org/sanketsingh24/sketches/vJM9_yMBt).

**Comment by stalgiag** [comment]
Hi @sanketsingh24 and @aferriss, after finishing the summer, what are your thoughts on this issue? Thanks!

**Comment by aferriss** [comment]
@stalgiag @sanketsingh24 I still think this would be a good feature to add, but it's probably not a simple PR. This touches a lot of the webGL rendering pipeline and untangling and sorting things out is probably going to be a bit of an effort. 

I don't think I'll have much time anytime soon to work on this and I'm pretty certain Sanket is also busy in the coming months. Maybe this warrants a help wanted tag?

**Comment by stalgiag** [comment]
Thanks for the thoughts @aferriss !

I agree that this seems a bit rough, and definitely feels like it would need to be part of a larger restructuring. I am looking into these kinds of changes as part of #3794. I am happy to do the work if there is a sound high-level plan for a restructure or redesign, but without this I am reluctant to start messing with this many parts of the code before the 1.0 release. I'd be curious to draw opinions on something like this, but that might require first making a very clear map of the rendering pipeline as it stands now.

I also don't know if the effort-to-reward ratio is ideal with a large GL restructure currently. The stability, functionality, and performance trend of the GL Renderer has been strongly upward for the past few years, but the portion of users that work with it may still be relatively low. Of course, this is difficult to know for sure since we don't capture data about these kinds of things.
