### ISSUE TITLE
Remove alpha arguments from ambientMaterial and specularMaterial

### ISSUE THREAD

**Issue by sanketsingh24** [processing/p5.js#3807]
#### Nature of issue?

- [x] Found a bug

#### Most appropriate sub-area of p5.js?

- [x] WebGL

#### Which platform were you using when you encountered this?

- [x] Desktop/Laptop

#### Details about the bug: 

- p5.js version: master build
- Web browser and version: 
 1. Chromium  74.0.3729.169
 2. Firefox 67.0.1

- Operating System: Arch Linux 5.1.5
- Steps to reproduce this:

[Take a look at this](https://editor.p5js.org/sanketsingh24/sketches/TTNyjrLfJ).
The right sphere has opacity value one less than the default value. And a weird glitch shows up. We (me and @aferriss) were trying the opacity value when we caught this glitch. To me, it seems for those vertexes or fragments the color is not getting calculated and shows what the color without the directional light would be rendered.
[Here's another one](https://editor.p5js.org/sanketsingh24/sketches/OAYVmQ0wk)

Edit: Also, wanted to add that upon [disabling depth](https://github.com/processing/p5.js/issues/3736#issue-442358350) by this method makes the glitch appear in both the spheres, maybe it might help.

**Comment by Spongman** [comment]
I trouble this may be similar to #2616.

**Comment by sanketsingh24** [comment]
@Spongman Yes, probably, can't say surely though.

Also, this happens with `pointLight()` too.
Also, changing `directionalLight()`'s z-axis direction  seems to invert the pattern. And doesn't depends on x,y,z.

**Comment by Spongman** [comment]
Yeah this is just a side-effect of not depth-sorting the triangles. There’s not really an easy solution for this.

**Comment by stalgiag** [comment]
I think that depth sorting is out of scope. One thought, Processing doesn't allow alpha arguments to `ambient()`. We should consider doing the same.

**Comment by stalgiag** [comment]
The todo here is to remove the alpha arguments from `ambientMaterial()` and `specularMaterial()`.

**Comment by Spongman** [comment]
I'm not sure that'll help, though. wouldn't this also repro if you pass alpha in `fill()` ?

**Comment by stalgiag** [comment]
Ah yes, the above to-do would at least isolate the occurrence to `fill()` and then maybe we should consider adding a note about combining transparency and lighting. For reference, here is a photo of the above example with transparent `fill()` instead of `ambient()` in Processing, the rendering is near identical.

![Screenshot (90)](https://user-images.githubusercontent.com/10382506/60476989-87abec80-9c32-11e9-8d19-e0f8ef96e3c5.png)

I think removing the alpha argument from the materials at least helps to imply that alpha and lighting don't mix well.
