### ISSUE TITLE
saveCanvas() in WEBGL in Safari - image flipped

### ISSUE THREAD

**Issue by cdaein** [processing/p5.js#3812]
#### Nature of issue?

- [x ] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [x] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 0.8.0 
- Web browser and version: Safari 12.1.1 
- Operating System: MacOS Mojave 10.14.5 
- Steps to reproduce this:

When saving canvas in WEBGL mode in Safari, the saved image is flipped. It works fine in Chrome on the same computer. I also tested it on iPhone and iOS Safari and Chrome both have the same issue.

```js
function setup() {
  createCanvas(400, 400, WEBGL);
}

function draw() {
  background(220);
  
  fill(255, 0, 0);
  ellipse(-150, -150, 100, 100);
}

function keyPressed() {
  saveCanvas();
}
```

**Comment by Spongman** [comment]
Maybe related: https://github.com/pixijs/pixi.js/issues/2283

**Comment by cdaein** [comment]
Thank you, @Spongman - I followed your link and setting `setAttributes('premultipliedAlpha', true);` did fix the issue although I am not sure what other impacts this change might have.

**Comment by stalgiag** [comment]
Hi @cdaein thanks for filing the issue! [Here is a link with some info ](https://limnu.com/webgl-blending-youre-probably-wrong/)about what premultipliedAlpha is. This value is false to start with so that the color blending in the WebGL canvas is as close to that of the 2D canvas as possible.

This problem seems to be outside of p5. There is this [post as well](https://forums.developer.apple.com/thread/6003) which points to a stale Safari issue. I think it would be a bad idea to handle this bug on the p5 side because any solution would likely produce new problems once the bug status is changed on the safari side.

Instead, if cross-platform WEBGL canvas saving is central to a project that you are developing, and premultipliedAlpha has undesirable effects, I would recommend using a browser testing method [such as this one](https://wp-mix.com/detect-chrome-ie-firefox-opera-safari/), and then use something like this:
```
function mousePressed() {
  if(isSafari) {
    img = get();
    push();
    scale(-1.0, 1.0);
    image(img, -width, 0);
    save();
    pop();
 }
}
```
I know it is a bit wonky but I think for something that is encountered this rarely, and seems to be a problem with a browser rather than the library, it makes more sense for users to handle this on their end. Hope this helps! Closing this for now but if other people find that they are encountering this bug a lot, then ping me in this thread and I'll reopen.
