### ISSUE TITLE
mouseIsPressed returns incorrect value after redirecting page

### ISSUE THREAD

**Issue by Vrx8** [processing/p5.js#3841]
#### Nature of issue?

- [x ] Found a bug

#### Most appropriate sub-area of p5.js?
- [x] Events

#### Which platform were you using when you encountered this?

- [x] Desktop/Laptop

#### Details about the bug: 

- p5.js version: "https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.8.0/p5.js" 
- Web browser and version: 67.0.4 Firefox
- Operating System: Windows 10 
- Steps to reproduce this:

```
function setup(){
	createCanvas(500, 500);
	once = true;
}

function update(){
	//run code once each time mouse pressed
	if (mouseIsPressed && once){
		once = false;
		window.location.href = "Page2.html";
	}
	if (!mouseIsPressed){
		once = true;
	}
	console.log(mouseIsPressed);
}


function draw(){
	update();
	background(0,0,0);
}
```

After redirecting to Page2.html, When I click the browser back button to go back to Index.html page, the value of mouseIsPressed is still true even though there is no mouse press is done in the page. 

when mouse is clicked again after going back to index.html from Page2.html, mouseIsPressed will return the correct value again.

**Comment by stalgiag** [comment]
Able to reproduce - only in Windows 10 with Firefox 67.

**Comment by lmccart** [comment]
@Vrx8 this is an interesting case. Basically, the `mouseIsPressed` variable is not getting set when a new page is opened because the sketch exits before the `mouseup` event fires. We could reset this value when a page redirect is detected. But if we did, this would make the case where someone has the mouse down on a second page and uses the backspace key to get back to the sketch incorrect. In this case, mouseIsPressed would be set to false, when it is actually now true. So our best suggestion is to handle this case in your own sketch. You can do this by adding this block of code to the end of your sketch file:

```js
window.addEventListener('unload', function(event) {
  mouseIsPressed = false;
});
```

Hope this helps!
