### ISSUE TITLE
GIF files often save larger than they load

### ISSUE THREAD

**Issue by stalgiag** [processing/p5.js#3871]
#### Nature of issue?

- [ ] Found a bug
- [x] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [x] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [ ] Desktop/Laptop
- [ ] Others (specify if possible)

#### Summary
GIF images will often save much larger than the files that are loaded. This is because loaded GIFs do not retain global palettes. This is because the global palette may change with editing and also to avoid storing it in memory when most sketches will not use it. This means that when GIFs are saved, [the palette is generated for each individual frame and then it is encoded as a local palette for each frame](https://github.com/processing/p5.js/blob/master/src/image/image.js#L218). This results in larger saved files.

#### If We Decide to Fix
Not sure of the best solution here. GIF support hasn't been publicly released yet, but this issue can be a way of tracking whether people encounter this problem.

If it seems like it negatively impacts a significant number of people then we can consider:
 - storing the global palette on decoding along with a `paletteModified` boolean defaulted to false
 - monitoring for palette breaking changes and setting paletteModified to true if they happen
 - when saving if `paletteModified` is still false, encoding with the stored global palette, otherwise use the current method

#### Sidenote
There are other options, one that comes to mind immediately is that we can analyze the entire GIF and build a new global palette upon saving. This might introduce other problems with files that should be using some combination of local and global palettes because the palette will be too large otherwise.

**Comment by akshay-99** [comment]
@stalgiag I would like to work on this issue 

Also I noticed one more optimization issue [here](https://github.com/processing/p5.js/blob/master/src/image/image.js#L224)
As the indexOf lookup runs in linear time, this method proves extremely slow for larger GIFs ( A gif of size 8.7 MB took 7956 ms )
When I changed it to object lookup and tried it with the same GIF, it took just 899 ms.

I can work on both these things if you give the go ahead. :smile:

**Comment by stalgiag** [comment]
Haha that is a great speedup @akshay-99 ! And yes, feel free to work on it.

**Comment by akshay-99** [comment]
So my idea right now is to break down saveGif into two passes on the frames.
Pass 1 analyses all the palettes in all the frames and considers the most common one as the global palette. 
Pass 2 uses this global palette as reference  and checks if the current frame needs a local palette of its own ( it has a color not contained in the considered global palette ). If so the local palette will we built and used for the frame. 
Does this method seem reasonable? @stalgiag 

I will try this and get back with any differences in space utilization.

**Comment by stalgiag** [comment]
That sounds like a good idea @akshay-99. Good luck!

**Comment by akshay-99** [comment]
@stalgiag there's this variable `gifFormatDelay` [here](https://github.com/processing/p5.js/blob/master/src/image/image.js#L210)
It isn't defined anywhere and appears only [once](https://github.com/processing/p5.js/search?q=gifFormatDelay&unscoped_q=gifFormatDelay) in the entire project. 

So far I have been calling saveGif after removing `gifFormatDelay`, because if I run saveGif with that still in, I get an error as it isn't defined anywhere.

Can I continue ignoring it and keeping it out or is it something I should care about? :sweat_smile:

**Comment by stalgiag** [comment]
Ah @akshay-99 I must have missed that when I got rid of :-P

So that is my bad, I will remove it from the upstream right now (processing/master). But this is a good illustration of the fact that we need a GIF saving unit test. So as part of your changes, I would add one of those.

We can take it one step at a time though. Thanks for finding that!

**Comment by akshay-99** [comment]
@stalgiag  Also I noticed that the size of the GIF purely dependent on the size of the buffer created for GIFWriter. 
I noticed this when I saw no change in filesize even after I used a global palette for all frames
So for a 1280x720 GIF of 25 Frames, the size comes to about 1270 * 720 * 25=23040000. 
And sure enough, when I run saveGif and download it, the fize size is 23 MB. 

So just to check I loaded the output gif with loadImage().
Interestingly enough this  is the frameInfo of the last frame:
```
{
  x: 0,
  y: 0,
  width: 1280,
  height: 720,
  has_local_palette: false,
  palette_offset: 13,
  palette_size: 256,
  data_offset: 12419513,
  data_length: 521687,
  transparent_index: null,
  interlaced: false,
  delay: 4,
  disposal: 0,
  __proto__: Object
}
```

This tells us that the it should only use 13 MB not 23 MB.  ( The original filesize is 8.7 MB but 13  is better than 23 :sweat_smile:. and the other 4.3 MB are wasted due to some other optimization issue probably )
I will look into it and will get back soon.

**Comment by akshay-99** [comment]
@stalgiag I was able to optimize further by using the transparency property of GIFs. 
I observed that using global or local palettes had little impact on the size of the gifs.
It turned out that most of the GIFs that were blown up in size by saveGif originally used transparency as an optimization. 
This was removed by saveGif by setting `transparent_index` to null for all frames.

Here are the sizes produced by 3 variants of saveGif, taking the same 8.7 MB GIF as input.

The one currently on master: 23 MB
The one with the buffer sliced at the end and using global palettes wherever possible: 12.9 MB
The one using the transparency property: 8.9 MB 

I did increase the length of saveGif a lot in the process :sweat_smile: 
Should I go ahead and create a pull request?
