### ISSUE TITLE
2 deprecation warnings in the console

### ISSUE THREAD

**Issue by r00ster91** [processing/p5.js#3918]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [x] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 0.9.0
- Web browser and version: Mozilla Firefox 68.0.1
- Operating System: Windows 10
- Steps to reproduce this:
  Use this code:
  ```js
  function setup() {}
  ```
  And look into the console. You will see:
  ```
  Use of the orientation sensor is deprecated. p5.min.js:3:233176
  Use of the motion sensor is deprecated.      p5.min.js:3:233176
  ```

**Comment by limzykenneth** [comment]
These are just warnings and should not cause any problem regarding its usage. Firefox has been showing this warning for a long time now and most believed the features mentioned won't be removed otherwise Firefox will not be unable to support WebVR. See [here](https://www.fxsitecompat.dev/en-CA/docs/2018/various-device-sensor-apis-are-now-deprecated/)

In any case, this is not something we can fix or get around, so I'm closing this issue for now.
