### ISSUE TITLE
55806

### ISSUE THREAD

**Issue by thirukumars** [processing/p5.js#3960]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [x] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 
- Web browser and version: 
- Operating System: 
- Steps to reproduce this:

**Comment by thirukumars** [comment]
Button=createButton('ukele');
      ukeleButton.mousePressed(function(){
      classifier.addImage('ukele');   
      });

while pressing the button,this error arises
error:
p5.js:55860 Uncaught TypeError: Cannot read property '_setProperty' of undefined
    at p5.Element.eventPrependedFxn (p5.js:55860)

**Comment by stalgiag** [comment]
Hello @thirukumars your code snippet is a bit limited but I think I see the problem.  It seems like the bug is due to setting the `mousePressed` value of the variable `ukeleButton` when the variable `Button` is the button element that you created using `createButton`. The label of the button does not get added to the variable name, so `Button` does not become `ukeleButton`. I tested button element `mousePressed` functionality [with this example](https://editor.p5js.org/stalgiag/sketches/OtQd_fmOB) and am seeing no odd behavior. For the future, the github repo is for times when a user is fairly confident that the bug they are seeing is due to a problem in the library. All other coding questions should go [on the discourse forum](https://discourse.processing.org/c/p5js/p5js-questions). If you are unsure if the bug is in your code or in the library code, I would try posting there. I am closing now for organization purposes. Thanks!
