### ISSUE TITLE
Inaccurate RGBA colors values when using pixels[]

### ISSUE THREAD

**Issue by STPR** [processing/p5.js#3971]
#### Nature of issue?

- [X] Found a bug

#### Most appropriate sub-area of p5.js?

- [X] Image

#### Which platform were you using when you encountered this?

- [X] Desktop/Laptop

#### Details about the bug: 

- p5.js version: v0.9.0 July 01, 2019
- Web browser and version: Firefox 69.0
- Operating System: Windows 10 64bits

I've inaccurate RGBA colors values when using pixels[] on a 32 bits png file :
The values are sometimes off by one (254 instead of 255).
And when the alpha value is equal to 0, the R, G or B values are equals to 0 (instead of 255).

**Comment by STPR** [comment]
[RGBA_BUG.zip](https://github.com/processing/p5.js/files/3541606/RGBA_BUG.zip)

The RGBA.png is made of 3 horizontal stripes of colors (red 255, green 255 and blue 255).
And the alpha value goes from 255 to 0 (left to right).

Just choose the RGBA.png file and look the colors table inside the console.

**Comment by STPR** [comment]
Does this problem occur because p5.js seems to use both Uint8ClampedArray and Uint8Array ?

The clamped version uses rounding: Uint8ClampedArray([0.9]) = [1]
But the basic version uses floor: Uint8Array([0.9]) = [0]

**Comment by stalgiag** [comment]
Hi @STPR Thank you for the well-written issue with the examples!

Just to clarify a few points:
  - Are you using 2D or WEBGL mode?
  - Can you point to where you see the `pixels` array using Uint8ClampedArray with a link in the code?

**Comment by stalgiag** [comment]
Hi @STPR thank you for the well-written issue with examples! Sorry for that first post, didn't realize you have example code in your zip.

So I am able to see the second problem you listed 'when the alpha value is equal to 0, the R, G or B values are equals to 0 (instead of 255).' but unable to see the first. I never see 254 for any of the values other than the alpha when it is counting down.

As for the second behavior which I can recreate, I am not sure if this is different [than the behavior](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/getImageData) for `drawingContext.getImageData` which is what the [2D renderer is using to load pixels](https://github.com/processing/p5.js/blob/master/src/core/p5.Renderer2D.js#L296).

I am running Windows 10 Chrome 76.038 by the way!

**Comment by STPR** [comment]
Hi,

That's interesting. The innacurate values could be a firefox issue.

**Comment by stalgiag** [comment]
Great! Thank you for the research and follow-up @STPR !

I am going to close this issue for organizational purposes.
