### ISSUE TITLE
p5.Vector in LocalStorage

### ISSUE THREAD

**Issue by Exifers** [processing/p5.js#3990]
#### Nature of issue?

- [ ] Found a bug
- [ ] Existing feature enhancement
- [X] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [X] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [X] Math
- [ ] Typography
- [X] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### New feature details:

Hi,
I'm making a small web app where I store some data in localStorage. storeitem and getitem are very handy for this, but somehow it is not supposed to work with p5.Vector (only String|Number|Object|Boolean|p5.Color).

I thought it would be cool if p5 would provide this feature so that we don't have to serialize/deserialize the vectors in the code.

Thanks

**Comment by singhvisha** [comment]
@outofambit ,
Can I work on this issue?

**Comment by stalgiag** [comment]
@Exifers I like that idea!

This should be relatively straightforward. The serialization [happens here](https://github.com/processing/p5.js/blob/master/src/data/local_storage.js#L71) and deserialization would [be a new switch case here.](https://github.com/processing/p5.js/blob/master/src/data/local_storage.js#L148).

@singhvisha it is a good idea to only be assigned to one issue at a time, at least for your first few contributions. If you no longer want to work on #3897, that is definitely okay, just let us know so we can pass the task on to other people that are interested in helping.

**Comment by singhvisha** [comment]
@stalgiag 
hi ,Sorry for the delay. I will be submitting it soon.

**Comment by singhvisha** [comment]
Hi @stalgiag ,I commited for this issue  on my previous fork in which I made commit for #3978.
Should I delete that fork and do the same for this issue?

**Comment by stalgiag** [comment]
Hi @singhvisha! I highly recommend that you work [in a branch](https://help.github.com/en/articles/about-branches) within your fork. This allows you to work on different parts of p5 independently. So this means that you should have a different branch for every new issue that you work on. Such as:

`singhvisha/p5.js:basicJSDocs`
and
`singhvisha/p5.js:vectorLocalStorage`

So for that second branch above, you would make a new branch with something like:
`git branch vectorLocalStorage`
then you would switch to it with
`git checkout vectorLocalStorage`
Then any changes you make, commit, and push will go to that specific branch. Once you have made changes you can open a pull request with a specific branch of your fork.

I think the easiest way to clean up this work is to make backups, create new branches, add your work back in, and then open new separate pull requests. I will give detailed instructions in #3978 in order to keep this issue thread somewhat on topic.
