### ISSUE TITLE
How to draw or use if "mouseIsPressed" option to create ellipses ON TOP of an existing ellipse drawing

### ISSUE THREAD

**Issue by ai-dani** [processing/p5.js#4018]
I'm a super beginner on p5.js and I'm hoping this community can help me. So I drew a simple code that includes one fixed 300x300 ellipse on the middle of the canvas, and I plan to have the user be able to add smaller circles on top (like pepperoni on pizza)--when I later add in a statement of " if(mouseIsPressed)" --> "create 'ellipse(mouseX, mouseY,25,25)", it adds the tiny circles but BEHIND the large fixed ellipse drawing instead of on top? Is there a way to fix this?

**Comment by stalgiag** [comment]
Hi @ai-dani this page is for the development of the library. So this is where bugs are reported, features are requested, and contributors work together on the library. For more general help on how to use the library and assistance with coding challenges it is better to [ask on this forum](https://discourse.processing.org/c/p5js).

But since you are already here, I can help you briefly and say that the code that comes first (top -> bottom) draws first. You can think of it like drawing. If you draw the 300x300 ellipse first, above, then things you draw later will be on top of it. Also, there might be other aspects affecting what is drawn on top, such as the fact that `setup()` runs once and `draw()` runs repeatedly. Here is an example with [comments that explain that.](https://p5js.org/examples/structure-setup-and-draw.html)

But I'd recommend [posting on the forum](https://discourse.processing.org/c/p5js). If you make a post with example of the code you are using, and what you are trying to accomplish, someone there can certainly help you out.

Good luck!
