### ISSUE TITLE
texture() doesn't seem to work for loaded model() objects

### ISSUE THREAD

**Issue by ffd8** [processing/p5.js#4032]
#### Nature of issue?

- [ ] Found a bug
- [x] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [x] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 0.9.0
- Web browser and version: Chrome 76.0.3809.132
- Operating System: MacOS 10.13.6

#### Feature enhancement details:
Not sure if this is a bug or just something that hasn't been implemented yet. Can't  apply a texture to a loaded model. `texture()` works just fine with primitives, but when used just before `model()` – the model disappears and nothing is shown. 

@kjhollen or @stalgiag have you run into this?

... why is it necessary? Fish teapot's!

```
let tea, fish;

function preload() {
	tea = loadModel("data/3d/teapot.obj");
	fish = loadImage("data/images/fish.png");
}

function setup() {
	createCanvas(windowWidth, windowHeight, WEBGL);
}

function draw() {
	background(0);
	scale(-4);
	texture(fish); // toggle off to see teapot again
	model(tea);
}
```

**Comment by stalgiag** [comment]
Hi @ffd8 thanks for the issue!

It is working for me on Chrome 76.0.3809.132 on Windows 10. Here is an [example in the editor.](https://editor.p5js.org/stalgiag/sketches/iQAZ1wlW6). 

Let me know if that example works for you.

If that example is working for you then your troubles likely arise from your model file. The model in that example has [UV maps](https://en.wikipedia.org/wiki/UV_mapping) (albeit very bad ones). These are necessary in order to wrap the model with a 2D texture. Otherwise a single pixel from your texture may be used to wrap your entire model, and if that pixel was black it may appear as though the model disappeared.

**Comment by ffd8** [comment]
Yupyup, no bug! Just my novice knowledge of obj files and UV maps... didn't realize the file needed that information built in. Many thanks for pointing that out.
