### ISSUE TITLE
Textures don't work with custom shapes

### ISSUE THREAD

**Issue by Chlyb** [processing/p5.js#4035]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [x] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 0.9.0
- latest Chrome and Edge
- Windows 10 
- Steps to reproduce this:
https://editor.p5js.org/Chlyb/sketches/bUkc2uuEGM

This code is copied from the documentation and does not work.

**Comment by stalgiag** [comment]
Hi @Chlyb the default [textureMode](https://p5js.org/reference/#/p5/textureMode) is `IMAGE`. So your example works if you make either of the following changes:

- Add `textureMode(NORMAL)` to the sketch
or
- Change your U and V arguments for `vertex()` to be your texture's width and height in pixels, respectively. So for your texture file:
```
  beginShape();
  vertex(0, 0, 0, 0, 0);
  vertex(100, 0, 0, 535, 0);
  vertex(100, 100, 0, 535, 559);
  vertex(0, 100, 0, 0, 559);
  endShape(CLOSE);
```

So this all falls under expected behavior.

Can you point me to the location in documentation that you got this code from? Just want to make sure there aren't incorrect docs somewhere. Thanks!

**Comment by Chlyb** [comment]
Hey @stalgiag Thank you for solving my problem! Here's the code https://github.com/processing/p5.js/wiki/Getting-started-with-WebGL-in-p5 under Texture paragraph.

**Comment by stalgiag** [comment]
I edited that example with the correct code and a bit of info. I am closing this now. Thanks for the help tracking down the misleading info @Chlyb !
