### ISSUE TITLE
The main animation loop is 2X slower than the declared framerate

### ISSUE THREAD

**Issue by zaerl** [processing/p5.js#405]
If I set a `framerate(60)` I don't get 60 FPS, I get 30. If I set 120 (or higher) I get 60.

If I have analyzed correctly the code the main animation loop is at [/src/core/core.js#L260](https://github.com/lmccart/p5.js/blob/master/src/core/core.js#L260). Assuming that 60 is the desired framerate you set a timeout at 1000/60 which calls the `requestDraw` polyfill.

Such approach is wrong cause the polyfill calls the native `requestAnimationFrame` or `setTimeout` with a delta of 1000 / 60 (which is forced in the code in you fallback to setTimeout) causing further delay.

I can send a pull request if you want, let me know.

**Comment by arxpoetica** [comment]
Some helps found here under "What if I want to set a frame rate?":

http://creativejs.com/resources/requestanimationframe/

**Comment by mehtmehtsen** [comment]
Woah, thank god I found this.
I have been searching and hacking around for hours trying to figure out why my p5js game (@ p5js 0.4.4) is running at about 30fps in IE and Firefox even though I set `frameRate(60)` in setup. 
It was running at 60fps in Chrome, so I thought I had performance issues although I was just drawing a little triangle.
Now I have set the frameRate to 120 and it runs with 60fps in every browser I tested (FF 37.0.2, IE 11.whatever, Chrome 42.0.2311.90).
Is this a suggested workaround for this problem? Seems kind of dangerous.

**Comment by zaerl** [comment]
Maybe the implementation I have suggested is the right one. I don't think that we are talking about performance here. This is just a bug.

**Comment by mehtmehtsen** [comment]
Yes, it's a bug alright. Performance is very fine when using the "workaround".

Imho it's a bug that is capable of making people not choose p5js over other js libs like paper.js.
I'm a pretty big Processing fan, and even I thought about switching, because I thought p5js' performance was bad.

I would also love to help correct this bug, but I'm a bit of a js newbie. :-/

So what do you think? Is setting the framerate to 120 a solution? Or will I just run into problems with browsers running my game twice as fast?

**Comment by kjhollen** [comment]
I'm really stumped on this one. Here's a branch that I think implements what's been discussed here. (Note that the draw code still uses requestDraw, but there's a shim that replaces it with requestAnimationFrame in src/core/shim.js)

https://github.com/kjhollen/p5.js/tree/framerate

But, I'm not seeing the performance improvement I'd expect. Lauren's taking a look now, but other eyes wouldn't hurt, too.

**Comment by kjhollen** [comment]
Okay. Here's an update on what we've learned.

p5 should only paint when we it gets permission via requestAnimationFrame callback, which is roughly 60 FPS. The interplay with setTimeout or SetInterval is strange, because it means you end up not requesting the frames often enough. So on some callbacks, you miss your chance and just over queue.

On the flipside, if requestAnimationFrame does trigger the callback but not enough time has passed per the user's set frameRate, animation may be skipped, but the browser may not be ready again until well after the desired time. What this looks like is that you can set a frameRate of 30 but actually see one that's more like ~24 because p5 & the browser refresh are out of sync.

Soooo, we can get a better frame rate by adjusting the "not yet ready to draw" time to be a little less by an epsilon value. I went with 5ms. The nature of this approach also means that the max frame rate is determined by the browser repaint rate (probably the same as the screen refresh rate?). For most people this will be 60 FPS.

Anyway, I'll put up a pull request soon.
