### ISSUE TITLE
DOM documentation for create elements is unclear

### ISSUE THREAD

**Issue by haschdl** [processing/p5.js#4072]
The documentation for all DOM methods in the format `createXXX` mentions 9 times that the new element is appended "to the container node if one is specified, otherwise appends to body". This leads the reader to interpret that a container node *can* be provided, for example as an argument to the function, however none such argument exists.
An example for `createSlider`:

https://github.com/processing/p5.js/blob/dd9cf98907829d42c1e7270924baf88b13349fd9/src/dom/dom.js#L467-L468

This information is very unclear. Digging into the code it seems like the "container node, if one is specified" refers to the parent element when one is working with "instance mode" in p5js. Quite a stretch to figure out by reading the documentation of p5.dom!

https://github.com/processing/p5.js/wiki/Global-and-instance-mode#specifying-parent-html-element

In my opinion it would be more informative to state something along the lines:

`The new element is appended as a child of the `body` element, unless the sketch is running in Instance mode and another parent has been  provided. See xxx (link to Global and instance mode documentation`.

Another option is to simply remove this sentence entirely. Advanced users of p5js who intentionally work in "instance mode" would know that elements will be appended to their parent of choice, and not to `body`.  

Would a fix to the documentation be enough?  I can submit a PR.

**Comment by stalgiag** [comment]
Thanks for the thorough issue! I think that a documentation fix should be enough.

I am in favor of removing the sentence altogether as you suggest. Instance-mode users will understand that they can operate within a specified container node, and since the vast majority of users are global mode we shouldn't confuse them with extraneous info in the main reference. Especially since that info will be implied, or redundant, to instance-mode users.
