### ISSUE TITLE
p5 WEBGL and canvas.parent() issue

### ISSUE THREAD

**Issue by wanbinkimoon** [processing/p5.js#4080]
Apparently declaring a WEBGL canvas is in conflict with positioning the same within a parent div 

```
    const canv = createCanvas(state.width, state.height, WEBGL);
    canv.parent('animation-coldx');
    canv.id('home-anime');
```

this code doesn't work while a keep declaring `WEBGL` as type of the canvas

UPDATE: is the `smooth` function that caused the error

**Comment by wanbinkimoon** [comment]
FIXED

Declating `smooth()` before the canvas fixed the issue

```
    smooth();
    const canv = createCanvas(state.width, state.height, WEBGL);
    canv.parent('animation-coldx');
    canv.id('home-anime');
```

**Comment by stalgiag** [comment]
Hi @wanbinkimoon thanks for the issue!

When you call `smooth()` or `setAttributes()` on an existing WebGL canvas, the canvas is removed and recreated. This is due to a limitation on setting attributes for WebGL rendering context.

That said, the new canvas should be automatically parent to the correct DOM element. Any references that you have made (such as `canv` in your posted code) will not point to the correct element anymore though.

**Comment by stalgiag** [comment]
Hi @wanbinkimoon I am going to close this issue since this is expected and necessary behavior. If you feel that some changes should be made feel free to ping me here and I will reopen. Thanks!
