### ISSUE TITLE
P5.Image.filter(BLUR) and filter(BLUR) produce different results

### ISSUE THREAD

**Issue by WojtekTB** [processing/p5.js#4092]
#### Nature of issue?

- [X] Found a bug?
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [X] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [X] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 0.9.0
- Web browser and version: Chrome 77.0.3865.90
- Operating System: Mac os X
- Steps to reproduce this: Draw an image and the use filter(BLUR); looks very different to applying filter to an image and then drawing that image

On p5js documentation it seems that p5.Image.filter is not even searchable anymore? It looks like when you apply blur to image through p5.Image.filter() it doesnt use Guassian blur like just using filter()

Is there a way to avoid this and save gaussian blurred image?

**Comment by stalgiag** [comment]
Thanks for the issue!

[p5.Image.filter](https://p5js.org/reference/#/p5.Image/filter) is here. Since it is a class method it is navigated to by first going to `p5.Image` in the main reference page.

I am having trouble reproducing. On Windows 10 with Chrome 77.0.3865.90
This code --
```js
  img.filter(BLUR, 5);
  image(img, 0, 0, width, height);
```
produces this for me:
![Screenshot (152)](https://user-images.githubusercontent.com/10382506/67309792-52612e00-f4b1-11e9-887b-ac2b5533c47a.png)

and this code ---
```js
  image(img, 0, 0, width, height);
  filter(BLUR, 5);
```
produces this:
![Screenshot (153)](https://user-images.githubusercontent.com/10382506/67309820-63aa3a80-f4b1-11e9-9ad3-58f69219efd8.png)

As you can see, other than my screenshot crop, these are identical. Also the code that modifies both p5.Image and canvas with filters is identical.

Let me know if you can provide an example of this working, or if it seems to be working differently on your specific machine.

**Comment by WojtekTB** [comment]
> Thanks for the issue!
> 
> [p5.Image.filter](https://p5js.org/reference/#/p5.Image/filter) is here. Since it is a class method it is navigated to by first going to `p5.Image` in the main reference page.
> 
> I am having trouble reproducing. On Windows 10 with Chrome 77.0.3865.90
> This code --
> 
> ```js
>   img.filter(BLUR, 5);
>   image(img, 0, 0, width, height);
> ```
> 
> produces this for me:
> ![Screenshot (152)](https://user-images.githubusercontent.com/10382506/67309792-52612e00-f4b1-11e9-887b-ac2b5533c47a.png)
> 
> and this code ---
> 
> ```js
>   image(img, 0, 0, width, height);
>   filter(BLUR, 5);
> ```
> 
> produces this:
> ![Screenshot (153)](https://user-images.githubusercontent.com/10382506/67309820-63aa3a80-f4b1-11e9-9ad3-58f69219efd8.png)
> 
> As you can see, other than my screenshot crop, these are identical. Also the code that modifies both p5.Image and canvas with filters is identical.
> 
> Let me know if you can provide an example of this working, or if it seems to be working differently on your specific machine.

Hey there!
yeah after playing around with it some more it seems that it specifically happens when you have images with a transparent background.

Here is an example image:
<img width="375" alt="Screen Shot 2019-10-22 at 7 05 05 PM" src="https://user-images.githubusercontent.com/34536619/67350196-eefded00-f4fe-11e9-9189-486f35c3576b.png">

Left is the image being drawn and then blurred, right one is the same image having a filter applied and then drawn.

The code is as follow:
`
function preload() {
  mainImage = loadImage("sword_test.png");
}

function setup() {
  myCanvas = createCanvas(400, 400);
  myCanvas.parent("mainSketch");
  background(0);
  mainImage = resizeNN(mainImage, 10);
  imageOfGlow = isolateColor(
    mainImage,
    { r: 255, g: 0, b: 255 },
    { r: 255, g: 0, b: 255 }
  );

  image(imageOfGlow, 0, 0);
  filter(BLUR, 6);
  imageOfGlow.filter(BLUR, 10);
  image(imageOfGlow, imageOfGlow.width, 0);
}
`

funnily enough, I discovered that compressing an image to a very small size and then resizing it back actually gives a similar result as to what I am looking for.

**Comment by stalgiag** [comment]
Now I understand a little better and [I am able to reproduce. ](https://editor.p5js.org/stalgiag/sketches/DRsy55WFU)

Perhaps this is related to the pixelDensity differences between p5.Image and the canvas? Requires further investigation.

**Comment by MGelein** [comment]
Some further investigation has shown that POSTERIZE, THRESHOLD both have a (minor) difference between the canvas filter (left) and the image filter (right), supposedly to do with pixeldensity.

![image](https://user-images.githubusercontent.com/13851284/69467005-9a13f780-0d86-11ea-8520-f0dded633dc7.png)

GRAY and INVERT however do not have this difference:

![image](https://user-images.githubusercontent.com/13851284/69467063-c3348800-0d86-11ea-8fc1-9192492c97be.png)

**Comment by DivyamAhuja** [comment]
I think this(blur problem) is happening because after drawing image to canvas and then applying filter the alpha/transparency is lost and background pixels replace transparent pixels and when we apply filter to transparent image first, it still has alpha value so it blurs differently cause of alpha value and then gets drawn on canvas 

https://editor.p5js.org/DivyamAhuja/sketches/Rk4Whc8N

https://editor.p5js.org/DivyamAhuja/sketches/RODBJhHe

**Comment by M-shameel-Alpha** [comment]
> I think this(blur problem) is happening because after drawing image to canvas and then applying filter the alpha/transparency is lost and background pixels replace transparent pixels and when we apply filter to transparent image first, it still has alpha value so it blurs differently cause of alpha value and then gets drawn on canvas
> 
> https://editor.p5js.org/DivyamAhuja/sketches/Rk4Whc8N
> 
> https://editor.p5js.org/DivyamAhuja/sketches/RODBJhHe

I tested it and can confirm that p5.Image.filter and filter gives different results on the same image in blur. This problem is also present on images without transparent pixels. 
I also observed that giving double the value of filter parameter used in p5.image.filter to filter yields same result.Other than different amount of blur in the edges.
Demonstrated in this sketch:https://editor.p5js.org/M-shameel-Alpha/sketches/TP7NQ9Q4k
I am new to open source and this is my first comment

**Comment by Prateek93a** [comment]
It might be late to comment on this, but since the difference in `img.filter(BLUR)` and `filter(BLUR)` is still noticeable, hence I would like to put forward my take on this. 

I think this is an expected behaviour. Calling `img.filter(BLUR)` calculates the pixel values for the image only. After that the updated pixels are placed on the canvas.

On the other hand, first drawing the image on the canvas and then calling `filter(BLUR)`  applies the calculation on whatever pixels are present on the canvas(image + background). Hence the difference is noticeable between when the image does not cover the entire canvas and when it does. This can be seen in the first comment by @stalgiag . There, the difference is not visible since image covers entire canvas. But in the sketches by @DivyamAhuja , @M-shameel-Alpha , the difference is visible, since the background pixels are also considered in the calculation of the new values in case of `filter(BLUR)`.

**Comment by WojtekTB** [comment]
Looks like at some point this has been resolved. Now the blur looks the same as long as the magnitude given to the filter is about the same
