### ISSUE TITLE
Warning: Task "eslint:build" failed. Use --force to continue.

### ISSUE THREAD

**Issue by abhisheknaiidu** [processing/p5.js#4115]
While running the " npm run grunt " command getting this Error.

![issue](https://user-images.githubusercontent.com/55599878/67596155-b91e6a00-f785-11e9-83d7-6b44b4f1f3b7.png)

**Comment by lmccart** [comment]
hi @abhisheknaiidu sorry you're having trouble. have you tried running `npm install`? did that command execute successfully?

**Comment by abhisheknaiidu** [comment]
Yes, that worked fine infact! but if I'm running npm run grunt command, its giving error.

**Comment by lmccart** [comment]
I see, thanks. Can you please post the full readout that is excerpted above?

**Comment by abhisheknaiidu** [comment]
yeah sure. So, if I am running the "npm install" command im getting these two as warnings, I don't think it will cause any problem.
![npm](https://user-images.githubusercontent.com/55599878/67632554-e58fce80-f8ca-11e9-9d44-bfa6b632f9da.png)


And after running "npm run grunt" command, im getting this error - 

![npm2](https://user-images.githubusercontent.com/55599878/67632570-1bcd4e00-f8cb-11e9-9af2-d8e27c85afc3.png)

is this fine? or should i provide any  more information ?

**Comment by jrlowent** [comment]
Hello All,

I am new to working in open source, and new to this project!  

I am getting a very similar error when I run "npm run grunt".  This error comes after following the instructions for the "Development Process" in the "Developer Docs", where I commit my first message to my local copy.

Thanks in advance for your help, and let me know how I can help you all.

Best,
Jake

**Comment by stalgiag** [comment]
Hi @abhisheknaiidu & @jrlowent thanks for your interest in contributing!

I tried to recreate this by setting up a new development environment and I wasn't able to recreate. I used the instructions from the [Development Process section](https://github.com/processing/p5.js/tree/master/developer_docs#development-process). 

My system setup is:
**os**: Windows 10 build 18362
**git**: version 2.23.0.windows.1 
**node**: v8.15.1
**npm**: v 6.41.1

Would you mind posting info about your development environment(s) as well? I have seen problems with node or npm version cause problems in the past.

**Comment by limzykenneth** [comment]
@abhisheknaiidu It seems the npm version you are using is very old (v3.5.2), can you update that to the latest version and see if that works?

**Comment by abhisheknaiidu** [comment]
@limzykenneth After using node version 6.1.2 also I'm getting a error, but it's different from previous scenario's 
![err](https://user-images.githubusercontent.com/55599878/67867818-fc475700-fb50-11e9-8392-6aec50b93878.png)

**Comment by lmccart** [comment]
can you try updating to node v12?

**Comment by abhisheknaiidu** [comment]
@lmccart I have been using node v13 only, it is not working in that version also!
![err2](https://user-images.githubusercontent.com/55599878/67936029-03be3d00-fbf1-11e9-8e30-aa6fdfa2635e.png)

**Comment by jrlowent** [comment]
> Hi @abhisheknaiidu & @jrlowent thanks for your interest in contributing!
> 
> I tried to recreate this by setting up a new development environment and I wasn't able to recreate. I used the instructions from the [Development Process section](https://github.com/processing/p5.js/tree/master/developer_docs#development-process).
> 
> My system setup is:
> **os**: Windows 10 build 18362
> **git**: version 2.23.0.windows.1
> **node**: v8.15.1
> **npm**: v 6.41.1
> 
> Would you mind posting info about your development environment(s) as well? I have seen node or npm version cause problems in the past.

=================================================================

Thank you for your help!  Here is my development environment:

OS:   Windows 10 version 1903 build 18362.449
Git:   2.23.0.windows.1
Node:   12.13.0
npm:    6.12.0

Here is my error message when running "npm run grunt" after arriving at eslint:build:

"Running "eslint:build" (eslint) task
No parser and no filepath given, using 'babel' the parser now but this will throw an error in the future. Please specify a parser or a filepath so one can be 
inferred.
No parser and no filepath given, using 'babel' the parser now but this will throw an error in the future. Please specify a parser or a filepath so one can be 
inferred.
No parser and no filepath given, using 'babel' the parser now but this will throw an error in the future. Please specify a parser or a filepath so one can be 
inferred.
No parser and no filepath given, using 'babel' the parser now but this will throw an error in the future. Please specify a parser or a filepath so one can be 
inferred.
No parser and no filepath given, using 'babel' the parser now but this will throw an error in the future. Please specify a parser or a filepath so one can be 
inferred.
No parser and no filepath given, using 'babel' the parser now but this will throw an error in the future. Please specify a parser or a filepath so one can be 
inferred.
No parser and no filepath given, using 'babel' the parser now but this will throw an error in the future. Please specify a parser or a filepath so one can be 
inferred.
No parser and no filepath given, using 'babel' the parser now but this will throw an error in the future. Please specify a parser or a filepath so one can be 
inferred.
No parser and no filepath given, using 'babel' the parser now but this will throw an error in the future. Please specify a parser or a filepath so one can be 
inferred.
No parser and no filepath given, using 'babel' the parser now but this will throw an error in the future. Please specify a parser or a filepath so one can be 
inferred.
No parser and no filepath given, using 'babel' the parser now but this will throw an error in the future. Please specify a parser or a filepath so one can be 
inferred.
No parser and no filepath given, using 'babel' the parser now but this will throw an error in the future. Please specify a parser or a filepath so one can be 
inferred.
⏎·······` [Error/prettier/prettier]e\Github\p5.js\tasks\build\browserify.js:22:17: Replace `·?·'p5-test.js'` with `

1 problem
Warning: Task "eslint:build" failed. Use --force to continue.

Aborted due to warnings.
npm ERR! code ELIFECYCLE
npm ERR! errno 3
npm ERR! p5@0.10.2 grunt: `grunt`
npm ERR! Exit status 3
npm ERR!
npm ERR! Failed at the p5@0.10.2 grunt script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:"

**Comment by jrlowent** [comment]
@abhisheknaiidu & @lmccart,

Yesterday, I Installed the latest version of Python, added it to the Windows path, and ran npm update.  I did not have the same issue after performing these steps.  I am not sure if all the steps are necessary, but my branch coincidentally worked after this.

If you have any comments or suggestions, I would appreciate them.  I hope this helps!

Best,
Jake
