### ISSUE TITLE
Add support for glTF file format

### ISSUE THREAD

**Issue by Jedi18** [processing/p5.js#4206]
#### Nature of issue?

- [ ] Found a bug
- [ ] Existing feature enhancement
- [x] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [x] WebGL
- [ ] Other (specify if possible)

#### New feature details:

As of now, the loadModel() function supports obj and stl file formats. I was wondering how difficult it would be to add support for the [glTF file format](https://www.khronos.org/gltf/) .

Three.js has a glTF file loader, which could be used for reference while developing it.

If it's not too difficult, I'd like to try implementing it, if anyone could guide me as to how to do it.

**Comment by stalgiag** [comment]
I have often thought that this would be cool. Especially since it would open the possibility of importing models with embedded animations.

Looking at the [three.js gltf loader](https://github.com/johh/three-gltf-loader/blob/master/index.js), it seems like this would be fairly involved to implement. A lot of the gltf features could be ignored, so a p5 loader would be significantly simpler but it would still require quite a bit of planning and consideration. Our goal with the WebGL mode isn't to offer a full-featured WebGL library (like Three.js), but instead to offer an entry point to 3D in the browser for learning, getting excited, and prototyping for people that are more comfortable with a p5-style approach to coding.

That said, there might be a way to pull this off that appeals to that mission, without adding too much complexity to the code base. The safest way to do this would be to offer a library that enables gltf loading, at least to start. Let me know if this is something you would be interested in doing, and I can help lead you through the different parts of the source that you would be interacting with.

**Comment by Jedi18** [comment]
Thanks for replying @stalgiag , and yeah I agree with you that offering a library would be a better option.

I'm interested in doing this, could you give me a basic rundown of how I should proceed with making this library?

Should we further discuss this by commenting on this issue thread or should I contact u some other way?

**Comment by stalgiag** [comment]
Hi @Jedi18 definitely!

I'd start by reading [the contributor doc on writing a library](https://p5js.org/contributor-docs/#/creating_libraries).

Then your library can add a prototype that loads a gltf. You will probably want to use another gltf parser for reading the file. After you have read the file, you want to convert the data into a format that is useful to p5. You can look [at the code for `loadModel` to ](https://github.com/processing/p5.js/blob/master/src/webgl/loading.js)get an idea of how this is done for the other file types. It should return a [p5.Geometry object](https://github.com/processing/p5.js/blob/master/src/webgl/p5.Geometry.js#L21).

At first, your loader can be simple, ignoring most of the features of the gltf file format. Once you have that working you can start to use more of the features. Eventually you might want to add features for playing model animations, or add an entire custom shader to support the gltf material features.

Hopefully this helps. I am excited to watch the progress!

**Comment by Jedi18** [comment]
I've been trying to find a suitable glTF parser in javascript but unfortunately have not been able to find one. Libraries like tinygltf are available for cpp however not in javascript.

Should I try implementing my own gltf parser?

**Comment by stalgiag** [comment]
I see. I incorrectly assumed that there would be already be a parser, but I see that the threejs loader uses its own. Perhaps the better approach for you would be to make your own open source general purpose gltf -> webgl parser, then you could make a second library to bridge that with p5. That would probably give you the best effort to use-value ratio. I am going to close this for now since it is getting a bit far afield from the core p5 development but feel free to @ me in any of these projects and I'll discuss them with you in their respective repos. Good luck!

**Comment by jagadeeshCoder** [comment]
nice idea about gltf parser in p5.js
