### ISSUE TITLE
Limited number of lightsources ?

### ISSUE THREAD

**Issue by DjangoCharango** [processing/p5.js#4234]
Is the numbers of lightsources (pointlight, directional ...) you can add to a 3-dimensional scene limited in some way?

I am trying to figure out, why some lightsources in my scene are being rendered, while others are not.

**Comment by stalgiag** [comment]
Hi @DjangoCharango yes there is a limit to the number of lighting uniforms that mobile devices and browsers support. So the hard limit is 5 per type at any one time.

Thanks for pointing this out. It is clear that this should be documented better.

I am going to add a `help wanted` label. The todo is to add a note in the inline reference for each of the lighting functions that explains that a sketch only supports a maximum of five lights of each type.

This should be done with:
- [directionalLight()](https://github.com/processing/p5.js/blob/master/src/webgl/light.js#L170)
- [pointLight()](https://github.com/processing/p5.js/blob/master/src/webgl/light.js#L273)
- [spotLight()](https://github.com/processing/p5.js/blob/master/src/webgl/light.js#L501)

**Comment by DjangoCharango** [comment]
Thanks a lot for your answer. My Tests show, that I can have 9 pointLights in Chrome. Do you know, where I could find more information, on how many light sources, browsers support ?

**Comment by stalgiag** [comment]
If you are using a version <= 10.2 of p5 then you will have an upper limit of 8. Not sure how you are getting 9. 

Version 1.0 will have a limit of 5 lights. This is because the number of uniforms is limited to 64 in iOS. We do not adjust the number of uniforms based on the browser/device, so these limitations will apply to all sketches made with p5. You can view [this PR for more info.](https://github.com/processing/p5.js/pull/4159). Also [here is the relevant shader](https://github.com/processing/p5.js/blob/master/src/webgl/shaders/lighting.glsl).

**Comment by blackboxlogic** [comment]
I came here to report the same problem five years later, found this issue marked done, found the merged PR... but the documentation doesn't mention the 5-per-type limit.
