### ISSUE TITLE
Releases branch removed

### ISSUE THREAD

**Issue by Samisaprogrammer** [processing/p5.js#4238]
#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [x] Other (specify if possible)

#### Details about the bug: 

- p5.js version: 
- Web browser and version: Chrome 79.0.3945.88
- Operating System: Windows
- Steps to reproduce this: Try downloading the Complete Library

The download button isn't working because the releases branch is deleted.

**Comment by AnuragGupta93** [comment]
@Samisaprogrammer  You are not facing an issue because of the deletion of the releases branch. 
The releases link is [here](https://github.com/processing/p5.js/releases). If you still needed to download the complete p5.js zip file, you can download it [here](https://github.com/processing/p5.js/releases).

As from my perspective, the issue is because of redirecting the web page when clicking on the download button and it will soon be solved.
