### ISSUE TITLE
Way to check if draw() is currently looping (i.e. if noLoop/loop was called)

### ISSUE THREAD

**Issue by maayanalbert** [processing/p5.js#4241]
#3547 ## Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [x] Other (specify if possible)

#### Feature enhancement details:
Would it be possible to expose whether draw is currently looping? This is perhaps a niche need, so is there any way to access this under the hood?

**Comment by ffd8** [comment]
@maayanalbert It would be really useful... was just searching the web and now issues for just this. Since you closed it the same day, did you find the answer? I thought there was something like `isLooping()` or `isDrawing()`, but I can't find anything now....

**Comment by hellonearthis** [comment]
You could set a drawing_flag to true at the start of the draw function loop and the last instruction in the draw function loop would set drawing_flag to false.

**Comment by limzykenneth** [comment]
You might be interested in looking at #3242

**Comment by ffd8** [comment]
While working on a p5 library, realized I needed a method to double check if the sketch was in a looping state or not, so this search began. This was the first issue I found, followed by the one above as mentioned by @limzykenneth which also referenced the same intrest in knowing the `loop()` state in #3486 . 

Tested [one technique](https://editor.p5js.org/ffd8/sketches/R3PN3QHrK) based upon suggestions above for a `_isLooping` property.. however once I tried implementing that to the p5 library, realized `this.____` is protected... since there's been 3 issues wanting to know the state of `loop()`/`noLoop()`, seemed reasonable to create a PR for a new `isLooping()` function that simply returns the `this._loop` private var. I think this will be really useful for any custom event handlers that doesn't already listen to the loop state (like `keyPressed()` + `mousePressed()` do).

Here's [the example](https://editor.p5js.org/ffd8/sketches/Vs92BaNds) for it's usage (the same example added to the references for the function)

Submitted PR as #4542
