### ISSUE TITLE
JSON not parsing correctly

### ISSUE THREAD

**Issue by robynitp** [processing/p5.js#425]
Comparing two pieces of JSON, which both seem to be properly formatted, one works with `loadJSON` and one doesn't:

works: http://api.openweathermap.org/data/2.5/weather?q=New+York&units=imperial  
doesn't work: http://api.openweathermap.org/data/2.5/station?id=5091

I get the error `Uncaught SyntaxError: Unexpected token : ` and then `Uncaught TypeError: Cannot read property 'responseText' of undefined` 

As a comparison, I tried consuming both URLs in jquery using $.ajax() with the 'json' dataType and they both worked. Interestingly, when I tried using the 'jsonp' dataType instead, the one that broke in p5 also broke in jquery.

**Comment by therewasaguy** [comment]
Revisiting this issue with a failing test case for loadJSON from a local JSON file with 4000+ lines, via @b2renger 

https://gist.github.com/therewasaguy/f8d65d200887d8dc6a8b#file-sketch-js

**Comment by robynover** [comment]
1. does it work with a subset of this data, say 100 lines?
2. i don't think this would break it, but there is a comma after the last item in the JSON array

**Comment by zaerl** [comment]
@therewasaguy It's not a valid JSON file.

**Comment by therewasaguy** [comment]
whoops, good call @zaerl ! It works...this would be a great spot to throw an error message as part of https://github.com/processing/p5.js/issues/657

**Comment by therewasaguy** [comment]
Closing this issue because additional methods can now be passed to preload with https://github.com/processing/p5.js/pull/538

The only remaining issue mentioned [here](https://github.com/processing/p5.js/issues/425#issuecomment-64131479) is that callbacks in preload (including JSONP stop everything. Moving that to a new ticket https://github.com/processing/p5.js/issues/668
