### ISSUE TITLE
Adding getPosition() for world coordinates with the p5.Camera class.

### ISSUE THREAD

**Issue by Liran648** [processing/p5.js#4275]
**Most appropriate sub-area of p5.js?**
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [x] WebGL
- [ ] Other (specify if possible)

Currently there's a way to get a p5.Camera object's position relative to its local coordinates system (eyeX, eyeY, eyeZ), but from what it seems there's no way to get the 'world' X Y Z coordinates of where the camera is positioned.
Could such a thing be added?

**Comment by sourabhdharpure** [comment]
Hello @stalgiag 
I would like to work on this issue
Can you please point me to the appropriate file or reference so that I can get the idea of the coordinate system?

**Comment by DivyamAhuja** [comment]
@stalgiag I would like to work on this issue.

**Comment by stalgiag** [comment]
@sourabhdharpure the relevant code is in [the p5.Camera file in src/webgl](https://github.com/processing/p5.js/blob/master/src/webgl/p5.Camera.js). 

@sourabhdharpure and @DivyamAhuja, before requesting to work on a new feature, we should be able to determine two things.
1. The feature is desirable for the community. People express interest in the feature.
2. The feature is technically feasible without an incompatible amount of work or restructuring.

A good way to address the first part is to simply add your own opinion. Do you think you would use a feature like this? Do you think it would be useful to others?

And the second part requires a bit of investigation. Look at the code that would be impacted by this, see what the limits of the structure are. See if you can figure out a simple way to implement the feature. If so, then add that suggested solution to the discussion. If not, check with people that have worked on the relevant code in the past. If we look at the history for that file we can see that most of the code was written by @AidanNelson. Your fellow community members can serve as a resource if you want to find out whether a feature is plausible or not.

This is all just to say that sometimes diving directly into a problem isn't the best way to go about solving it. Discussion and planning is a big part of working together. Good luck!

**Comment by AidanNelson** [comment]
Hi All, 

The eyeX, eyeY and eyeZ variables stored as part of a p5.Camera object refer to the camera's position in the world coordinate system.  So, @sourabhdharpure and @DivyamAhuja, from a technical perspective, adding a `cam.getPosition()` helper function is certainly possible, but these coordinates are also accessible directly if you've created a p5.Camera object using `createCamera()`.

See this example [here](https://editor.p5js.org/AidanNelson/sketches/KXtkecl_).

@Liran648 , what the p5.Camera documentation refers to when talking about coordinate systems (https://p5js.org/reference/#/p5.Camera) is that several of the p5.Camera functions (`move`, `tilt`, `pan`) operate with respect to the camera's own axes.  For example, if you use `cam.move(0,0,100)`, the camera will move forward (in the +Z direction) toward wherever it is pointing, even if it is pointing right (in the +X direction) in world-space.  I'm not sure the documentation does the best job of explaining the difference here...  Basically, the point of the `pan`, `tilt` and `move` camera functions are to make it easier to move the camera according to the camera's current point-of-view rather than the world system.  Does this make sense?

**Comment by DivyamAhuja** [comment]
I think you can directly access camera's coordinates in world space too using centerX, centerY, centerZ

**Comment by AidanNelson** [comment]
@DivyamAhuja `centerX/Y/Z` actually refer to the coordinate where the camera is pointed (i.e. the center of the sketch) rather than where the camera is located.  The terminology is a bit confusing here...

To access the cameras position, you can use `eyeX/Y/Z`.

**Comment by DivyamAhuja** [comment]
@AidanNelson I got it.....too much thinking earlier got me confused and I took centerX/Y/Z for eyeX/Y/Z and vice versa

and I think a helper function might be good for getting position now (after getting confused myself once) and it won't have any impact on existing code

**Comment by edwin-channel** [comment]
default camera position is (0,0,625)

**Comment by Gaurav-1306** [comment]
@davepagurek I think this issue can be closed as the doubt has been solved and adding one more function won't be necessary.

**Comment by Garima3110** [comment]
> adding a cam.getPosition() helper function is certainly possible, but these coordinates are also accessible directly if you've created a p5.Camera object using createCamera().
Is there any work required on this issue after what @AidanNelson has said!?
@davepagurek

**Comment by davepagurek** [comment]
I think getting the location of the camera is a solved problem. Getting the world position of an object, taking into account its transforms, is not, but it sounds like this issue is just for getting the camera's position, so I'll close this issue as completed and we can open a new one for that feature if that's something people are interested in.
