### ISSUE TITLE
Smooth Quad Distortion

### ISSUE THREAD

**Issue by Vamoss** [processing/p5.js#4288]
#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [X] WebGL
- [ ] Other (specify if possible)

#### New feature details:
Quad distortion now:
https://editor.p5js.org/Vamoss/sketches/vWdWD1q4
![image](https://user-images.githubusercontent.com/245841/74598546-16e70280-5052-11ea-9559-b4363c9dc156.png)

Smooth squad demo suggestion:
https://editor.p5js.org/Vamoss/sketches/1iaogZo2
![image](https://user-images.githubusercontent.com/245841/74598553-2e25f000-5052-11ea-8062-d98ab7905444.png)

**Comment by stalgiag** [comment]
I like your example. I don't think we will be adding more features before the 1.0 release but this is a simple enough addition to consider adding in some capacity in the future.

Do you think it would be possible to rewrite this in such a way that the existing `quad` function could take `detailX` and `detailY` optional parameters?

This feature sits in an odd place because it is a combination of `plane` and `quad` in that it offers the independent corner pin of the `quad` arguments with the flexible detail of the `plane` arguments.

**Comment by Vamoss** [comment]
Great, I saw 1.0 was released, congratulations!

Totally agree, the `quad` function could be already replaced by this one, as you can see, the default `detailX`and `detailY` is 8, if you change the default to 2, the result will be the same of `quad` function.
