### ISSUE TITLE
p5.js and p5.sound.js not work with different machine  

### ISSUE THREAD

**Issue by devanghingu** [processing/p5.js#4332]
Hey there,
i just made one front-end HTML project which take audio from user using `p5.js` and `p5.sound.js`.
Everything working fine with my HTML + p5 audio recording code. but when i integrated that HTML code with my DJANGO back-end. it works fine with only same computer(`http://localhost:8000/`). when i try to run DJANGO app from another machine(like `http://192.168.0.43:8000/`) it raise 
following error in browser console.

![Screenshot_20200228_114015](https://user-images.githubusercontent.com/43535635/75515158-4f59e980-5a1f-11ea-8857-72e125a2aa13.png)

i don't know what happening around there. 
please help me. i m very depressed 
thanks.

**Comment by limzykenneth** [comment]
@devanghingu Can you fill out the issue template just so that we have enough info to debug your situation? Initial thoughts is that it may be due to the security policy of browsers and a `http://` connection to `192.168.x.x` address is not considered secure unless it is served over `https://`, but again, to confirm I will need more information.

**Comment by devanghingu** [comment]
Actually i figure out this issue. and ( @limzykenneth )you are right there. its happening due to security policy. so what i need to do when i want to test with my local machine?

**Comment by limzykenneth** [comment]
There's no straightforward way if you want to test it from a local machine to another local machine, what I would do in this case is to upload the site to a dev server online and test it through that.
