### ISSUE TITLE
p5.vector math signatures with the target argument return undefined when passed values

### ISSUE THREAD

**Issue by aferriss** [processing/p5.js#4348]
#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [X] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Details about the bug: 

- p5.js version: Master
- Web browser and version: All major browsers
- Operating System: OSX
- Steps to reproduce this:

I noticed that the vector signatures that include a `target` argument only work correctly when a `p5.Vector` is passed in. 

For example this works:

```javascript

let target = new p5.Vector(0, 0, 0);
let v0 = new p5.Vector(1, 1, 1);
let v1 = new p5.Vector(2, 2, 2);

p5.Vector.add(v0, v1, target); 
// target is (3, 3, 3)
``` 

This does not:

```javascript

let target;
let v0 = new p5.Vector(1, 1, 1);
let v1 = new p5.Vector(2, 2, 2);

p5.Vector.add(v0, v1, target); 
// target is undefined
``` 

I believe this is happening because when target is `undefined` it gets treated as a value, and so it never gets changed. When a p5.Vector get's passed in, it gets treated as a reference, and the function works as expected.

Is the signature with `target` even necessary? You can accomplish the same thing by using the return of the vector operation
```javascript
let v0 = new p5.Vector(1, 1, 1);
let v1 = new p5.Vector(2, 2, 2);

let target = p5.Vector.add(v0, v1); // target is (3, 3, 3)
```

The only other solution I can think of here is to log a warning to alert the user that the value they've passed in is not a `p5.Vector`

**Comment by limzykenneth** [comment]
I believe you are right on the pass by reference theory, don't have the capacity right now to test it out myself though.

I'm not sure how often the signature that takes `target` is used but since it is a publicly documented API we can't exactly remove it at this point since it is a breaking change. The idea of logging a warning could work though.

**Comment by DivyamAhuja** [comment]
![Screenshot from 2020-03-05 21-02-16](https://user-images.githubusercontent.com/39771050/75997039-c6621700-5f24-11ea-87b8-baab04978147.png)
@limzykenneth Something like this?
If this is okay then I can work on this...am learning a lot by going though the source code

**Comment by aferriss** [comment]
@limzykenneth ok, added in all the signatures that I could think of. It makes the docs page look a little scary imo, but it should at least be comprehensive.

![Screen Shot 2020-03-06 at 10 58 38 AM](https://user-images.githubusercontent.com/3698659/76113771-92750900-5f99-11ea-8911-4fb13b1140df.png)

**Comment by aferriss** [comment]
@DivyamAhuja I think it might make sense to wait until #4322 gets merged, but if you'd like to work on this that'd be great!

Maybe expand the warning to mention that the `target` parameter needs to be a `p5.Vector type`

**Comment by DivyamAhuja** [comment]
@aferriss Sure I will wait for #4322 to get merged as I think same has to be done for all static methods like add sub mult div which may take target vector as argument

**Comment by aferriss** [comment]
@DivyamAhuja we're all merged up!

**Comment by DivyamAhuja** [comment]
@aferriss so while implementing this, this time it was not logging(was showing hidden) in chrome(Ubuntu 18.04 LTS) but was working fine in Firefox. so any idea why this would've been happening and _friendlyError() system appends function name to [https://p5js.org/reference/#/p5/]("https://p5js.org/reference/#/p5/") URL so I was not able to correctly redirect to reference page for p5.Vector.add and others so I left it as blank string so that it redirects to home of reference page.

**Comment by aferriss** [comment]
@DivyamAhuja Can you clarify, what wasn't logging? I think you can probably just use `console.warn` instead of fes since the vector math function urls are a little weird.

**Comment by DivyamAhuja** [comment]
FES for logging link to reference has this call
![Screenshot from 2020-03-18 13-17-36](https://user-images.githubusercontent.com/39771050/76937504-ecbb8580-691a-11ea-99b0-e45889a48244.png)

but p5.Vector functions have reference URL as such -
https://p5js.org/reference/#/p5.Vector/add

so I don't think we can pass something to func parameter to link it to reference page for function, so i just left it empty so that it can link to home of reference page.

and as for console.warn, I didn't want it to be logged when FES is disabled so I just didn't use it.

**Comment by aferriss** [comment]
@DivyamAhuja Out of curiosity, what does the url look like that gets passed to FES?

**Comment by DivyamAhuja** [comment]
@aferriss The full URL depends upon `method` parameter that we pass to `p5._friendlyError(message, method)` function, which calls a `report(message, func, color)` method
and whatever string we pass as `method ` parameter gets appended at end of `http://p5js.org/reference/#p5/` URL string.
So if I pass `'add'` it will link to `http://p5js.org/reference/#p5/add` and if I pass `'p5.Vector.add'` then it will link to `http://p5js.org/reference/#p5/p5.Vector.add` and if I pass `'.Vector.add'`, It will link to `https://p5js.org/reference/#p5/.Vector/add` which doesn't work and real link to reference is https://p5js.org/reference/#/p5.Vector/add or https://p5js.org/reference/#p5.Vector/add .

**Comment by aferriss** [comment]
@DivyamAhuja Makes sense, thank you for explaining. Can you please open a separate issue regarding this problem?

In the meantime I think your solution of leaving the method parameter empty is fine.

**Comment by DivyamAhuja** [comment]
Yeah sure @aferriss . BTW I wanna take WebGL API for p5 as project for GSoC 2020. but am not sure about how much I can add to it, like it lacks Shadows , some Material System flaws and  optimizations, but idk where I can talk about it as Possible Mentors for project are unknown for now. So can you guide me through it?

**Comment by aferriss** [comment]
@DivyamAhuja That's great! I'm mentoring this summer for gsoc and looking for students interested in helping out with webGL. I think there's probably lots of room for bug fixes and there's quite a few webGL related issues open right now. 

Probably best to move this discussion over to the processing forums [here](https://discourse.processing.org/c/summer-of-code/26). I believe the first step would be proposing a project on that board. You can take a look to see what some of the other students have started. There's also a bunch more info [here](https://github.com/processing/processing/wiki/Project-List) as well.
