### ISSUE TITLE
p5.Vector.Cross incorrect example

### ISSUE THREAD

**Issue by vanyamil** [processing/p5.js#4353]
### Issue description
The first example on the page linked below is incorrect : v1.cross(v2) returns a new PVector; it does not modify v1.

### URL(s) of affected page(s)
https://p5js.org/reference/#/p5.Vector/cross

### Proposed fix
Remove the first example. There is already emphasis in the description that this is the correct behaviour.

**Comment by DivyamAhuja** [comment]
Yeah You are right.
Can I work on this and change the example?

**Comment by limzykenneth** [comment]
From my understanding, "static" here is the programming sense of the word "static", in that it is a method that is called directly from the class instead of the object instance. In this case "static" and "non-static" does not make any guarantee about whether the callee or arguments are modified or not.

The "static" keyword is also part of ES6 class syntax so although it is a jargon, it is still part of the Javascript language so it wouldn't be incorrect to use it this way.

**Comment by DivyamAhuja** [comment]
```
let v1 = createVector(1, 2, 3);
let v2 = createVector(1, 2, 3);

v1.cross(v2); // v's components are [0, 0, 0]
```
In here maybe the person wanted it to be like
```
let v = v1.cross(v2);
```

as both static and non-static methods for cross product return a vector instead of setting value of vector v1 as cross product

so I think example must be updated
to 
```
let v1 = createVector(1, 2, 3);
let v2 = createVector(1, 2, 3);

let v = v1.cross(v2); // v's components are [0, 0, 0]
```

**Comment by limzykenneth** [comment]
@DivyamAhuja Yes the example should be updated to show that the value is return but the vector itself is not modified. But the use of "static" and "non-static" on the docs is not incorrect.

**Comment by DivyamAhuja** [comment]
Yeah the use of "static" and "non static" is correct.
