### ISSUE TITLE
Switch to more precise timing in p5js

### ISSUE THREAD

**Issue by kroko** [processing/p5.js#437]
Well, I could implement more precise timing myself and do a pull request, but were to start?

Everywhere time deltas in p5 are used, for example millis(), much more precise solution could be used.

First we need to place a polyfill somewhere:
```
// use window.performance() to get max fast and accurate time in milliseconds
window.performance = window.performance || {};
performance.now = (function () {
    return performance.now ||
            performance.mozNow ||
            performance.msNow ||
            performance.oNow ||
            performance.webkitNow ||
            Date.now
})();

…

this._startTime = performance.now();

...
p5.prototype.millis = function() {
  return performance.now() - this._startTime;
};

```
Also use more precise timing for ```this._lastFrameTime```, ```this._frameRate``` calculation… well in so many places as I return to the first question… where to start?
Remember that ```performance.now()``` can be used only for runtime deltas, it does not use epoch as reference, but milliseconds since webpage started to load, so it may not apply to all timing events in p5js, but surely it should be used at least for the two cases mentioned above (millis fcn thst is used for precise timing of events and framerate calculation).

https://developer.mozilla.org/en-US/docs/Web/API/Performance.now
http://updates.html5rocks.com/2012/08/When-milliseconds-are-not-enough-performance-now

**Comment by kjhollen** [comment]
I've been looking at this one. I think ``millis()`` and frame rate are the only things we can optimize here. ``Date.now()`` is probably faster than ``new Date().getTime()`` because it goes ahead and gives you the millisecond value without having to make a date object—``years()``, ``month()``, etc. all defer to ``Date`` methods that we'd have to re-implement to avoid making a date object. Sounds risky.

I'm still trying to figure out updating ``millis()`` and frame rate calculations to use a cached ``performance.now()``, which I think we should be able to do. The present complication is that ``performance`` isn't available in our tests.
