### ISSUE TITLE
createSelect does not handle existing dom elements

### ISSUE THREAD

**Issue by fenilgandhi** [processing/p5.js#4394]
#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [x] Other (dom)

#### Details about the bug: 

- p5.js version: 1.0.0
- Web browser and version: Chrome 80.0.3987.122
- Operating System: Manjaro 19.0.2 Kyria (Linux 4.19.108-1-MANJARO)
- Steps to reproduce this:

As per the documentation, [`createSelect`](https://p5js.org/reference/#/p5/createSelect) should be able to take an existing DOM select element and return a `p5.Element` of select type. But the current implementation does not handle such a case and throws an Error. It only handles either a `p5.Element` or creates a new one. Is it documentated wrong or implemented wrong ?

**Comment by fenilgandhi** [comment]
For reference, here's a sketch file
https://editor.p5js.org/fenilgandhi/sketches/SXJ_YnVM

**Comment by fenilgandhi** [comment]
And for future reference if i find myself in a condition where the documentation says it should do something but the implementation does not, what should be my source of truth, documentation or implementation or something else ? Can someone help me out on this one. @lmccart, @limzykenneth

**Comment by limzykenneth** [comment]
It depends. For the most part because we are now at semver 1.0.0 it means breaking changes cannot be introduced within a major version, so it means the implementation should take priority, unless it is obviously incorrect. For this case however, the implementation contradicts with itself which means it is a bug that should be fixed in the implementation itself.

As I understand it, `createSelect()` here is not meant to be used for selecting DOM element, `select()` should be used and when that has selected a `<select>` element it can then be passed to `createSelect()` as an argument to add specific methods to it. Though the documentation could also use some clarifications as well.
