### ISSUE TITLE
Updating BrowserSync info in Wiki

### ISSUE THREAD

**Issue by jeffThompson** [processing/p5.js#4416]
I've been learning to use P5JS with Sublime and have a few updates that I think will be helpful in the [`browser-sync` section of the `Local Server` wiki page](https://github.com/processing/p5.js/wiki/Local-server). 

TLDR: there is an option listed that's not necessary and another that might be helpful for folks to include. Happy to update if you can add me as a contributor!

**Comment by limzykenneth** [comment]
Hi @jeffThompson, which specific part of the `browser-sync` option are you thinking of changing?

**Comment by jeffThompson** [comment]
@limzykenneth – a couple of things:

* The wiki suggests both `-f` and `-w`, but from my research it looks like `-f` is for specifying specific files it should watch. I think just `-w` makes the most sense. I'd also maybe suggest expanding it to the full `--watch` just so it's clearer without looking at the docs  
* I think a link to the `browser-sync` doc page would also be helpful, especially because it has so many other options  
* I found the `--no-notify` option to be nice; it keeps `browser-sync` from showing it's little popup text every time it refreshes  
* Generally, I think the Node section is a little cluttered too and could be cleaned up

**Comment by jeffThompson** [comment]
Bump! I know P5JS is all about having a high-quality  and carefully-moderated community, but this approval process is a barrier to participation.

**Comment by limzykenneth** [comment]
@jeffThompson I understand you may be frustrated over the lack of progress on this issue but I find my perceived passive agressiveness from your last comment a bit demotivating. The only reason we don't open wiki edit access to the public is because of past malicious edit. 

While I can make the edits to these sections myself I would prefer to leave the opprtunity to a new contributor like you. At the same time I do not have the authority to give you direct edit access to the wiki. I will ping @lmccart here about this but do understand that the contributors here are working on the project mostly on a volunteer basis and we may not have the time to keep up with everything. Yes we may miss thing now and then and it's fine to ping us when that happens but that's no reason to be passive aggresive about it.

If you simply wish the section to be edited and not keen on doing the edits yourself, just let me know here and I'll make the changes. Thanks.

**Comment by lmccart** [comment]
Hi @jeffThompson thanks for your suggestions and feedback. And thanks @limzykenneth for your honest and open response.

As @limzykenneth mentioned, this is a primarily volunteer-driven project, so it does mean that we are at times unable to be as responsive as we'd like. Things may be especially slow right now because I have recently [stepped down as project lead](https://medium.com/processing-foundation/making-space-for-the-future-of-p5-js-d3c6bd3da9ac) and we are in the process of launching a call for a new one. This process has unfortunately been slowed further by the ongoing health crisis, where I'm finding myself struggling to focus, as I'm sure others are too. So your patience and understanding during this period is very much appreciated, as is your enthusiasm to improve the project. :)

@jeffThompson I'm adding your access right now so you can go ahead and make the wiki edits, they all look great. Thank you. @limzykenneth, thanks for all you've been doing to keep things rolling with this project. I'm going to see if I can bump up your access so you also have the ability to grant access and I don't bottleneck things in the future.

**Comment by jeffThompson** [comment]
@limzykenneth – sorry, didn't meant to come across as passive aggressive at all.

I just wanted you all to know the perspective of a first-time contributor to the project. I have a number of (muuuuch smaller) open-source projects that I administer and totally get the time commitment required even on those. I'm also a very long-time Processing user and am deeply appreciative of the huge community that makes it possible.

Not being privy to the behind-the-scenes issues you all might had in the past, I was just raising the downside of such a controlled environment is that new contributors feel like there's a black-box vetting process. The Wiki is a strange thing without the formal mechanism of a fork, etc too so I'm sure that's part of it. Anyway, this might totally be something already on your radar, but just my two cents...

PS @lmccart – huge thanks for all your work on this project! My students are wrapping up an interactive face-tracking/mask project in P5JS and the results are super fun. Also thanks for access – I'll happily make those edits myself asap!

**Comment by limzykenneth** [comment]
@jeffThompson No worries. You do raise an important point about the feeling that the process can seem black-boxed and that's something that we can definitely address better. There are recent discussion about introducing section by section stewardship of the project so if a new contributor have particular question or interest on a part of the project, they will have a clearer picture of who to contact. That may come when we transition to a new project lead and is something I personally very look forward to.

Also I agree the wiki format isn't the greatest which I think is also part of the reason why the contributor docs that were previously contained in the wiki moved to being committed directly in the repo. I think future efforts to move ever more content out of the wiki onto the repo or the website wouldn't be a bad idea.

**Comment by jeffThompson** [comment]
Thanks @limzykenneth – I'll close this now since Lauren added me to the repo. Even after just a few days, I see the issues coming into my email and get a tiny view of what maintaining this project must be like :)

(Off-topic, I really love the wiki format overall, but my experience has mostly been Wikipedia where edits are open to all. Wikis are really hidden on Github, so I agree moving them away from the behind-the-scenes code-base to somewhere more public would be a great asset.)

**Comment by lmccart** [comment]
Thanks @jeffThompson. For background, our thinking with the wiki is that all of the tutorials are linked from https://p5js.org/learn/, so people don't need to find this wiki on their own. We felt that editing the wiki pages, while still requiring a step of getting access, was a lower barrier to entry than cloning, setting up, and editing the p5.js-website, and submitting a PR. This intuition may be incorrect though, totally open to moving these over if these don't make sense here.

Thanks again for your help. And a note if you didn't find this already, you can "unwatch" the repo and you won't get an email notification with every comment and issue. :)
