### ISSUE TITLE
Why does the error comes even though the function is defined?

### ISSUE THREAD

**Issue by Rohitaicyber** [processing/p5.js#4462]
here is the link to my project https://editor.p5js.org/rohitgokul817/sketches/yhOcLU2KX

please help me to figure out the error the function is defined buti am getting the error Uncaught ReferenceError: antsweets is not defined (sketch: line 164)

please help me as soon as possible

**Comment by limzykenneth** [comment]
@Rohitaicyber I'm not getting the error you mentioned in the link you provided. There is another error which stems from using `randomNumber()` when it isn't defined anywhere in the code, I assume you meant to use `random()` instead?

In any case, I'm closing this because we usually use github issues only for bug reports and feaature requests. If you need help with your code do post them on the [forum](https://discourse.processing.org). Thanks.
