### ISSUE TITLE
Add a way to point to unreleased version of p5.js

### ISSUE THREAD

**Issue by diegodorado** [processing/p5.js#4480]
How could one point npm to the latest (unreleased) version of p5.js?

In npm one can point to a specific repo#branch, but something related to the build process of p5.js makes this impossible since lib folder is empty.

I would like to be able to install the master branch of p5 form npm in order to take advantage of yet unreleased features, in this way

`npm install "processing/p5.js#master"`

But if I do so, I get an empty lib folder....how could one overcome this trouble to get latest features and bug fixes properly?

Thanks

**Comment by limzykenneth** [comment]
@diegodorado I don't know that npm supports installing from a specific branch, unless you are talking about installing with git repository (eg. `npm install git://github.com/npm/cli.git#v1.0.27`).

**Comment by diegodorado** [comment]
npm (and yarn) does support installing form a specific branch. You do so like this
`npm install "processing/p5.js#master" ` for github repositories

**Comment by limzykenneth** [comment]
That is the same as `npm install git://github.com/processing/p5.js.git#master` just a shorten form, it is still installing from github and not NPM.

**Comment by diegodorado** [comment]
Yes, but that is not the problem. 
The thing about this issue is that the lib folder is empty, or there is no `prepare` npm script to generate the lib files

**Comment by limzykenneth** [comment]
Installing from a git repository is not something that we support as the build artifacts are not commited into the library. As for `prepare` script, without the dev dependencies installed, which npm wouldn't for project dependencies, the library cannot be built. 

It is not common for JS library to support installing directly from github like this, mainly because of the logistics of supporting unreleased version of the library being too difficult and potentially confusing to the users.

**Comment by lmccart** [comment]
we are not supporting the distribution of unreleased versions of p5.js due to the overhead required and the possibility it could cause confusion for beginner users if they end up using one of these versions. the best way to get an unreleased version is to clone the repository and build your own copy.
