### ISSUE TITLE
Supporting existing canvas elements for createGraphic

### ISSUE THREAD

**Issue by valentinptc** [processing/p5.js#4564]
#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Dom
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [x] WebGL
- [ ] Other (specify if possible)

#### Feature enhancement details:

Allow the use of existing canvas elements for createGraphic. This makes it much easier to integrate p5js with existing content. 

#### Solution
https://github.com/processing/p5.js/pull/4563

**Comment by valentinptc** [comment]
@limzykenneth why did you closed this pull request without comments? Is it not a good idea?

**Comment by limzykenneth** [comment]
The implementation should be worked out in the issue first before a PR should be filed. The PR is closed so that we can focus discussions in the issue instead of splitting it between the issue and the PR.

**Comment by ffd8** [comment]
Would love it if this PR could be accepted! Just tried making the case to do so on the [v1.6 open call](https://github.com/processing/p5.js/issues/5966#issuecomment-1407771781) by @Qianqianye 

The first use case I can imagine is [using p5.js as a canvas texture for A-Frame](https://github.com/stemkoski/A-Frame-Examples/blob/master/canvas-texture.html), specifically for AR usage. Anywhere else that one would first create a canvas, then populate it with p5.js content would be relevant. I could also imagine it being useful for using p5.js as the engine within a fancy web-app where various views (`createGraphics()` content) is provided within draggable canvas elements across a website – all run from a single sketch.

**Comment by ffd8** [comment]
Quick add-on, while this PR was specific to modifying how `createGraphics()` is implemented  – what if it was also an option for the main canvas, created by `createCanvas()` – allowing one to use an existing canvas as well, not only an [instance container](https://p5js.org/examples/instance-mode-instance-container.html)? Same reasoning as above, A-Frame texture is the main one I think of where the canvas needs to already exist, but perhaps there are other uses?

**Comment by limzykenneth** [comment]
@ffd8 I think this is fine to add and with some minor adjustment in #4563 it should be ok, although I'm not quite satisfied with the parameters ordering, there probably isn't a non-breaking way to solve that (ideally the `canvas` is not the last parameter for `p5.Graphics` and `createGraphics`).

**Comment by Qianqianye** [comment]
Thanks for restarting this conversation. I'm inviting @davepagurek to this discussion as well.

**Comment by ffd8** [comment]
@limzykenneth I agree with the order being a little strange.. though it's probably the only way to approach it in a non-breaking way. Perhaps with P2D being the default renderer, `createGraphics()` could check if that 3rd value was a renderer (`P2D` or `WEBGL` if thats it?) or an html element (canvas)? Then one could use just 3 values, `createGraphics(width, height, canvas)` or 4 `createGraphics(width, height, renderer, canvas)`?

**Comment by davepagurek** [comment]
We could maybe do something like `createGaphics([element], width, height, [mode])` if we want to support supplying the canvas first, relying on checking whether the first argument is a number or not to see how to read the arguments.

Although, just a heads up, whenever one calls `setAttributes` on a WebGL graphic/canvas, it recreates the canvas here: https://github.com/processing/p5.js/blob/main/src/webgl/p5.RendererGL.js#L341 I'm not sure if it's possibly to get a new WebGL context out of a canvas element with new attributes if one has already done so earlier (unless someone knows a way to do that?), so we'd have to add a disclaimer that you would need to just accept whatever attributes are in the existing canvas or disable `setAttributes`. We might also want to detect existing values of attributes, like whether or not the canvas has an alpha channel, so `_renderer._glAttributes` is still correct.

**Comment by ffd8** [comment]
Personally I find it alright to mention the `[element]` towards the end of the `createGraphics()` list of params, so one enters as usual, then under special circumstances says "oh yeah and draw it in that canvas"...?

As for the context/setAttributes – I'm a total canvas/getContext noob.. but potentially couldn't it run a [`getContextAttributes`](https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/getContextAttributes) on the existing canvas to make sure nothing is lost?

**Comment by davepagurek** [comment]
@ffd8 right, we'd have to use that to populate `_render._glAttributes`, so that shouldn't be a problem! It would just be any subsequent calls to `setAttributes()` that we wouldn't be able to support.

**Comment by Qianqianye** [comment]
Thanks @ffd8 @limzykenneth and @davepagurek for sharing your thoughts. What will be the good next steps to move this issue forward?

**Comment by limzykenneth** [comment]
If @valentinptc is still interested in moving forward with the existing implementation in the closed PR we can reopen it and implement any additional changes if required. Otherwise @ffd8 if you would like to provide an implementation or base a new PR off of work already done in #4563 that is fine as well.

We can go with the signature of `createGraphics(width, height, canvas)` and `createGraphics(width, height, renderer, canvas)` overloading the function signature with checking if third parameter's type. For WebGL I guess we will need to specify the quirk with `setAttributes()` in the documentation, ideally in documentation both of `createGraphics` and `setAttributes`.

**Comment by Qianqianye** [comment]
Hi I'd like to bump up this issue for the upcoming release. @ffd8, @limzykenneth @davepagurek, please feel free to go ahead with a fix since we haven't heard back from @valentinptc since we checked in February.
@valentinptc, please feel free to chime in if you have any thoughts. Thanks!

**Comment by ffd8** [comment]
Since we hadn't heard from @valentinptc, I've started an [implementation](https://github.com/ffd8/p5.js/tree/dev-existing-canvas) of this within the 1.6.0 codebase. It works as per the initial idea for the `createGraphics()` function. There's two ideas mentioned above, which would be nice to have, however it requires help from others:

- allow 3rd param to be either renderer or canvas (if no renderer is given, defaults to P2D).
- adapt for `createCanvas()` which prevents the need to use a `get()` of main canvas (easier for beginners/efficient).

The current usage would look like:
Within HTML doc:
```html
<canvas id="canvasAR"></canvas>
```

Within sketch.js:
```js
// within setup()
ar = createGraphics(width, height, P2D, document.getElementById('canvasAR'));

// at bottom of draw()
// grab canvas and place on AR layer
ar.image(get(0, 0, width, height), 0, 0, ar.width, ar.height)
```
(for context, this is for a web-based AR workflow, once part of p5.js, will create a tutorial to share)

@limzykenneth + @davepagurek perhaps you can have a look at my implementation within [rendering.js](https://github.com/ffd8/p5.js/blob/04d90f24eb637c4b1bc47822ebf8eff4c348aff0/src/core/rendering.js#L219) + [p5.Graphics.js](https://github.com/ffd8/p5.js/blob/04d90f24eb637c4b1bc47822ebf8eff4c348aff0/src/core/p5.Graphics.js#L17) to see how the 3rd/4th parameter issue could be resolved? And if you have ideas for `createCanvas()` or if that should be held off for potential future update.

**Comment by davepagurek** [comment]
@ffd8 I think you can do something like this:
```js
if (arguments[2] instanceof HTMLCanvasElement) {
  renderer = constants.P2D;
  canvas = arguments[2];
}
```

Our friendly error parameter validation function looks at the method signatures in the docs, so you'd have to add a second docstring with the renderer mode omitted. Here's an example of another function that has method overloads so you can see how they have multiple docstrings with different signatures (if you open the source file and scroll down there's another one below): https://github.com/processing/p5.js/blob/3b0d1328b96a6d46dfc77e3f33e97077934967fa/src/image/loading_displaying.js#L816-L822

**Comment by ffd8** [comment]
@davepagurek thanks! Your snippet for checking the 3rd parameter works great. Now I'm trying to do this overload technique, but am running into the issue of having the same param names... If I try adding the following docstring:
```js
/**
 * @method createGraphics
 * @param  {Number} w width of the offscreen graphics buffer
 * @param  {Number} h height of the offscreen graphics buffer
 * @param  {Object} [canvas] existing html canvas element
 * @return {p5.Graphics} offscreen graphics buffer
 */
```
I get the following error on doc compilation:
`Warning: for p5.createGraphics() defined in src/core/rendering.js:267, description for param "w" should only be defined in its first use; subsequent overloads should leave it empty ("<p>width of the offscreen graphics buffer</p>\n" !== "") Use --force to continue.`

If I give them unique names, like `gw, gh, gcanvas`, then I get this strange docs output, which should be avoided..
<img width="1108" alt="Screenshot 2023-06-19 at 23 06 16" src="https://github.com/processing/p5.js/assets/570957/b736146b-202c-4b9b-bc72-ce86359f6cdb">

What do I need to give as that docstring to simply have it accept the 2 variants (or can you point me to an example that does this?):
```
createGraphics(w, h, [renderer], [canvas])
createGraphics(w, h, [canvas])
```

**Comment by davepagurek** [comment]
@ffd8 Does it work if in the first overload, you have:
```
@param  {Number} w width of the offscreen graphics buffer
```
and in the second overload, it's just this?
```
@param {Number} w
```

**Comment by limzykenneth** [comment]
Yes as @davepagurek shown, for overloading parameters the descriptions shoud stay the same if the parameter name are the same so only need to be defined once. ie something like:

```
/**
 * @method createGraphics
 * @param  {Number} w width of the offscreen graphics buffer
 * @param  {Number} h height of the offscreen graphics buffer
 * @param  {Object} [canvas] existing html canvas element
 * @return {p5.Graphics} offscreen graphics buffer
 */
```

```
/**
 * @method createGraphics
 * @param  {Number} w
 * @param  {Number} h
 * @param  {Object} [renderer] P2D or WEBGL
 * @param  {Object} [canvas]
 * @return {p5.Graphics}
 */
```

**Comment by ffd8** [comment]
@davepagurek @limzykenneth - perfect, thanks, that was the answer to overload!

What are your thoughts about `createCanvas()` also being modified to accept an existing canvas? Or that's bonus for the future and better to wrap this up for the pending 1.7.0 release?

**Comment by davepagurek** [comment]
I think if we're allowing it for graphics and are already having to document the caveat about how `setAttributes` recreates the canvas, it would make sense to allow the same things for `createCanvas`. Anything I'm missing @limzykenneth?

**Comment by limzykenneth** [comment]
Yeah I think if we are doing it for createGraphics it would make sense to do it for createCanvas as well if it is possible.

**Comment by ffd8** [comment]
Sounds good – and now, the question, could I get some help/tips in this direction? I made one failed attempt (tried wrapping big chunks of code around an 'if' the canvas isn't provided.. but didn't work..)

**Comment by davepagurek** [comment]
I think passing a canvas should ideally get us into this branch: https://github.com/processing/p5.js/blob/3b0d1328b96a6d46dfc77e3f33e97077934967fa/src/core/rendering.js#L72-L81 ...where it adds the default canvas attributes. We'd probably just want skip line 74 where it actually makes a new canvas.

**Comment by ffd8** [comment]
Figured out the [`createCanvas()` implementation](https://github.com/ffd8/p5.js/blob/a3eb3de15c83823fa31f9c115abc8e6c9265c93f/src/core/rendering.js#L70)! In the process, learned that `setup()` creates an initial 100,100 canvas that gets immediately replaced when calling `createCanvas()`. One thing that is a little confusing is whether the existing canvas remains visible (`createCanvas()`) or is made hidden (`createGraphics()`) – but with that, they act as expected. It's then possible for one to use CSS to hide/show on demand. 

Here's the [branch](https://github.com/ffd8/p5.js/tree/dev-existing-canvas) – I tried adding very minimal examples to both functions (essentially just adding a `document.getElementById('canvas')` param) – but got a strange *works* error while running `npm run test`... It's probably not necessary anyways, since in the function doc description, it mentions one should use a selector and includes such an example.

Whyyy is this useful? We can build p5 worlds within A-Frame, also allowing for wild p5.js + AR via MindAR in the browser.
[Here's an A-Frame demo](https://editor.p5js.org/ffd8/full/PbqrLrTIQ) using multiple `createGraphics()`!

<img width="400" alt="image" src="https://github.com/processing/p5.js/assets/570957/dfda6435-e724-4043-adb3-350dc7733a07">

I'm not familiar enough with the WEBGL _setAttributes to know what one should write in the doc as a warning. Perhaps you can test using the p5-dev.min.js linked above to see if it works as expected or needs a warning.

**Comment by ffd8** [comment]
I'm AFK for the upcoming few days, thus created a PR just now so that this could be integrated if agreed for the upcoming release. 

I don't think there's a need for having examples embedded within the docs, since it's all about using an existing canvas element from html. Nevertheless, the descriptive text includes insights to what should be done.
