### ISSUE TITLE
touchStarted event handler called before touches[] is updated.

### ISSUE THREAD

**Issue by JimBrink** [processing/p5.js#4610]
#### Most appropriate sub-area of p5.js?
- [x ] Events

#### Details about the bug:
The touchStarted event happens before the touches array is updated.  To see the problem, touch the screen. The touchStarted event knows that a touch was started but the length of touches[] is still 0. This happens because touchStarted event handler is called before the touches[] information is updated. In somewhat a strange context, I able to solve the problem by having a touchStarted event calling _updateTouchCoords set up before user program started running.
- p5.js version: February 29, 2020
- Web browser and version:  tested in Firefox and Opera but the error doesn't depend on the
  browser.
- Operating System: Windows 10 but the error doesn't depend on the system.
- Code illustrating the problem:
The problem is illustrated in <a href = "http://brinkje.com/p5js/mouseEvents.html">
http://brinkje.com/p5js/mouseEvents.html</a>
<pre>
let msgStarted = false;
let msgTouches = "";

function setup() {
  p55 = createCanvas(300, 200);
  p55.touchStarted(started);
  p55.touchEnded(ended);  
} // setup

function draw() {
  background(210);
  text("TouchStarted reports this information", 10, 74);
  text("touchStarted: " + msgStarted, 10, 92);
  text("touchStarted touches.length:  " + msgTouches, 10, 110);
  text("But draw() reports the following", 10, 146);
  text("current touches.length: " + touches.length, 10, 164);

}  // draw

function started() {
  msgStarted = true;
  msgTouches = touches.length;
}

function ended() {
  msgStarted = false;
}
</pre>

**Comment by lmccart** [comment]
This is happening because the `.touchStarted()` listener is a wrapper around `window.addEventListener` which fires immediately on touch start. The p5.js library also listens to this event and update the touches array, but it doesn't happen before the listener you've attached fires. If you want the behavior to work as expected you have two options.
Use the [`touchStarted()` function](https://p5js.org/reference/#/p5/touchStarted) which will ensure that the proper update order occurs. 

Alternatively, you can use your current setup, but instead of using the `touches` array, you can use the native js event data. Something like this:
```js
function started(event) {
  msgStarted = true;
  msgTouches = event.touches;
}
```

I'm going to close this because the library is working as expected but let us know if you have more questions or issues with this.
