### ISSUE TITLE
rename master branch

### ISSUE THREAD

**Issue by lmccart** [processing/p5.js#4631]
To "main"? Or something else?

Other precedents and discussions:
- @outofambit's thread on [desktop](https://github.com/desktop/desktop/issues/6478)
- [drupal](https://www.drupal.org/project/drupal/issues/2275877)
- [djangjo](https://github.com/django/django/pull/2692)

**Comment by outofambit** [comment]
i like "main" or "development" but i think "main" is friendlier and simpler!

i could also see something like "current" for this repo in particular, but i don't have a strong argument for or against that.

**Comment by stalgiag** [comment]
"main" works. So so glad about this!

**Comment by montoyamoraga** [comment]
sounds great! i like "main" :)

**Comment by MylesBorins** [comment]
I'm going to be helping to push for this change in the Node.js project (and am an employee of GitHub)... if there is anything I can do to help y'all with this please lmk.

**Comment by lmccart** [comment]
@outofambit do you know the next steps for us here? you mentioned a guide you were working on? and thanks @MylesBorins! if you know any tips or best practices for making this change smoothly would love to hear. otherwise I can just give it a try and see how it goes..

**Comment by outofambit** [comment]
@lmccart yes, me, @MylesBorins, and others are working on a GitHubby guide, but I can share the highlights here!

## Automatic Option

@grege2 has a great little tool that does all the manual steps below for you. i haven't used it personally but he's been maintaining it for a while now! https://github.com/gr2m/octokit-rename-branch

## Manual Steps

- [ ] create `main` branch from `master` (i think you have to do this locally and push it up to github)
- [ ] make `main` the default branch on GitHub (https://github.com/processing/p5.js/settings/branches)
- [ ] redirect open PRs to `main` 
![retarget_branch](https://user-images.githubusercontent.com/964912/84598899-dc844b00-ae22-11ea-889a-83c1f3083cdc.gif)
- [ ] modify docs to reference `main` instead of `master` (you can usually do a mass find + replace here)
- [ ] delete `master` branch to avoid confusion

## Warning: Broken links!

One tricky thing, especially for p5.js, is that some URLs will be broken by this. For example, https://github.com/processing/p5.js/blob/master/Gruntfile.js will no longer work because it refers to `master` in the URL. If we don't delete `master`, these links will not break **but they will no longer stay up to date as we push new changes to `main`**. Unfortunately there's not really a good solution here yet.

I think this will require updating such links in https://github.com/processing/p5.js-website, and our [wiki](https://github.com/processing/p5.js/wiki). This should be a [complete list of instances in the processing org](https://github.com/search?q=org%3Aprocessing+%22github.com%2Fprocessing%2Fp5.js%2Fblob%2Fmaster%22&type=Code).

These links [often appear in issues as well](https://github.com/search?q=org%3Aprocessing+%22github.com%2Fprocessing%2Fp5.js%2Fblob%2Fmaster%22&type=Issues). 😕 I don't have an automated way to fix those, though one probably could be written...

**Comment by lmccart** [comment]
thanks @outofambit this was so helpful. I did it by hand because scripts scare me sometimes. I'm sure I broke some things. :)

I'm keeping this open because there's still work to be done:
- [ ] updating the [wiki](https://github.com/processing/p5.js/wiki)
- [ ] updating [links in issues](https://github.com/processing/p5.js/issues?q=is%3Aissue+%22processing%2Fp5.js%2Fblob%2Fmaster%22+)

help is welcome with these. each instance of `p5.js/blob/master` just needs to be updated to `p5.js/blob/main`.

i'm going to work on making the shift for the `p5.js-website` and `p5.js-release` repos now. cc @catarak @therewasaguy in case you'd like to consider this for the repos you manage.

**Comment by ffd8** [comment]
@outofambit + @MylesBorins would it be possible for Github to implement a default branch check before showing 404, to prevent these broken links throughout the web? Like the example [https://github.com/processing/p5.js/blob/master/Gruntfile.js](https://github.com/processing/p5.js/blob/master/Gruntfile.js) – instead of landing on a 404 page, attempt to replace the given branch of that URL with the repos default branch name? Then it would auto-load/forward to [https://github.com/processing/p5.js/blob/main/Gruntfile.js](https://github.com/processing/p5.js/blob/main/Gruntfile.js) before showing a true 404 if the file really is missing or was removed. Might ease other repos transition towards this positive change.

**Comment by catarak** [comment]
I'm very into this change :) I actually ended up changing the default branch to in the web editor repository to `develop` a few weeks ago (following [git flow](https://nvie.com/posts/a-successful-git-branching-model/) conventions, but instead of `master` for the release branch am using `release`) when transitioning the project to have releases (see processing/p5.js-web-editor#1421).

**Comment by gr2m** [comment]
Sorry that I only caught this issue now

> did it by hand because scripts scare me sometimes

I made that particual script :) Please feel free to reach out next time, I'm very happy to help when it comes to GitHub automation thingies.

**Comment by lmccart** [comment]
oh @catarak that's wonderful!

thanks @gr2m! and the fear is not really about the script maker, just my own generalized anxiety about getting a command wrong and other control issues lol! thank you for making this. now that i've gone through the process, i am going to try the automated tool out on some other repos of my own. <3

**Comment by gr2m** [comment]
Sorry for the off-topic comments 🙇 

Hold on, I'm writing a better solution, with more control for you. It will be a GitHub app that you can install and uninstall once the migration is done. It will create a pull request with a search&replace for the code. And only when merged, it will update the branch. 

I'll test that thoroughly on my own repos first. 

If you don't want to wait, I'm happy to help anyone with the migration with the scripts that I have today.

**Comment by roman1bondarenko** [comment]
Guys, are you serious??? it's just word, how it affect to racism???

**Comment by stalgiag** [comment]
I just want to respond to a deleted comment that question the efficacy of this change in combating racism because I don't want it to feel like people are expected to just get it. I also want to express some feelings that have been brewing as I watch the response to GitHub making this decision as a company and I assume this thread will be my only chance.

This (renaming the primary branch) is definitely a simple aesthetic change and may be born more out of a desire to do something within open-source without actually challenging anything fundamental to the ecosystem. But there is definitely a good argument for why this simple aesthetic change is useful. These threads are good starting points for seeing what the debate internal or external looks like:
[reddit post comment thread](https://www.reddit.com/r/programming/comments/h8w36t/github_will_no_longer_use_the_term_master_as/)
[twitter post response thread](https://twitter.com/mislav/status/1270388510684598272)
[small personal essay with response thread](https://dev.to/_garybell/why-github-renaming-master-is-good-4b64)
[another github issue discussion](https://github.com/pmmmwh/react-refresh-webpack-plugin/issues/113)

My general feeling is that the origin of the use of `master` in git is in master/slave terminology so let's ditch it. As mentioned, it isn't a lot of work and it is a way to focus a positive desire for confronting racism. 

That said, if you look at the above threads, you will find mostly white men arguing over the decision by Github. Many BIPOC contributors that you see in the comments (or that I have talked to in person) see this as a facile PR stunt.

I do not want to start a debate, as I think that is unnecessary and I resolve pretty resolutely into the 'change it' camp but I also just want to bring up the devastating smallness of this change relative to the size of the problem. I think this is especially evident on this platform as Microsoft is a consistent supporter of police and ICE. They are deeply invested in surveillance technologies and work to build software tools specifically for policing.

I would like to see this change be the beginning of dreaming up bigger changes, perhaps even discussing the viability of abandoning GitHub for a self-hosted GitLab. But that is definitely not the only thing that can be done. I am sure there are other drastic and meaningful forms of antiracist activism that can take place within FLOSS. This is something that I for one want to find a deeper imagination for.

**Comment by roman1bondarenko** [comment]
cool, delete another view for this situation...

**Comment by stalgiag** [comment]
@roman1bondarenko your comment was deleted because the tone was aggressive. Check out the [code of conduct for this repo](https://github.com/processing/p5.js/blob/main/CODE_OF_CONDUCT.md) and use patient, open, and respectful language or you will not be a part of the conversation.

**Comment by roman1bondarenko** [comment]
> @roman1bondarenko your comment was deleted because the tone was aggressive. Check out the [code of conduct for this repo](https://github.com/processing/p5.js/blob/main/CODE_OF_CONDUCT.md) and use patient, open, and respectful language or you will not be a part of the conversation.

so, where i was aggressive? i just say that this renaming are not affect to life quality:)

**Comment by lmccart** [comment]
@roman1bondarenko if you'd like to post your view with respect and care, please do. i think it is important for different viewpoints to be welcome here. thank you! however, i don't want to spend too much energy on this decision, as @stalgiag mentions, there is more work to be done. and considering `main` does not seem to be a term that offends anyone, it doesn't feel necessary to debate this at length. i think the threads posted above do this already.

**Comment by DivyamAhuja** [comment]
Leaving every other aspect aside, I think the term "main" is aesthetically better and defines the purpose of the branch more clearly. I like this change. 😁

**Comment by lmccart** [comment]
Ok all links in wiki and open issues are have been updated. There may be some remaining broken links in closed issues, but I think we can update these as needed. Thanks everyone.
