### ISSUE TITLE
noLoop() - example not working

### ISSUE THREAD

**Issue by anniemckinnon** [processing/p5.js#4663]
Hi everyone, 
noLoop() p5.MediaElement isn't working. 
I don't yet have the skills to fix this and would love to be able to use this function, 
any help would be greatly appreciated. 
Best, 
Annie

**Comment by limzykenneth** [comment]
The `loop` attribute set on the audio element should be removed instead of set to false in order for it to stop looping, [this line](https://github.com/processing/p5.js/blob/1.0.0/src/dom/dom.js#L2657) needs to be changed from `this.elt.setAttribute('loop', false);` to `this.elt.removeAttribute('loop');`. The example is also missing a `sampleIsPlaying = false;` [here](https://github.com/processing/p5.js/blob/1.0.0/src/dom/dom.js#L2644).

If you would like to fix this let me know. I can assign the issue to you. 😄

**Comment by anniemckinnon** [comment]
Hi Kenneth, 
thank you! I will give it a go now!
Thanks for the encouragement. 
:)

**Comment by anniemckinnon** [comment]
@limzykenneth and @lmccart . I have done my best to make my first pull request to resolve this issue. 
I hope it works. Thanks again for the encouragement.
