### ISSUE TITLE
Perlin noise patterns

### ISSUE THREAD

**Issue by Mindrix95** [processing/p5.js#4724]
Hi,

When i use the noise function, i can see the noise making paterns, i've made an exemple  : 

https://editor.p5js.org/nicomaindroult/present/hdW3B7soM

We can see shapes repeating, maybe I'm doing something wrong.

Can you help me to have a nice random perlin noise please ?

Thanks for your help and for your work on this project,

Regards

**Comment by ScottGrogin** [comment]
Hi Mindrix, 

I would recommend trying out using noise octaves for better patterns. You could also add in layered trig functions to your noise for more variety. Here is a web page that helped me understand layering noise https://thebookofshaders.com/13/

Good Luck!

**Comment by limzykenneth** [comment]
As far as I know, at larger scale, perlin noise do have periodicity which is why most usage will scale it down in steps of more or less 0.01. You can have a look at [`noiseDetail`](https://p5js.org/reference/#/p5/noiseDetail) if you want to tweak the characteristic of the noise while using smaller scale steps.
