### ISSUE TITLE
Implementation of p5.Vector setHeading()

### ISSUE THREAD

**Issue by samdelong** [processing/p5.js#4767]
I am opening a new issue to implement a `setHeading` method for the p5.Vector class. Currently, p5 contains a function `rotate()`, which rotates the vector `by` a certain value, but no such method exists for setting the vector's rotation to an explicit direction. I currently have something working, and am planning to pull request an implementation.

An implementation would look as follows:
```javascript

p5.Vector.setHeading = function(angle){
  this.rotate(-this.heading())
  this.rotate(angle)
}
```

This is my first time attempting to contribue to open source, so any tips would be greatly appreciated!

**Comment by mishazawa** [comment]
Hello.
> no such method exists for setting the vector's rotation to an explicit direction

AFAIK: vector is object that have _direction_ and length. By creating vector you already set his rotation that point to direction.  

Take a look at [fromAngle](https://p5js.org/reference/#/p5.Vector/fromAngle) function. I think it doing exactly what you want.

Probably this operation may be cheaper (for CPU cycles) when you create new vector and rotate it. Because `heading()` calculates arctangent, `rotate()` calculates sine and cosine (for coordinates [x, y] that will be point to vector with 0 angle), then new rotation calculates sine and cosine again.

**Comment by samdelong** [comment]
Hi mishazawa

The issue with creating a new vector altogether with `fromAngle()` would be any user-defined characteristics of the vector would be erased. However I can see why my implementation would be poor practice for performance.

Perhaps we could copy the code from `fromAngle()`, but instead of returning a new vector, we just modify the vector in the current context?

**Comment by mishazawa** [comment]
> any user-defined characteristics of the vector would be erased

Which ones? Vector has only [x, y, z] properties.
If you trying to store any other data inside vector f.e.:
```js
let vec = createVector(1, 2, 3);
vec.offset = createVector(2, 2, 2);
```
I highly recommend not to do it. Because vector is designed to store only direction and length (through coordinates). 
Instead you could create your own structure f.e.:
```js
let arrow = {
  direction: createVector(1,2,3),
  offset: createVector(2, 2, 2),
}
```

> we could copy the code from fromAngle()

Proper way is to create new vector. I don't see any use cases when you should modify vector instead just re-write it.

**Comment by samdelong** [comment]
I can see where you're coming from, but often times p5.js is used by beginners, and having to create a new vector using `fromAngle()` is pretty unintuitive. I think a `setHeading()` function would help ease some confusion. If not it's own implementation, an alias would still be helpful.

Also just to note, a vector's `z` property would be lost if using the `fromAngle()` function. Even though the `heading()` function should only be used on 2D vectors, it would be beneficial in reducing some confusion.

**Comment by burnedsap** [comment]
I agree, I think it would be handy to have a `setHeading()` function.

**Comment by samdelong** [comment]
As per @mishazawa s suggestion, I edited the setHeading() functions implementation to more closely represent the fromAngle() function, but without the need to create a new object. I still think this feature would improve the p5.js library.

**Comment by limzykenneth** [comment]
Thanks for the discussions! I'm ok with this being added, can someone else have a look at this proposal and if it's ok, we'll merge it? @lmccart @montoyamoraga @outofambit @stalgiag

**Comment by samdelong** [comment]
I included that this method would only work for 2d vectors in the method documentation. Im not sure if something should prevent a user from rotating a 3d vector...maybe a console warning would be helpful here?
