### ISSUE TITLE
slice and arrayCopy on p5.image.pixels returns error

### ISSUE THREAD

**Issue by eyaler** [processing/p5.js#478]
the documentation states that p5.image.pixels is an array. however when applying slice() or arrayCopy() on it we get: Uncaught TypeError: undefined is not a function

code to recreate:

var good = [1,2,3,4];
var bad;
function setup()
{
	bad = createCapture(VIDEO); 
	bad.size(2,2);

// alternatively: bad = loadImage("image.jpg");
}

function draw()
{
  bad.loadPixels();
  print(good);
  print(good.slice(0));
  print(bad.pixels);
  print(bad.pixels.slice(0)); // gives error
  arrayCopy(bad.pixels,good); // gives error
}

**Comment by GoToLoop** [comment]
Actually `pixels[]` is a **TypedArray**:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray

Which is itself an **ArrayBuffer**:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer

More specifically,  `pixels[]` is a **Uint8ClampedArray**:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray

**Comment by shiffman** [comment]
Just ran into this issue porting [LinearImage](https://processing.org/examples/linearimage.html).  It's probably worth overloading `arrayCopy()` to work with the pixels array if possible as this is a common operation in various applications.

**Comment by workergnome** [comment]
Should we fix this with a documentation change, or with overloaded functions for `slice()` or `arrayCopy()`?

**Comment by lmccart** [comment]
I think fixing documentation is definite yes, overloading `arrayCopy()` makes sense as a nice helper.

**Comment by workergnome** [comment]
Rockin'.  I'll fix the documentation for this, and I added an issue for the enhancement.

**Comment by kjhollen** [comment]
Hey all, just checking something here... in the sample snippet provided in the original post, what's the expected behavior for the arrayCopy call? I've fixed the error generated by slice, but the example eventually produces another error because the array gets progressively bigger. The function is given 2 arguments but expects 5. The behavior I'm seeing with the sample as provided is an eventual maximum call stack exceeded error. But if I change the last line in draw to:

<code>
  arrayCopy(bad.pixels, 0, good, 0, 4);
</code>

Everything is fine. Worth filing another bug for the other behavior?

**Comment by workergnome** [comment]
Yes.  File a new bug for it, please!
