### ISSUE TITLE
Center function is not working..

### ISSUE THREAD

**Issue by AadiDasLM** [processing/p5.js#4780]
The rectMode(CENTER) is not working even when I write center in capital letters.
![The Issue)](https://user-images.githubusercontent.com/70469181/91655943-3d422c00-ead2-11ea-8514-f62d74c1e1cb.png)

**Comment by limzykenneth** [comment]
It is working as intended, I'm not sure what the expectation here is but `rectMode(CENTER)` changes the way the four arguments (`50, 50, 30, 30` in this case) is interpretated, in that the first two arguments define where the **center** of the rectangle should be (instead of where the **top left** corner of the rectangle which is the default). 

If you meant to place the rectangle at the center of the canvas, you should use [`translate()`](https://p5js.org/reference/#/p5/translate) instead.

If you need further help, please do post them on the [forum](https://discourse.processing.org). Thanks.
