### ISSUE TITLE
Live Input Sound

### ISSUE THREAD

**Issue by alsumwas** [processing/p5.js#4798]
I was playing around with one of the examples and found that it doesn't work outside of the editor.   The red dot indicating that audio is inputing is active but the ball does not go up when you make noise.  
here is the sample in the editor, you have to go to share and open it in a browser to see it not work.

https://editor.p5js.org/p5/sketches/sWixDmW4K8

**Comment by limzykenneth** [comment]
The mic input requires a user input in order to start recording audio, it is a relatively recent change so the sample code is not up to date. We provided a function to help with this called `usertStartAudio`, you can see how to use it [here](https://p5js.org/reference/#/p5/userStartAudio) and [here](https://p5js.org/reference/#/p5.AudioIn).

When in the editor it works because clicking on the run sketch button counts as a user interaction so the audio context is started.

If you have further questions, do post them on the [forum](https://discourse.processing.org). Thanks!
