### ISSUE TITLE
poseNet nn model using p5.js online editor

### ISSUE THREAD

**Issue by dev348** [processing/p5.js#4808]
Uncaught TypeError: Cannot read property 'split' of undefined (: line 50)
![image](https://user-images.githubusercontent.com/47909485/94055987-48e7f080-fdfb-11ea-8da9-bbba6420028f.png)

**Comment by lmccart** [comment]
hi @dev348 this looks like it may be an issue with ml5, since it's flagging the line that says "load", which is not a p5 function but a ml5 one. you could try posting your issue on the [ml5 issues](https://github.com/ml5js/ml5-library/issues), or on the [processing forum](https://discourse.processing.org/) for more p5 coding help.
