### ISSUE TITLE
Animated GIF frame delay off when drawing multiple times per frame

### ISSUE THREAD

**Issue by owenbmcc** [processing/p5.js#4818]
#### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Dom
- [ ] Events
- [x] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Feature enhancement details:

Rendering an animated GIF multiple times in one frame causes the frame rate to increase relative to the number of times the GIF is displayed.  See [example](https://editor.p5js.org/owenroberts/sketches/AK0iCKqXx).

It is possible to adjust the delay based on the number of instances by multiplying the delay of each frame by the number of instances, but only if you know how many instances will be drawn in each frame, and the result is slightly off (see example).

The simplest fix I came up with for this feels a bit hacky but seems to work.  [This commit](https://github.com/owenbmcc/p5.js/commit/7c63a90f05b11e8377d65e53fc785b0c47c7989e) compares the current frameCount to an added property to the GIF image so it doesn't advance the gif more than once per frame.

This assumes that desired way of rendering multiple instances of one animated GIF is they play at the same rate as one instance of the GIF would play.  I think it's what one would expect to see.  If that's not the desired approach, it could be added as an optional argument or something.

Another possibility would be adding a new method to multiply the delay by the number of instances, that seems to work okay but also is a bit off as I mentioned, I haven't looked into why.

For some context, I use p5 in classes I teach and this has come up recently with a student who wanted to create a tiled background of animated GIFs, which causes them to animate 16x faster.  I've used p5.play in the past for sprites, I did a quick test there and it looks like it has the same issue when using sprite sheets.

Using the delay method is a relatively simple sketch level fix but it would be nice if this was either fixed or somehow the way to fix it was documented.

**Comment by akshay-99** [comment]
Hi @owenbmcc that's interesting. So as correctly identified in your fix, the problem happens because [`timeDisplayed`](https://github.com/processing/p5.js/blob/3f0b2f0fe575dc81c724474154f5b23a517b7233/src/image/p5.Image.js#L228) is updated each time the gif is drawn. If the same GIF instance is drawn multiple times in a frame, `timeDisplayed` will be updated multiple times in the same frame. This makes the GIF run faster. I don't think this is the desired outcome here. 

But there is no need to have `timeDisplayed` as a property of GIFs as it is not used anywhere else. An alternative solution is to remove the `timeDisplayed` property altogether and instead add `curFrameFirstPaintTime` as a GIF property. If the difference between the current time and `curFrameFirstPaintTime` exceeds the `curDelay`, we update the GIF frame. That we don't have to manually update `timeDisplayed` and the frame updates are calculated correctly, regardless of how many times `image()` is called.

To me, this method seems a bit less hacky but I don't really know.

**Comment by stalgiag** [comment]
Thanks for reporting this @owenbmcc ! Also -- hi! I also teach at a CUNY school (CCNY).

So since I didn't think to prepare for this behavior when making the GIF functionality, I decided to take a crack at fixing it. @akshay-99 I mostly took your suggestion. This was what I wanted to do when originally implementing the GIFs but I didn't because of potential differences between when the GIF is loaded and when it is first used. If we check current time against `curFrameFirstPaintTime` then we will end up skipping the first frame when a user has a delay between loading the GIF and displaying it.

So I slightly modified the approach to set `lastChangedTime` (my version of your `curFrameFirstPaintTime`) to `millis()` when the GIF is displayed and `lastChangedTime` is 0. This allows us to set `lastChangedTime` to 0 on load, `reset()`, and `setFrame()` and not concern ourselves with the difference between the time of this modification and display time.

I also encountered another bug while fixing this. The last frame was being painted first. This was due to the fact that the `drawingContext` of the p5.Image is used for painting and saving during frame loading for GIFs. So the last frame, the frame that was loaded last was still painted in after load. We don't have the option to load the frames in reverse order unfortunately because of the way that GIF disposal codes work. So I just manually painted the first frame back in after loading is complete.

I will open a PR and request reviews from both of you.
