### ISSUE TITLE
Missing project

### ISSUE THREAD

**Issue by Nisseboy** [processing/p5.js#4850]
#### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Color
- [ ] Core/Environment/Rendering
- [ x] Data
- [ ] Dom
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Details about the bug:

- p5.js version: 1.1.9
- Web browser and version: Google Chrome | 85.0.4183.121 (Official Build) (64-bit) (cohort: Stable)
- Operating System: Windows 10 x64
- Steps to reproduce this:
I just recently closed a project to start a new one, however, when i went to open the first project but it was nowhere to be found.

**Comment by limzykenneth** [comment]
@Nisseboy I think you probably meant to file this at the [web editor repo](https://github.com/processing/p5.js-web-editor), this is the repo for the p5.js library only. From your description it sounds like you didn't save the first project before creating a new one, projects are not saved by default.

I'm closing this issue here, if you have further problems with the editor please file the issue there. Thanks.
