### ISSUE TITLE
New function to display table on canvas in nice format

### ISSUE THREAD

**Issue by TanishqPal** [processing/p5.js#4900]
### How would this new feature help [increase access](https://github.com/processing/p5.js/blob/main/contributor_docs/access.md) to p5.js?
I think it would be nice to have a function that takes a table and displays it to a canvas like an MS Excel or Google sheets

#### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Friendly error system
- [ ] Image
- [x] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### New feature details:
Perhaps some new function like 
printTable(table1) or
table1.print()

Does a js library already exist that does the same thing ?

**Comment by limzykenneth** [comment]
I think this is out of scope for p5.js but such a functionality would fit very well in an [addon library](https://github.com/processing/p5.js/blob/main/contributor_docs/creating_libraries.md) or even a standalone library creating HTML `<table>` elements directly (maybe such a thing already exist).

**Comment by GregStanton** [comment]
### Canvas vs HTML
Ooh! I'm actually working on a library now that can display and style tables, and I need to decide if I should display them on the canvas, if I should display them as HTML tables, or if I should try to do both. Do you have a preference?

### What I have so far
Specifically, I'm refactoring (and eventually extending) a library that I originally wrote in ProcessingJS, so that it will work as a p5 [community library](https://p5js.org/libraries/). The library is currently called visualODE, since it's developed for visualizing ordinary differential equations, but it will have to have basic table functionality as a part of that. (I imagine the table functionality could be spun off as a separate library if that would be helpful.)

The ProcessingJS version of visualODE displays tables on the canvas, with default or custom styling. You can view a [working demo](https://www.khanacademy.org/computer-programming/visualode-demo/6127327220629504) of it on Khan Academy; the table examples are in Part 3 of the demo, starting on Scene 31 (you can navigate there by clicking the next button on the bottom right of the canvas).

An example of a table displayed on the canvas with custom styling is below.
![Formatted Table Example](https://user-images.githubusercontent.com/51820777/100041848-661f4800-2dc7-11eb-9748-71c7c7dd450f.png)

Scene 43 of the linked demo shows a possible use case for a canvas table (basically, displaying the table on the canvas may be helpful in cases where the table is to be displayed and interacted with alongside a graph or other visualization).

Code for a simpler table with default formatting (from Scene 32 in the demo) is below. This table is also displayed on the canvas. Here, the table data are passed in individually, but they can also be passed in via an array. (The exact syntax may change, since I'll probably want to use a p5.Table object when I develop the library in p5.)

    //create table
    beginTable("rows"); //data interpreted as rows
    tableData("x", -2, -1, 0, 1, 2);
    tableData("y", 4, 1, 0, 1, 4);
    endTable();
    
    //set (X, Y) position of table's top left corner
    setTablePosition(20, 100);
    
    //draw table
    drawTable();

This results in the table below.

![Simple Table Example](https://user-images.githubusercontent.com/51820777/100043354-856ba480-2dca-11eb-9665-50bbbbc6b21e.png)

### Advantages of HTML?
On the other hand, HTML tables might be more accessible in general, e.g. for users who rely on screen readers, and there may be other advantages. 

I haven't researched the trade-offs but would love to hear from anyone with more expertise in this area! If you (@TanishqPal) have a reason for wanting the tables to appear on the canvas, rather than as HTML tables, it'd be super helpful if you could explain why.

**Comment by limzykenneth** [comment]
@GregStanton Sound like a really interesting project!

Your analysis of canvas vs HTML table are pretty much on point and it is a trade off between ease of interactibility/interoperability with the canvas and accessibility. In the ideal world, both would be an option so the user can choose to render the tabular data either in canvas or as HTML table but that might take some work though.

**Comment by GregStanton** [comment]
@limzykenneth Thanks so much for the feedback and for sharing your expertise! I'm really glad you think the project sounds interesting :) I may need to prioritize either canvas tables or HTML tables in the short term, but it would be nice to implement both options in the long term, since that seems to be ideal as you suggested.

**Comment by limzykenneth** [comment]
I'm closing the issue for organizational purpose but feel free to continue the discussion here if needed.

**Comment by TanishqPal** [comment]
Hi @GregStanton sorry for replying very late 

Your project really intrigues me.

I actually have do not have any reason for wanting canvas table Now that I think about it, HTML table would be nicer because of the ease of modification of styles. Also as you mentioned HTML is more accessible.

How can I help you in the project ?

**Comment by frenamezian** [comment]
Hi, I am also new to P5 and I also needed to display an HTML table outside the canvas.

I tried to create a function build_HTML_table (tbl, tableID, parentID) to build an HTML table based on the p5.Table object. The function would then place the table under the parent ID html element. But I cant get the p5.Table.get(row, colum) function to return the content of a cell. Here is the sketch with a sample data

https://editor.p5js.org/laurent.tran/sketches/CwwF02GX9

```

function build_HTML_table (tbl, tableID, parentID){
  // create an HTML table wirh w3.css class with the table tbl
  // tbl should be a p5.Table object
  // tableID is the selector ID you want to assign to the table
  // parentID is the element ID under which you want to locate the table
  
  let cc = tbl.getColumnCount();
  let rc = tbl.getRowCount();  
  let rows = tbl.getRows();
  
  print('col =' +cc + ' row = ' +rc);
  print(tbl);
  
  // setup the table header HTML string
  let hh ="<tr>"; // header html
  for (let c = 0; c < cc; c++) {
    hh +="<th>" +  tbl.columns[c] +"</th>";
  }
  hh +="</tr>"
  
  // setup the table row HTML string
  let rh =""; // row html
  
  for (let r = 0; r < rc; r++){
    rh +="<tr>";
    for (let c = 0; c < cc; c++){
      
       // this is not returning the conent of the cell. tbl.get(r,c) returns undefined
       rh +="<td>" +  tbl.get(r,c) + "</td>"; 
      //print(tbl.get(r, c));
      //rh +="<td>" + 'test ttest' + "</td>";
       
    }
    rh +="</tr>";
  }
  
  //print('cell (0,1) = ' + tbl.get(0, 1));
  //print('cell (0,0) = ' + tbl.get(0, 0));
  
  let t = createElement('table', hh+rh);
  
  t.addClass('w3-table-all'); // add the  table class from w3.csss
  t.id(tableID); // sets the id for this <table>
  t.parent(parentID);
  
}

```

**Comment by frenamezian** [comment]
Hi again, actually i just got it to work. The problem was with the table object i was creating from scratch for testing. I wasnt not inserting rows correctly. My sktech works now.

https://editor.p5js.org/laurent.tran/sketches/CwwF02GX9
