### ISSUE TITLE
loadX functions add undeclared return variables to the global scope.

### ISSUE THREAD

**Issue by stalgiag** [processing/p5.js#4935]
#### Most appropriate sub-area of p5.js?

- [x] Loading

#### Details about the bug:

- p5.js version: 1.1.9
- Web browser and version: Any

This works without errors.

```js
function preload() {
  // if I declare this variable here it will actually throw an error
  // let variableThatWasNeverDeclared;
  variableThatWasNeverDeclared = loadImage('link-to.jpeg');
  another = loadStrings('link-to.txt');
}

function setup() {
  createCanvas(400, 400);
  image(variableThatWasNeverDeclared, 100, 100, 200, 200);
  text(another[0], 100, 100);
}
```

[Here's a link.](https://editor.p5js.org/stalgiag/sketches/Py8d1rcJ0) It is making my students distrust me 😅

**Comment by lmccart** [comment]
Hm I think this is a correct behavior. Here's the typical way of using preload:

```
let variableThatWasNeverDeclared;

function preload() {
  variableThatWasNeverDeclared = loadImage('https://i.imgur.com/kg4kVsD.jpeg');
  another = loadStrings('style.css');
}

function setup() {
  createCanvas(400, 400);
  image(variableThatWasNeverDeclared, 100, 100, 200, 200);
  print(another[0]);
}
```

The reason you get that error if you declare `let variableThatWasNeverDeclared ` in `preload()` is that in the `image()` line, it has no knowledge of the variable, because it's scope was limited only to the `preload()` function. If you skip the declaration, as you have it, JS defaults to adding that variable to the global scope, so it is then accessible anywhere in the sketch. But, maybe I am misunderstanding the issue?

**Comment by stalgiag** [comment]
Nope that solves it. Thank you!

I didn't realize that you could skip declaration and automatically add variables to the global object in non-strict mode.

Reading over the strict mode documentation, I can't help but feel like strict mode is better suited to learning and the starter sketch in the online editor should use it. But that is another conversation. Thanks for patiently answering my question that was likely better suited to the discord forum :-P
