### ISSUE TITLE
Although box() accepts a vector, it generates a warning 

### ISSUE THREAD

**Issue by felds** [processing/p5.js#4978]
#### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [x] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Details about the bug:

- p5.js version: 1.2.0
- Web browser and version: Chrome 87.0.4280.88
- Operating System: OSX Catalina
- Steps to reproduce this:

```js
const x = createVector(10, 20, 30);
box(x);
```

**Comment by siv2r** [comment]
I am not sure about passing the vector `x` as `box(x)` will work. I think the parameters for the `box()` must be numbers (mentioned on its [reference page](https://p5js.org/reference/#/p5/box)). 

Separating the vector components before passing them to `box()` works.
```javascript
const x = createVector(10, 20, 30);
box(x.x, x.y, x.z);
```

**Comment by akshay-99** [comment]
The reason for this working seems more likely to be a lucky accident due to the way the source code is written, rather than an intended way of use.

 `box()` treats the entire vector as `width`. But later in the drawing process, the `scale()` function is called internally which does accept a vector and hence can work with it.
