### ISSUE TITLE
p5.js Element style example is overlapping with the website text

### ISSUE THREAD

**Issue by rt1301** [processing/p5.js#5010]
#### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [x] DOM
- [ ] Events
- [ ] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Details about the bug:

- Web browser and version:  Chromium 88.0.4324.96
- Operating System:  Ubuntu 20.04
- Steps to reproduce this:

The third example on the Element style reference page overlaps with the website text
![Screenshot from 2021-01-24 23-23-25](https://user-images.githubusercontent.com/63252510/105638984-c439db80-5e9b-11eb-8478-04fdde491f64.png)

Would you like to work on this issue? - Yes

**Comment by stalgiag** [comment]
Hi @rt1301 thanks for the issue!

I always saw this as intentional. I think the goal is to show that p5.Elements are just like any other DOM Element and can exist visually alongside other elements outside the canvas. I could be mistaken though.

**Comment by johnmusk** [comment]
i would like to work

**Comment by rt1301** [comment]
@limzykenneth  Can you suggest whether this enhancement is required? If it does, I would like to work on it

**Comment by Aloneduckling** [comment]
@stalgiag I have made some changes so that the font-size of the text is limited and is shown in such a way that it conveys the idea (p5.Elements are just like any other DOM Element and can exist visually alongside other elements outside the canvas) while being visually appealing and less cluttering.

![image](https://user-images.githubusercontent.com/54030684/109131975-58d47980-7779-11eb-918f-1b610a75677a.png)
![image](https://user-images.githubusercontent.com/54030684/109131999-5d992d80-7779-11eb-9643-14470b3d8c41.png)

does this seem fine?

**Comment by lmccart** [comment]
@Aloneduckling thanks! to simplify, I would suggest changing this to:
```js
let fontSize = max(mouseX, 100);
myDiv.style('font-size', fontSize + 'px');
```

**Comment by Aloneduckling** [comment]
@lmccart, sorry for the late reply. I will change this.

**Comment by Aloneduckling** [comment]
@lmccart, I have made some changes in all the examples and now they look better and less cluttering. Please have a look.

![image](https://user-images.githubusercontent.com/54030684/110902835-7cc4bd00-832c-11eb-84eb-dc77fbfc6abd.png)

Should I open a PR?

**Comment by Aloneduckling** [comment]
Also, I wanted to know how much time it takes for the online reference manual to get updated. I asked because I have created this [PR](https://github.com/processing/p5.js/pull/4979), and the website doesn't seem to be updated. [This]( https://p5js.org/reference/#/p5/createButton) is the page for reference.

**Comment by lmccart** [comment]
@Aloneduckling yes please do submit a PR. There is a issue with updating the reference that I am working to resolve, so I don't have an estimated time for the next update right now. Hopefully soon.
