### ISSUE TITLE
found a bug  in trigonometry part

### ISSUE THREAD

**Issue by ashokkumar6377** [processing/p5.js#5101]
#### Details about the bug:

- p5.js version: 
- Web browser and version: 
- Operating System: 
- Steps to reproduce this:

**Comment by Prateek93a** [comment]
@ashokkumar6377 Can you please describe the bug you are facing?

**Comment by limzykenneth** [comment]
I'm closing this for now but we can reopen once more info is provided. Thanks.

**Comment by ashokkumar6377** [comment]
> u

hello, actually the value of cos(90) is 0 but its give another number( 6.123233995736766e-17). please  fix it .thanks

**Comment by limzykenneth** [comment]
@ashokkumar6377 The value given by `Math.cos(Math.PI/2)` in Javascript itself is `6.123233995736766e-17`. Because of floating point number's limited precision, it is not possible to get an output of `0` from the `cos` function. Only Pi with unlimited digits can make `cos` give an output of `0`.

Usually `6.123233995736766e-17` is so small that it is for most intends and purposes close enough to `0` that it shouldn't cause a problem.

**Comment by ashokkumar6377** [comment]
Ok ,thanks  for your information
