### ISSUE TITLE
p5.Vector explanation of setMag

### ISSUE THREAD

**Issue by micuat** [processing/p5.js#5151]
**Actual Behaviour**

in https://p5js.org/reference/#/p5.Vector

> Set the magnitude of this vector to the value used for the **len** parameter.

 

 **Expected Behaviour**

if I understand correctly

> Set the magnitude of this vector to the value used for the **mag** parameter.

**Comment by DavidWeiss2** [comment]
I think that corrently is very clear.
Magnitudes is size of the vector. 
Len is size from one point to another.

**Comment by Qianqianye** [comment]
Thank you all for working on this issue. I am inviting the current Math stewards to this discussion @limzykenneth, @ericnlchen, @ChihYungChang, @bsubbaraman, @albertomancia, @JazerUCSB, @tedkmburu, @perminder-17, @Obi-Engine10, @jeanetteandrews. Would love to hear what y'all think. Thanks!

**Comment by bsubbaraman** [comment]
I think the documentation wording has been changed since the original issue, in August 2023 ([commit details](https://github.com/processing/p5.js/commit/87bd7d3974054cdc48708bbe91ffbdfe5d94d0c8#diff-dcc8667ec26b7325ed85ffb5f061d2812e22feac4e5df4acb8dbec80448bc072L1353)). 

The `setMag()` description reads:
> Sets a vector's magnitude to a given value.

And the `p5.Vector` description introduces both the terms 'magnitude' and 'length':
> Vectors have both magnitude (length) and direction.

I personally think this works, and agree with @limzykenneth's eariler point that changing the parameter name from `len` to `mag` might cause confusion with the `mag()` method; introducing magnitude and length as interchangeable terms seems like a good way to go about it. There is now a small typo, with `(Optional)`  being written twice. 

Do others think that the current explanations are clear enough?

**Comment by limzykenneth** [comment]
Addressed with recent changes
