### ISSUE TITLE
load/updatePixels() and set() / get()

### ISSUE THREAD

**Issue by shiffman** [processing/p5.js#521]
In porting some examples from Processing I noticed that `set()` (as indicated [in the documentation](http://p5js.org/reference/#/p5/set)) requires a call to `updatePixels()`.   In Processing `set()` internally calls load and update pixels which makes it more convenient (but much slower) than accessing the pixel array directly.  I'm ok with this break from Processing API but just wanted to confirm this is the desired behavior?

**Comment by lmccart** [comment]
yes the thinking was... it's more difficult to figure out the correct pixel position with this new pixel scheme, so `set()` might be used more often. however due to canvas limitations, calling `updatePixels()` after every set call could really drag if you were setting multiple pixels rather than one. so instead it requires a manual call. however maybe a better thing to do is by default call `updatePixels()` but have an optional arg to turn this off so you can call it manually at the end.

all that being said, the pixel stuff is in need of a rework to factor in the retina scaling, hopefully you don't run into too many issues with this.

**Comment by hamoid** [comment]
Looking at the source code it looks to me like get(x, y) returns all the
pixels, not one. Can it be?

    if (w === 1 && h === 1) {
      var pixels = [];
      for (var i = 0; i < data.length; i += 4) {
        pixels.push(data[i], data[i+1], data[i+2], data[i+3]);
      }
      return pixels;
    }

**Comment by brysonian** [comment]
@hamoid, no it doesn't Notice the width and height are 1, it returns an array of [r,g,b,a] for a single pixel.

**Comment by hamoid** [comment]
width and height were set to 1 because they were missing as arguments.

Sorry if my brain is not working but... data contains all the pixels,
right? So doesn't it push all the data into the pixels variable, and
return that?

The easiest would be to try it, but I'm in a hurry :)

**Comment by brysonian** [comment]
no it doesn't, you are missing this:

`var imageData = this.drawingContext.getImageData(x, y, w, h);`

get image data of w and h of 1, i.e. a single pixel.

**Comment by hamoid** [comment]
Sorry, I was assuming that data contained all the pixels, sorry! Too much work this week :)

**Comment by workergnome** [comment]
To clarify this issue:  `set()` requires `updatePixels()` to be called on completion for performance reasons.  This is a break from Processing, but we are fine with that.  Assuming that is true, there are no changes that need to be made.
