### ISSUE TITLE
Matrix Math for p5js

### ISSUE THREAD

**Issue by matiasvlevi** [processing/p5.js#5210]
#### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [x] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### New feature details:
We should have a way to describe Matrices in a similar way `p5.Vector` describe vectors. Currently p5js does not contain a way to describe Matrices with a set of simple user-friendly bindings. Operations such as Matrix multiplication would be useful for various applications. Adding such a feature to p5js would be a great way ta make it more accessible to beginners.

**Comment by lmccart** [comment]
Thanks @matiasvlevi can you please answer the first question in the template: How would this new feature help [increase access](https://github.com/processing/p5.js/blob/main/contributor_docs/access.md) to p5.js?

**Comment by matiasvlevi** [comment]
It would help increase access for beginners. 
Having an easy way to play around with matrices lowers the barrier for beginners wanting to experiment with such concepts. I feel that this is what p5js does, it makes things easier & simpler allowing for an easier access for beginners.

**Comment by matiasvlevi** [comment]
If this sounds like an interesting addition to p5js, I would have no problem being assigned to this task.

**Comment by micuat** [comment]
there is p5.Matrix but I guess it's a helper class for webgl:

https://github.com/processing/p5.js/blob/main/src/webgl/p5.Matrix.js

to me it's difficult to justify the accessibility - I think there are other math libraries that can be used with p5.js for this purpose. I would suggest to make it not directly into the core but as an extension either from scratch or as a binding to another library like [math.js](https://mathjs.org/docs/datatypes/matrices.html) and see what happens from there.

**Comment by Qianqianye** [comment]
Thanks @matiasvlevi. We are not seeing a further explanation of how this issue [expands access](https://github.com/processing/p5.js/blob/main/contributor_docs/access.md), so I will close this issue for now. If you can add: 1) a more detailed access statement and 2) more info responding to @micuat's suggest to the feature request, please feel welcome to reopen it. Thank you!

**Comment by matiasvlevi** [comment]
Expanding access? I am curious as to how a piece of code could be of help to a minority such as people of color or marginalized genders. Why would marginalized people need something more from a JavaScript library? Why can we assume that X type of people needs Y type of assistance? Code is just code, you learn from it, and you teach with it, minorities have nothing to do with it.

Keep this issue closed, I don't understand where your vision is coming from. Don't get me wrong, I enjoy p5js, but the vision just seems overly obsessed with "woke" issues that barely apply to a learning setting.

**Comment by golanlevin** [comment]
Hi @matiasvlevi, 
There are lots of ways of increasing access, and many different kinds of audiences who can be helped by this effort. 

One of the p5 community's initiatives for doing so is to make it easier for people with _disabilities_ to use and create software. Some examples of a piece of code that do this are the [`describe()`](https://p5js.org/reference/#/p5/describe) and [`textOutput()`](https://p5js.org/reference/#/p5/textOutput) functions, which make it easier for people who are visually impaired to [use p5.js with a screen reader](https://p5js.org/learn/p5-screen-reader.html). People with disabilities are a minority (X) whose needs for assistance (Y) are comparatively well-understood, but unfortunately, not enough software projects take these needs into account. 

The p5.community also acknowledges that there are many kinds of contribution, besides just code, that can expand access. An example is [internationalization](https://github.com/processing/p5.js/blob/main/contributor_docs/internationalization.md). It's pretty clear that having good language translations is essential in a learning setting. For young learners outside of the United States — even for speakers of comparatively common languages like French or Spanish — it's a lot to ask that they first be fluent in English before they can learn to code. But because [English is so overwhelmingly ubiquitous on the Internet](https://en.wikipedia.org/wiki/Languages_used_on_the_Internet), software developers rarely take into account the needs of non-English speakers — effectively treating them like an irrelevant minority, and perpetuating the problem.

So, above are a couple of possible responses to your question. To better understand the community's vision for how p5.js can expand access to an ever-wider group of learners, including people from marginalized backgrounds, I encourage you to check out the talks from the recent [p5.js Access Day 2022](https://www.youtube.com/playlist?list=PLMVpERuYgvujy_hdjnmHui17HFMo2Ma4r) conference, which just went online. Personally, I think the inclusive vision of p5.js is an incredibly smart strategy for cultivating a massive user base, since, compared to the _entire world_ — able-bodied, English-speaking, cis-gendered white guys like me are the actual minority. 

Regarding this specific issue of Matrix Math, I think the challenge posed by Micuat was reasonable. It would be helpful to see some examples of "user-friendly bindings" for a Matrix library. What would that look like in practice (in contrast to the internal p5.Matrix codebase, or the similar-sounding p5 addon library [Número](https://github.com/nickmcintyre/numero))? What would be some specific examples of creative things (e.g. mini-demo nuggets) that would be made possible with such a library, and would illustrate its value? As often happens with open-source software tools for the arts, a great way to make this case is to create an [external library for p5.js](https://p5js.org/libraries/). 

By the way, as a side note — I see that you're the author of [Dann.js](https://dannjs.org/)? There's a ton of interest in neural networks in this community. I think Dann.js would be a great candidate for a thin wrapper that could make it accessible as an [external addon library](https://p5js.org/libraries/). It looks like the only thing you'd really need would be some p5-based examples and starter projects — another key way of supporting access — and you'd get lots of users.

Best,
Golan

**Comment by matiasvlevi** [comment]
@golanlevin My trimester ends soon, Ill be back with an interesting external addon library.
