### ISSUE TITLE
codecov has started commenting on all pull requests

### ISSUE THREAD

**Issue by outofambit** [processing/p5.js#5231]
Somehow [our configuration for codecov](https://github.com/processing/p5.js/blob/main/.codecov.yml) has stopped working and now it comments on all pull requests with numbers about how testing coverage has changed.

See https://github.com/processing/p5.js/pull/5230#issuecomment-835619909 for an example of its comment.

**Comment by outofambit** [comment]
update: tried https://github.com/processing/p5.js/commit/413ed4630864208e1209ee4ae359a44c2cf93353 to see if that might help

**Comment by outofambit** [comment]
I think we might need to add something like https://docs.codecov.io/docs/pull-request-comments#disable-comment to our codedov yaml

**Comment by maxdevjs** [comment]
@outofambit please, let me understand. Do you mean that `codecov-commenter` started commenting on all pull requests even if coverage **hasn't actually** changed?

Meaning, something that:

`require_changes: false  # if true: only post the comment if coverage changes`

could solve?

**Comment by outofambit** [comment]
hey @max good question, sorry i wasn't clearer in the issue body. previously, codecov never commented on pull requests and i'd like us to reinstate that behavior.

**Comment by maxdevjs** [comment]
@outofambit I'd like to help. 

But without breaking everything, as I am not used to how things work :)

I looked into:

- [p5.js/pulls](https://github.com/processing/p5.js/pulls) and checked for [commenter:codecov-commenter](https://github.com/processing/p5.js/pulls?q=commenter%3Acodecov-commenter) behavior:
	- #4561 seems to be the first occurrence (it dates back to May 18, 2020)
- [Release notes for Codecov](https://docs.codecov.io/changelog) reports a few changes to comment system, but one year old seems to be [Release Notes for Codecov v4.5.0](https://docs.codecov.io/changelog/release-notes-for-codecov-v450)
- [Actions](https://github.com/processing/p5.js/actions?query=code): do not specify a custom/fixed `codecov` version, right?

Am I missing something?

Did something change, at some point, in repo configurations that could affect `codecov-commenter` behaviour? I find only [two](https://github.com/processing/p5.js/commits/main/.codecov.yml) commits specifically involving `.codecov.yml`

Right now, I suspect that if the wanted behavior is no comments at all, the top-level `comment` key should then simply be set as `false`:

```yaml
comment: false
```

in `.codecov.yml`

Something that I am curious about is that does not affect all PRs, but I do not have knowledge of the code base.

Do you have any suggestions on a safe path to test this behavior?

**Comment by outofambit** [comment]
wow @maxdevjs thanks for all this great and thorough research!! 😍 I honestly don't know what changed, I'm assuming it was something on codecov's side since we've barely touched our config since we wrote it initially, but I don't really know. Maybe this has been broken for a long time (at least since May 2020?)

> Actions: do not specify a custom/fixed codecov version, right?

Correct! Our GitHub actions workflow [downloads the bash uploader directly from codecov](https://github.com/processing/p5.js/blob/7e348d3ddc6d9d4e89848b4a4ac9fe8697f078e4/.github/workflows/ci-test.yml#L30) and we don't specify a specific version. (I'm not even sure if we can.)

> Something that I am curious about is that does not affect all PRs, but I do not have knowledge of the code base. Do you have any suggestions on a safe path to test this behavior?

ah you are right, its not all of them. i just looked through a few PRs and i can't find a common theme for why some are but others not. regardless, i'm fine with trying your suggested solution and seeing if it helps! we can revisit if it comments again :)

> Right now, I suspect that if the wanted behavior is no comments at all, the top-level comment key should then simply be set as false

lets try it and see if it helps! thank you again! would you like to put that change up in a pull request?

**Comment by maxdevjs** [comment]
> don't know what changed, I'm assuming it was something on codecov's side

Neither I do :) I initially thought that this could be the case (change on their side), but so far I did not find clues about a change in `codecov` policy (going through its documentation).

> Correct! Our GitHub actions workflow [downloads the bash uploader directly from codecov](https://github.com/processing/p5.js/blob/7e348d3ddc6d9d4e89848b4a4ac9fe8697f078e4/.github/workflows/ci-test.yml#L30) and we don't specify a specific version. (I'm not even sure if we can.)

A quick look at [bash](https://codecov.io/bash) script does not make it clear if it is possible to pass the version. Probably it depends on their `CODECOV_ENV` or some other env variable.

> just looked through a few PRs and i can't find a common theme

Neither I found it so far. Actually I'd expect to find more comments on PRs. This is what makes me curious about its behavior.

> i'm fine with trying your suggested solution and seeing if it helps! 

I guess this would work:

```yaml
codecov:
  token: ...
comment: false
```

but, as it is not clear at the moment if `codecov-commenter` actually works as expected, I'd also propose

```yaml
codecov:
  token: ...
comment:
  require_changes: true
```

to check how it'd behave in future (only post the comment if coverage changes).

> we can revisit if it comments again :)

Actually, if it is good for you, I'd ask to wait a couple days: in this way I'd have the time to check more PRs and see if we can have more clues on why it comments as it does.

Perhaps it works just fine, but I also saw at least one PR in which I would not expect comments (and there were), and at least a couple in which I'd expect to find comments (but there were not) 🤪 this is curious (and probably depends on my lack of knowledge of the code base and the interaction with `codecov`).

> lets try it and see if it helps! thank you again! would you like to put that change up in a pull request?

Thanks to you. Yes, I would like. Please, before let me know if my proposed 'investigation' makes sense to you and if we can follow that path. Otherwise, I'd go with the `comment: false`.

**Comment by outofambit** [comment]
@maxdevjs I'm good with whatever change you want to try first! 🚀

**Comment by outofambit** [comment]
i think we're good now, thank you @maxdevjs! if anyone sees this happen again, we can repoen this issue and investigate.
