### ISSUE TITLE
State of Typescript declarations

### ISSUE THREAD

**Issue by cupcakearmy** [processing/p5.js#5247]
### How would this new feature help [increase access](https://github.com/processing/p5.js/blob/main/contributor_docs/access.md) to p5.js?

Actual typings help a ton since we can get autocompletions, code checking, function parameter guide, etc. Even if the user does not actually use typescript typings help a lot in editors like vscode where that information is used regardless if the actual language is js or ts.

#### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [x] Other (specify if possible)

#### Feature enhancement details:

There was a PR (https://github.com/processing/p5.js/pull/2279) and a related issue (https://github.com/processing/p5.js/issues/1392) about this that seemed merged. However in the bundle for the latest version `1.3.1` there is no sign of declaration files. The latest `@types/p5` `0.9.1` (probably outdated rn?) are not really usable and do not provide meaningful information as the instance mode is simply set to `any`.

Is there something in the pipeline? I think it would greatly increase the quality of the project 🙂

**Comment by limzykenneth** [comment]
@cupcakearmy The typescript definitions for p5.js (which is also the one published at `@types/p5`) is not maintained in this repo or under the processing organization but instead as a mostly volunteer run repo [here](https://github.com/p5-types/p5.ts). I'm not familiar with their current status so if there's specific out of date related issues, you should probably file it there. 

We also don't bundle typescript definitions with the overall p5.js bundle because we are not the one maintaining it so it can go out of date, in addition to us not having expectation of beginners using the typescript definitions and potentially get confused by the existence of the definition files.

**Comment by cupcakearmy** [comment]
Yeah it does not make sense to ship them if they are not coming from the source of course.
That's a pity, as beginner to p5 types would have helped me a ton, but for "non programmers" it might be confusing :)
