### ISSUE TITLE
CDN not working...

### ISSUE THREAD

**Issue by Coders-Digest911** [processing/p5.js#5333]
#### Most appropriate sub-area of p5.js?

- [x ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Details about the bug:
- p5.js version: 1.3
- Web browser and version: 91.0.4472.81
- Operating System: Chrome OS
- Steps to reproduce this:
No longer works for p5.js on KA, repl.it, or elsewhere.

**Comment by limzykenneth** [comment]
@Coders-Digest911 What is the URL of the CDN in use? As far as I've checked there doesn't seem to be a problem with the CDNs.

**Comment by Coders-Digest911** [comment]
I use this on KA and repl.it. Neither seem to work: <script src="
***@***.***/lib/p5.js"></script>
Could possibly be another problem, since a few other things have stopped
working now too.
Thanks for looking into this!

**Comment by limzykenneth** [comment]
@Coders-Digest911 I don't think the reply came through properly as I still can't see what the cdn link is. Can you try again? Perhaps directly through github would help.

**Comment by Coders-Digest911** [comment]
I used this one:   https://cdn.jsdelivr.net/npm/p5@1.3.1/lib/p5.js
This is found on your website. 
Example of not working:
https://www.khanacademy.org/computer-programming/new-coders-digest-911-hq-20/4523106246803456
Scroll to below Logo: There should be a canvas below there.
I also used to it create a Data Selfie App, using a different technique such as p5.js setup, draw, and other functions. This has stopped working too,...
Thanks for your help!

**Comment by limzykenneth** [comment]
The errors here are not related to CDN. The Khan Academy example is not using p5.js at all, it's using some kind of Processing syntax but p5.js is not the same as Processing so it won't run the code. The other example you provided has syntax error in the sketch code itself (there is a `let` keyword without a variable name declared after it).

I'm going to close this for now since as far as I can see no CDN issues are occurring. I would suggest posting on the [forum](https://discourse.processing.org) to help debug your code.
