### ISSUE TITLE
Source code links in Reference page no longer work

### ISSUE THREAD

**Issue by JetStarBlues** [processing/p5.js#5344]
#### Most appropriate sub-area of p5.js?
- [x] Other (documentation)

#### Details about the bug:

At the bottom of a Reference page entry, there is a link that points to the code associated with a function.

![sourceCodeLink](https://user-images.githubusercontent.com/4354703/124193973-fa037180-da84-11eb-856c-ebde84d355e2.png)

With the new release `1.4.0`, these links no longer work.

The urls seem to point to `https://github.com/processing/p5.js/blob/1.4.0/src/...`
However the tag in the repo is named `v1.4.0` not `1.4.0`.
Previous releases have both a `v` prefixed tag, and one without. Which is likely why the links worked before.

![sourceCodeLink2](https://user-images.githubusercontent.com/4354703/124193985-ff60bc00-da84-11eb-9be9-3704fc42a9e2.png)

**Comment by limzykenneth** [comment]
@outofambit Was the release steps run as `npm run release`? What I think is the problem here is that the git tag generated by `npm version` (ie. the versions without the "v" prefix) is either not generated (`npm version` was not run as part of `npm run release` or otherwise) or the generated git tag is not pushed to remote here. `npm run release` should have taken care of these already.

Can you check locally on the machine you created the release whether the git tag exist or not?

**Comment by outofambit** [comment]
@allcontributors add @jiwonme for code

**Comment by outofambit** [comment]
fixed with https://github.com/processing/p5.js-website/pull/1051
