### ISSUE TITLE
Increase the period of Perlin noise function

### ISSUE THREAD

**Issue by EnderShadow8** [processing/p5.js#5370]
I've been using the noise function built into p5 for creating a procedurally generated world. However, I've noticed that the noise function seems to be periodic. After a bit of research I found #4724 which also mentions the same issue. However, it was closed quickly with only an unsatisfactory response of "sample with a higher frequency" and "add more octaves". For some use cases, like mine, this is imply not possible according to my knowledge.

My desired result is something like this:

![](https://i.stack.imgur.com/khGGr.png)

Increasing the sampling frequency produces this:

![](https://i.stack.imgur.com/aN56S.png)

Increasing the sampling frequency and adding more octaves produces this:

![](https://i.stack.imgur.com/QurZo.png)

This is very different from the first image: the former has more peaks and troughs on a global scale, while the latter only has more local fluctuations.

**To be clear, noise layering is not the solution, as it produces the third result, not the first.**

Is it possible to include a noise implementation with a longer period? One or two orders of magnitude greater should be enough for almost any conceivable use case.

If not, are there any workarounds that produce more global fluctuations without encountering a repetition within a reasonable distance?

I've also posted a related question on gamedev SE [here](https://gamedev.stackexchange.com/questions/195108/how-can-i-increase-the-amount-of-peaks-in-perlin-noise-without-decreasing-sampli).

**Comment by limzykenneth** [comment]
The idea is to increase sampling frequency and increase the number of octaves while shortening the sample length so as to not hit the maximum period. The falloff factor will determine how much each subsequent octaves contributes to the overall noise which can be used to tweak the noise characteristic. Since perlin noise is fractal-like to a certain degree, you can sample from a small section of it instead of the whole period and since it returns values between 0-1, you can scale it up to fit your needs.

Looking at your graph however it seems what you want is not noise but rather random, noise don't tend to fluctuate that much in practice. You may want to look at interpolating a list of random numbers instead of noise.

**Comment by EnderShadow8** [comment]
I ended up interpolating hashes of coordinates in space like you said and it worked pretty well. Thanks.

Just out of curiosity, is it possible to increase the period of the noise function without that much effort by tweaking constants? I'm sure there are use cases for that where simple interpolation of hashes doesn't work.

**Comment by EnderShadow8** [comment]
@limzykenneth I ended up interpolating hashes of coordinates in space like you said and it worked pretty well. Thanks.

Just out of curiosity, is it possible to increase the period of the noise function without that much effort by tweaking constants? I'm sure there are use cases for that where simple interpolation of hashes doesn't work.

**Comment by limzykenneth** [comment]
The size is indeed hard coded (`4095` in the [codebase](https://github.com/processing/p5.js/blob/374acfb44588bfd565c54d61264df197d798d121/src/math/noise.js#L27)) and theoretically you can increase that size to get a longer period but in practice there is little reason to do so, aside from slowing down the function, because of the self similar nature and being able to add additional octaves for more detail, there is no real need to do that because with enough detail and sampling in small steps it will effectively be the same as increasing the overall period of the perlin noise. I'd recommend [this video](https://www.youtube.com/watch?v=Qf4dIN99e2w) if you want a bit more intuition about perlin noise.

As you've found as well if your use case somehow can't be met by perlin noise then you'll probably don't need perlin noise and instead use something else.
