### ISSUE TITLE
Unable to deconstruct p5 methods from npm library 

### ISSUE THREAD

**Issue by mikedane** [processing/p5.js#5401]
#### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [x] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [x] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Details about the bug:

This bug relates to the npm package. When creating a new instance of p5 `new p5(s => {})` the `s` parameter in the callback function is not able to be deconstructed.

It is my expectation that a dev would be able to say something like :

```js
new p5(s => {
  const { createCanvas, rect, fill, circle } = s
})
```

But upon calling any of these deconstructed functions the library throws an error. I haven't looked into this too much on the p5 side, but it seems to be an issue regarding 'this' and scoping. It's worth noting that when these functions are bound to the `s` variable they work (see third code example below)

I'm not sure if this is expected behavior or not, but with object deconstruction becoming more an more popular in the language at the very least this issue can serve as basic documentation of the quirk

- p5.js version: v1.4.0 (using npm package https://www.npmjs.com/package/p5)
- Web browser and version: Chrome 93.0.4577.63, Safari 14.1.2, Firefox 92.0
- Operating System: MacOSX 11.5.2
- Steps to reproduce this: 

I've created a minimal reproduction of the issue on Stackblitz (this uses a react template, but I've also tested this in Svelte and a vanilla npm project)
https://stackblitz.com/edit/react-jp1d6n?file=src/App.js

Simplified code for quick reference:

```js
import p5 from 'p5'

// this works
new p5(s => {
  s.setup = function() {
    s.createCanvas(100, 100);
  };
});

// this errors out
new p5(s => {
  const { createCanvas } = s;

  s.setup = function() {
    createCanvas(100, 100);
  };
});

// this works but we have to bind s to the call
new p5(s => {
  const { createCanvas } = s;

  s.setup = function() {
    createCanvas.call(s, 100, 100);
    // createCanvas.bind(s)(100, 100)
    // createCanvas.apply(s, [100, 100])
  };
});
```

I've tried this same thing with many of the p5 functions, not just `createCanvas`

**Comment by limzykenneth** [comment]
This is an inherent problem with the destructuring syntax and not a p5.js caveat. For example when you try to run the following:

```javascript
const date = new Date();

const { getDate } = date;
console.log(getDate());
```

You will get an error about `undefined` as well. The reason is that a lot of the object oriented functions in JS require that they be executed in the right context (ie. the right value of `this`). When a function is destructured from the underlying object, it loses its original context as there is not a direct association with the newly destructured and the parent object (essentially a new copy is created) so any reference to `this` in the function's implementation will return `undefined` or whatever context it happens to be in (maybe `window`).

**Comment by mikedane** [comment]
Thanks for the explanation!
