### ISSUE TITLE
Loading audio in React

### ISSUE THREAD

**Issue by malutanpetronel** [processing/p5.js#5435]
Hi all 

I get an issue described also here: https://github.com/jamesrweb/react-p5-wrapper/issues/122

It looks I get
p5.sound.js:543 Uncaught ReferenceError: p5 is not defined
at Object. (2.c4420ea7.chunk.js:2)
at n (2.c4420ea7.chunk.js:2)
at Module. (2.c4420ea7.chunk.js:2)
at n (2.c4420ea7.chunk.js:2)
at 2.c4420ea7.chunk.js:2
at Object. (2.c4420ea7.chunk.js:2)
at a (localhost/:1)
at Module.148 (main.7dfa0fb0.chunk.js:1)
at a (localhost/:1)
at t (localhost/:1)

```
import React from "react";
import { ReactP5Wrapper } from "react-p5-wrapper";

import p5 from "p5";
import "p5/lib/addons/p5.sound";

const mic = new p5.AudioIn();

function sketch(p5) {
    p5.setup = () => {
        mic.start();
        p5.createCanvas(710, 200);
    };

    p5.draw = () => {
        p5.background(200);

        let vol = mic.getLevel();
        console.log(vol);

        p5.fill(127);
        p5.stroke(0);
        // Draw an ellipse with height based on volume
        let h = p5.map(vol, 0, 1, p5.height, 0);
        console.log(h);
        p5.ellipse(p5.width / 2, h - 25, 50, 50);
        p5.ellipse(0, 100, 100, 200);
    };
}

export default function Ambient() {
    return <ReactP5Wrapper sketch={sketch} />;
}
```

**Comment by limzykenneth** [comment]
I'm not sure that `import "p5/lib/addons/p5.sound";` will work at all as addon libraries relies on existing globally available `p5` object in order to bind their methods to it.

**Comment by Asilver-jpg** [comment]
Been looking for the last 5 hours on a solution for this that actually works. Tried in instance mode and with various p5-react wrappers to no avail and been on tons of github threads. I'm at the point where I am just using an external library to handle sound/sound analysis and passing the data in props with a wrapper. Would love to see this fixed since p5js' implementation is simple to use and it's an elegant library. Unfortunately, most of the forums I've found point to p5js just not working super well with other libraries all the time due to the way it exports things. A shame.

**Comment by jamesrweb** [comment]
I just documented how to use plugins and constructors in [P5-wrapper/react](https://github.com/P5-wrapper/react) to help users with using the audio plugin or any other plugin or constructor more generally for that matter. Hope it helps and when it is merged I hope you get chance to use it.

You can find [the documentation](https://github.com/P5-wrapper/react#p5-plugins-and-constructors) for using plugins and constructors in react with an example in the link above.

**Comment by limzykenneth** [comment]
I would recommend as @jamesrweb mentioned using P5-wrapper/react if using imports and constructors are required. I'm closing this issue for now.
