### ISSUE TITLE
Incompatibility between p5.ble.js and full-screen share

### ISSUE THREAD

**Issue by meh-who** [processing/p5.js#5475]
p5.ble.js used to work when present in share/full-screen mode, now it no longer works and gives the error message: 

Error: SecurityError: requestDevice() called from cross-origin iframe.

Any ways to fix it or go back to previous full-screen version?

**Comment by limzykenneth** [comment]
I believe your problems are with the online editor. Currently all sketch (even fullscreen ones) are run through an iframe which cannot call requestDevice(). You may want to file an issue with the web editor team [here](https://github.com/processing/p5.js-web-editor/issues) and see if there can be a away around it. Otherwise you can try running a local server.

I'm closing this for now as it's not related to the p5.js library itself.
