### ISSUE TITLE
p5js copy() function - but it won't paste...

### ISSUE THREAD

**Issue by cutandpost** [processing/p5.js#5496]
Hello!

I've been playing with the copy() function and following examples online but when I use it I can't seem to get what has been copied to stay pasted - it flashes up for an instant. I perhaps thought this was because I had put it in draw() and examples I had seen had it in setup() however, I saw an example that used it in mouseDrag - that code worked perfectly and I emulated it in my code, or so I thought I did, and it hasn't worked either. I then tried to make it it's own function and to simply call that in draw instead but that hasn't worked - I get the same result.

Can anyone help?
Here is my code posted below, the version with the copy in its own function but the way I had it in previously is there but commented out:

let greenL, people, rocks, people2, people3, ice, space;
let sx, sy, sw, sh, dx, dy, dw, dh;
let timer = 0;

function preload() {
 greenL = loadImage('data/marvellous-green.jpg');
 people = loadImage('data/people1.jpg');
 rocks = loadImage('data/rocks1.jpg');
 people2= loadImage('data/person2.jpg');
 people3= loadImage('data/person3.jpg');
 ice= loadImage('data/ice.jpg');
 space= loadImage('data/digital-space.jpg');
}

function setup() {
 createCanvas(windowWidth, windowHeight);
}

function copyCat() {
   copy(sx, sy, sw, sh, dx, dy, dw, dh);
}

function draw() {
 background(0);

 image(people, 0, 0, (width/3), height);
 image(rocks, (width / 3), 0, (width/2), (height/2));
 image(people3, (width/1.5), 0, (width / 4), height );
 image(greenL, 0, (height/1.75), width, (height/2.5));
 image(space, 0, (height/2), width, 50); 
 image(people2, (width/2), 0, (width/4), height);
 
 sx = int(random(0, width));
 sy = int(random(0, height));
 sw = int(random(50, 600));
 sh = int(random(30, 400));
 dx = int(random(-50, (width-50)));
 dy = int(random(-50, (height-50)));
 dw = int(random(50, 600));
 dh = int(random(30, 400));
 
 /*  copy((sx+50), (sy+50), sw, sh, (dx+100), (dy+100), dw, dh);
   copy((sx+100), (sy+100), sw, sh, (dx+150), (dy+150), dw, dh);
   copy(sx, sy, sw, sh, dx, dy, dw, dh); */
 
 if (millis() >= 1000+timer) {
  copyCat(); 
  timer = millis();
  print('1 x timer');
 }
}

**Comment by cutandpost** [comment]
Thank you!

**Comment by awelles** [comment]
Hi @cutandpost,

The first line in your `draw()` clears your canvas and sets everything black:

```js
background(0);
```

Then six images are loaded every loop, so they'll appear in the same place all the time, being redrawn after being cleared:

```js
image(people, 0, 0, (width/3), height);
image(rocks, (width / 3), 0, (width/2), (height/2));
image(people3, (width/1.5), 0, (width / 4), height );
image(greenL, 0, (height/1.75), width, (height/2.5));
image(space, 0, (height/2), width, 50);
image(people2, (width/2), 0, (width/4), height);
```

Finally you randomly generate parameters to call copy with:

```js
sx = int(random(0, width));
sy = int(random(0, height));
sw = int(random(50, 600));
sh = int(random(30, 400));
dx = int(random(-50, (width-50)));
dy = int(random(-50, (height-50)));
dw = int(random(50, 600));
dh = int(random(30, 400));
```

If you were to call copy with these random parameters _every_ loop a randomly placed copy would be visible only for that frame, before getting cleared by `background(0)` next loop. So yeah, you'll see a flashing random result bounding around on top of the six images you drew.

However you don't call it every loop. You only call it when 1000ms has passed since your last call:

```js 
if (millis() >= 1000+timer) {
copyCat();
timer = millis();
print('1 x timer');
}
```

So you'll see a random copy for **1 brief frame every second** or so. All frames (most of them) will just be the six images.

Try moving the `background(0)` call into `setup()`. Then your canvas doesn't get cleared every frame, and your copies will pile up, one new one every second. Maybe that's what you're looking for?

**Comment by cutandpost** [comment]
Hi there!

Oh so simple yes thats done it - ive put the background() and the images
into setup() and its sorted it out, thank you!
