### ISSUE TITLE
angleMode not changing for external canvas

### ISSUE THREAD

**Issue by saiakarsh193** [processing/p5.js#5499]
The angleMode is not changing when I use it on a new canvas (created using createGraphics).

#### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [x] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Details about the bug:

- p5.js version: 1.4.0
- Web browser and version: Chrome 96.0.4664.93 (Official Build) (64-bit) (cohort: Stable)
- Operating System: Windows 11 Version 21H2 (Build 22000.318)
- Steps to reproduce this:
```js
overlay = createGraphics(width, height);
overlay.angleMode(DEGREES);
```

**Comment by limzykenneth** [comment]
I'm not fully sure what the use case would be here, can you perhaps provide a short snippet of intended usage? Thanks.

**Comment by limzykenneth** [comment]
The angle mode is set per p5 instance instead of per graphics instance. The difference being functions such as `cos()` `sin()` etc are not related to the canvas created by `createCanvas` or graphics created by `createGraphics` but rather to the p5 instance itself (created by implicit `new p5()` or explicit `new p5(sketch)` calls), which means there is no `angleMode` function that you can call on p5.Graphics as that is set basically globally.

**Comment by saiakarsh193** [comment]
OK, thanks for the clarification. Sorry for the false alarm.
