### ISSUE TITLE
elt.size() issues

### ISSUE THREAD

**Issue by b2renger** [processing/p5.js#552]
I tried several things to get the size of several kind of elements, and run in a few issues

Let's consider this code 

```javascript
  var p = createElement('p',"a length varying string can be put here, so that the text overlaps and maybe even several times...");
  //p.size(720,AUTO);
  p.position(600,420);
  p.id('para');

  var elt = document.getElementById('para');
  var paragraphHeight = float(elt.height);
  var paragraphWidth = float(elt.width);
  console.log(paragraphHeight);
  console.log(paragraphWidth);
```

if you don't resize the element with the size() method, I get "NaN".

if I use AUTO in the size() method, i get "undefined".

if I use hardcoded numbers, I get the right numbers.

Maybe I shouldn't be doing this, that way ?

Also I noticed that using 'AUTO' on a video elt doesn't work, you have to hardcode the number.

**Comment by b2renger** [comment]
Actually my method wasn't right, this works and seems much more direct

```javascript
var p = createP("very long string ..."); // declared as a global variable
p.size(720,AUTO);
console.log(p.height);
```

though using 'AUTO' on a video element still seems to be an issue

**Comment by lmccart** [comment]
I just fixed a couple lines so AUTO should work now. however, it may come out looking weird depending on when you call it. this is because the video takes a moment to load asynchronously once createVideo() is called, so if you call size() right after, it won't yet have loaded a default size / aspect ratio to work with. you could work around this by wrapping the size() call within a short setTimeout.

**Comment by brysonian** [comment]
or better yet pass a callback as the second arg. Seems `createImg()` doesn't expose the onload callback, should probably add that in, i'll make a separate issue.

**Comment by lmccart** [comment]
yes very good idea!
