### ISSUE TITLE
loadXML() not working with preload

### ISSUE THREAD

**Issue by shiffman** [processing/p5.js#562]
Not sure if this is related to #486, but this is working for me:

```
function setup() {
  loadXML("data/data.xml",test);
}

function test(xml) {
  console.log(xml);
}
```

but this is not:

```
function preload() {
  xml = loadXML("data/data.xml");
}

function setup() {
  console.log(xml);
}
```

**Comment by lmccart** [comment]
I looked into this a bit, the issue is that while methods like loadJSON add properties to an existing returned object (https://github.com/processing/p5.js/blob/master/lib/p5.js#L3074) loadXML doesn't do anything at the moment (https://github.com/processing/p5.js/blob/master/lib/p5.js#L3254).

A quick fix would be to add a line `ret.push(resp)` inside the reqwest callback. However, I mention all this because it brings up a larger question about xml. As it is, the methods to dig into the #document object returned are a little opaque: http://www.w3schools.com/dom/dom_document.asp. Do we want helpers for this? By adding the `ret.push(resp)` line, we would further obscure the data by placing the #document node inside an array. Any thoughts?

**Comment by shiffman** [comment]
Ah, interesting question.  I haven't dug into the XML stuff at all b/c I just always jump immediately to JSON with my examples.  I now see that what is returned is the native xml document object.  This is tricky b/c on the one hand my instinct is to say let's not recreate the wheel and build out an entire new set of XML methods. At the same time if we're including and supporting `loadXML()` we've got to provide pathways to success and not just expect users to find another JS framework or wade through the mozilla docs, etc.

I suppose the obvious answer here is to just mirror the basic methods from Processing:

https://processing.org/reference/XML.html

Are these weird and not-consistent with the web ways of doing XML?  Unlike with JSON where we would never reimplement all the crazy `getJSONObject()` from Processing/Java, this might actually be a place where the Processing API is a good guide?

**Comment by alignedleft** [comment]
I just came across this issue while trying to see if p5 implements any XML features.

I'd vote in support of implementing something to this effect.  To answer @shiffman’s question, I don't know if Processing's XML methods are a good model for p5's context, but the native browser methods are a bit crazy, er, not exactly beginner-friendly.

**Comment by workergnome** [comment]
So, just to clarify:  loadXML **does not** work with preload.  We should either remove the documentation that says it does, or we should fix the code. 

Additionally, we should consider adding a new feature, which are the processing XML methods.  (I would recommend opening a new issue for that.)

Have I missed something?

**Comment by lmccart** [comment]
closed with https://github.com/processing/p5.js/pull/709
