### ISSUE TITLE
how to add .gltf loder in p5.js

### ISSUE THREAD

**Issue by jagadeeshCoder** [processing/p5.js#5674]
### Increasing Access

this new feature helps in animating and also for 3d games 

### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [X] WebGL
- [ ] Other (specify if possible)

### Feature request details

how to add .gltf in p5.js

**Comment by jagadeeshCoder** [comment]
how to add .gltf in p5.js
there is any way to add .gltf in p5.js

**Comment by jagadeeshCoder** [comment]
i also want to add my gltf models in p5.js
gltf loder is so help ful to  make 3d games in p5.js

**Comment by stalgiag** [comment]
p5.js does not support GLTF. Check out babylon.js or three.js.

**Comment by jagadeeshCoder** [comment]
To Stalgiag 

I dont want to go to babylon.js or three.js.
because they are so tough and they are not satysfyng me in 3d rendering as p5.js

**Comment by stalgiag** [comment]
Hi @jagadeeshCoder thanks for letting me know. The goal of p5's WebGL mode is to give a space to play with p5's syntax in a 3D space. This means that we only offer primitive geometry, simple lighting, limited materials, and two options for 3D model loading. These two options were chosen because they are the most common file formats for people first learning how to make models. GLTF is a more advanced file format because it can contain so much information about texture, material, animation, rigging, etc. This file format is better suited to a full 3D game engine. p5.js WebGL mode is not this.

If you want to work with p5.js, I recommend embracing the constraints. Sometimes limitations on what you can use can result in exciting creative surprises. If the constraints don't feel useful, you can also try looking into a-frame which runs on three.js. It has a straightforward HTML-based syntax and it runs on top of three.js so it supports GLTF/GLB files.

**Comment by jagadeeshCoder** [comment]
can you help me on making a 3d game website.
url  " https://alpha-1238.web.app/ " this is my website
please help me on making 3d game on it

**Comment by jagadeeshCoder** [comment]
i want to add gltf models in my website
