### ISSUE TITLE
webgl pixel density adjustments lead to inconsistent results across browsers 

### ISSUE THREAD

**Issue by ofZach** [processing/p5.js#5690]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [X] WebGL
- [ ] Other (specify if possible)

### p5.js version

v1.4.1

### Web browser and version

chrome 102.0.5005.115  / safari Version 15.5 (17613.2.7.1.8)

### Operating System

osx

### Steps:
1.  run this sketch (based on @aferriss shader code) https://www.dropbox.com/s/65e6acfnuzspjt2/simpleCode.zip?dl=0
2. adjust density (1, 3, 10, etc) 
3. notice that chrome seems similar until a certain point, at which point it differs from safari 

density = 1
<img width="1408" alt="Screen Shot 2022-06-12 at 9 29 45 PM" src="https://user-images.githubusercontent.com/142897/173264557-feb9ddf2-ca5e-4ece-86ab-72a06aec2dad.png">
density = 10
<img width="1425" alt="Screen Shot 2022-06-12 at 9 30 07 PM" src="https://user-images.githubusercontent.com/142897/173264553-e64d57db-54bb-4545-986d-50385dbd9f61.png">

it feels like at some point, chrome may be rendering only a subsection of the canvas, etc.

**Comment by aferriss** [comment]
Hey Zach, I believe this is actually an issue with different browser vendors and not p5. There's a couple different values to watch here. 

First we have webGL's viewport dimensions. This is what p5 is setting when you make a big canvas or set the pixel density really high. Effectively `gl.viewport(x, y, w, h)`. You can inspect these dimensions by doing 
```
const renderer = createCanvas(windowWidth, windowHeight, WEBGL);
const gl = renderer.GL;
const dims = gl.getParameter(gl.MAX_VIEWPORT_DIMS);
```
On my machine these are 16384x16384.

Next we have drawing buffer dimensions. This is the size that the browser is capable of drawing the canvas at. This varies by browser vendor. On my machine in chrome the max for a square canvas was 5760x5760, though this can vary if your canvas is rectangular (for ex 7892x4203 would still work). In Safari it seemed to be unbounded (or at least safari ran out of memory before I got to the max). 

You can query drawing buffer dims pretty easily.
```
const renderer = createCanvas(windowWidth, windowHeight, WEBGL);
const gl = renderer.GL;
console.log(gl.drawingBufferWidth, gl.drawingBufferHeight);
```

In your example, instead of passing the canvas width and height to the shader, you should pass the drawingBufferWidth & drawingBufferHeight instead. And in the shader you no longer need to account for pixelDensity when calculating your uv's.

If you're trying to make a really big canvas for saving high resolution output, then you probably need to use a framebuffer, which I don't believe are subject to the same limitations as the drawing buffer. I have a small extension library to help with this in p5, although it still needs some work.
https://github.com/aferriss/p5Fbo

I also saw another one published recently, but haven't tried it yet.
https://github.com/davepagurek/p5.Framebuffer

Hope that helps!

**Comment by ofZach** [comment]
ah thanks!  that's super helpful (and similar-is to results I saw) -- so I'm going to close this as your answer gives enough info for how to fix the discrepancy.    I will check out the fbo options -- in my experience with OF the solution I always go to is to use maxTexture size for the largest possible FBO for large scale offscreen drawing.

**Comment by aferriss** [comment]
One gotcha with fbo's in webGL is that at least in webGL1, they don't do any antialiasing for 3d geometry. So you may see some differences depending on what you're doing. The other thing is that they render with the y uv flipped. An easy fix, but sometimes annoying if you have a ping pong buffer or feedback loop type thing happening.

**Comment by ofZach** [comment]
this is probably a separate issue, but in case it's useful I've noticed that if I change pixelDensity after createCanvas with webgl (say to render higher res on key pressed) the canvas size changes (ie, the output image if I save) but the gl.drawingBufferWidth and height do not -- meaning, if I use them in my shader, the sketch is scaled based on the relative change density....

I can't 100% tell if pixelDensity is working as intended in this case :)    what I am trying to do is say, save a pixelDensity(4) version of a shader on keypressed which is default pixelDensity(2) on screen.   

this isn't a huge issue, I can def work around it since it seems consistent, but mainly speaks to a larger question I don't 100% understand which is how to reallocate the graphics context -- ie, I am fine creating a new canvas with webgl for a screenshot and then allocating back to the original when done, but I found once I do remove() it's kind of game over.   I think it's not 100% clear how you could change the canvas (or if you need to)

**Comment by ofZach** [comment]
again, probably a good case for using an FBO :)

**Comment by ofZach** [comment]
to follow up (and apologies for moving this in another direction) I found a combination of 

```
pixelDensity() 
renderer.resize();
```
worked -- I will open another issue as I feel like it's a little unclear how pixelDensity should work with webgl and to make sure I understand what's going on under the hood.    My impression (and again, I don't 100% understand things so apologies if I'm off here) is that calling pixelDensity after the renderer has been allocated seems to change the canvas (output) but not the rendering context for webgl...     

(again this isn't exactly related to the above issue but all these things are in the context of trying to do high res output...)
