### ISSUE TITLE
Properties of a dom p5.element, position?

### ISSUE THREAD

**Issue by radames** [processing/p5.js#579]
I was trying to access the position of a slider and noticed that only the property `slider.width` and `slider.heigh` are accessible.
I manage to get the relative positions  through `slider.elt.style.left` or `slider.elt.style.top` .
Wouldn't be nice to have access straight from the element like `slider.x` `slider.y`? Perhaps with center mode or corner mode.

**Comment by futuremarc** [comment]
`position()` with null args now returns an object with `x` and `y`. 

Going to close this one because we decided against storing the position in `x` `y` on the Element since any changes to position in css made without using p5 would break those attributes. Same thing applies to `width` and `height` attrs but we need those for the canvas.

**Comment by radames** [comment]
it makes sense! great!

**Comment by workergnome** [comment]
It will certainly break a ton of examples, and also working code.  Would it be a terrible idea to hook into the window `resize` event, and check-and-update canvas sizes when that happens?

**Comment by futuremarc** [comment]
@lmccart is this something we should try to address?

**Comment by shiffman** [comment]
@workergnome are you confusing the global `width` and `height` variables for the `p5.Element` ones?  I don't believe the latter appear in many examples (and are unrelated to a `resize()

**Comment by workergnome** [comment]
Oops—I am in fact confusing those!  Thank you for the clarification.
