### ISSUE TITLE
The method keyIsDown() does not work with or || statements.

### ISSUE THREAD

**Issue by iwantfoodzz** [processing/p5.js#5808]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [X] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [X] Other (specify if possible)

### Web browser and version

Google Chrome

### Operating System

Chrome OS

### Steps:
1.run
2. test different keys

### Snippet:
[bug.p5.js.zip](https://github.com/processing/p5.js/files/9611904/bug.p5.js.zip)

```
[bug.p5.js.zip](https://github.com/processing/p5.js/files/9611906/bug.p5.js.zip)

function draw() {
  //38= up arrow key 40 = down arrow key
   if (keyIsDown(38||40)){
      print (1);
       }
}
```

**Comment by javiert01** [comment]
I don't think this is a bug since the `keyIsDown` function expects as param a `Number`. The expression "38 || 40" will return the number 38 and that's why it is only working for the up arrow key. If you want to make it work with an or statement or any other logical operator you should use it like this:
```
if (keyIsDown(38) || keyIsDown(40)) {
    // your code here
}
```
Hope this helps!
