### ISSUE TITLE
Tint not working on webcam

### ISSUE THREAD

**Issue by Vamoss** [processing/p5.js#5868]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [X] Other (specify if possible)

### p5.js version

1.5

### Web browser and version

107.0.5304.110 (x86_64) 

### Operating System

Mac 11.2.1

### Steps to reproduce this

Tinting webcam is not working on 1.5 version:
https://editor.p5js.org/Vamoss/sketches/Sxtk8038o

Same code working on 0.7.2:
https://editor.p5js.org/Vamoss/sketches/R0-NIgDcT

Cheers,
Vamoss

**Comment by davepagurek** [comment]
Oops, I caused this regression, thanks for catching this! I removed the `loadPixels` call inside `_getTintedImageCanvas` because the new implementation doesn't loop through the `pixels` array, but that call also had the side effect of making sure media elements had a canvas that could be used to do the tint on. I'll try to fix it!
