### ISSUE TITLE
vertical textAlign center broken in 1.5.0 when printing multiple lines

### ISSUE THREAD

**Issue by JuanIrache** [processing/p5.js#5880]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [X] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### p5.js version

1.5.0

### Web browser and version

multiple

### Operating System

multiple

### Steps:
1. Example: https://editor.p5js.org/JuanIrache/sketches/WSqCpDuTp

The first line of text disappears when using textAlign(anything, CENTER)

```
textAlign(CENTER, CENTER)
text('first line\nsecond line\nthird', 150, 150)
```

This is working well on version 1.4

**Comment by dhowe** [comment]
Confirmed

**Comment by limzykenneth** [comment]
@dhowe I did a git bisect and narrow down the first commit to have the problem at https://github.com/processing/p5.js/commit/764edeb6dc610cea7810cda255ffaa0720fbff45 which probably make more sense than https://github.com/processing/p5.js/commit/aeda6d2f54b8567bababa6a01676e613e3513088 as the latter only changes markdown files in the contributor docs.

**Comment by dhowe** [comment]
yes, I saw that aeda6d2 had no code changes, which didn't make much sense ...

**Comment by inaridarkfox4231** [comment]
Excuse me, I have a suggestion.  
First, there are two problems.  

1. If you specify CENTER or BOTTOM for the second argument of textAlign without the 4th and 5th arguments of the text function, some lines will disappear. [sample code here](https://editor.p5js.org/dark_fox/sketches/I6E6F_Bzh)
2. If CENTER is specified for rectMode, some lines may disappear when box is set by the text function. [sample code here](https://editor.p5js.org/dark_fox/sketches/GFw5zBkaSg) 

This can be fixed by doing:
First, the first problem is that finalMinHeight remains y when the 4th and 5th arguments are not specified, so you can subtract offset like this:
Line numbers refer here: [src/core/p5.Renderer.js](https://github.com/processing/p5.js/blob/main/src/core/p5.Renderer.js)

Before correction:

```javascript
// src/core/p5.Renderer.js
442      this._renderText(
443        p,
444        lines[i],
445        x,
446        y - offset,
447        finalMaxHeight,
448        finalMinHeight
449     );
```

after correction:

```javascript
// src/core/p5.Renderer.js
442      this._renderText(
443        p,
444        lines[i],
445        x,
446        y - offset,
447        finalMaxHeight,
448        finalMinHeight - offset
449     );
```

The second problem is that finalMinHeight is not corrected when rectMode is CENTER, so you should correct it as follows:

before correction:

```javascript
// src/core/p5.Renderer.js
269      if (this._rectMode === constants.CENTER) {
270        y -= maxHeight / 2;
271      }
```

after correction:

```javascript
// src/core/p5.Renderer.js
269    if (this._rectMode === constants.CENTER) {
270      y -= maxHeight / 2; finalMinHeight -= maxHeight/2;
271    }
```

These corrections do not affect the specification that the overflowing lines are eliminated.

**Comment by dhowe** [comment]
this is great, @inaridarkfox4231 - do you want to submit a pr ?

**Comment by inaridarkfox4231** [comment]
thank you for your reply!
I want to submit pr, but I'm sorry, I don't know how to do it. so if you don't mind, I would like you to teach me...

**Comment by inaridarkfox4231** [comment]
thanks! I tried creating a pull request. It's the first time I made it, so there may be some flaws, so if you don't mind, I'd appreciate it if you could check it...
