### ISSUE TITLE
startup exception:  TypeError: Array.prototype.forEach called on null or undefined

### ISSUE THREAD

**Issue by magicmouse** [processing/p5.js#5942]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### p5.js version

v1.5.0

### Web browser and version

Chrome

### Operating System

Mac OSX

### Steps:
1.  during init of p5.js it generates the error without doing anything
2.
3.

### Snippet:

```js

// Paste your code here :)
![bug1](https://user-images.githubusercontent.com/5481132/211134529-670c515a-6eb9-4ea0-9601-f1bccf71c6b2.gif)

```

**Comment by magicmouse** [comment]
If you turn on the "stop on an exception" in Chrome, the p5.js code will die during its initialization. So there is a serious bug in the init code. The p5 system should be able to be loaded without hitting an exception. I only have 5 lines of code in my example, so this is not in my code or caused by my code.

**Comment by gaurav8y785675474** [comment]
hello magicmouse
i am a beginner in open source world
can you please tell me exact location of code in files .
so that i can work on that

**Comment by magicmouse** [comment]
Just run through 5KJS and turn on stop on exception in chrome, and it should happen to you as well. It's just a bug inside the o5 JS initialization code, or someone has forgotten to test for null before they iterate across array— Whoever is happy will make others happy tooOn Jan 7, 2023, at 2:34 AM, gaurav8y785675474 ***@***.***> wrote:﻿
hello magicmouse
i am a beginner in open source world
can you please tell me exact location of code in files .
so that i can work on that

**Comment by davepagurek** [comment]
When I create a new project on editor.p5js.org and run it, I don't the debugger caught on any exceptions, except for if I enable pausing on *caught* exceptions:

<img width="200" alt="image" src="https://user-images.githubusercontent.com/5315059/211166025-89a9bfc4-c5fe-4a24-aab0-b918ba14cb10.png">

This exception is intentional (I believe it's part of Webpack's module importing?) and gets caught and handled. Do you still get any errors if you turn off that caught exceptions checkbox?

**Comment by magicmouse** [comment]
No, just caught exceptions.
If this behavior is intentional, that is fairly odd practice, as it is very common for developers to wish to trap exceptions.
One doesn’t normally use exceptions, but perhaps this is the only way to detect some feature.

you can consider this issue closed i guess then.

**Comment by limzykenneth** [comment]
> it is very common for developers to wish to trap exceptions

This is exactly what is happening in the p5.js code, exception are generated and trapped (caught) then handled. Turning on "Pause on caught exceptions" is a debugging tool that enables developers to see that the exceptions generated are caught properly and as expected, where as the browser would normally only pause on **uncaught** exception, this toggle make it so that the browser pause on **all** exceptions, even those that has been trapped (caught).
