### ISSUE TITLE
textAlign(CENTER, CENTER) causes a text string containing a line break to not display first line

### ISSUE THREAD

**Issue by tomthecollins** [processing/p5.js#5956]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [X] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### p5.js version

1.5.0

### Web browser and version

Chrome 108.0.5359.124

### Operating System

MacOSX 10.14.5

### Steps:

In setup(), put `textAlign(CENTER, CENTER)` and a text string containing a line break `\n`. The first line will not be rendered. For example, for the following code, only the word "disappears" appears. Works fine (as expected) in version 1.4.2.

### Snippet:

```js
textSize(12);
textAlign(CENTER, CENTER);
text('word\ndisappears', width/2, height/2);
```

**Comment by davepagurek** [comment]
Hi, thanks for filing this! I think this is the same bug as in https://github.com/processing/p5.js/issues/5880, which has now been fixed in the main branch but hasn't yet landed in a new p5 release. I'm going to close this one for organizational purposes, but feel free to reopen this if you notice it continue to happen afterwards!

**Comment by tomthecollins** [comment]
Thanks, yes, agreed it's the same.
