### ISSUE TITLE
Fatal error When running npm test on fresh github clone

### ISSUE THREAD

**Issue by shamun-khatri** [processing/p5.js#6038]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [X] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### Operating System

Windows 

### Steps to reproduce this

While setting up p5.js locally i am getting this error. whn i press command npm test after npm ci.
### Snippet:

Running "eslint-samples:source" (eslint-samples) task
Fatal error: Cannot read properties of undefined (reading 'prefixLength')

```

**Comment by limzykenneth** [comment]
Can we get the node.js and npm version you have?

**Comment by aditya-shrivastavv** [comment]
I am facing the same problem. 
node version - "18.12.1"

**Comment by limzykenneth** [comment]
@aditya-shrivastavv Can you share the npm version as well? The OS version could be helpful too.

**Comment by aditya-shrivastavv** [comment]
nvm version = **1.1.10**

OS version-
Windows 11
version = **22H2**

Another problem I am having is with prettier, The problem is so annoying that I had to disable prettier. When I save the file so many changes happens.
for example -

```js
function foo() {

}
// turns to 
function foo () {  // gap inserted

}

const obj = {
 prop1: value1,
 prop2: value2
}
// turns to
const obj = {
 prop1: value1,
 prop2: value2,  // comma automatically inserted
}
```

and so many changes like this
prettier latest version

**Comment by monmon2003** [comment]
Include this line of code inside rules in .eslintrc.json file : "linebreak-style": ["error", "windows"]
On including this, npm test works
![2023-03-03](https://user-images.githubusercontent.com/122162780/222529555-838f67fa-7bbd-4b84-b8d6-ceeeb17701da.png)

**Comment by limzykenneth** [comment]
@aditya-shrivastavv I can't fully replicate, if you can find out a bit more why that's happening it would be great. We do not use prettier for the formatting of p5.js and I don't recommend the use of prettier here.

@monmon2003 I don't think that is relevant here and for p5.js we will enfore unix line endings instead of windows line endings. You should either set your text editor to use unix line endings, auto detect file line endings, or use the editorconfig plugin.

**Comment by aditya-shrivastavv** [comment]
If we don't use prettier then why there is `.prettierrc` file in the codebase ? shouldn't we remove it ? due to it my prettier extension activates.

and here is my log on running `npm test` on a fresh github clone

![image](https://user-images.githubusercontent.com/81470938/222636476-d847180f-6c50-4775-8129-7f447862bcd5.png)

**Comment by limzykenneth** [comment]
We should remove the prettierrc file, I probably forgot last time, but the prettier dependency has already been removed from the project.

**Comment by aditya-shrivastavv** [comment]
Yes @limzykenneth , that will be very helpful 😊

**Comment by monmon2003** [comment]
@limzykenneth  Okay I will try using the editorconfig plugin.

**Comment by aditya-shrivastavv** [comment]
`Fatal error: Cannot read properties of undefined (reading 'prefixLength')`
is still not resolved. I wonder is there a global dependency the project requires to run tests? 🤔

**Comment by limzykenneth** [comment]
@aditya-shrivastavv There should be no global dependency required. If you have access to another machine, try building and testing on it, if it passes, we can start to compare the two.

**Comment by shamun-khatri** [comment]
Having one more question, Is this happening to all of the windows machines?

**Comment by limzykenneth** [comment]
@calebfoss I think it would make sense to do so, especially if that would solve this issue. Do go ahead with a PR if you like.
