### ISSUE TITLE
vector.get() doesn't seem to work anymore?

### ISSUE THREAD

**Issue by hanswillem** [processing/p5.js#605]
Hi all,

For some reason vector.get() doesn't work for me anymore. I use version 0.4.4 (April 12, 2015).
Any ideas?

Grtz,
Hans Willem

**Comment by GoToLoop** [comment]
* Name was changed to **copy()**, but maintained the old name **get()** in the reference page:  
https://github.com/processing/p5.js/blob/master/src/objects/p5.Vector.js#L130
* Even though arbitrarily deprecated now, **get()** is still the most known name in order to get a clone outta a vector.
* And still present in the Processing Java's reference page:  
https://processing.org/reference/PVector_get_.html
* While **copy()** is not even mentioned nor found there:  
https://processing.org/reference/PVector.html
* IMO, **get()** should be accepted along **copy()**, since the latter is not very known and the former is valid in Processing Java w/ no end in sight!

**Comment by hanswillem** [comment]
Hi, vector.copy() does indeed work! Thanks for the info!

**Comment by lmccart** [comment]
ah I think we need to update the ref thank you for catching this and sorry for the confusion. copy() has replaced get().
