### ISSUE TITLE
Example not working correctly in textAlign() reference

### ISSUE THREAD

**Issue by nikhilhvr** [processing/p5.js#6056]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [X] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### p5.js version

v1.5.0

### Web browser and version

Microsoft Edge Version 110.0.1587.63 (Official build) (64-bit)

### Operating System

Windows 10

### Steps:
1. Go to this website https://p5js.org/reference/#/p5/textAlign
2. Need to Be Fixed:- The CENTER text not showing up in the center is not visible and the BOTTOM text is at the bottom.The CENTER and BOTTOM text are not visible.

![p5js example](https://user-images.githubusercontent.com/97503662/223188011-ac5d94fb-5ab8-4c1c-b50b-41a43a533227.JPG)
### Snippet:
``` js


textSize(16);
strokeWeight(0.5);

line(0, 12, width, 12);
textAlign(CENTER, TOP);
text('TOP', 0, 12, width);

line(0, 37, width, 37);
textAlign(CENTER);
text('CENTER', 0, 37, width);

line(0, 62, width, 62);
textAlign(CENTER, BASELINE);
text('BASELINE', 0, 62, width);

line(0, 87, width, 87);
textAlign(BOTTOM);
textAlign(CENTER);
text('BOTTOM', 0, 87, width);

describe(`The names of the four vertical alignments (TOP, CENTER, BASELINE,
  and BOTTOM) rendered each showing that alignment's placement relative to a
  horizontal line.`);


```

### Currently
I  am working on this Issue

**Comment by nikhilhvr** [comment]
Can I work on this issue? @davepagurek  @limzykenneth

**Comment by Qianqianye** [comment]
Hi @nikhilhvr, thanks for catching it. Yes, you can work on it. Before you get started, could you share how you are planning to rewrite the example code? Thanks!

**Comment by nikhilhvr** [comment]
> 

Yeah, it is a syntax error that can be fixed.
textAlign(horizAlign, [vertAlign]).
The verAlign should be in square backets textAlign(CENTER, [CENTER]); & textAlign(CENTER, [BOTTOM]);
![image](https://user-images.githubusercontent.com/97503662/223358823-7fe64086-4e05-468d-82aa-d8e2f55ec1ca.png)

**Comment by davepagurek** [comment]
Hey @nikhilhvr, thanks for your interest in this issue! I believe this isn't a syntax issue -- in documentation, putting a parameter in square brackets is normally a way to indicate that it's optional, not that it must be passed in in square brackets. In your screenshot, for example, the `CENTER` text is placed below the line, where in p5 1.4.2, the line goes through the center of the text:
![eg142](https://user-images.githubusercontent.com/5315059/224558608-4af144ec-3b52-4367-a235-e078b80d9d75.png)

It looks like this will be fixed in this open PR https://github.com/processing/p5.js/pull/6060, so I believe we can close this issue once that PR has been merged.

**Comment by davepagurek** [comment]
I'm going to mark this as closed now that https://github.com/processing/p5.js/pull/6060 is in! Feel free to carry on the discussion if there's anything we've missed.
