### ISSUE TITLE
Deleting a 'Done. Downloading your gif!🌸' paragraph after a while

### ISSUE THREAD

**Issue by agrshch** [processing/p5.js#6084]
### Increasing Access

Unsure

### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [X] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### Feature enhancement details

Hi,
this is a really minor improvement. Currently, when a user successfully generated a GIF with saveGif function, p5 shows a message **Done. Downloading your gif!🌸**, which stays on the screen forever. It would be nice to remove it after some amount of time. 

`p.html('Done. Downloading your gif!🌸');`
 `setTimeout(()=> p.remove(),5000);`

Thanks!

**Comment by anpanring** [comment]
Is it okay if I work on this issue?

**Comment by agrshch** [comment]
@anpanring if you don't mind, I would like to do it by myself. This would be my first contribution and this issue seems to be not too critical or too scary to work with.

**Comment by anpanring** [comment]
@agrshch Of course, I understand!

**Comment by Cvr421** [comment]
Can i work on these issue

**Comment by agrshch** [comment]
@Cvr421 I am working

**Comment by ffd8** [comment]
@agrshch thanks for pointing this out and working on it! Just came here to chime in and say 'what an amaaazing feature this `saveGif()` is!.... but that notification never goes away'.

It would also be helpful if there was either a `silent:true` option (so nothing is displayed on demand), and/or the ability to have the current notifications passed via callback with those values – so one could display the updates within a p5 sketch, rather than overlaying html.
