### ISSUE TITLE
Why could not I use arrow functions in the main js?

### ISSUE THREAD

**Issue by carnivion** [processing/p5.js#6103]
### Topic

Please forgive me for being fussy. But I'd really rather use arrow functions like this:
`const setup = () => {}
const draw = () => {}`
I have no idea why this doesn't work. It should be the same as traditional `function` notation.

**Comment by limzykenneth** [comment]
For global mode to work, the `setup()` and `draw()` functions (and other globally defined functions) must be available under the `window` object. Using `const` or `let` to define variables or functions will cause them not to be attached to the `window` object, whereas using `function setup()` or using `var` will attach them to the `window` object.

There is a few option if you really don't want to use `function setup()` (although there is nothing wrong at all with using that in Javascript). You can use `var`:

```js
var setup = () => {
};
```
but I imagine you may not want to do that; another option is to explicitly attach to the `window` object:

```js
window.setup = () => {
};
```

There could be a problem when you are using the arrow notation though since the value of `this` will not be the expected one when using that. But then again, the easiest solution is to just use `function setup()`.

**Comment by SomasekharSunkari** [comment]
Ok
