### ISSUE TITLE
loadModel() function is only loading .obj but not .mtl file

### ISSUE THREAD

**Issue by jagadeeshCoder** [processing/p5.js#6117]
### Increasing Access

loadModel() function is only loading .obj but not .mtl file 

.mtl helps a lot like i have a large model for large model we cannot applu textures correctly in that way .mtl file help ful a lot

### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [X] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### Feature enhancement details

loadModel() function is only loading .obj but not .mtl file 

.mtl helps a lot like i have a large model for large model we cannot applu textures correctly in that way .mtl file help ful a lot

**Comment by davepagurek** [comment]
This one is interesting because we don't currently have a way in p5 of storing both a shape (p5.Geometry) and materials. So maybe we'd need to introduce a new data structure for that? Or have a way to load a material into a function you can call, which internally calls `ambientMaterial()` and `specularMaterial()` with appropriate parameters?

**Comment by jagadeeshCoder** [comment]
i can add texture image directly to model by texture function. but i have peaces of img of textures of model .                                    p5.js has obj parser it has obj file data and in that obj file data we have mtl adress specified with mtllib
