### ISSUE TITLE
WebGL ambientMaterial() defaults to white instead of the fill color

### ISSUE THREAD

**Issue by davepagurek** [processing/p5.js#6125]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [X] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### p5.js version

1.6.0

### Web browser and version

Firefox 108.0

### Operating System

MacOS 12.5.1

### Steps to reproduce this

Here's [an example sketch](https://openprocessing.org/sketch/1815047) that shows how the colors in WebGL mode changed between v1.4.2 and the current version, and how to get back to the same look under the current system: 

<table>
<tr>
<td>

```js
// v1.4.2
fill(this.c)
```

</td>

<td>

```js
// v1.6.0
fill(this.c)
```

</td>

<td>

```js
// v1.6.0
const c = color(this.c)
ambientMaterial(
  red(c),
  green(c),
  blue(c)
)
fill(this.c)
```

</td>
</tr>
<tr>
<td>

<img src="https://user-images.githubusercontent.com/5315059/235451474-5d841881-4eb9-4023-bef8-e68d01b1acc1.png" width=200 />

</td>
<td>

<img src="https://user-images.githubusercontent.com/5315059/235451490-9c63a42b-606d-4d95-a774-a7e1f72e1419.png" width=200 />

</td>
<td>

<img src="https://user-images.githubusercontent.com/5315059/235451505-b47b49bd-dc77-4488-b0d7-6681d28e9177.png" width=200 />

</td>
</tr>
</table>

This happened when we made it possible to separately tweak the ambient material from the specular or fill material of an object. We did this because Processing also allows this, but [Processing also defaults the ambient material to the fill material unless explicitly specified.](https://github.com/processing/processing4/blob/80a5b124f1aa4e08e4d23d1eac97a5b1feb5211a/core/src/processing/core/PShape.java#L892-L894)

To match the default behaviour of 1.4.2 (and also Processing) to not get washed out colours by default, we should also default the ambient material to the fill material unless an ambient material is specified.

**Comment by inaridarkfox4231** [comment]
If the vertex color is used, the color determined by fill is not used, but what should I do in that case?
Also, I don't think it's a very clean process to just specify the same color.

Also, this sketch assumes the use of lights(), but I don't think it's appropriate to disregard that assumption. Is there any problem with the specification of lights()? I don't think it's a simple problem.

Emphasizing that this is not a right or wrong answer, we do this instead of lights().
```js
directionalLight(255,255,255,0,0,-1);
ambientLight(48);
```
![255_48](https://user-images.githubusercontent.com/39549290/235465077-8391e6e0-091b-4027-a5d6-29b6fed33e96.png)

The problem of appearance is really difficult because subjectivity is involved. I think that some coders may not mean it because the appearance is determined arbitrarily just by not executing ambientMaterial().

**Comment by davepagurek** [comment]
> If the vertex color is used, the color determined by fill is not used, but what should I do in that case?

The default would be to use the same material color for everything, so I think in this case the ambient material would be the vertex color. You bring up a good point though about it being hard to tweak the ambient colour for vertex colored materials, although I'll maybe discuss that more in your other issue, as this one is more of a bug fix to get back to Processing's behavior.

> Also, I don't think it's a very clean process to just specify the same color.

Agreed, so fixing this issue would mean that you wouldn't have to, as it would default to the same color.

> Also, this sketch assumes the use of lights(), but I don't think it's appropriate to disregard that assumption. Is there any problem with the specification of lights()? I don't think it's a simple problem.

`lights()` is just a shortcut for some specific directional lights and ambient light values, so this bug fix would work the same for both.

**Comment by inaridarkfox4231** [comment]
I still don't quite understand what [#5774](https://github.com/processing/p5.js/pull/5774)  means, but it seems to boil down to using ambientMaterial instead of fill when using lighting method...

I felt that way because the sample code doesn't use fill.
Also, in the example work, if fill(this.c) was set to ambientMaterial(color(this.c)), the appearance certainly changed.

However, it is natural to use fill() when coloring with a single color, so I feel that there is a misunderstanding and that is causing the problem.

**Comment by davepagurek** [comment]
Just put up a PR making the behaviour match Processing! It should restore the earlier behaviour when just using `fill()` without specifying any other material properties.
