### ISSUE TITLE
.webm videos with alpha channel are rendered with stacked frames

### ISSUE THREAD

**Issue by donaldzhu** [processing/p5.js#6258]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [X] Other (specify if possible) --> Video

### p5.js version

1.6.0

### Web browser and version

Chrome 114.0.5735.198

### Operating System

OS 12.5.1

### Steps:
When placing a `p5.MediaElement` created from a `.webm` video (with alpha channel/transparency) onto the canvas, all previous frames of the video are stacked on to of each other. This behavior is different from of the `<video>` element in the DOM, where each frame is a new frame without the previous frames. 

### Snippet:

```js

let vid;
function preload() {
  vid = createVideo('vid.webm');
}

function setup() {
  createCanvas(1280, 720);
  vid.size(width, height);
  vid.loop();
}

function draw() {
  background(255,0,0);
  image(vid,0,0);
}

function mouseClicked() {
  vid.play();
}

```
Issue replicated in web editor [here](https://editor.p5js.org/donaldzhu/sketches/3TueC_pOz).

**Comment by davepagurek** [comment]
This might be the same bug as https://github.com/processing/p5.js/issues/6071 for h.265 videos. Possibly a chrome bug?

**Comment by limzykenneth** [comment]
I think this is probably simpler. Videos are drawn onto their own canvas every frame when played before that canvas is drawn onto the user's canvas when the video is drawn using the `image()` function. The part where videos are drawn onto their own canvas did not have canvas clearing between each frame being drawn, because that's not necessary with fully opaque videos. In this case with transparent background video, the next frame is simply drawn on top of the existing internal canvas that may already have contents of the previous frame.

We can add canvas clearing by default for videos but it would be nice if we can conditionally do it for just videos that could have transparent background.

**Comment by donaldzhu** [comment]
Based on the comment, adding the following code to the end of every draw loop works:

```js
  if (vid.src.match(/\.webm$/)) {
    const { canvas } = vid
    canvas.getContext('2d').clearRect(0, 0, canvas.width, canvas.height)
  }
```
Not sure if this is the right way of doing it, but had to use HTML's own clearing function since `vid.canvas` isn't a p5 object.

**Comment by limzykenneth** [comment]
For simplicity sake I think just clearing without the conditional checking should be fine. @donaldzhu If you like to submit a PR to fix this I can assign this to you, just let me know.

**Comment by donaldzhu** [comment]
@limzykenneth I submitted a PR. I hope I did it correctly since this is the first time I had worked on someone else's code on Github.
