### ISSUE TITLE
unexpected behaviour of print()/console.log()

### ISSUE THREAD

**Issue by kybr** [processing/p5.js#6264]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [X] Other (specify if possible)

### p5.js version

1.6.0, 1.5.0, 1.4.2, 1.4.1, 1.4.0

### Web browser and version

Firefox, Safari, Chrome

### Operating System

macOS

### Steps to reproduce this

So, 1000 apologies if I am just dumb or didn't read the right part of the manual. After a bit searching, I didn't find anything---Perhaps I am just failing to at search.

p5js is prints unexpectedly (see snippet). It is as if all print/console.log statements are deferred until the end of the scope. Perhaps there is a pre-interpreter pass on the code, changing the order of events? or print/console.log are overridden so they queue statements until the end of the scope? How can one perform basic debugging if a the system does not print the current value of a variable?

This is so weird and so basic that I must understand p5js (and/or javascript), though I have used both quite a lot. Again, forgive me and close this if this is expected behavior or if I am somehow doing something dumb. I am still not an expert in javascript. I will ask in the discord as well.

### Steps:
1. print list
2. change list
3. print list

### Snippet:

```js

let number = [];

function foo() {
  let version = []; // keep track of versions of bar
  
  let bar = [];

  console.log(bar); // bar == [] (should print; doesn't)
  
  version.push(bar); // push current version of bar: []
  
  bar.push(1); // update bar; (should be [1])
  
  version.push(bar); // push current version of bar [1]
  
  console.log(bar); // bar == [1] (print is correct)
  
  console.log(version[0], version[1]); // show versions of bar (
  
  // p5js prints this:
  // (1) [1] // unexpected
  // (1) [1] // correct
  // (1) [1] (1) [1] // unexpected
  // what is the (1)?

  // node prints this:
  // [] // correct
  // [ 1 ] // correct
  // [ 1 ] [ 1 ] // WHY? (should be [] [1]) this must be how js works
}

function setup() {
  foo();
}


```

**Comment by davepagurek** [comment]
Hey! So this is a behaviour of the browser a bit. It comes down to a balance between having console.log() be useful and having it be fast.

So ideally, when you log something, you want to take a snapshot of the object you log in the state that you log it. But also objects can sometimes have a lot of nested properties, and have a lot of data, so copying them could cause slowdowns, and also the act of copying is nontrivial (there's not a good general purpose way to clone an object in JS -- maybe serializing to JSON works for many cases, but you lose information about the class/prototypes that some developers want to see.) So browsers typically compromise and don't always make a copy, or only do a shallow copy, for the sake of speed, and only log nested values when you try to view them. That's how you end up with arrays showing all the items youve pushed into them even at the first log sometimes.

One other thing to note about js: When you do `version.push(bar)`, you are pushing a reference to the object `bar` into `version`, *not a copy of its current state,* so if you modify `bar` afterwards, the version you pushed into the array works too. If you want to get a copy of `bar` (that won't update when `bar` updates), you can use `bar.slice()` (or `[...bar]` in ES6, which is convenient because you can also do `{...someObject}` to shallow-copy an object.) To be clear though, this does a *shallow* copy, so only the first layer of properties are still referencing the same things. IF you have a 2D array, for example, you have to do `bar.map((arr) => arr.slice())`.

**Comment by kybr** [comment]
On Mon, Jul 10, 2023 at 8:16 AM Dave Pagurek ***@***.***>
wrote:

> Hey! So this is a behaviour of the browser a bit. It comes down to a
> balance between having console.log() be useful and having it be fast.
>
Ah. I see the motivation and trade off.


> So ideally, when you log something, you want to take a snapshot of the
> object you log in the state that you log it.
>
Yes. It is absolutely critical to have this functionality somewhere.


> But also objects can sometimes have a lot of nested properties, and have a
> lot of data, so copying them could cause slowdowns, and also the act of
> copying is nontrivial (there's not a good general purpose way to clone an
> object in JS -- maybe serializing to JSON works for many cases, but you
> lose information about the class/prototypes that some developers want to
> see.)
>
That's tough. I want a workaround, so I might write something that
serializes.


> So browsers typically compromise and don't always make a copy, or only do
> a shallow copy, for the sake of speed, and only log nested values when you
> try to view them. That's how you end up with arrays showing all the items
> youve pushed into them even at the first log sometimes.
>
I propose something like `printMode(SNAPSHOT)` that replaces `print()` with
something like this:

```
function print(thing) {
  console.log(JSON.stringify(thing));
  // except using the arguments object or variadics somehow, probably
}
```

But I understand if we don't want to clutter the p5js API with such things.
I will tell my students to use `print(JSON.stringify(thing))` for debugging.

And/or some note in the documentation of `print` that gently explains some
of this.

One other thing to note about js: When you do version.push(bar), you are
> pushing a reference to the object bar into version, *not a copy of its
> current state,* so if you modify bar afterwards, the version you pushed
> into the array works too.
>
:facepalm: of course! Thanks :)


> If you want to get a copy of bar (that won't update when bar updates),
> you can use bar.slice() (or [...bar] in ES6, which is convenient because
> you can also do {...someObject} to shallow-copy an object.) To be clear
> though, this does a *shallow* copy, so only the first layer of properties
> are still referencing the same things. IF you have a 2D array, for example,
> you have to do bar.map((arr) => arr.slice()).
>
Thank you.
