### ISSUE TITLE
document saveTable(), saveJSON(), saveStrings()

### ISSUE THREAD

**Issue by workergnome** [processing/p5.js#639]
Following the conversation in #280, we would like to implement `saveTable()` in p5.

For reference, see [filesaver.js](https://github.com/eligrey/FileSaver.js) and [stack overflow](http://stackoverflow.com/questions/17836273/export-javascript-data-to-csv-file-without-server-interaction).

See [the Processing docs](https://processing.org/reference/saveTable_.html) for syntax and parameters.

**Comment by therewasaguy** [comment]
saveTable is implemented, but not documented - apologies for not mentioning that at #280.

Right now it is called by [the save() method](http://p5js.org/reference/#/p5/save), which is the only documented output method, following this discussion at https://github.com/processing/p5.js/pull/313#issuecomment-52186939

The save() method calls saveCanvas() by default, and otherwise parses the type of thing you want to save, and calls saveJSON, saveTable, saveStrings, or saveSound.

It's worth mentioning that, right now, p5.Image is the only object that has its own save method:

``myImage.save('myImage.png');``

Everything else is saved like this:
save(myArrayOfStrings, 'textFile.txt');

That's based on the discussion at #313, but could totally change.

It sounds like it would be useful to add documentation for all of the other save methods, so that people looking through the reference know that they can output these types of files. My plan is for them to be filed under Output on the documentation page, and to mention the syntax for saving in the p5.Table class.

Anybody wanna tackle this documentation? Or, I can do it!

**Comment by workergnome** [comment]
@therewasaguy Go for it!

**Comment by workergnome** [comment]
Thanks!
