### ISSUE TITLE
Safari IOS

### ISSUE THREAD

**Issue by Loquatious-Celea** [processing/p5.js#6393]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [X] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [X] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### p5.js version

p5.js v1.6.0 February 22, 2023

### Web browser and version

Safari IOS 16.6

### Operating System

Iphone IOS 16.6

### Steps:
1. try to create a canvas where the height is 1617 or greater
2. load on an up to date iphone on safari

### Snippet:

```js

function setup() {
  createCanvas(1155,1963)
}

function draw() {
  background(0);
}

//   the window height seems to fail if I try to do 1617 or larger
//
// function setup () {
//   createCanvas(155,1613.9)
//  }
// function draw () {
//    background (0);
//     }


```

**Comment by Qianqianye** [comment]
Hi @Loquatious-Celea, can you be more specific about how the window height seems to 'fail'? Like it's not displaying the entire height?

**Comment by Loquatious-Celea** [comment]
Sorry for the late reply, when I put in a canvas height above 1700 pixels it only displays a blank white screen, seemingly without any dom elements at all. Hope this helps!

**Comment by Loquatious-Celea** [comment]
it displays on my samsung device and on ipad, but on an iphone with ios16 safari, it only shows a blank white screen

**Comment by limzykenneth** [comment]
@Loquatious-Celea This is actually a rather obscure problem which is that there is a maximum size a canvas can be. It is different for every browser (including desktop and ios Safari) and is usually pretty big for most use cases. For iOS Safari it is as the warning message in the console below

```
[Warning] Canvas area exceeds the maximum limit (width * height > 16777216). (p5.js, line 64660)
```

This works out to be about 4096 * 4096 if you are using a square canvas, which might seem like a lot larger than what you defined, the problem is that on iOS there would also be `pixelDensity` of 3 which will make the final canvas `(1155*3)*(1963*3)` which is about 20 million so larger than the allowable size. One way to solve this is to use `pixelDensity(1)` for a smaller canvas, it won't look as crisp but it may not be very noticable depending on what you do.

**Comment by Loquatious-Celea** [comment]
thank you so much! this @limzykenneth, this bug had been plagueing me for weeks. I was able to add
window.devicePixelRatio = 1;
and it fixed the issue and works flawlessly!
