### ISSUE TITLE
windowWidth and windowHeight not being mapped correctly to counterparts

### ISSUE THREAD

**Issue by Evorage0** [processing/p5.js#6396]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [X] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### p5.js version

1.7.0

### Web browser and version

Microsoft Edge 116.0.1938.69; Chromium version 116.0.5845.141

### Operating System

Windows 11 Version 22H2 (Build 22621.2134)

### Steps:
1. Create a new tab in your browser
2. Enter the url and navigate to a site with a p5js sketch
3. Check the console for the output of the code below

### Snippet:

```js
function setup() {
    console.log(windowWidth, windowHeight);
    console.log(innerWidth, innerHeight);
}
```

This behaviour occurs on MS edge (running chromium). Discord user: davepagurek (138146691151822848) tested this issue in a chrome browser which resulted in the same bug, they also tested this in a firefox browser which **did not** result in this oddity happening which suggests that it is an issue with chromium.

I found that after refreshing the tab, the values are the same so this bug occurs only in new tabs.

https://github.com/processing/p5.js/assets/68397475/5e69273f-b522-43ad-92af-8cec209722eb

### Possible Fix:
Set the values of windowWidth and windowHeight manually before calling the setup() function.

**Comment by DarKDevz** [comment]
This isn't a bug afaik, because if you reload the page it works,
it's just an issue with chrome not setting the height correctly when first opening the window
not an issue with p5.js

**Comment by limzykenneth** [comment]
@Evorage0 This happens because Chromium incorrectly included the bookmarks bar in the height calculation on page load when the user hides the bookmark bar when not on empty page. Firefox does not include the bar at all when it is set to be hidden except for on empty page so it gets consistent value, while Chromium likely calculate it on the fly, making the two values different between line execution (that's my guess at least).

As noted this is not an issue with p5.js and we can't really resolve this on our side since it is a problem with incorrect value provided by Chromium. I'll close this for now and this problem should be reported to Chromium instead. Thanks!

**Comment by davepagurek** [comment]
Just want to point out that we might be able to work around this: in the example code, `innerWidth`/`innerHeight` seems to be correct in `setup`, which implies that it's only incorrect right on page load? So we only set the initial value right before we run preload or setup, we could get correct behaviour without degrading the experience anywhere else. Do you think that'd be worth implementing?

**Comment by bensgilbert** [comment]
I believe this has now been solved by https://github.com/processing/p5.js/pull/7134 which implements the solution dave mentioned above
