### ISSUE TITLE
color spaces are crazy — implementing hsba & hsla

### ISSUE THREAD

**Issue by sarahgp** [processing/p5.js#649]
Colors in the HSB(a) space are not currently being interpreted correctly.

For instance, two circles that should be the same color ([you can check the conversion here](http://www.rapidtables.com/convert/color/rgb-to-hsv.htm)):

```js
  colorMode(RGB);
  fill(255, 204, 0);
  noStroke();
  ellipse(25, 25, 80, 80);

  colorMode(HSB);
  fill(48, 100, 100);
  ellipse(75, 75, 80, 80);
```

instead appear like so:

![screen shot 2015-05-27 at 6 43 40 pm](https://cloud.githubusercontent.com/assets/1477362/7850358/45570dac-04af-11e5-8c84-a9e974b0b114.png)

This is because the default `maxHSB` array is `[255, 255, 255, 255]` whereas HSBa is specified on the web with the max values `[360, 100%, 100%, 1]`, as is HSLa. From a web approach, the alpha channel in RGBa would be expressed as a float between 0 and 1 as well.

Of course, in other graphics contexts `[255, 255, 255, 255]` makes sense, but I would argue that for the web, we should be designing with the web user in mind. 

Thoughts? Things I've missed?

Pinging @kadamwhite @cambridgemike & @lmccart, in particular.

**Comment by sarahgp** [comment]
Related to #591

**Comment by kadamwhite** [comment]
I can definitely see your argument for making HSB default to the 360/100/100 mode to match the web's color space -- it looks like that's our default because Processing itself defaults to the 0-255 range, but [`colorMode()`](https://processing.org/reference/colorMode_.html) permits adjusting those ranges to 360/100/100. It's definitely unintuitive for the web that 360/100/100 isn't the default, but it does have a precedent -- @lmccart, thoughts? HSB itself isn't "web native" either, since CSS colors only support HSL, and as long as `hsl()` strings gets correctly mapped to RGB I think #591 will be satisfied.

Long-term though would it make sense for p5.Color to support accessing colors in the HSLA color space too, as we do with HSBA and RGBA? I suspect there's Processing precedent here I don't know of.

(and I'm pinging @mrspeaker because I know he has feelings about HSL, and may have a different or more comprehensive opinion)

**Comment by sarahgp** [comment]
Supporting HSLa is what I started working on today, which prompted this
thread, so it's definitely more soon future than murky future. I too have
lots of HSLa feels so am very motivated.

**Comment by sarahgp** [comment]
Another note about the way the code currently works. Even when users explicitly set the maxValues array via `colorMode()` to the standard 360/100/100, we are instantly re-setting it to 255/255/255 — even before we set `this.hsba`. 

That means, among other things, that `hue()` returns a 255-converted value regardless of the user input.

That is, this: 

```js
colorMode(RGB);
var c = color(255, 204, 0);
fill(c);
noStroke();
ellipse(25, 25, 80, 80);
print(hue(c));

colorMode(HSB, 360, 100, 100);
c = color(48, 100, 100);
fill(c);
ellipse(75, 75, 80, 80);
print(hue(c));
```

prints 
```js
34
34
```

wheras expected behavior, if you specified your hue under 360 would be to return the hue you specified:`48`.

Regardless of the default behavior we settle on, this should be fixed, so I am going to move ahead on that.

**Comment by kadamwhite** [comment]
Ooh, nice catch, @sarahgp! That definitely needs to be fixed.

**Comment by cambridgemike** [comment]
I think I wrote/refactored some of the code you're talking about, so I'm happy to help fix things if needed. Unfortunately I'm away from a computer for a few days though. 






On Thu, May 28, 2015 at 11:58 AM -0700, "K.Adam White" <notifications@github.com> wrote:












Ooh, nice catch, @sarahgp! That definitely needs to be fixed.

**Comment by sarahgp** [comment]
Thanks @cambridgemike, I think I've got a handle on the code — mostly I was asking for feedback on the idea that we shouldn't be defaulting to 255 values for spaces where that's not the actual description of the space: namely HSBa & HSLa.

**Comment by cambridgemike** [comment]
Sounds good. I think someone else mentioned but the reason for the defaults were because that's what Processing uses. I agree it's confusing though. It should probably be true to Processing but well documented. 





On Fri, May 29, 2015 at 6:32 AM -0700, "Sarah Groff-Palermo" <notifications@github.com> wrote:












Thanks @cambridgemike, I think I've got a handle on the code — mostly I was asking for feedback on the idea that we shouldn't be defaulting to 255 values for spaces where that's not the actual description of the space: namely HSBa & HSLa.

**Comment by sarahgp** [comment]
Well so I guess my question is — why be true to Processing in this case? Assuming that most p5.js users are web users rather than Processing converts (and that number will grow as schools move to p5.js entirely), insisting users pass another set of parameters to get the default behavior* of the color space seems backwards and artificially constricts the hue-definition space. 

And sure, documentation can be, and is being, updated but the current setup requiring people read closely to get intuitive behavior strikes me as a very porous and bug-prone setup. Since we aren't removing the ability to set the 255 space, just swapping the defaults, I would argue we would be putting the burden of deeper understanding on those better to handle it.

*see color space definitions [like this](http://colorizer.org/) or [this](http://en.wikipedia.org/wiki/HSL_and_HSV)

**Comment by sarahgp** [comment]
I'm closing this because the conversation is happening in #696.
