### ISSUE TITLE
FrameBuffer support on Firefox — illegal feedback

### ISSUE THREAD

**Issue by agrshch** [processing/p5.js#6563]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [X] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### p5.js version

1.8

### Web browser and version

Firefox

### Operating System

MacOS

### Steps to reproduce this

It looks like Firefox does not allow use FrameBuffer objects for feedback loops, it throws an error "WebGL warning: drawElementsInstanced: Texture level 0 would be read by TEXTURE_2D unit 0, but written by framebuffer attachment COLOR_ATTACHMENT0, which would be illegal feedback." 

simple example code https://editor.p5js.org/agrshch/sketches/RPyv0IdxE
It works perfectly everywhere excepting firefox

same example with p5.Graphics instead of FBO works in Firefox well https://editor.p5js.org/agrshch/sketches/v9bjtfQgR

**Comment by davepagurek** [comment]
The general strategy to avoid this is to use "ping ponging", where you use two framebuffers representing the previous and next state, and flip back and forth between them, like in the first example here: https://p5js.org/reference/#/p5/createFramebuffer

While some browsers may allow it, it's not something p5 has control over, so it's best avoided via ping ponging. The browser differences may also have to do with whether they antialias by default, since our antualiasing setup may also work around feedback loops by internally using separate read and write textures.

**Comment by agrshch** [comment]
Thanks! I just thought, that it was working with p5.graphics so it should work with framebuffers too. But now I know!

**Comment by davepagurek** [comment]
No problem! I'm going to close this for organizational purposes but let me know if there's anything else we've missed!
