### ISSUE TITLE
Multiple reference to non-existant constant `POLYGON` in Renderer2D

### ISSUE THREAD

**Issue by limzykenneth** [processing/p5.js#6565]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [X] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### p5.js version

1.8.0

### Web browser and version

*

### Operating System

*

### Steps to reproduce this

There are multiple [references](https://github.com/processing/p5.js/blob/v1.8.0/src/core/p5.Renderer2D.js#L857) to `constants.POLYGON` in `src/core/p5.Renderer2D.js` but in `src/core/constants.js` where all constants came from, there is no `POLYGON` defined.

I don't know if it has affected anything (haven't looked into it) but if so it probably is very subtle as this has been around for a very very long time without notice. I would suggest anyone wanting to address this look into whether this problem has an effect or not first.

**Comment by limzykenneth** [comment]
Another slightly related one is in `src/events/acceleration.js` there is a [reference](https://github.com/processing/p5.js/blob/v1.8.0/src/events/acceleration.js#L622) to `constants.radians` where it probably should be `constants.RADIANS`. Again, do check what effect this have first before attempting to address this.

**Comment by SlightlyEpic** [comment]
Hello, I looked into this and it seems that it has no effect on anything, as that symbol is only ever evaluted in three places like so inside an if condition `(shapeKind === constants.POLYGON || shapeKind === null)`. All the three spots lie inside the `endShape` method in core/p5.Renderer2D.js and `shapeKind` is a parameter of that method.
I scanned through the code and found that this method is only ever called by (the user facing) `endShape` inside core/shapes/vertex.js.
https://github.com/processing/p5.js/blob/fe9444879a817bb3d165da327cd8b04a78c6bfaf/src/core/shape/vertex.js#L745-L753

And `beginShape` is the only function that sets `shapeKind` here (which is local to the file), and it never sets it to undefined. `shapeKind` is either always a valid constant from the constants file or null.
https://github.com/processing/p5.js/blob/fe9444879a817bb3d165da327cd8b04a78c6bfaf/src/core/shape/vertex.js#L272-L295

Due to that restriction on `shapeKind`, our original if condition effectively turns into just `(shapeKind === null)` because `shapeKind === constants.POLYGON` will always be false since the latter is undefined. Which means there is no role of `constants.POLYGON` in anything.

I can do the cleanup and open a PR if this makes sense and i have not completely missed out on something.

**Comment by limzykenneth** [comment]
Thanks @SlightlyEpic for looking into this, it is very insightful. I think I understand the reasoning behind why POLYGON is there as the default mode for begin and end shape is essentially POLYGON, having it be undefined have the same effect as having it as the default. In this case let's just remove the reference to the POLYGON constant entirely since the statement will never evaluate to true anyway. You can go ahead with a PR. Thanks!

**Comment by limzykenneth** [comment]
Still need to fix reference to `radians`

**Comment by SlightlyEpic** [comment]
Changing that turned out to be a rabbithole because it seems that because of the improper casing, the rotation properties were always in degrees irrespective of the angle mode.
This uncovered the deeper problem that stuff in the library is written to only work with rotation values in degrees. Till now i've spotted the rotation tests expecting values in degrees even though the default angleMode is radian, and the `deviceTurned` event not firing in radian mode because the mistakenly assumes radian values to be degrees.

I'm currently adapting the code to respect the current angleMode, and ive modified the tests so that they expect values in radians as that is the default mode.
