### ISSUE TITLE
Low opacity color added repeatedly never reaches the full value.

### ISSUE THREAD

**Issue by mescalina** [processing/p5.js#6568]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [X] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### p5.js version

1.8.0

### Web browser and version

chrome 119.0.6045.160

### Operating System

Windows

### Steps to reproduce this

// IN THE FOLLOWING EXAMPLE THE CIRCLE NEVER COMPLETELY DISAPPEARS INTO BLACK.

function setup() {
  createCanvas(800, 800);
  background(0)
  fill('#FF0000')
  circle(400,400,400)
}

function draw() {
  background('#00000011')
}

**Comment by davepagurek** [comment]
Example code aside, this happens because 2D canvases use integer-precision colors. This is not a p5 limitation, but a 2D Javascript Canvas limitation. If you're able to switch to WebGL mode, you can use floating point colors at a higher precision, which gets rid of the issue: https://p5js.org/reference/#/p5/createFramebuffer

I'm going to close this issue since it isn't something p5 is able to solve and we have a WebGL workaround, but let me know if I've misinterpreted your problem!

**Comment by mescalina** [comment]
Hi Dave, thanks a lot. Yes, I guess what you pointed me to is the real issue. 
In the example the code was supposed to be #00000011, no idea why the 0es are gone, anyway makes no difference.
Thanks and I'll consider the webgl trick.
Bless!

**Comment by davepagurek** [comment]
Oh it looks like Github is treating the hex code as a reference to a Github issue 😅 Maybe if you write your code in backticks it will avoid that:
```js
Like this: `#000011`

Or this:
    ```js
    #000011
    ```
```
