### ISSUE TITLE
textAlign(CENTER, CENTER) does not vertically center user-loaded fonts

### ISSUE THREAD

**Issue by micuat** [processing/p5.js#6593]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [X] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### p5.js version

1.8.0

### Web browser and version

any

### Operating System

any

### Steps to reproduce this

*below is copied from a topic on discourse by @quinton-ashley : https://discourse.processing.org/t/why-is-text-not-centered-properly-with-textalign-center-center/*

---

textAlign(CENTER, CENTER) does not seem to work when used with user loaded fonts.

Here is a demonstration I made in p5.js:
[editor.p5js.org](https://editor.p5js.org/quinton-ashley/sketches/eRxv-ODDX)

Here’s the same code run with q5.js showing how the text is supposed to be displayed in the center of the canvas.
[editor.p5js.org](https://editor.p5js.org/quinton-ashley/sketches/9g4rSXQGm)

I think the problem is caused by the use of OpenType instead of the native canvas text drawing. Text quality is also noticeably worse than native canvas rendering at lower resolutions as shown in the demonstrations.

**Comment by micuat** [comment]
After his initial post, I (Naoto) noticed that q5.js simply uses `textBaseline` under the hood. I don't exactly know what p5.js is doing, but skimming other issues, I'm guessing it calculates the vertical position on its own to support multiline.

Also, I found that by using textBounds, same alignment as `ctx.textBaseline = "middle"` can be achieved:
https://editor.p5js.org/micuat/sketches/jWiM9dMcu

**Comment by diyaayay** [comment]
Hey, 
I would like to work on this issue. 
Thanks.

**Comment by micuat** [comment]
@diyaayay feel free to, but can you suggest what steps have to be taken?

**Comment by davepagurek** [comment]
@micuat I noticed on the Discourse thread you mentioned:
> (while researching, I noticed that q5.js (thus textBaseline) won’t center multiline properly, and this is why p5.js is doing some additional calculation)

Do you think we need to adjust this to treat single lines differently? https://github.com/processing/p5.js/blob/7587e0acfa5b3a73826135041fe9c7cfd4816f04/src/core/p5.Renderer.js#L305-L306

**Comment by diyaayay** [comment]
Thanks to @perminder-17 for helping me with this issue. This is what we came up with, which solves the issue. There may be better ways to achieve this still. Let me know if there are any changes that could be a better approach, Thanks.
`let offset = 0;`
`if (this._textBaseline === constants.CENTER) {`
` if (lines.length === 1) {`
`offset = 6 *(p.textAscent() - 90);`
`}`
`else {`
` offset = (lines.length - 1) * p.textLeading() / 2;`
`}}`

**Comment by dhowe** [comment]
Can you clarify what those hard-coded numbers (6 and 90) represent ?

**Comment by diyaayay** [comment]
@dhowe 
0.9084: This is because the p.textAscent() is 0.9084 times textsize when we don't use textFont. When we use textfont we adjust the offset and when we don't get the offset with value 0.
This value is used to calculate the offset for vertically centering single lines of text when a text font is not used. It represents the ratio of the text ascent to the text size when the default font is used. This value is hardcoded because it is an empirical observation based on the default font metrics in various browsers. It might not be accurate for all fonts, but it provides a reasonable approximation for cases.

6:  It is used to compensate for the difference between the actual text ascent and the value obtained using the 0.9084 ratio. This difference arises due to the variations in font metrics across different browsers and systems. Like we are adjusting the offset. Let's say, we are drawing textFont with an offset of 12 pixels below the original. And the value which we were getting with (p.textAscent() -0. 9084(textSize) =-2) then we multiplied with 6 to get the original value and drew it to the center by aligning vertically.

There is another approach that I came across which does not involve hardcoded values. 
`let offset = 0;`
      `if (this._textBaseline === constants.CENTER) {`
        `if (lines.length === 1) {`
          `const textWidth = this.textWidth(lines[0]);`
          `const canvasWidth = this.canvas.width;`
         ` offset = (canvasWidth - textWidth) / 2;`
        `} else {`
       `   offset = (lines.length - 1) * p.textLeading() / 2;`
        `}`
      `}`
      
The screenshots below are the outputs and accuracy achieved from the hardcoded values approach:
      
![1a](https://github.com/processing/p5.js/assets/110971977/dc5fdd5b-6101-435e-baa0-2c561a7bb0bd)

      
![1b](https://github.com/processing/p5.js/assets/110971977/087cb921-58e6-438f-be67-6096627d462f)

The screenshots below are the outputs of the second approach that I mentioned above:

![1](https://github.com/processing/p5.js/assets/110971977/3883cdb2-d8b4-410b-b850-57ed8880c24d)
![2](https://github.com/processing/p5.js/assets/110971977/b65d4e00-fa32-4468-afc0-e5801b66d691)
![3](https://github.com/processing/p5.js/assets/110971977/f9aa47b3-7d44-4971-bf88-829e4d698b17)

**Comment by dhowe** [comment]
The outputs look correct for the 2nd method, but I'm not sure I understand the code: we are talking about vertically centering a single line of text, but the calculation uses `textWidth` and `canvasWidth` only ?

**Comment by diyaayay** [comment]
I tested the code for various font styles and sizes, but the accuracy still does not match what is needed. Can somebody help a little and direct me as to what I should be looking more into? @davepagurek @dhowe @micuat

**Comment by diyaayay** [comment]
@dhowe Sorry for replying so late, I was busy with university exams.
After going through the calculations a little bit, I am a little confused. textLeading is defined as spacing between lines of text in units of pixels. It should exist between multiple lines of text, that's what I can see on the reference page.
So for a single line of text, I'm assuming there should not be a value I mean zero or not defined.
I console logged the textLeading value for single lines that we're dealing with here, for a textSize of 100, it is 125, for textSize 200, it is 250, and for 20 it is 25, respectively. the offset calculation here in the code is shown below:
```
// Offset to account for vertically centering multiple lines of text - no
 // need to adjust anything for vertical align top or baseline
      let offset = 0;
      if (this._textBaseline === constants.CENTER) {
        offset = (lines.length - 1) * p.textLeading() / 2;
      } else if (this._textBaseline === constants.BOTTOM) {
        offset = (lines.length - 1) * p.textLeading();
      }
```
this is what p5.js is currently using for vertically centering multiple lines of text.

Should we be handling textLeading for single lines or calculating offset with including textLeading for single lines? 

Or am I in the wrong direction?

**Comment by dhowe** [comment]
It seems the issue is with the value of the y-adjustment in [this line](https://github.com/processing/p5.js/blob/main/src/typography/p5.Font.js#L565)

**Comment by diyaayay** [comment]
@dhowe

This is the Bottom alignment:
![image](https://github.com/processing/p5.js/assets/110971977/19313bfc-8faa-4947-a71c-2f32c9b26dcf)
This is the Top alignment:
![image](https://github.com/processing/p5.js/assets/110971977/e1595c2e-7c92-4c1d-bf93-ced40646ae60)
This is Center Alignment:
![image](https://github.com/processing/p5.js/assets/110971977/9667b74a-000f-4e9a-bef6-f2c030b4d851)

So I thought I need to incorporate the full height and tried using these calculations:
```
switch (renderer._textBaseline) {
      case constants.TOP:
        y += this._textAscent(fontSize)-this._textDescent(fontSize);
        break;
      case constants.CENTER:
        y += (this._textAscent(fontSize) - this._textDescent(fontSize)) / 2;
        break;
      case constants.BOTTOM:
        y -= this._textDescent(fontSize);
        break;
    }

```

I feel this also isn't the most correct approach because for top , the earlier approach of the code should have worked. However ,these were the results.

Top:
![image](https://github.com/processing/p5.js/assets/110971977/bcfe0ef3-afce-4524-8b0a-e0fa00f97a51)


Center:

![image](https://github.com/processing/p5.js/assets/110971977/dbeac21c-92fc-47ac-b63b-e04ab816a6be)

**Comment by diyaayay** [comment]
Idk what is wrong with the calculation of the ascent because the top alignment should have worked right? or is there an extra offset at the ascent because of the nature of user-loaded fonts.

**Comment by VikasRajput-18** [comment]
.names span.first {
    display: flex;
    align-items: baseline;
    font-weight: bold;
    margin-top: 16px;
}

this is modified class to center "**qashto**" text

**Comment by limzykenneth** [comment]
@diyaayay Looking at your screenshots, could it be that the top and center align text is using the font's bounding box top instead of ascent to calculate its position, accounting for the extra space at the top?

**Comment by diyaayay** [comment]
@limzykenneth Oh! maybe. I will look into this again. I still have the branch where I was working on this issue. Thanks for mentioning another potential cause of why this might be happening.

**Comment by dhowe** [comment]
closing pending further information

**Comment by quinton-ashley** [comment]
@dhowe This issue shouldn't have been closed, since it's still unresolved right?

**Comment by davepagurek** [comment]
I believe this was closed because the original issue was a discrepancy between native canvas text rendering and custom font rendering, and in 2.0 the rendering of custom fonts also uses native canvas rendering now.

**Comment by quinton-ashley** [comment]
ah good!
