### ISSUE TITLE
textFont() not correctly using fonts with multi-word names

### ISSUE THREAD

**Issue by dipamsen** [processing/p5.js#6652]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [X] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### p5.js version

1.9.0

### Web browser and version

Google Chrome 120.0.6099.111 (Official Build) (64-bit)

### Operating System

Windows 11

### Steps:
While loading Google Fonts from their cdn, the font should be available to use through `textFont()`, but fonts having multi-word names are only usable if additional quotes are added to the font name.

### Example:

[p5.js web editor example](https://editor.p5js.org/funplanet/sketches/V2BEPfP9s)

(the font may not load the first time, run the sketch again to load the font properly)

**Comment by dhowe** [comment]
I've verified this issue, though the problem doesn't have to do with spaces, rather the parsing of the font string by the browser, which doesn't like the leading `2` in the 3rd word of the font name (I'm guessing that it is trying to parse this as a font size and failing, which results in no change to the `drawingContext.font` property.

You can see the issue below:

```js
function setup() {
  createCanvas(400, 400);
  
  textFont("Press Start 2P");         
  console.log(drawingContext.font);   // -> 12px sans-serif       FAIL
  
  textFont("Press Start P");
  console.log(drawingContext.font);   // -> 12px "Press Start P"  OK

  textFont("\"Press Start 2P\"");
  console.log(drawingContext.font);   // -> 12px "Press Start 2P" OK
}
```

The solution, as @dipamsen discovered, is to wrap the font name in double-quotes, which appears to work in _all_ cases, though I have not tested this. I've provisionally made the change in [this PR]().

There is another interesting issue that arises in this example, due to the fact the font-loading via css is not synchronous, which means that setting the font does not mean that the font will be immediately available, which can be confusing:
