### ISSUE TITLE
Default values of arguments

### ISSUE THREAD

**Issue by mohitbalwani** [processing/p5.js#6721]
### Topic

I noticed that the default values for arguments are being set using if ladders. I think we can pass the defaults in the function's parameters itself to save lots of lines of code. But before jumping into making those changes I wanted to know the reason behind setting them like that. What do you think about changing the way of setting the default values?

```js
p5.prototype.cone = function(radius, height, detailX, detailY, cap) {
  this._assert3d('cone');
  p5._validateParameters('cone', arguments);
  if (typeof radius === 'undefined') {
    radius = 50;
  }
  if (typeof height === 'undefined') {
    height = radius;
  }
  if (typeof detailX === 'undefined') {
    detailX = 24;
  }
  if (typeof detailY === 'undefined') {
    detailY = 1;
  }
  if (typeof cap === 'undefined') {
    cap = true;
  }
```

**Comment by GregStanton** [comment]
Great find @mohitbalwani!

This code was introduced in commit https://github.com/processing/p5.js/commit/41025510d7ddeec704613696eaa283291a69e5da, which dates to 2017. Setting default values in this way [was common until ECMASCRIPT 2015 (aka ES6)](http://es6-features.org/#DefaultParameterValues), which was the specification that introduced many of the features we now refer to as "modern JavaScript," including [default parameters](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Default_parameters). It took developers some time to adopt the new features. For example, here's [an article from 2018](https://www.freecodecamp.org/news/a-general-review-of-ecmascript-2015-es6-f524d5f8c095/) that still refers to these features as "new." So, I suspect this usage is a result of developers not being familiar with the new syntax, or wanting to maintain consistency with the old approach.

[We're just starting work toward p5.js 2.0](https://github.com/processing/p5.js/blob/dev-2.0/rfc_p5js_2.md), and one of the goals is to thoroughly modernize the p5.js codebase. The issue you found would likely be a part of that effort. I'll go ahead and link to your issue from the main discussion about p5.js 2.0, which is happening in #6678, so that we can figure out the best way to proceed.

**Comment by mohitbalwani** [comment]
Thanks for the detailed explanation @GregStanton! I'm excited about the ongoing work on p5.js 2.0 and would love to contribute to the modernization effort. If there's any specific guidance or tasks related to this issue that I can help with, please let me know. Looking forward to being a part of the progress!

**Comment by GregStanton** [comment]
I'm glad to help @mohitbalwani! 

To get started, you could read [my informal modernization proposal](https://github.com/processing/p5.js/issues/6678#issuecomment-1884173961) and then indicate whether you're interested in leading that effort or whether you'd like to work on specific tasks like the one you identified.

If you want to lead the effort and help volunteers to contribute, I suggest that you write up a detailed proposal indicating the types of modernizations you propose and how you would break up the work into manageable tasks. However, do note that we're currently figuring out a new issue template for the p5.js 2.0 proposals, and it will be easier to make the proposal once that template is available. If you prefer to start immediately, you're still welcome to submit a proposal now; in that case, I would use the Existing Feature Enhancement issue template.

**Comment by GregStanton** [comment]
That's fantastic @mohitbalwani! I'm looking forward to seeing what you put together!

**Comment by GregStanton** [comment]
Hi @mohitbalwani! The new issue form for p5.js 2.0 proposals is live!

**Comment by vaishnavi192** [comment]
Hery @GregStanton I wanted to know what skills should I have in order to contribute in something as big as changing from p5.js to p5.js 2.0 ?

**Comment by GregStanton** [comment]
Hi @vaishnavi192! Thanks for your question! 

The same skills that are usually helpful will also be helpful for p5.js 2.0. No special expertise is required. Here are some skills that are generally helpful:

1. For code contributions, a working knowledge of JavaScript, as well as Git and GitHub, is helpful. Here's a nice [tutorial series on Git and GitHub](https://www.youtube.com/playlist?list=PLRqwX-V7Uu6ZF9C0YMKuns9sLDzK6zoiV) for anyone who is new to those things. For details about contributing to p5.js specifically, you can check out the [p5.js contributor docs](https://p5js.org/contributor-docs/#/).
2. For other kinds of contributions, like outreach, the main thing that's needed is a desire to help! 

Here a couple of specific ways to help:

1. Inform others that proposals are being accepted for p5.js 2.0. Priority will be given to proposals that would change existing features in a way that's difficult to do under normal circumstances (breaking changes, systemic changes, or overdue changes). For example, a breaking change to p5.js will make people's sketches work differently even if their own code stays the same; here's an example of [a proposal that involves breaking changes](https://github.com/processing/p5.js/issues/6766). We need to give people a lot of advance notice before making these kinds of changes, so we can only make them as part of a major release like 2.0. However, that doesn't mean that making these changes requires any special skills.
2. Provide feedback on existing proposals. For example, if you're not a total expert in JavaScript, that can actually be helpful, since proposals like [#6767](https://github.com/processing/p5.js/issues/6767) depend on whether the changes will be understandable to beginners.

Note that the list of current proposals is maintained at the top of issue #6678. I expect this is not the final list, as we'll probbaly continue to see new proposals submitted through the [p5.js 2.0 proposal form](https://github.com/processing/p5.js/issues/new?assignees=&labels=p5.js+2.0&projects=&template=1-p5.js-2.0-RFC-proposal.yml&title=%5Bp5.js+2.0+RFC+Proposal%5D%3A+).

I hope that helps!

**Comment by GregStanton** [comment]
Hi @mohitbalwani! Are you still planning to submit a proposal to modernize syntax in the p5.js codebase? As a reminder, the informal idea is outlined in [this comment](https://github.com/processing/p5.js/issues/6678#issuecomment-1884173961). It's totally fine if you're too busy or if you need some more time. I just thought I'd check in, since if you won't be able to work on this, I can submit the proposal or else find another contributor who'd like to do it.

**Comment by vaishnavi192** [comment]
@GregStanton Thanks for the great explanation! Rn I have medium level proficiency in js. Currently gaining more understanding about p5.js and js. So, like as you mentioned in #6767 issue above in comments, how can I help them as a beginner, I have to tell them my reviews as a beginner?

**Comment by mohitbalwani** [comment]
@GregStanton I will submit proposal very soon. I apologize for the delay in my response, I was traveling/vacationing and just returned back.

**Comment by GregStanton** [comment]
Hi @mohitbalwani! No worries! Take your time. I just wanted to ask in case you had moved on to something else.

**Comment by vaishnavi192** [comment]
@GregStanton Yes I got it coz of your detailed explanation. Thanks, will try to help for sure!
