### ISSUE TITLE
Support a functional fashion of programming with `setup` and `draw`

### ISSUE THREAD

**Issue by lpil** [processing/p5.js#673]
[quil](https://github.com/quil/quil/), the Clojure flavour processing library, supports a functional style of programming where the state of the sketch can be returned from `setup` and passed as an argument to `draw` on each frame. This allows us to manage state without using side effects, I would love to be able to use this style of programming in p5.js.

Before being passed to `draw` each frame, it is passed to an `update` function, which returns the new value for the state. The return value of `draw` is discarded. 

https://github.com/quil/quil/wiki/Functional-mode-(fun-mode)

Currently I'm using a singular global variable to hold my state, and my `draw` function looks something like this:

```javascript
function draw() {
  state = update(state);
  render(state);
}
```

Which isn't quite as nice!

**Comment by workergnome** [comment]
@lpil — That's a interesting idea—I hadn't been aware of quill before. 

My feeling, though, is that p5.js currently relies very heavily on global states and side effects.  Converting it to a functional style would require a pretty substantial refactor, particularly since we would have to *also* continue to support the current style.

If you're interested in taking a stab at this yourself, it might be worthwhile to write up a proposal that discusses what this would take, and how the architecture would need to change to support something like that.

Thanks!
