### ISSUE TITLE
Edges offseted in webgl ortho

### ISSUE THREAD

**Issue by vicdoval** [processing/p5.js#6956]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [X] WebGL
- [ ] Build process
- [ ] Unit testing
- [ ] Internationalization
- [ ] Friendly errors
- [ ] Other (specify if possible)

### p5.js version

1.91

### Web browser and version

123.0.6312.106

### Operating system

Windows

### Steps to reproduce this

When creating geometry in  webgl canvas in ortho() edges get offseted from the fill geometry
![download (26)](https://github.com/processing/p5.js/assets/10011941/450ac3ce-5702-4b70-b9a0-9b0e32decdd8)
![image](https://github.com/processing/p5.js/assets/10011941/77cb0bb9-4eb8-4c0b-b1a7-a0ffbe3e9b8c)
![image](https://github.com/processing/p5.js/assets/10011941/bc3e8634-6664-4664-ab83-20742e084f65)

[link to p5 editor sketch](https://editor.p5js.org/vicdoval/sketches/VsL1ILZ-_)
simpified code:
```
function setup() {
  createCanvas(800, 1200, WEBGL);
}

function draw() {
  background(220);
  stroke(2);

  propFactor = 0.75;
  ortho(-500 * propFactor, 500 * propFactor, -500, 500, 1, 10000);
  camera(1000, 1000, -1000, 0, 0, 0, 0, 0, 1);
  box(200, 200, 800);
}
```

**Comment by davepagurek** [comment]
The way we make lines go on top of fills on angled surfaces is by scaling down their coordinates based on their angle here:

https://github.com/processing/p5.js/blob/bcf9134547389fd26cdb251d3055206866dc3498/src/webgl/shaders/line.vert#L82-L89

https://github.com/processing/p5.js/blob/bcf9134547389fd26cdb251d3055206866dc3498/src/webgl/shaders/line.vert#L91-L94

The idea (described more in https://github.com/processing/p5.js/issues/2938#issuecomment-1404391366) is that when it's perpendicular to the camera, we don't need to move it forward at all, but we want to move it forward a little bit if it's on an angle that points it into the camera a bit.

I think the thing that has changed from before is that the camera is now 800 away from the subject by default, where previously things were closer. So scaling coordinates by 0.995 has a bigger impact than before.

So, if anyone wants to tackle this, some things to try:
- Can we use a scaling factor closer to 1? maybe 0.9975?
- Instead of shrinking the coordinates by a scaling factor (from 0.995 to 1), we subtract something from the z value to move it forward a constant amount?

**Comment by JordanSucher** [comment]
Changing the scaling factor to 0.9985 seems to eliminate this problem, without causing any issues on the more complicated graphic from #2938 

![image](https://github.com/processing/p5.js/assets/9809109/d478d1b2-3a60-4ad2-a685-e97981d1790b)

https://github.com/processing/p5.js/assets/9809109/9b086cfe-6282-4070-8cdd-f6d489a4b96e

Subtracting a constant of 1.0 from the z value also seems to work:

https://github.com/processing/p5.js/assets/9809109/94cb3a5d-9ec0-4774-9832-5677d88b5633

**Comment by davepagurek** [comment]
Awesome, thanks for experimenting with this! Maybe we should be going with the constant offset then. Maybe the last test we should run is just drawing some rectangles on top of each other at the same depth (basically a 2d sketch but in WebGL) to make sure the latest drawn rectangle goes on top without earlier strokes poking through. If that still works, feel free to open a PR with this!

**Comment by JordanSucher** [comment]
Good call - I tested 2 squares and found that the biggest offset I could offset before the stroke clipped through was ~0.00045, which isn't enough to fix the stroke jumping issue with more complex objects like the sphere above - though it does fix the edge clipping with the 3d cubes.

Perhaps there's something we could do to more explicitly handle rendering 2d shapes when using webGL? Like setting a z-offset to shift shapes that should be on top forward a bit, to create a little more room for the stroke z-offset?

**Comment by davepagurek** [comment]
> Perhaps there's something we could do to more explicitly handle rendering 2d shapes when using webGL? Like setting a z-offset to shift shapes that should be on top forward a bit, to create a little more room for the stroke z-offset?

This is a tough one because you could change the camera angle and see through the gap between them.

When you were doing the offset, was that still using a `mix(a, b, facingCamera)` to use an offset of 0 when `facingCamera == 0`? if not, that could be something to try -- `facingCamera` is something kinda like a 2d-ish detector, since 2d lines will have `facingCamera == 0`.

**Comment by JordanSucher** [comment]
Using  float zOffset = mix(-0.00045, -1., facingCamera) solves the square overlaps but reintroduces some of the jumping effects in 3d. I think it's a good compromise.

Maybe in the future we could conditionally apply the stroke z-offset only to 3d objects

**Comment by davepagurek** [comment]
that sounds good for now, thanks for your help!

**Comment by JordanSucher** [comment]
jumping with current code:

![complex shape w current scale modifier](https://github.com/processing/p5.js/assets/9809109/f2ee3f36-0cf8-462b-9606-100d907beb71)

jumping with mix z-offset

![complex shape w const offset](https://github.com/processing/p5.js/assets/9809109/34a4bc2b-4579-48b2-b15b-200a494b6630)

**Comment by davepagurek** [comment]
Closed by https://github.com/processing/p5.js/pull/7064
