### ISSUE TITLE
Automate the release process

### ISSUE THREAD

**Issue by workergnome** [processing/p5.js#707]
As part of p5jscon, we removed all the grunt tasks that have to do with releases, mostly because they weren't being used.  At some point, we should automate how we do releases, and document the parts that can't be automated.

This will require talking with @lmccart to figure out how, exactly, releases are _actually_ done.

**Comment by dhowe** [comment]
Any further thought on this (appears the latest release on GH is over 3 weeks old)? I remember a discussion about doing nightlies...

**Comment by workergnome** [comment]
I don't think anyone is currently working on this.  Unfortunately, I think that it's going to have to be someone who can work closely with @lmccart—I think a lot of the deploy details are still in her head.

**Comment by lmccart** [comment]
The details around deploy are not too complicated, I could probably write them out and come up with a script to automate even. The bigger point to tackle is our decision to use milestones to determine releases. I think we need to come up with a process/workflow for determining which issues and features go into a milestone. That would make it more clear when to push the new one out. 

I just pushed 0.4.6 which is the first release since before p5jscon. The delay with this one was fixing some remaining issues from our major refactor(s) at CMU, so I expect future releases won't have such a lag. I know it was sort of a drag because this also held up the release of a lot of the new functionality and fixes we made at CMU, so apologies for that.

**Comment by kadamwhite** [comment]
One thing I'd love to see documented (and if it is and I missed it, sorry!) is a guide for when to rebuild the files with grunt when making a PR. Having the built files included in your PR both makes reviewing the code tricky (through duplication) and introduces merge conflicts, so it feels like it would be good to e.g. Clarify "the lib/ files will get rebuilt when a PR is merged, so you don't need to check them in." Maybe that's outside the purview of this discussion but it felt release-oriented

**Comment by joecridge** [comment]
Is there a possibility that we could add the `lib` folder to the `.gitignore`? I feel like the built files should be versioned separately from the codebase because
- at the moment it's confusing when you're searching the code history in the repo and the results include built files that are out of sync with the source (it makes it difficult to work out where a change was actually made); and
- we're already having problems where different people end up with different versions of the built files that have the same nominal version at the top, because grunt built them in between official releases.

**Comment by workergnome** [comment]
This is really @lmccart's call, but I agree that it would be useful to do so.  I'll create a new issue for that, so we don't hijack this thread for that.

**Comment by lmccart** [comment]
I took a first pass [here](https://github.com/processing/p5.js/commit/834737bbb94dc2bf3c3248872dfb543b5ca42f52), using [grunt-release-it](https://github.com/webpro/grunt-release-it). The following things are now automated through a grunt call:

1. version number is bumped
2. lib files are built
3. new release is published on p5.js repo
4. files in `lib/` are copied to https://github.com/lmccart/p5.js-release (for use with bower etc)
5. publish to npm (maybe. I was afraid to test, worried it would publish the wrong files/the whole repo. I want it to just publish [these files](https://github.com/processing/p5.js/blob/master/package.json#L44).)

What doesn't work:
* New release published to p5.js just zips up the entire repo right now. What it should actually include can be seen [here](https://github.com/processing/p5.js/releases/tag/0.4.8), specifically:
  * p5.js
  * p5.min.js
  * p5.js
  * p5.sound.js
  * p5.sound.min.js
  * p5.zip containing all of the above plus empty example
* I'm not sure about the npm options I have set right now. I grabbed them from [here](https://github.com/webpro/release-it) but they weren't listed in the readme for grunt-release-it.

**Comment by lmccart** [comment]
Forgot a couple other tasks that'd be nice to add to automation:
1. call `grunt yui` to rebuild docs.
2. copy `docs/reference` folder to `reference` folder in p5js.org repo.

**Comment by lmccart** [comment]
just a note that I added this here https://github.com/processing/p5.js/wiki/Release-steps

**Comment by sakshamsaxena** [comment]
> New release published to p5.js just zips up the entire repo right now. What it should actually include can be seen here, specifically:
p5.js
p5.min.js
p5.js
p5.sound.js
p5.sound.min.js
p5.zip containing all of the above plus empty example

I think [this](https://developer.github.com/v3/repos/releases/#upload-a-release-asset) might help ? If we somehow further refine the entire automation process (going beyond `grunt` basically), maybe we can include a suitable call to set up the release! Publishing on NPM would could be conditionally triggered then (as only the p5.js owners can publish the release). 

I think there is a good scope of streamlined and independent automation here :)

**Comment by sakshamsaxena** [comment]
(Re)Activating this discussion.

I have been involved lately with writing a dedicated and detailed Grunt Task which handles the release process end to end. It covers Testing, Version Bump, Building Library and Docs, Creating a new Commit and Tag with the bumped package.json, Pushing these changes to GitHub (to this p5.js repo), Release the library files only on NPM, Bower (by updating the release repo maintained by @lmccart), Updating the docs in the website repo with newly generated ones, Drafting a GitHub Release (on this repo) with the JS files and the Zip as mentioned (Phew!)

Now that it's automated (PR coming within a day or two, a bit delayed, apologies), the non-mundane part of creating a meaningful "Changelog" with each GitHub Release is the point which requires some discussion and decision. If I do a `git log --pretty=format:"* %s" 0.5.12..0.5.13 --no-merges`, I get the following history between the two tags :
```
* Updated README to include some mentions of modularisation capability
* updating docs for issue https://github.com/processing/p5.js-website/issues/132
* Delete .gitkeep
* removing grunt yui:dev task, now grunt yui generates both prod and testing docs issue #1954
* fix for ordering of test grunt task #2125
* adding comment to make stroke fill swap in point clear
* fix point color closes #2119
* small fixes
* style clean up
* unit test update
* this and p5 unified to p5
* p5 vs this
* clean up for merge; fixed FES bugs
* added unit tests for string_functions; updated string_functions inline doc
* added unit tests for color/creating_reading, added FES for utilities/string_functions
* color/creading_reading: updated documentation and clean ups
* color/creading_reading: color() fixed via updating documentation
* core/curves functions added FES & unit tests; color/creading_reading in progress. color() not working
* added Array checking to validateParameters(); implementing FES to curves and color/creating_reading functions
* minor updates
* 2d primitives unit tests
* 2d primitives unit tests
* 2d primitives unit tests
* 2d primitives unit tests
* unit test typo
* validateParameters() modification + small fixes
* fixes and improvements based on comments
* removed validateNumParameters() and re-arranged validateParameters()
* removed validateNumParameters() and re-arranged validateParameters()
* removed validateNumParameters() and re-arranged validateParameters()
* small bug-fix and clean up
* parameter checking based on data.json
* parameter checking based on data.json
* validateNumParameters and unit tests cleaned up
* validateNumParameters and unit tests cleaned up
* clean up
* added examples and cleaned up
* added validateNumParameters in error helpers and applied them in 2d primitives
```

There was a branch merge as well as another PR merge between the two patches, and these are the commits in order between the two tags (irrespective of _dates_). Clearly, relying on commit messages to determine the changelog isn't very wise, given that we'll be merging a lot of PRs and code, and then, it also doesn't seem fit as it's all been in the development, so these messages are all fair too. (Suggestions welcome here).

I personally think now that we have Issue Templates in place, we can easily create and assign milestones as and when new issues arises. It would really aid in keeping a track of our progress, as well as keep some transparency too so that one can anticipate when the next minor or major (yay!) release is coming up. Even though the Release notes would still require manual effort, there would at least exist a resource of such milestones to list out the issues resolved and features implemented. 

More thoughts welcome! :smile:

**Comment by lmccart** [comment]
@sakshamsaxena discussed a bit offline and feel that the best option for now is to rely on manual editing of the changelog. this also provides a nice check in point so that when a new release is made, we have a good sense of what's actually in it.

we both agreed the use of milestones and release planning would be very beneficial and is a goal to should target as a next step after the work on the release automation process.

**Comment by lmccart** [comment]
@sakshamsaxena is this one good to close?

**Comment by sakshamsaxena** [comment]
Yep, closing this now. We can discuss milestones over a general discussion in another thread whenever we're ready for it :-)
