### ISSUE TITLE
"point" class documentation text misprint

### ISSUE THREAD

**Issue by Paulo005** [processing/p5.js#7086]
The description text of "point" class p5js documentation contains an error and need to be changed from :
"The version of point() with _one parameter_ allows the point's location to be set with its x- and y-coordinates, as in point(10, 20)."
to :  
"The version of point() with _two parameters_ allows the point's location to be set with its x- and y-coordinates, as in point(10, 20)."

I noticed this error trying to draw a point with one parameter with a p.vector and that didn't work, I think I made no error in my code but it could. For the moment I'll just use the two parameters method.

TY, have a nice day.

**Comment by NicholasGillen** [comment]
Hi, I'd like to be assigned this issue (as a good first issue to get started). Are you happy if I implement the fix?

**Comment by Qianqianye** [comment]
Thanks @Paulo005 for catching it and @NicholasGillen for your interest.
Hi @nickmcintyre, what's your thought on the this before we assign the issue?

**Comment by yaojiejia** [comment]
Hi @Paulo005 by "I noticed this error trying to draw a point with one parameter with a p.vector and that didn't work" do you mean if I make point(10) will not work and if I make point(10,20) will work because it has two parameter values to pass in? If that is the case I think by simply fixing the documentation will do it but I will also dig into the code!

**Comment by yaojiejia** [comment]
Hi @Paulo005, I have tested the issue and indeed there is some confusion regarding the documentation, I tested 3 situations that require 1 parameter and 2 parameters: https://editor.p5js.org/AlexJia/sketches/t5uvK0VOS and seems like they all work as expected. I think we can just simply change the documentation from 
"The version of point() with one parameter allows the point's location to be set with its x- and y-coordinates, as in point(10, 20)."
to :
"The version of point() with two parameters allows the point's location to be set with its x- and y-coordinates, as in point(10, 20)."
And include another line that specifically addresses the usage of one parameter in the point() class.
@Qianqianye If it's possible, I'd like to be assigned for this issue, thanks!

**Comment by nickmcintyre** [comment]
Good catch @Paulo005!

It'd be helpful to replace "one parameter" with "two parameters" as you suggested: The version of `point()` with two parameters allows the point's location to be set with its x- and y-coordinates, as in `point(10, 20)`.

The one-parameter version could also be clarified a bit: The version of `point()` with one parameter allows the point's location to be set with a p5.Vector object, as in `point(myVector)`.

That description was placed last because vectors are an advanced topic and it's a less common use case. Reading it again, it seems like we should order the descriptions by the number of parameters 1-2-3. Thoughts?

**Comment by Paulo005** [comment]
hi @yaojiejia Yes the class seems to work with one parameter, in my code that cleary didnt work but as I was working with a lot of librairies it surely comes from me. In a raw sketch that works well. I think there no bug, just a little misprint in the documentation !

TY for testing it !

**Comment by Chaitanya1672** [comment]
@Paulo005 I would like to work on this issue. Could you please tell me where we should make the changes?

**Comment by kmr-ankitt** [comment]
can i fix this issue
