### ISSUE TITLE
set() does not use correct color

### ISSUE THREAD

**Issue by marcstober** [processing/p5.js#7139]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [X] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build process
- [ ] Unit testing
- [ ] Internationalization
- [ ] Friendly errors
- [ ] Other (specify if possible)

### p5.js version

1.9.0

### Web browser and version

Edge 126.0.2592.68

### Operating system

Windows 11

### Steps:
1. Use the `set` function to update the color of a pixel (but not the top-left pixel of the canvas).
2. Call the `updatePixels` function with arguments to update only that pixel
3. **BUG:** Expect the pixel to update to the specified color. Instead, it actually updates to the color of the top-left pixel.

Note: this also occurs with a graphics buffer created with `createGraphics` (which is where I first observed this), and then I was able to reproduce the issue on the "regular" canvas.

### Snippet:

Also live at: https://editor.p5js.org/marcstober/sketches/bPy_jiZJS

```js

function setup() {
  createCanvas(400, 400);
}

function draw() {
  background(220);

  set(0, 0, [255, 0, 0, 255]); // red

  set(2, 2, [0, 0, 255, 255]); // blue
  updatePixels(2, 2, 1, 1);

  // BUG: The pixel at (2, 2) should be blue, but it is red.
}


```

**Comment by davepagurek** [comment]
Looks like the bug is in `updatePixels`: if you call `updatePixels()` with no arguments, then the result is correct. It seems like when passing the rectangle parameters, it is updating the correct region but with data from an incorrect region, placing the pixels from the top left of the canvas into the top left of the destination rectangle. (If you call `updatePixels(2, 2, 4, 4)` then you will see both the blur and red pixels, but with a 2px offset.)

**Comment by yuekaim** [comment]
Not sure if the problem is with `updatePixels`. Calling it without arguments just means calling `updatePixels(0, 0, width, height)`.

Addition note on this bug: The function `set` takes `imgOrCol` which can be in image or a color. When it takes an image, `clearRect` and `drawImage` is performed, which means the image is put onto the canvas starting from the (x, y) passed into `set`. Meanwhile, when a color is passed into the argument it changes the value of `pixelsState.pixels[...]`

https://editor.p5js.org/yuekaim/sketches/bkCjBiE8R
here is a sketch to show what I mean.

**Comment by davepagurek** [comment]
I think the reason why I assume `updatePixels` is the problem is that it places the contents of the `pixels` array at the given x, y coordinate:
https://github.com/processing/p5.js/blob/b467200952d92422bd2d494588aa8d3a06f9b83b/src/core/p5.Renderer2D.js#L528

[The MDN docs for `putImageData`](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/putImageData) list the arguments as `putImageData(imageData, dx, dy, dirtyX, dirtyY, dirtyWidth, dirtyHeight)`. So here, the x and y in `updatePixels` are used as `dx` and `dy`.

That image data is just the contents of the `pixels` array, so if one calls `set(0, 0, [255, 0, 0, 255])`, the first pixel in the pixel data will turn red. If you call `updatePixels` with no arguments or manually specify 0,0 as the coordinate, then the top left pixel from the data correctly gets mapped to the top left pixel of the canvas. However, if a different coordinate is used (say, 2,2), rather than grabbing the **sub-image** of the pixel data starting at that 2,2 and placing that at 2,2 on the main canvas, the full pixel data is grabbed and placed at 2,2, so what was at 0,0 in the image data gets placed at 2,2 on the canvas.

In order to not have this offset when non-zero coordinates are used, I think dx and dy should always by 0, and instead, `dirtyX` and `dirtyY` would be what `updatePixels` sets. Here's a live demo of that, and it seems to address the original bug: https://editor.p5js.org/davepagurek/sketches/a9mS4O3pZ

**Comment by yuekaim** [comment]
Ahh yes you are totally right!
