### ISSUE TITLE
Prevent mouseIsPressed if not directly over canvas element

### ISSUE THREAD

**Issue by Tsourdox** [processing/p5.js#7196]
### Topic

Is there a way to prevent the mouseIsPressed to become true if there is an element overlaying the canvas?

Basically I don't want to draw the circle when the mouse is over the div element.

```
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/1.10.0/p5.min.js"></script>

  <style>
    #overlay {
      position: fixed;
      top: 50px;
      left: 50px;
      width: 5rem;
      height: 5rem;
      background: red;
      opacity: .4;
    }
  </style>
</head>

<body>
  <div id="overlay"></div>

  <script>
    overlay.onclick = (e) => {
      e.stopPropagation();
      return false;
    };
    overlay.onmouseover = (e) => {
      e.stopPropagation();
      return false;
    };

    function setup() {
      createCanvas(400, 400);
    }

    function draw() {
      background(220);
      fill("black");
      if (mouseIsPressed) {
        circle(mouseX, mouseY, 20);
      }
    }
  </script>
</body>

</html>
```

**Comment by sikaili** [comment]
Hi @Tsourdox,

[mouseIsPressed](https://p5js.org/reference/p5/mouseIsPressed/) is a boolean that indicates whether the mouse is pressed (true if pressed, false otherwise). It’s not an event like mousePressed().

I made a working example for your use case, which stops to draw the circle when hovering over an overlay:
[Example](https://editor.p5js.org/skug/sketches/WXAPrJegV)

```
let isMouseInOverlay = false;
const overlayElement = document.querySelector('#overlay');

overlayElement.addEventListener('mouseover', () => {
  isMouseInOverlay = true;
});

overlayElement.addEventListener('mouseout', () => {
  isMouseInOverlay = false;
});

function setup() { 
  createCanvas(400, 400);
}

function draw() { 
  background(255, 100, 100);
  if (mouseIsPressed && !isMouseInOverlay) {
    ellipse(mouseX, mouseY, 100);
  }
}
```

Additionally, here’s another example comparing mousePressed() and mouseIsPressed:
[Comparison example](https://editor.p5js.org/fergfluff/sketches/HkAydbxiZ)

Hope this helps!

**Comment by limzykenneth** [comment]
Thanks @sikaili for answering here! @Tsourdox if you have further questions or need additional help with your code, feel free to join the community [Discord](https://discord.gg/SHQ8dH25r9) if you haven't already.
