### ISSUE TITLE
Determine proper output for `Color.toString()` method

### ISSUE THREAD

**Issue by kadamwhite** [processing/p5.js#723]
In #696 it was brought up that `toString()` will always output a RGBA CSS color string (in the format `rgba( r, g, b, a )`) regardless of what `colorMode` is specified. #696 is focused on the internal state of `colorMode`, so this issue serves to discuss the `toString` question in isolation.

As I understand the debate, there are three primary options:

- `toString` should always produce a basic color string in a consistent, CSS/SVG-compatible format, regardless of the current `colorMode` (basically, keep things as-is)
- `toString` should return a string reflecting the current colorMode, regardless of whether it is CSS/SVG compatible (e.g. return an HSB string if that is the current mode)
- `toString` should return a serialized object containing strings representing all supported color modes

If I've missed some of the nuances, please add info below!

**Comment by kadamwhite** [comment]
My stance, not to be over-conservative, is that the current status quo (exporting a CSS-compatible `rgba` string) is satisfactory. To quote MDN, "the toString() method you create can be any value you want, but it will be most useful if it carries information about the object" -- in the lack of any standard about how to handle this method's output, I err towards using it to define a consistent, readable output format.

I imagine that the main use-case I'd have for `toColor` is to plug a P5 color into another context or a different color utility; that use-case doesn't need to be colorMode aware, since if I'm plugging it into a utility like Chroma or TinyColor it will be parsed and converted with that library's methods, and if I'm e.g. writing it out into CSS or SVG it's set-and-forget.

**Comment by sarahgp** [comment]
I don't see the distinction. Whatever is decided about the functioning of `colorMode` in relation to its constituent parts should apply to `toString()`.

 There should be a consistent color API, which, I would posit is that properties unique to modes, say `brightness`, are returned in the only possible mode and others are returned in the current. The alterntive is that properties are returned in the mode specified, but that, according to #696, is not the behavior of Processing and so probably shouldn't be the behavior in p5.js.

**Comment by sarahgp** [comment]
I disagree. Why treat users like we know better than them? RGBA is the default mode and beginners will use it and will never run into this.

But say someone who is experienced enough to to change `colorMode` is using it for debugging or to pass into something we haven't thought of. If they are working in HSL, they should get it in HSL. I know I prefer HSL and would be irritated if regardless of how I entered a color, I got RGB when asking for a string. As long as we are transparent and predicable in our behavior, I don't think we should be constraining users from the output they can receive.

**Comment by kadamwhite** [comment]
My concern is that e.g. if I set color mode HSB, then hit toString, if I get an HSB string that string now has no meaning outside of p5 -- I've been viewing toString as a sort of export format.

We could potentially be more explicit and have toRgbString, toHslString, etc?

**Comment by kadamwhite** [comment]
Again, I want to try to get an understanding of what the defined purpose of this toString method is, because knowing the goal will help us measure how sufficient (or in-) our solutions are -- and I'm definitely playing catch-up from any prior art within Processing proper.

**Comment by sarahgp** [comment]
Yeah, I am definitely working less from prior Processing art than from a UX sense — and it is possible there is context I am missing.

Outside of that, the HSB is definitely a legitimate color space: if someone intends to use to use the string method within that mode, I don't want to prevent them. Being more explicit might make sense. We could also match the `colorMode` API and do `color.toString(RGB)`.

**Comment by kadamwhite** [comment]
The reason I consider HSB string output problematic is that HSB is not a recognized CSS color identifier, whereas RGB and HSL are -- if we output an HSB string then neither most other color libs nor SVG/CSS will know what to do with it. That may not be a reason not to do it, but as I said, I was seeing toString as a way of generating a single, usable-everywhere value, and HSB wouldn't work in that context.

**Comment by brysonian** [comment]
@kadamwhite I definitely hear you on passing the value to other contexts, but that use case feels like a sideeffecty was of using toString. If the user is sophisticated enough to be passing the value around, then she/he should maybe be more specific about what they want. So this would be either explicit toXXX methods or something like @sarahgp suggested and toString takes an optional arg for the output mode. 

FWIW my suggestion of a overly complex output from toString is motivated by the assumption that toString on a color will mostly be used for quick debugging.

**Comment by kadamwhite** [comment]
@brysonian Interesting comment on the debugging argument, that's a good point.

I'm going to look around this week for prior art

**Comment by workergnome** [comment]
Maybe we have four color modes?  RGB [255,255,255,255]  WEB_RGB [255,255,255,1.0], HSL [360,100,100], and HSB [360,100,100]?

I think that by default using a CSS `rgba(255,255,255,1.0)` as the toString() makes sense, and letting someone pass in a colorMode to get a different value would be fine.  Having it respect the global `colorMode` seems like too much magic.

**Comment by crhallberg** [comment]
What about HEX?

**Comment by sarahgp** [comment]
From my point of view, these seems like were are getting into a morass of special cases and I am not sure why. Letting people set a colorMode and then get anything possible back in that mode, including `toString()` seems like the most transparent behavior.

A little context: I've spent the past week at p5jscon refactoring the `color` files — I went in to undertake #591 and it turned up a bunch of code written under the assumption of one or two color spaces and some bugs related to 255-space assumptions. (PRs from earlier in the week include #674 and #683.) So I have basically been living inside our color setup.*

The current implementation of `color` is as an object wherein all instances have a core `rgba(255, 255, 255, 255)` representation — this is used to set the `ctx.fill`, etc. on the canvas itself and as a lingua franca in conversions. Color objects may also have a custom `colorMode` with any range specification the user desires. That is, `rgba(100, 1000, 4, 22)` is a totally legitimate space within p5.js. This is defined when the user calls color mode. Other representations are created if/when a user calls for a value that has an expected space. That is, you can call `brightness()` from an RGB color-space and get back the value from HSB. Once converted, the new color space color, with default maxes, is available for the lifetime of the object.

Given all that I would say it is only logical that: `toString` should respect the global flag like anything else and what users do with it is their business.

I'm not sure why that would be "too much magic" or otherwise problematic. It seems like the simplest extension of the principles @benfry [expressed in describing how `colorMode` should work](https://github.com/processing/p5.js/issues/696#issuecomment-107260886) back in #696.

Another, different discussion would be needed for whether we want to specify WEB_RGBA and HEX as "settable" color spaces or whether they are best treated as subcategories of RGBA as they are currently — the result of this would influence if they are proper arguments to `toString()` as well as any other similar methods.


* If you want to check it out, there is a biggish bit of changes still in progress [here](https://github.com/sarahgp/p5.js/tree/adding-hsla/src/color).

**Comment by kadamwhite** [comment]
I don't think that hex or other non-numeric color strings should be an output format, parsing them was added primarily to support easier color input and it'd take a lot of code to recreate them that I don't think would give us much benefit -- this seems to be a common decision after doing a cursory look through some other color libs. 

I have more thoughts but it's too late to articulate them well and I'm traveling tomorrow, so I'll defer my response for a while. I still don't think it makes sense to output a non-svg compatible string, but I'll return to the issue later with fresh eyes :)

**Comment by sarahgp** [comment]
I will reiterate that I think artificially constraining a method because we think we know better than users is a recipe for frustration, and implementing this should be pretty straightforward. Regardless of the mode, we have array representations of the colors and setting them to string is a check for the set mode and then one like of concatenation.

But I need to start on my GSOC project, so I am going to back out of this for now. If we decide we want to add functionality, we can open a new issue with the beginner tag on it and someone can grab it.

**Comment by kadamwhite** [comment]
I don't think we know better than users, I just think that `toString` should output a method that is a valid web color :) But I will concede to the will of the group, whatever that may be.

**Comment by lmccart** [comment]
closed with #857
