### ISSUE TITLE
Enhancement:  support chaining on all functions

### ISSUE THREAD

**Issue by dhowe** [processing/p5.js#727]
All functions without returns can return a reference to the p5 instance, to allow functions to be chained as per common JS practice. An example:

``` javascript
textFont(afont).textSize(18).text("my heart", 30, 30);
```

Functions can also support both get/set when appropriate (is there a name for this pattern?) An example:

``` javascript
textSize(18); // setter, returns p5 instance
textSize(); // getter, returns number (e.g., 18)
```

I notice that this is implemented for some functions in p5.js, while others not, which may cause errors for those expecting it

**Comment by jedahan** [comment]
The inconsistency should be addressed, though I'm not sure what the best solution is.

With more ways to write the same thing, we will have code that reads differently, which might add friction when learning.

It does read nice (and personally I am a fan chaining in places like jquery), but I am also worried about how chaining hides the changing of global state a bit.

Its probably fine, but just wanted to play a bit of devils advocate

**Comment by brysonian** [comment]
I understand the value of chaining in some places (dom for example) but not as much for functions that set global flags. @dhowe can you expand on why you think this ought to be the default? 

The unitary getter/setter is maybe best taken up in a separate issue to keep discussions on point, but i would just say that for some functions we would want to be very aware of any performance implications for functions that need to be particularly performant.

**Comment by sepans** [comment]
If I am not wrong, Processing by design was made in a way that 
<pre>
textFont(afont);
textSize(18);
text("my heart", 30, 30);
</pre>
and chaining (if it was supported)
<pre>
textFont(afont).textSize(18).text("my heart", 30, 30);
</pre>
do the same thing because either way it affects the global state and not a local state object returned by the first function in the chain (which is a terrible idea for a non-educational tool but a brilliant one when it comes to teaching programming: it is consistent with the metaphor of switching pens, in real world or photoshop).

As for getter/setter, I don't think it would affect the performance because it is a matter of adding a very simple and cheap check. 
<pre>
// this is just a sample and not the actual p5 code.
p5.textSize = function(value) {
    if (!arguments.length) return textSize; // where textSize is the global value.
    textSize = value;
    //return my;   // this line adds method chaining capability but I am not sure if it is useful
};
</pre>
so I don't think there is any reason not to have that.

**Comment by dhowe** [comment]
I think the primary concern is to be consistent -- currently some functions support chaining and other don't (which makes chains break in surprising ways). 

To be clear, I am only suggesting that we consider this in *addition* to our current syntax, not that it be some kind of default. Further, if added, I would suggest that all examples/documentation continue using the basic (non-chained) syntax, which is easier to read.

But from my perspective, this is a very common idiom for JavaScript libraries, and one that more proficient users will expect. So we then need to consider whether there is a downside for learners (who will continue to use the basic syntax as they do in Processing). The one argument that comes to mind  here is whether, if people post external examples or demo code that use chaining, it will make it more difficult for beginners to understand such code (I am talking about examples/demos posted outside of the p5js website).

**Comment by workergnome** [comment]
I like chaining in libraries that support it—d3, jQuery, etc, but in my head p5.js isn't a chaining or chainable library.  

We could implement it in the methods that don't explicitly return a value now, but I think that the inconsistencies it would create in p5 might make it more complicated or confusing.  I think the confusion between the global state machine (which is how I think about p5) and the chainable, passable object, that returns instances of a element (like jQUery) are different concepts, and I'm not sure that they can be combined without confusion.

Just my opinion—I don't feel *strongly* about this, but I'm trying to figure out the philosophy of p5.js and this is definitely part of it.

**Comment by sepans** [comment]
Which brings us to the more philosophical question of how suitable p5.js is for advanced JS programmers who also use libraries like d3 and regularly do chaining?

I personally think there are features in p5.js which make it an amazing framework for learning how to code, but not as useful for advanced users. (specifically the nature of <code>draw()</code> method is kind of in clash with event-driven nature of JS, and also makes it hard to take advantage of GPU optimized animations when it comes to performance optimization).

I agree with @dhowe about consistency, regardless of the decision about usefulness of chaining.

**Comment by workergnome** [comment]
I think that the `setup()`, `draw()', frame-based, not event-based, model of p5.js is sort of its signature feature/philosophy, and that coding techniques that use and support that functionality should be supported.   I also think that it differentiates us from things like d3, which is explicitly based on data-binding, or jQuery, which is much more event-based.

It means we're not as good, or perhaps even not appropriate, for things that are not frame-based.  Much like chaining, I think maybe supporting *multiple* methods might add more complexity, and will certainly make it more confusing for people, than choosing one and supporting it well.

Super-open to other opinions, though, and really enjoying this discussion.

**Comment by Ucodia** [comment]
I agree that the chaining syntax is very convenient when using libraries like jquery or d3 but as it has been said p5 works in a very different way, which is, every style setter such as `stroke()` are acting on global flags, whereas jquery and d3 act directly on the object returned by the left function.

Indeed those setters could return the p5 instance but I believe that it could lead to weird situations like this one:

```javascript
// define styling
strokeWeight(5);

// this will have a stroke of 5
rect(50, 50, 50, 50);

// this will have a stroke of 1
strokeWeight(1).rect(150, 50, 50, 50);

// this will have a stroke of 1 :(
rect(250, 50, 50, 50);
```

Here chaining would impact other drawing functions that does not use style chaining. I feel that this is a weird because one of the typical behavior of chaining is to only impact what is on the left side. If you use chaining you would really expect the last rectangle to display with a size of 5.

Another unusual aspect of this chaining is that in fact it is reversed chaining. If we want proper chaining we should be able to use it in this fashion.

```javascript
rect(150, 50, 50, 50).strokeWeight(1);
```

But then I believe that there is another way to achieve chaining with a usual behavior. What about this:

```javascript
createRect(150, 50, 50, 50)
  .strokeWeight(1)
  .draw();
```

Here we achieved 2 things: chaining is in the right order and style is isolated to this particular drawing function. Here is how we could implement it:

```javascript
p5.prototype.Primitive = function() {
  this.matrix = {}; // TODO: get default from current p5 instance
  this.style = {}; // TODO: get default from current p5 instance
  this.drawPrim = function() {};

  return {
    strokeWeight : function(w) {
      this.style.strokeWeight = w;
      return this;
    },
    // ...
    // TODO: add matrix and style functions
    // ...
    draw() {
      push();

      // apply local style and matrix
      strokeWeight(this.style.strokeWeight);
      // ...
      // TODO: apply matrix and style functions
      // ...

      this.primDraw();
      pop();
    }
  }
}

p5.prototype.createRect = function(x, y, w, h) {
  var props = { x: x, y:y, w:w, h:h };
  var prim = Object.create(p5.Primitive.prototype);

  prim.drawPrim = function {
    rect(props.x, props.y, props.w, props.h);
  }

  return prim;
}
```

I have not tried to run this code but that is the global idea of how we could achieve chaining and isolation but there might be a better way to write this. Of course isolation has an overhead as drawing would require a systematic `push()` and `pop()`.

If you think that could be an acceptable solution I will go ahead and write it in the form of a plugin as a proof of concept in order to assess it.

**Comment by lmccart** [comment]
thanks @Ucodia very cool. I don't think we'd merge this into the core library as it's a bit at odds with the current system of drawing that we have going on. but I think this makes sense as an addon we could add to the libraries page for users that want to use p5 in this way.

**Comment by Ucodia** [comment]
@lmccart totally agree, this has to remain an addon. The only thing that would be required in core is to allow `push()` to return the current style/matrix in order to consistently gather this object from current p5 instance: [see this line] (https://github.com/processing/p5.js/blob/master/src/core/structure.js#L161). All addons requiring to manipulate styles could benefit from that.

**Comment by lmccart** [comment]
makes sense, I'd be fine to make this change, I'll do that now. is it useful for `pop()` to return this as well?

**Comment by Ucodia** [comment]
@lmccart I don't immediately see a good usage for it but for staying consistent I guess that cannot hurt.

**Comment by lmccart** [comment]
ah I forgot, this is tricky because the canvas doesn't actually keep track of the transform matrix and neither does p5. adding this on would significantly slow down transform operations. we could return the styles but I'm not sure if this is helpful without the matrix data?

**Comment by Ucodia** [comment]
@lmccart well if `push()` returns an object, it would have to return everything related to pushing, which means styles and matrix. Even in the present case, though it was not demonstrated, chaining matrix transformations would be very useful. Imagine that you could do something like `createRect(50, 50, 50, 50).rotate(TWO_PI / 4).draw()`.

So I would say, let's keep it simple for now. I will just experiment with an addon with a hardcoded style/matrix in the first place. Then if the experiment proves successful, we can start migrating the hardcoded part by fiddling with the `push()` and `pop()` functions to improve the general addon integration.

**Comment by lmccart** [comment]
there hasn't been much discussion on the original topic of this issue in a couple years, so I'm going to close this as it seems to have dropped in priority. we can reopen later if need be.
