### ISSUE TITLE
default textureMode changes if an image is drawn

### ISSUE THREAD

**Issue by shiffman** [processing/p5.js#7357]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [X] WebGL
- [ ] Build process
- [ ] Unit testing
- [ ] Internationalization
- [ ] Friendly errors
- [ ] Other (specify if possible)

### p5.js version

1.11.0

### Web browser and version

130.0.6723.70 (Official Build) (arm64) 

### Operating system

Mac OSX

### Steps to reproduce this

The reference indicates the default texture mode is `IMAGE`. I made a simple example to demonstrate texture mapping with an image of clouds:

```js
llet img;

function preload() {
  img = loadImage("clouds.jpg");
}

function setup() {
  createCanvas(100, 100, WEBGL);
}

function draw() {
  background(0);
  // imageMode(CENTER);
  // image(img, 0, 0, 10, 10);
  rotateY(frameCount * 0.01);
  texture(img);
  beginShape();
  vertex(-40, -40, 0, 0);
  vertex(40, -40, 640, 0);
  vertex(40, 40, 640, 480);
  vertex(-40, 40, 0, 480);
  endShape();
}
```

The output is as expected:

![image](https://github.com/user-attachments/assets/b5c99c1c-fee9-4fc2-9ed9-2820184b34d5)

However, if you uncomment line 13/14 above and draw an image, the default texture mode changes to `NORMAL`. I can force it back by calling `textureMode(IMAGE)` but this behavior was very confusing to me. (I was working on a much more elaborate example and it took me quite some time to track down why texturing wasn't working as expected!) 

![image](https://github.com/user-attachments/assets/296c5166-f8bc-469d-b655-d4ef5f4be336)

The above code is also available in this web editor sketch: https://editor.p5js.org/codingtrain/sketches/NFu5OVc2h

**Comment by davepagurek** [comment]
It looks like `textureMode` is updated between a push/pop here: https://github.com/processing/p5.js/blob/6b69d26e3e0764bc85d84da210851ea99f8545d7/src/webgl/3d_primitives.js#L3409-L3415

...but it looks like we don't actually save/restore `textureMode` in `RendererGL`'s `push`/`pop`: https://github.com/processing/p5.js/blob/6b69d26e3e0764bc85d84da210851ea99f8545d7/src/webgl/p5.RendererGL.js#L1600

This is actually already fixed in 2.0, where we changed it to have to do less manual work to save/restore states: https://github.com/processing/p5.js/blob/8909e1b76f5fb3bbb8a0301ddf78b885b8d43284/src/webgl/p5.RendererGL.js#L239-L241

I'll do a quick PR fixing this in 1.x in case we do another release before 2.0.
