### ISSUE TITLE
texture() doesn't work with push and pop

### ISSUE THREAD

**Issue by jacopomazzoni** [processing/p5.js#7385]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [X] WebGL
- [ ] Build process
- [ ] Unit testing
- [ ] Internationalization
- [ ] Friendly errors
- [ ] Other (specify if possible)

### p5.js version

1.11.1

### Web browser and version

p5js editor, firefox and chrome latest lts tested 

### Operating system

mac and win

### Steps:
1. tested the file ( a bent plane with an image texture ) loads ok see sketch: https://editor.p5js.org/jacopom/sketches/fX6YlQimX
2. tested in my 3d particles example and the texture doesn't work: https://editor.p5js.org/jacopom/sketches/qSLLcrpSi
3. commenting out lines 70 and 75 (push and pop) prevents the translate rotate etc from working but fixes the missing texture

### Snippet:

```js

    //relevant method of the particle class
    push();
        rotateY(this.yangle);
        translate(this.x, this.y, this.z)
        model(leafModel);
        texture(leafTexture);
        pop();

```

**Comment by ffd8** [comment]
@jacopomazzoni – just checking out issues thread and can lend a quick answer here. It is working – however `texture()` should be assigned before the `model()`, similar to `fill()/stroke()` style properties. It was working without `push()/pop()`, because it was being set at the bottom and then continued working on next draw cycle. It happens so fast, one doesn't notice. With the texture not appearing when under the model within a push/pop, actually means it is working since it's preventing anything else from knowing that texture was set. Hope that helps!

**Comment by davepagurek** [comment]
Thanks @ffd8! I'm going to close this for now since it seems like the library is working correctly. Feel free to comment below if any new info comes up though!
