### ISSUE TITLE
noStroke() does not work in a p5.Graphics context, but strokeWeight(0) does...

### ISSUE THREAD

**Issue by ccheaton** [processing/p5.js#754]
The example code on this page http://p5js.org/reference/#/p5/createGraphics is:

```javascript
var pg;
function setup() {
  createCanvas(100, 100);
  pg = createGraphics(100, 100);
}
function draw() {
  background(200);
  pg.background(100);
  pg.noStroke();
  pg.ellipse(pg.width/2, pg.height/2, 50, 50);
  image(pg, 50, 50);
  image(pg, 0, 0, 50, 50);
}
```

The `pg.noStroke()` call does nothing.

Replace `pg.noStroke()` with `pg.strokeWeight(0)` and you'll see the desired effect. I'm uncertain whether this is a mistake in the example or a mistake in the `noStroke()` code within a p5.Graphics context.

**Comment by joecridge** [comment]
Do you have this issue when running the example code locally? For me it only occurs when viewing the sketch on the p5.js website.

**Comment by ccheaton** [comment]
I do have the issue when running the example code locally. I'm using the un-minified 0.4.5 release from 02 June 2015 (downloaded from the p5js.org site).

**Comment by joecridge** [comment]
That's interesting, I'm using p5.js v0.4.5 as well (which I downloaded from p5js.org today), although mine is dated 27 May 2015.

Which browser are you using? I don't have this issue on Chrome 43.0.2357 or Safari 8.0.6 on OS X.

**Comment by ccheaton** [comment]
Hmm... I don't remember grabbing it from somewhere else. Anyhow, I just took a fresh clone of the repo and tested this:

```javascript
var pg;
function setup() {
  createCanvas(300, 300);
  pg = createGraphics(300, 300);
}
function draw() {
  pg.background(color("#efefef"));
  pg.noStroke();
  pg.ellipse(pg.width/2, pg.height/2, 50, 50);
  image(pg, 0,0);
}
```

The stroke is clearly visible. I suspect that I was incorrect about downloading from the site and that I just don't remember cloning the repository before. Either way, the bug seems to be present in the current master version of the repository.  Here's what I see when I run the code above:

![screen shot 2015-06-17 at 10 19 24 am](https://cloud.githubusercontent.com/assets/205364/8209320/5c528e10-14da-11e5-8889-5f94f880c0e4.png)

Sorry for the confusion!

**Comment by lmccart** [comment]
sorry for the confusion. so it works with the current lib file from the repo but not the one downloaded from the site, correct? I will package a new version for download today and hopefully this resolves the issue?

**Comment by joecridge** [comment]
Yes, I get this issue now with a clone of the repo.

It could possibly be related to @dhowe's [changes](https://github.com/processing/p5.js/commit/b1ccba0a180ac439e1a73ffaa9dc63d04d9a996f#diff-39ee1ae1ff494d026d5e8118dc36ee44) to `color/settings.js` a couple weeks ago?

**Comment by dhowe** [comment]
those changes appear to be part of the big graphics reorganization (is this correct @lmccart ?)

**Comment by lmccart** [comment]
that would be my suspicion. looks like there are a number of small issues with p5.Graphics since then. i'll try to look into it today or tomorrow.

**Comment by lmccart** [comment]
ok after a little investigation...

the more general issue here is that when we switched to having a p5.Graphics2D object and a p5.Graphics3D object, flags like `this._doFill` and `this._doStroke` and a lot of variables related to drawing are attached to the p5 object. so they are accessed inside p5.Graphics2D for example like, `this._pInst._doStroke`, when it used to be accessed by `this._doStroke`. adding the `._pInst` in there made it work for the normal drawing context, but it looks like now some of the drawing functions for a `p5.Graphics` buffer object are broken because in this case, we actually want to call `this._doStroke` etc rather than accessing the properties on the pInst.

so I guess the fix is to actually move these variables off of the p5.prototype and onto the p5.Graphics object itself.

I would guess some similar problem is happening in https://github.com/processing/p5.js/issues/753 as well.

**Comment by lmccart** [comment]
@ccheaton can you test with the version of the lib on the graphics-fix branch [here](https://github.com/processing/p5.js/blob/6fe01bc650c708f2285186d1b9846c421dd40605/lib/p5.js)? 

I made a change in `_createGraphics2D` where `createGraphics()` now returns a `p5.Element` that has a `p5.Graphics` object set as it's `this._graphics` property, rather than returning a `p5.Graphics` object directly. it seems to fix the three issues you posted, but haven't tested it too much beyond that so I'm not sure whether I introduced any other complications. you can see the updated function [here](https://github.com/processing/p5.js/blob/6fe01bc650c708f2285186d1b9846c421dd40605/lib/p5.js#L6916)

also, we might need a naming change here, because it makes sense that `createGraphics()` should return a `p5.Graphics` object rather than a `p5.Element`. I thought of names like `p5.GraphicsHolder` but I think more logical would be to rename `p5.Graphics`, `p5.Graphics2D`, and `p5.Graphics3D` to `p5.GraphicsContext`, `p5.GraphicsContext2D`, and `p5.GraphicsContext3D`.

@indefinit thoughts on this?

I also temporarily commented out the parameter checking in `image()` until we get a fix in there for allowing graphics objects as well. (issue #755)

**Comment by ccheaton** [comment]
@lmccart I tested it with `noStroke()` and various `strokeWeight()` settings, including `strokeWeight(0)` and they all worked as I expected they would.

**Comment by indefinit** [comment]
I'm a little late on the reply here but re: renaming to 
> p5.GraphicsContext, p5.GraphicsContext2D, and p5.GraphicsContext3D.
> 

I could go both ways on this.  My issue is that technically those classes contain more than just a graphics context, so it could potentially be confusing to call the graphics context on a p5.Graphics* object.

**Comment by lmccart** [comment]
hm good point. so how about p5.GraphicsRenderer?

**Comment by indefinit** [comment]
Yea I like that a lot.
