### ISSUE TITLE
createClass() and getElementsByTag()?

### ISSUE THREAD

**Issue by futuremarc** [processing/p5.js#760]
There have been a few times when making DOM examples where I really need a method like createClass() to smoothen the process, especially when live coding.

something like:
```javascript
  createClass('myClass', 'font-family:monospace; background-color:#FF0000; color:#FFFFFF; font-size:18pt; padding:10px;');
  panelLeft.addClass('myClass');
  panelRight.addClass('myClass');
```

-- 
Also, as it stands now it seems there's no way for me to manipulate the `body` element of my page. Without something like `getElementsByTag()` a lot of control over the DOM (esp when live coding) feels missing. What if I wanted to style everything in my `body`? What if I wanted to only move around `p` elements?

**Comment by lmccart** [comment]
good point re: get elements by tag. maybe `getElements()` and `getElement()` are too vague anyway, and better might be something like `getClass()`, `getID()`, and `getTag()`? or something like that...

**Comment by lmccart** [comment]
alternatively, we could adopt the jquery like notation of using "." "#" or nothing to specify which you're searching for. I guess one downside of this approach is that it requires the user have some understanding of css notation and selectors. maybe this is an ok assumption if they are at the point that they're searching by tag, class, or ID?

**Comment by futuremarc** [comment]
I think `getClass()`, `getID()`, and `getTag()` makes a great solution. It's friendly, reads nicely, and is very clear.

**Comment by workergnome** [comment]
I've got no strong views on this, but at what point are we just re-implementing the DOM selector stuff from jQuery or a comparable library?  It's nice to have helper methods for some things, but every helper method also increases both the library size (which I'm less concerned about) and the number of things we have to support (which I am more concerned about).

**Comment by brysonian** [comment]
I agree with @workergnome here. Would it be better to encourage document.querySelector (or possibly wrap it) instead of separate methods? I think once folks start manipulating the dom some understanding of css selectors is reasonable.

**Comment by workergnome** [comment]
Taking the example of what @sciutoAlex has done with the d3 integration, would  a set of examples of how to use both native `document.querySelector()` and jQuery `$('.class') selectors with p5 be a much stronger way to do a lot of these things?

I often think that documentation and examples are stronger than code, particularly when it comes to long-term support.

**Comment by futuremarc** [comment]
@workergnome The p5 selector wraps the dom element it in a p5.Element

I think I like the idea of having 1 selector that takes tags, elts and ids. Any idea of a method name? select()?

**Comment by lmccart** [comment]
I think `select()` might be too vague? Would it make sense to use `getElement()` and `getElements()` but adjust them to use selectors?

**Comment by futuremarc** [comment]
Wouldnt both functions be doing the same thing?

**Comment by shiffman** [comment]
I have a few thoughts to add that are slowly forming.  I think it's pretty clear that p5 should not reimplement a more sophisticated DOM engine like JQuery and that for formal, larger-scale development, the DOM aspects of p5 are likely not the right choice.

I think the question here to ask (in my mind) is: “For a student learning the basics of programming and how the web works what concepts do they need feel comfortable with and practice in the context of "sketching for the web" *before* the wizard behind the curtain is revealed?”   I'm thinking that towards the beginning of, say, a course teaching this stuff  the selector concepts of `id`, `class`, and `tag` are pretty key and teaching them inside the friendly garden of p5 is something we'll want to do.   In fact, we have these ideas with setting `id()` and `class()` and creating tags with `createP()`, createDiv()` etc.   In this way I do think that modeling a way to access elements with the same naming convention works nicely -- `getID()`, `getClass()`, `getTag()`.  I suppose its really `getByID()` but ugh, that's not nearly as succinct.  I like the simplicity of `select()` in theory but have trouble picturing in my mind how the example will be clear enough. 

All that `$` magic with `#` etc. is nice for developers but in my experience its crypticness tends to put beginners off.   Then again, does my thinking do students a disservice if all this has to come eventually?  I don't think so, but I don't really know enough yet having not taught a full semester class just yet.

**Comment by futuremarc** [comment]
I had the same initial reaction. It feels better in the notes for my p5 class starting next week to use  `getID()`, `getClass()` and `getTag()` and a jquery-like convention would be the only place in p5 where this sort of convention is used.

**Comment by brysonian** [comment]
The thing is, it isn't magic, it isn't jQuery-like, it's just [JavaScript](https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelectorAll), having separate get* methods is in that regard more magical.

I think the question is more if you think that students using p5 to manipulate the DOM might not already be familiar with CSS selectors. If they might not, then separate methods might make sense, but if that seems unlikely (and I feel it probably is) then I'm not sure what the advantage would be to pushing them away from a universally standard way of picking out DOM elements. That is how every DOM library does it and how native JavaScript does it via querySelector (not to mention all major browsers already have $ defined nowadays for this).

So yeah, the question is just, will users who want/need to do this know enough CSS to write a selector? I also imagine that most people using this will not be using it to grab elements they created, following the standard in p5, wouldn't they be more likely to store the value returned from createTag in a variable it talk to it that way? So that further narrows the use case FWIW.

**Comment by shiffman** [comment]
@brysonian, thanks for these thoughts, this is incredibly helpful.  Now that I see `document.querySelectorAll()` this helps me to picture a simplified `select()` method.  I also see the validity of not bothering too much with this, as you state, users that want to access created elements will almost certainly just be using a variable with appropriate scope.

In my teaching, the most students have never encountered selectors, CSS and have barely touched HTML.    This ebbs and flows and is really a side conversation outside of this thread, but while I currently see an increase in facility with technology in general, I also see a decline in basic knowledge of the underpinnings of the browser.

What I find really useful to teach is 

1. Show building some DOM with p5 only!  and then . . . 
2. Look, we could just implement the HTML first and the access and manipulate it via p5!

Here is a way oversimplified outline of what I mean:

```
var txt;
function setup() {
  txt = createDiv('to be or not to be');
}

function mousePressed() {
  txt.html('all the world's a stage');
}
```

and now. . . 

```
<html>
  <body>
    <div id="shakes">to be or not to to be</div>
  </body>
</html>
```

```
function mousePressed() {
  var txt = getId('shakes');
  txt.html('all the world's a stage');
}
```

Or, now, would this be better?

```
function mousePressed() {
  var txt = select('#shakes');
  txt.html('all the world's a stage');
}
```

Thoughts?

**Comment by workergnome** [comment]
If we were going to implement a helper method, I might **only** do it for IDs.  Otherwise, we have to deal with the fact that `select('.child')` (or `selectClass('child')`, or `select('div')`)will return an unknown number of elements, and we'll need to think about how `p5.Element` handles arrays or groups of returned values.

IDs *should* be unique, and would return only a single item, which could then be put into a variable.  Otherwise what does this do if there are two `.shakes`?, 

```
function mousePressed() {
  var txt = select('.shakes');
  txt.html('all the world's a stage');
}
```

**Comment by lmccart** [comment]
Right now `getElement()` searches by ID and returns one p5.Element, `getElements()` searches by class and returns an array of p5.Elements, so I don't think the array is too big of an issue. 

I think @brysonian's point resonates most with me. @shiffman's example is a good counterpoint, however, I could imagine just teaching students to add or "#", "." to specify class or ID in a `select()` method without having to go into the whole logic of CSS and selectors. Then if they do later on go deeper into CSS (or jQuery or any other library that uses this convention), the pieces will line up in their understanding of the bigger picture of how it all works. I feel like this aligns with a goal of p5.js which is to provide scaffolding that you could use as a jumping off point to dive deeper, rather than a completely walled sandbox that you feel lost outside of.

**Comment by shiffman** [comment]
@lmccart agree!  I think we could probably say that `select()` always returns an array unless an id is specified via `#`?  I'm now completely onboard with teaching the concepts of `id` and `class` with `#` and `.`.   Basically we're just being more explicit saying "select" instead of "$" which they can changeover to once using jquery, etc.  

(In related news I was making a quick sketch today re group formation for ITP's Innovation lab and I kept using `getElement()` and `getElements()` and started wishing for `select()`!

**Comment by workergnome** [comment]
I may be beating a dead horse here, but I could see it not being obvious why  

```
  var txt = select('#shakes');
  txt.html('all the world's a stage');
```
works, but 

```
 var txt = select('.shakes');
 txt.html('all the world's a stage');
```
doesn't.  

Having different return values based on the string value passed into it seems like it's potentially problematic.  Not as problematic as returning an array or a `p5.Element` based on the count—that means that the code could work or fail based on changes to HTML outside of the sketch, or that users have to check for the return type every time they use `.select()`.

**Comment by shiffman** [comment]
That's an excellent point.   I am going to have to meditate on this one.   This leads back to the original `selectId()` thinking. . . hmmmm.  We could *always* return an array but that's pretty awkward for the case of `id`.  I'm stumped for the moment.

**Comment by lmccart** [comment]
I don't feel as worried... there are other functions that have different return values depending on arguments called, the string functions for example return either a single string or an array of strings depending on what you call it with. So there is some precedent for this. They seem more like different use cases to me?

**Comment by shiffman** [comment]
That makes sense @lmccart.  It's tricky but I think with good documentation and examples, we'll see how this plays out and can adjust from there.  I agree that a user is unlikely to be dynamically swapping out id and class names and if they are, perhaps something breaking isn't so terrible in terms of the learning process.

**Comment by brysonian** [comment]
To @workergnome's point, we could follow the lead of querySelector/querySelectorAll and have `select()` and `selectAll()` If you run something like `document.querySelector('.foo')` you only get the first element back and if you want them all you would use `document.querySelectorAll('.foo')`

Part of me feels it is fussy, but at the same time it does require–coerce maybe :)–the coder into being explicit as to what s/he expects.

**Comment by futuremarc** [comment]
I like that solution @brysonian! I think `select()` and `selectAll()` provides some clarity on what you can do with what is returned

**Comment by workergnome** [comment]
Oh, I like that, too.

**Comment by shiffman** [comment]
This sounds great!  And I like mirroring the underlying native DOM functionality itself.  @lmccart, shall @futuremarc start work on this as part of his GSoC to-do list?

**Comment by lmccart** [comment]
that'd be great, go for it @futuremarc!

**Comment by lmccart** [comment]
ok the getElementsByTagName part of this is done, how about createClass? my intuition is that it may be too much, that maybe this is the point where users start to learn about stylesheets. but I don't have any substantial reasoning for drawing the line here, just a hunch. I'd be curious what others think.

**Comment by shiffman** [comment]
@lmccart I'm inclined to agree.  At the very least, I think we want to put other DOM work higher priority-wise and see how teaching / examples work out in the coming months which may lead to more clarity on additional functionality?  The question I would ask here is:

"Is dynamically creating and modifying CSS classes with JavaScript a thing that people do outside of p5.js often and what are some examples?"

I can't imagine a basic / beginner-level example where it wouldn't be more appropriate to teach about CSS files.  Full programmatic control over CSS, however, might be good as an add-on or simply a set of examples with another framework?

All this aside, if we did go this route, I find the use of a long String in `createClass()` awkward and might suggesting using the `style()` method of `p5.element`, i.e.

```javascript
var someclass = createClass('classname');
someclass.style('background-color', '#FF0000');
// etc.
```

**Comment by lmccart** [comment]
all right, then I think I'd suggest we close this one for now and revisit later after some testing in the classroom this fall. I think there are more crucial items we could focus on and leave this for when we have a more informed idea. sound ok?

**Comment by futuremarc** [comment]
Makes sense
