### ISSUE TITLE
Remove lib directory from repo

### ISSUE THREAD

**Issue by workergnome** [processing/p5.js#774]
Following up on the discussion in #707, we should consider removing the generated files from the github repo.

  We would need to:

* Delete the p5.js and p5.min.js files from the repo
* Modify the release procedure to generate those files
* Document in the Github Readme how to install/run grunt

Thoughts?  Problems that people see with this?

**Comment by lmccart** [comment]
I agree this makes sense. The only small question I have is, sometimes when working on a fix, it's useful to have a built version of the library that the issue reporter and others can test. The lib files also serve as unofficial nightlies in some sense. I'm fine with doing away with it as it would seem to alleviate confusion between different dated files of the same version. Just want to make sure this doesn't seem problematic to anyone.

**Comment by workergnome** [comment]
It does mean that you have to pull down their copy of submitter's repo and build it on your machine—that's what I've been doing to test the arc code, for instance.

Is that a problem that could be solved with documentation?

**Comment by kadamwhite** [comment]
I know my colleagues have some experience weighing the pro's and con's of this type of decision—I'll see if @gnarf has any war stories to share from jQuery, e.g.

**Comment by joecridge** [comment]
I'm fairly new to GitHub but I feel that pulling down someone else's feature/fix branch to test it is a good general workflow. The alternative is that the submitter has to make sure that their working branch is up to date with the upstream master *every time* they need to request feedback, which detracts from the benefit of branching in the first place. This probably isn't much of a problem at the moment but as the project grows and there are more simultaneous branches I imagine it could become a pain to keep everyone in sync.

As for nightlies, couldn't we have Travis (or a process on the server) periodically pull and build lib files from the repo master branch automatically?  This would be especially good for non-developers who are reporting bugs since they wouldn't have to touch fit at all in order to test their issue on the latest build.

**Comment by gnarf** [comment]
We do not include built files in jquery.  We instead have a "deploy" / CI process that kicks out git builds based on master.  

Release versions get the files generated and tagged in a "release commit" which doesn't see master.

**Comment by jugglinmike** [comment]
> Release versions get the files generated and tagged in a "release commit" which doesn't see master.

That's my strong preference, as well.

**Comment by Wilto** [comment]
> Release versions get the files generated and tagged in a "release commit" which doesn't see master.

Yeah, we’ve been using this approach on Picturefill for a long time now—checking in dist files was a merge conflict nightmare. We recently started using a Grunt task to automate the release step, too: https://www.npmjs.com/package/grunt-release

**Comment by workergnome** [comment]
That's the second (or third) mention of `grunt-release`, both in this context and in #707.  We had it in our gruntfile but weren't using it, so I removed it.  I should probably add it back in.

**Comment by lmccart** [comment]
yup sounds good let's remove it then

**Comment by workergnome** [comment]
Can do.  Pull request coming.

**Comment by lmccart** [comment]
making a note we'll need to update this script as well
https://github.com/processing/p5.js-website/blob/master/download/release.php

**Comment by workergnome** [comment]
What should we do about  `lib/addons/p5.dom.js`?  The sound and sound.min files are in their own repo but as far as I know, that's the only place where the dom code exists, right?

**Comment by workergnome** [comment]
I created an initial pull request for this:  see #775.

**Comment by lmccart** [comment]
closed with https://github.com/processing/p5.js/pull/775.
will comment about the p5.dom.js file in the other thread, for now it is still in the lib/ folder.
