### ISSUE TITLE
Simplify docs & docs theme build process

### ISSUE THREAD

**Issue by kadamwhite** [processing/p5.js#782]
@taseenb @lmccart The only thing we're using require for at present is the YuiDoc theme, and I'm not familiar enough with that code to know whether we should keep it or whether there's an opportunity to clean up these tasks a bit. Would one of you be able to describe the current docs workflow, in terms of which commands we run and what they're supposed to do? What's the purpose of the yuidoc_theme RequireJS task within the overall process?

**Comment by lmccart** [comment]
`grunt requirejs:yuidoc_theme` is run anytime you make changes to the files behind the yuidoc reference page. These are changes in files located in the yuidoc-p5-theme-src folder or yuidoc-p5-theme folder (for example, changes to main.handlebars or to accompanying JS files), NOT inline documentation changes to src. This command regenerates the templates, then run `grunt yui` is run to regenerate the referenced based on the updated theme.

@taseenb set up this system originally, so he might have more insight into whether this can be simplified or what else may be happening here.

https://github.com/processing/p5.js/wiki/Inline-documentation#generating-documentation

**Comment by taseenb** [comment]
Hi @kadamwhite @lmccart 

I noticed you migrated to Browserify actually. I guess it won't be too hard to migrate the Docs too if you think it's necessary. 
I just don't know how easy is to import an html (text) file with Browserify and convert it into a string, to be used with a template engine. The Docs use the Text plugin of Require to import simple html files that contain the views: https://github.com/processing/p5.js/tree/master/docs/yuidoc-p5-theme-src/scripts/tpl

Otherwise, at the beginning of each file you have an array of required modules and a function with the corresponding arguments:

```
require([
  'underscore',
  'backbone'], function(_, Backbone) {
```

If I understand how Browserify works, that would be translated into something like:

```
var underscore = require('_');
var backbone = require('Backbone');
```

**Comment by kadamwhite** [comment]
So, embarrassing story: I had the "docs" folder excluded from my project in Sublime to simplify find-and-replace, and (out of sight, out of mind) I didn't think to look through that project. Thank you for your explanation, it makes sense now, and I can take a swing at moving this to Browserify as well for parity with the main application. I'll try that this afternoon.

Thanks, @taseenb!

**Comment by sakshamsaxena** [comment]
Closing this. Reopen if it's still something which was left off(looks unlikely?)
