### ISSUE TITLE
.remove() doesn't remove the canvas

### ISSUE THREAD

**Issue by SciutoAlex** [processing/p5.js#784]
p5.remove() should remove canvas, handlers, and draw loops. I'm finding a case where .remove() removes everything, except the canvas element itself.

This CodePen shows p5.remove() working correctly:
http://codepen.io/SciutoAlex/pen/ZGrZNE

But if I take that same code and place it in a plain html page—Chrome, Safari, Firefox. The <canvas> remains even though animations have been stopped.

Here's the HTML: https://gist.github.com/SciutoAlex/b8679b763c07690562de

I'm stumped why this is happening.

**Comment by iros** [comment]
I'm seeing the same behavior actually.

**Comment by iros** [comment]
I tried your code in a jsfiddle, and am also seeing the canvas not being removed properly.
http://jsfiddle.net/qo3duz1z/

**Comment by iros** [comment]
It looks like, the reason is because the codepen p5 lib is different. 
In codepen, when createCanvas is called, the current canvas is saved to this._elements:

```javascript
 if (!this._defaultGraphics) {
      this._defaultGraphics = new p5.Graphics(c, this, true);
      this._elements.push(this._defaultGraphics);
    }
```

Whereas, in the current version of p5.js, it is not. When you call `.remove`, the resulting `this._elements` is actually empty. @lmccart, I'm happy to make a pull req to fix this, by adding a remove on `this._curElement` at the end of the `.remove` call, if that would work for you.

**Comment by sepans** [comment]
I had this problem before and I thought it was intentionally set that way to 'reuse' the canvas and draw on top of it, or just to avoid DOM manipulation (silly thought, I agree). Now that it seems to be a bug, does it make sense to have the option of removing p5.js without removing canvas? Does the p5.js initialization support using <code>#defaultCanvas</code> if it already exists?

**Comment by shiffman** [comment]
is this related to #808?

**Comment by lmccart** [comment]
not related to #808.

@iros good catch! I think your fix would work, but the best one would be to add the canvas element to `this._elements`, but I can't remember if there was some reason why this line was removed...

p5.js does not allow you to specify a canvas to use because the larger conceptual model we are working with sees a p5.js sketch as more than just the canvas. so you can specify a container for all elements created to get appended to, but you can't specify specific elements to attach functionality to. in the same way that `createButton()` doesn't allow you to specify the input element, it appends a new one to the page.
