### ISSUE TITLE
p5 with browserify gives "Error: Cannot find module '../core/core'" in v0.4.6 and v0.4.7 

### ISSUE THREAD

**Issue by geekydatamonkey** [processing/p5.js#818]
I seem to be running into errors when using p5js v0.4.6 and v0.4.7 with browserify. However, with v0.4.5, I have no issues. Browserify runs as expected. Any tips?

For example, if I run `browserify main.js -o bundle.js` on [this code](https://github.com/johnsojr/test-p5-browserify), I get these errors:

```
Error: Cannot find module '../core/core' from '/Users/jjohnson136/dev/p5-browserify-test/node_modules/p5/lib'
    at /Users/jjohnson136/.nvm/versions/node/v0.12.5/lib/node_modules/browserify/node_modules/resolve/lib/async.js:55:21
    at load (/Users/jjohnson136/.nvm/versions/node/v0.12.5/lib/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
    at onex (/Users/jjohnson136/.nvm/versions/node/v0.12.5/lib/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
    at /Users/jjohnson136/.nvm/versions/node/v0.12.5/lib/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:95:15)
```

Thanks for any help!

**Comment by kadamwhite** [comment]
Thanks for the report! I'll take a look at this later this evening.

**Comment by johnsojr** [comment]
Great! Thanks.

**Comment by kadamwhite** [comment]
Sorry for the delay on investigation. Actively looking at this now

**Comment by kadamwhite** [comment]
This is a result of node-browserify#1151 : `--standalone` bundles aren't actually standalone, as Node will still try to parse those `require` statements if you try to use the generated bundle in another browserify project.

The rough approach I'm taking in this investigation is,

- Work on integrating OpenType into the built p5.js file (#781) so that the bundled file exposes one UMD object only
- See if using [derequire](https://www.npmjs.com/package/derequire) on the generated bundle fixes the problem (it does not, but that is probably related to the point above)
- Once a working build is in place, change the existing build process to use derequire on the generated bundle

As a note, the workaround for this in the shortest-term would be to include the entire `src` directory in our package.json's `files` option, since that way Node will properly crawl the entire project: however this would result in duplicate code within the built file, if not an outright error.

**Comment by kadamwhite** [comment]
Update: further progress on this is currently blocked by #828, since the file needs to be a well-formed UMD module before derequire will begin to cooperate

**Comment by kadamwhite** [comment]
Another update: this is still in progress. The current approach I'm taking is to make a custom Browserify task, rather than use the `grunt-browserify` one; this enables us to chain the `derequire` step into the generation of the original file. I'm rabbit-holing a bit on how to best conditionally stub out functionality in the minified builds, but I should have a result that will solve this issue by the end of the week. Thank you very much @geekydatamonkey for the repository demonstrating the issue, it may not be obvious but that sped up this process significantly!

**Comment by kadamwhite** [comment]
As a side-note: I did consider switching to Webpack for the build, since Webpack does a lot of the conditional build/dead code removal/*actually-makes-a-viable-UMD-module* things we want; but for now I've determined that Webpack adds too much complexity to be worth the change.

**Comment by iamkevingreen** [comment]
Having a similar issue, I have a public repo with a p5 branch where it's occurring. Library looks really fun would love to get this working with my browserify setup [this repo](https://github.com/iamkevingreen/animationland/tree/p5)

**Comment by kadamwhite** [comment]
@iamkevingreen Thanks for the additional test case! I'll have another update this week, I promise :)

**Comment by mflux** [comment]
Also running into this issue as well, currently using npm install p5 --save for prototyping and Cannot find module '../core/core'
