### ISSUE TITLE
Curious about WebGL progress... Are looking at 2d WebGL? Should we use pixi.js?

### ISSUE THREAD

**Issue by futuremarc** [processing/p5.js#838]
Hi everyone,

I know a few of us are working on WebGL stuff for 3d this summer, but just wondering if we are trying to add support for 2d WebGL?

The performance difference is staggering in the difference between WebGL and canvas, and is especially true for mobile.

[Phaser.io](http://phaser.io) uses [Pixi.js](http://www.pixijs.com/) which is a 2d WebGL renderer with a canvas fallback. Would it be possible to do the same?

Just wanted to start a conversation because of the huge difference it makes.

**Comment by indefinit** [comment]
Hi Marc,

Totally agree. There will definitely be 2d support for drawing in webgl.  We've been focussing a lot on the 3d side, however it's currently possible to start drawing in 2d "immediate mode".  have a look in the examples folder in the master branch to see what I mean. Right now Karen and I are focussing on getting the shaders and texture binding working properly and intuitively, but if you want to PR for 2D primitives like rect and ellipse, that would be awesome! Are there other specifically 2D features that anyone sees as "must-have's"?

**Comment by futuremarc** [comment]
I'm think I might dive into this over the next semester!

**Comment by indefinit** [comment]
Hi Marc,

We've updated a lot of the new features in webgl, including 2d-esque drawing features.  The examples to reference in the master branch are:  
examples/ --> 3d/ -->geometry/
and examples/ --> 3d/ --> immediateMode/

We are almost finished with the Getting Started Doc and official webgl announcement, which will help clarify most questions but in the meantime, a couple quick notes to get you going:

- in P2D we write rect() --> in webgl we use quad()
- beginShape() and endShape can draw both 2d and 3d shapes.  Therefore, this code will draw a custom triangle:
```
beginShape();
  vertex(x,y,z);
  vertex(x+1,y+10,z);
  vertex(x+5,y,z);
endShape();
```

If you don't mind, I'll close this thread since the title is outdated now, but if you want to start another thread with a more specific implementation/question/addition not already covered in the src please do.  Thanks!

**Comment by futuremarc** [comment]
Cool!
