### ISSUE TITLE
The 1st parameter of image() is checked before execution?

### ISSUE THREAD

**Issue by KouichiMatsuda** [processing/p5.js#877]
The following code renders a "dropped" movie file on "canvas".
It works well but causes the error:
"Uncaught TypeError: Cannot read property 'canvas' of undefined p5.js: 133317"
I am using version 0.4.8.

var video;
function setup() {
  var c = createCanvas(640, 320);
  c.drop(getFile);
  noLoop();
}

function draw() {
  image(video, 0, 0, width, height);
}

function getFile(file) {
  if (file.type === "video") {
    video = createVideo(file.data);
    video.loop();
    video.hide();
    loop();
  }
}

The "canvas" property of the 1st parameter "video" of image() is checked before executing it in draw();
The check should be delayed or is there a better way?

**Comment by lmccart** [comment]
if I'm understanding correctly, the problem is that draw runs but until something is dropped video is not defined so it throws an error? in this case you could add a check to see if video is defined before trying to draw it.
```javascript
if (video) {
  image(video, 0, 0, width, height);
}
```
code questions like this are really better suited for the [forum](http://forum.processing.org/two/categories/p5-js), the github issues list is really for bugs in the library that need to be fixed. if I'm misunderstanding this issue and it is a bug, I apologize, please feel free to reopen and clarify. :)

**Comment by KouichiMatsuda** [comment]
> the problem is that draw runs but until something is dropped,
I don't think so.
It is stopped by noLoop() in setup().

**Comment by KouichiMatsuda** [comment]
> the problem is that draw runs but until something is dropped,

I don't think so.
It is stopped by noLoop() in setup().

**Comment by lmccart** [comment]
ah sorry, I missed that! ok this does seem like it could be a bug, will check it out. thanks!

**Comment by lmccart** [comment]
`noLoop()` prevents draw from running more than once, but it still runs once. this is causing the error you're seeing. again, you could use the if check above. or you could put the `image()` call inside the `getFile()` method.

**Comment by KouichiMatsuda** [comment]
Thanks.

> you could put the image() call inside the getFile()

It can not play the video. That is the reason why image() is in draw().
Am I missing something?

> noLoop() prevents draw from running more than once, but it still runs once.
>  this is causing the error you're seeing. again, you could use the if check above.

I got it. 
However, it introduces unnecessary if-checking into draw() in this case.
