### ISSUE TITLE
arc() does not work for full ellipse (from 0 to TWO_PI)

### ISSUE THREAD

**Issue by shiffman** [processing/p5.js#902]
```javascript
  background(0);
  fill(127);
  stroke(255);
  strokeWeight(4);
  arc(50, 50, 50, 50, 0, TWO_PI);
```

![screen shot 2015-09-09 at 3 03 39 pm](https://cloud.githubusercontent.com/assets/191758/9771436/383c803c-5704-11e5-90cd-3c3b0b4a403f.png)

however:

```javascript
  background(0);
  fill(127);
  stroke(255);
  strokeWeight(4);
  arc(50, 50, 50, 50,0,TWO_PI-0.01);
```

![screen shot 2015-09-09 at 3 04 09 pm](https://cloud.githubusercontent.com/assets/191758/9771447/47016b00-5704-11e5-9fd8-81e41dd276cf.png)

**Comment by joecridge** [comment]
This behaviour is actually intentional (although it might not necessarily be desired).

p5 currently normalises all angles to the interval [0,2π) (i.e. 2π maps back to zero), which means that no matter what angle convention you use, swapping the `start` and `end` arguments around will always swap over the start and end angles of the arc, e.g.

```js
  background(0);
  fill(127);
  stroke(255);
  strokeWeight(4);
  arc(50, 50, 50, 50, -QUARTER_PI, QUARTER_PI); 
```
![qdz](https://cloud.githubusercontent.com/assets/11491479/9794095/1cff8bd8-57e1-11e5-8e1c-843ec30ea9e4.png)

and

```js
  background(0);
  fill(127);
  stroke(255);
  strokeWeight(4);
  arc(50, 50, 50, 50, QUARTER_PI, -QUARTER_PI); 
```
![gsx](https://cloud.githubusercontent.com/assets/11491479/9794104/265d089a-57e1-11e5-97e0-d32103687e87.png)

(this is different from Processing).

A side effect of this is that calling `arc(..., 0, TWO_PI)` is the same as calling `arc(..., 0, 0)`. Because the start and end angles are in the same place, `arc()` doesn't know whether you mean a full circle or no arc at all, and so defaults to the latter.

We could add a guard clause which draws an ellipse if both angles are equal (mod 2π) and nominally unequal, but I have a feeling that this could be a bit unpredictable?

**Comment by shiffman** [comment]
Ah, I see this makes sense to me.  It may be simply an issue of documentation then to help clarify for beginners?

**Comment by lmccart** [comment]
thanks @joecridge, yes, I think this is best resolved by just adding a line to the documentation noting that they should use ellipse if they want the full circle as 0~TWO_PI won't show up.
