### ISSUE TITLE
resizeCanvas() resets stroke and fill colours

### ISSUE THREAD

**Issue by joecridge** [processing/p5.js#905]
Calling `resizeCanvas()` will reset the stroke and fill colours (to black and white, respectively), but `noStroke()` and `noFill()` are remembered.

```js
function setup() {
  createCanvas(100, 100);
  fill(0);
  stroke(255);
}

function draw() {
  background(200);
  rect(25, 25, 50, 50);
}

function windowResized() {
  resizeCanvas(100, 100);
}
```

Before resize (or after refreshing):

![image](https://cloud.githubusercontent.com/assets/11491479/9819251/cf709564-58a4-11e5-9880-d39e7c65495a.png)

and after resizing the window:

![image](https://cloud.githubusercontent.com/assets/11491479/9819262/def718aa-58a4-11e5-9deb-4589c8ee2487.png)

**Comment by lmccart** [comment]
@joecridge what's happening here is that resizing an HTML5Canvas will completely reset all data attached to it. because we're not storing internal values for stroke or fill and these are set in `setup()`, they don't get called again when the canvas is resized and so the styling is lost. I suppose we could store these internally, there are a relatively small number of these (I think it would include fill, stroke, strokeWidth, linecap, and a few others). we could probably make use of the code that's happening inside `push()` in some smart way.

alternatively, we could just make this clear in the documentation and propose that users write an example like yours above as:

```javascript
function setup() {
  createCanvas(100, 100);
  init();
}

function draw() {
  background(200);
  rect(25, 25, 50, 50);
}

function init() {
  fill(0);
  stroke(255);
}

function windowResized() {
  resizeCanvas(100, 100);
  init();
}
```

what are your thoughts?

**Comment by joecridge** [comment]
Ah, that makes sense. I think that using an `init()` function as you suggest is a robust solution, but I wonder if it may be confusing for beginners to have to write two setup functions with similar names -- perhaps calling it something like `setStyle()` would be more transparent?

The main thing that confused me was that `noFill()` and `noStroke()` were remembered while `fill()` and `stroke()` were not. Is there anything straightforward that we can do about this inconsistency?

**Comment by lmccart** [comment]
yeah we could definitely just also reset noFill and noStroke properties when the canvas is resized. and then add some notes to the documentation with an example of making a separate `setStyle()` function to be called in `setup()` and after `resizeCanvas()`.

**Comment by toolness** [comment]
There's a weird edge case here if we add a `noLoop()` to @lmccart's example:

```diff
 function setup() {
   createCanvas(100, 100);
   init();
+  noLoop();
 }
```

The example *seems* like it ought to work, but because `resizeCanvas()` is calling `draw()` itself, `init()` won't be called until *after* the canvas has been redrawn. It works without the `noLoop()` because `draw()` will be called again on the next frame after `init()` has taken effect, but even that may cause a single mis-drawn frame on some browsers (I'm not sure).

Anyhow, I'm personally more inclined towards the [other strategy](https://github.com/processing/p5.js/issues/905#issuecomment-139829242) lmccart mentioned, where p5 restores the fill/stroke/linecap/etc, because it moves the burden off the developer and onto p5. I'm happy to file a PR for this if you want.

**Comment by lmccart** [comment]
hey @toolness you're totally right. i'm not sure why i had thought this would be such a pain to implement, anyway i just pushed a fix, so all styling is preserved and there's no need to add the init() example to the documentation. :) thanks for looking into it!

**Comment by toolness** [comment]
Oh awesome, thanks @lmccart!

**Comment by joecridge** [comment]
Yay :+1:
