### ISSUE TITLE
pixels[]

### ISSUE THREAD

**Issue by jsphweid** [processing/p5.js#926]
Below is some code that doesn't do what I would expect. It makes what seems to be an inverted color image but is grainy also. I would expect it to produce basically the exact same thing from the camera (without doing .hide())

Is this a bug or a lack of understanding pixels[] ? 

```
var capture;
var camWidth, camHeight;
var pd = 1; // pixel Density

function setup() {
    createCanvas(windowWidth, windowHeight);
    frameRate(1);

    capture = createCapture(VIDEO); // feed
    capture.size(320, 240);
    capture.hide();
    camWidth = capture.width;
    camHeight = capture.height;
}

function draw() {
    background(255);
    drawAllPixels();
}

function drawAllPixels() {
    var x, y;
    capture.loadPixels();
    for (x = 0; x < camWidth; x++) {
        for (y = 0; y < camHeight; y++) {
            stroke([capture.pixels[(y*camWidth*pd+x)*pd],
                    capture.pixels[(y*camWidth*pd+x)*(pd+1)],
                    capture.pixels[(y*camWidth*pd+x)*(pd+2)],
                    capture.pixels[(y*camWidth*pd+x)*(pd+3)]])
            point(x, y);
        }
    }
}
```

**Comment by limzykenneth** [comment]
@jsphweid There's a few problem here:

1. When you define the size with `capture.size()`, what it does is set the HTML5 video element size to what you defined. It is NOT setting the actual size the camera is capturing. As a result, you get different result when you call `camHeight * camWidth` and compare it to actual number of pixels given by `capture`.

1. The `pixels` array will be an array of size `width * height * 4`. The extra 4 is a result of the array keeping 4 colour values of each pixels in order, ie. for the first pixel it will be accessible by index of `0,1, 2, 3` for r, g, b, a respectively, second pixel will be `4, 5, 6, 7`. Accessing them means you need to increment the final index passed onto pixels by 4 each time.

I rewrote the above and it should work now as below:

```
var capture;
var camWidth, camHeight;
var pd = 1; // pixel Density

function setup() {
    createCanvas(320, 240);
    frameRate(1);

    capture = createCapture(VIDEO); // feed
    capture.size(320, 240);
    capture.hide();
    // Assuming a 640 * 480 pixels camera
    camWidth = 640;
    camHeight = 480;
}

function draw() {
    background(255);
    drawAllPixels();
}

function drawAllPixels() {
    var x, y;
    capture.loadPixels();
    // Divide by 2 and multiply index by 8 is to reduce the final resolution
    for (y = 0; y < camHeight/2; y++) {
        for (x = 0; x < camWidth/2; x++) {
            var idx = 8 * (y * camWidth + x);
            stroke([capture.pixels[idx],
                        capture.pixels[idx+1],
                        capture.pixels[idx+2],
                        capture.pixels[idx+3]]);
            point(x, y);
        }
    }
}
```

I left out pixels density because without means to test them I'm not sure where to put them or if they are really needed at all (personally guessing not but I could be wrong). The camera size is also defaulted to 640 * 480 which is VGA resolution but it will be better to ask for that resolution from the browser, I can't remember off the top of my head how but I'm sure you can look it up.

Hope that helps. :)

**Comment by lmccart** [comment]
thanks @limzykenneth!
