### ISSUE TITLE
preload() that doesn't call any load* methods prevents setup & draw from being called.

### ISSUE THREAD

**Issue by plural** [processing/p5.js#947]
A sketch like the following:

````js
var sketch = function(p5) {
  p5.preload = function() {
    console.log('preload without any load methods...');
  }

  p5.setup = function() {
    console.log('setup was called!  Yay Hooray!');
    // uncomment this line to make the canvas the full size of the window
    p5.createCanvas(p5.windowWidth, p5.windowHeight);
  }

  p5.draw = function() {
    p5.background(0, 128, 212);
  }
};

var myP5 = new p5(sketch);
````
will never have setup() or draw() called because no load* methods are ever called, thereby never decrementing the preload count.  I'm working on a patch to fix this.

**Comment by Jared-Sprague** [comment]
Good catch.  This is also currently breaking the p5.play bouncing example with the latest master branch of p5.js.  As you can see it has an empty preload() http://p5play.molleindustria.org/examples/index.html?fileName=collisions4.js

p5.play hasn't been updated since p5 version 0.4.5 and it was working then.

**Comment by plural** [comment]
@Jared-Sprague  - my patch fixes the p5.play example.

**Comment by lmccart** [comment]
fixed with https://github.com/processing/p5.js/pull/948
