### ISSUE TITLE
`set()` not displaying properly in Firefox v41

### ISSUE THREAD

**Issue by nlooije** [processing/p5.js#974]
System: Firefox version 41.0.1, Windows 10

It took me several hours to realize Firefox v41 is not displaying properly when using `set()`. See e.g. a snapshot of the reference page of `set()`:

![capture](https://cloud.githubusercontent.com/assets/3252193/10283801/9199570e-6b81-11e5-8652-4835f4f1e395.PNG)

Chrome & IE work fine

**Comment by toolness** [comment]
Are you still experiencing this bug? The [`set()` documentation](http://p5js.org/reference/#/p5/set) seems to look fine for me on Firefox 41.0.2 on Windows 10. I looked at the release notes for 41.0.2, though, and it seems the only thing different between your version and mine is the fixing of a security vulnerability, so I'm hesitant to say that this was somehow fixed by the latest version of Firefox...

**Comment by nlooije** [comment]
Yes, I am still experiencing this bug even in Firefox 41.0.2.
Weird thing is that the first two examples render incorrectly, while the
third seems to work fine.
I can see the image with a black cross through it.

On Fri, Oct 30, 2015 at 4:24 AM, Atul Varma <notifications@github.com>
wrote:

> Are you still experiencing this bug? The set() documentation
> <http://p5js.org/reference/#/p5/set> seems to look fine for me on Firefox
> 41.0.2 on Windows 10. I looked at the release notes for 41.0.2, though, and
> it seems the only thing different between your version and mine is the
> fixing of a security vulnerability, so I'm hesitant to say that this was
> somehow fixed by the latest version of Firefox...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/processing/p5.js/issues/974#issuecomment-152402743>.
>



-- 
Met vriendelijke groeten / Regards,
Niels Looije

**Comment by toolness** [comment]
Hmm, so looking at the [source code for `set()`](https://github.com/processing/p5.js/blob/0e304e1797f742163a4740ce5aab9a144c502658/src/core/p5.Renderer2D.js#L276-L335), it seems understandable that the third example would render okay, because it's ultimately running a separate branch of code that just delegates to [`canvas.drawImage()`](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/drawImage). However, the other examples are going through a separate branch that (I think) is ultimately writing to the raw pixel data of the canvas.

A lot of that branch of code seems to be taking into account a `pixelDensity` variable, so I'm curious if that's the culprit... What happens on your system if you add `console.log(pixelDensity)` to your sketch? My `pixelDensity` appears to be 1, and the examples work on my computer, but perhaps if yours is different, that might explain the discrepancy between what we're both seeing?

**Comment by toolness** [comment]
Erm, for that matter, what happens when you `console.log(window.devicePixelRatio)`?

I did a bit of web sleuthing and found [Firefox bug 809788](https://bugzilla.mozilla.org/show_bug.cgi?id=809788), which actually says that `window.devicePixelRatio` (which p5's `pixelDensity` is based on) *changes* when the user zooms the page using Ctrl-+/-!  Not only that, but it changes to non-integer values... **I actually just reproduced your bug by zooming my page in until `window.pixelDensity` is 1.5 and reloading it.**

As [comment 27](https://bugzilla.mozilla.org/show_bug.cgi?id=809788#c27) of that bug mentions, this wreaks havoc with libraries like p5, because using floating-point numbers as pixel array indices doesn't make a lot of sense.

I'm not really sure what the best solution is here, because that Firefox bug is labeled as WONTFIX, despite some protest... Does your sketch work if you call `devicePixelScaling(false)` at the very beginning of `setup()`? That's definitely not an ideal solution, but I'm guessing it might make things work on Firefox.

**Comment by toolness** [comment]
I think I've got a fix! Fortunately, p5 is dealing with hidpi displays in a nice way, it just seems to assume that the device pixel ratio is an integer, which isn't necessarily the case in Firefox. I submitted PR #1052 which attempts to fix the problem, and it seems to work on my system--I can zoom the page in or out as much as I want, and I no longer see anything like the screenshot in this issue's original description.

**Comment by nlooije** [comment]
When I run console.log(window.devicePixelRatio)in Firefox at default zoom
(100%) it return 1.25 so you are correct that it doesn't return integer
values. Applying your patch to my local version of p5 indeed fixes the
problem. thx


On Fri, Oct 30, 2015 at 11:34 PM, Atul Varma <notifications@github.com>
wrote:

> I think I've got a fix! Fortunately, p5 is dealing with hidpi displays in
> a nice way, it just seems to assume that the device pixel ratio is an
> integer, which isn't necessarily the case in Firefox. I submitted PR #1052
> <https://github.com/processing/p5.js/pull/1052> which attempts to fix the
> problem, and it seems to work on my system--I can zoom the page in or out
> as much as I want, and I no longer see anything like the screenshot in this
> issue's original description.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/processing/p5.js/issues/974#issuecomment-152666237>.
>



-- 
Met vriendelijke groeten / Regards,
Niels Looije
