### ISSUE TITLE
rename p5.Element.width, p5.Element.height to _width and _height, (and refer to size().width, size().height)

### ISSUE THREAD

**Issue by futuremarc** [processing/p5.js#989]

**Comment by lmccart** [comment]
I just remembered that `p5.Graphics` and `p5.Renderer` both extend `p5.Element`. For both of these, we would probably want to keep `.width` and `.height`, and keep them as "public" variables rather than `._width` and `._height`. Two options: 1. set the height and width properties of these two objects in the constructors after `p5.Element` is called or 2. leave things as is and just reinforce the documentation to use `.size()` when the element size may change. Thoughts?

**Comment by futuremarc** [comment]
I am down for either of the two. We should probably go with option 2 for now and focus on other things? @shiffman

**Comment by lmccart** [comment]
I think that makes sense for now.

**Comment by futuremarc** [comment]
Felt like it was mostly me who saw this as a big problem anyway.

**Comment by lmccart** [comment]
well I think your intuition is right on, and eventually it'd be nice to implement option 1 up there, but I agree it's not the highest priority item at the moment.
